package com.udhaardaar.mvp

object ArthSaathiNavigation {
    const val HOME = "HOME"
    const val REGISTER_CREDIT = "REGISTER_CREDIT"
    const val LOANS_UDHAAR = "LOANS_UDHAAR"
    const val QR_KHATA = "QR_KHATA"
    const val GROUP_KHATA = "GROUP_KHATA"
    const val REPAYMENT = "REPAYMENT"
    const val REPAYMENT_SCHEDULE = "REPAYMENT_SCHEDULE"
    const val PEOPLE = "PEOPLE"
    const val BORROWER_PROFILE = "BORROWER_PROFILE"
    const val LOCATION_ADDRESS = "LOCATION_ADDRESS"
    const val ASSET_VAULT = "ASSET_VAULT"
    const val LIABILITY_VAULT = "LIABILITY_VAULT"
    const val PORTFOLIO = "PORTFOLIO"
    const val MIS = "MIS"
    const val SWITCH_ANALYSIS = "SWITCH_ANALYSIS"
    const val PROTECTION = "PROTECTION"
    const val BENEFITS = "BENEFITS"
    const val CHARGECHECK = "CHARGECHECK"
    const val CLAIMS = "CLAIMS"
    const val WILL_LEGACY = "WILL_LEGACY"
    const val LEGAL = "LEGAL"
    const val ADVOCATES = "ADVOCATES"
    const val DOCUMENT_VAULT = "DOCUMENT_VAULT"
    const val DOCUMENT_CAPTURE = "DOCUMENT_CAPTURE"
    const val AI_ADVISOR = "AI_ADVISOR"
    const val REVENUE = "REVENUE"
    const val SECURITY_CONSENT = "SECURITY_CONSENT"
    const val OTP_CONSENT = "OTP_CONSENT"
    const val INTEGRATIONS = "INTEGRATIONS"
}
