package com.udhaardaar.mvp

import android.app.AlertDialog
import android.content.Intent
import android.graphics.Color
import android.graphics.Typeface
import android.net.Uri
import android.os.Bundle
import android.text.InputType
import android.view.Gravity
import android.view.View
import android.view.inputmethod.EditorInfo
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import org.json.JSONObject
import java.text.SimpleDateFormat
import java.util.*

/** ArthSaathi V6 extension centre: QR Khata, Insurance/Benefits, Will, Legal Assistance and AI Advisor. */
class ArthSaathiModulesActivity : AppCompatActivity() {
    private val store by lazy { V5LocalStore(this) }
    private val navy=Color.rgb(18,48,76); private val teal=Color.rgb(0,145,135); private val blue=Color.rgb(38,99,235)
    private val green=Color.rgb(22,137,75); private val amber=Color.rgb(188,122,18); private val red=Color.rgb(190,65,65)
    private val bg=Color.rgb(247,249,252); private val muted=Color.rgb(92,108,124); private val border=Color.rgb(218,226,235)
    private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt()
    private fun box(fill:Int=Color.WHITE,stroke:Int=border,r:Int=14)=android.graphics.drawable.GradientDrawable().apply{setColor(fill);setStroke(dp(1),stroke);cornerRadius=dp(r).toFloat()}
    private fun tv(s:String,size:Float=14f,color:Int=navy,bold:Boolean=false)=TextView(this).apply{text=s;textSize=size;setTextColor(color);typeface=Typeface.create("sans-serif",if(bold)Typeface.BOLD else Typeface.NORMAL)}
    private fun edit(h:String,multi:Boolean=false)=EditText(this).apply{hint=h;textSize=15f;setTextColor(navy);setHintTextColor(muted);setPadding(dp(14),dp(10),dp(14),dp(10));background=box();setSingleLine(!multi);if(multi){minLines=4;gravity=Gravity.TOP};imeOptions=EditorInfo.IME_ACTION_NEXT}
    private fun button(s:String,accent:Int=blue,click:()->Unit)=TextView(this).apply{text=s;textSize=14f;setTextColor(Color.WHITE);gravity=Gravity.CENTER;typeface=Typeface.create("sans-serif-medium",Typeface.NORMAL);minHeight=dp(52);background=box(accent,accent,12);setOnClickListener{click()}}
    private fun secondary(s:String,click:()->Unit)=TextView(this).apply{text=s;textSize=14f;setTextColor(navy);gravity=Gravity.CENTER;typeface=Typeface.DEFAULT_BOLD;minHeight=dp(50);background=box();setOnClickListener{click()}}
    private fun lp(top:Int=8)=LinearLayout.LayoutParams(-1,-2).apply{setMargins(0,dp(top),0,0)}
    private lateinit var scroll:ScrollView
    override fun onCreate(b:Bundle?){super.onCreate(b);window.setSoftInputMode(android.view.WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);show(intent.getStringExtra("mode")?:"MENU")}
    override fun onBackPressed(){startActivity(Intent(this,V5HomeActivity::class.java));finish()}
    private fun base(title:String,sub:String):LinearLayout{val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(18),dp(16),dp(18),dp(90));setBackgroundColor(bg)};val h=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(16),dp(16),dp(16),dp(16));background=box()};h.addView(tv("ARTHSAATHI",13f,teal,true));h.addView(tv(title,24f,navy,true),lp(5));h.addView(tv(sub,13f,muted),lp(4));r.addView(h);scroll=ScrollView(this).apply{isFillViewport=true;addView(r)};setContentView(scroll);return r}
    private fun add(r:LinearLayout,v:View,top:Int=8){r.addView(v,lp(top))}
    private fun show(mode:String){when(mode.uppercase(Locale.US)){"QR","QR_KHATA"->qrKhata();"INSURANCE","BENEFITS"->insurance();"WILL","LEGACY"->will();"LEGAL"->legal();"AI","ADVISOR"->advisor();else->menu()}}
    private fun menu(){val r=base("Financial Life Centre","Credit • protection • vault • checking • legacy • shared expenses");add(r,tv("NEW IN ARTHSAATHI V6",12f,muted,true),16);add(r,button("QR KHATA — MERCHANT CREDIT",teal){show("QR")});add(r,button("INSURANCE & BENEFITS PROTECT",green){show("INSURANCE")});add(r,button("WILL & LEGACY PLANNER",amber){show("WILL")});add(r,button("LEGAL ASSISTANCE DIRECTORY",red){show("LEGAL")});add(r,button("AI FINANCIAL ADVISOR",blue){show("AI")});add(r,tv("EXISTING V5 MODULES",12f,muted,true),18);add(r,button("INFORMAL CREDIT / UDHAARDAAR",blue){startActivity(Intent(this,V5InformalCreditActivity::class.java))});add(r,button("REPAYMENT CENTRE",green){startActivity(Intent(this,V5RepaymentActivity::class.java))});add(r,button("ASSET VAULT",teal){startActivity(Intent(this,V5AssetVaultActivity::class.java))});add(r,button("CHARGECHECK — SANCTION VS STATEMENT",amber){startActivity(Intent(this,V5ChargeComparisonActivity::class.java))});add(r,button("TTMM — SHARED EXPENSES",blue){startActivity(Intent(this,V5TTMMActivity::class.java))});add(r,button("INHERITANCE & CLAIM CENTRE",red){startActivity(Intent(this,V5DeathClaimLegalActivity::class.java))});add(r,secondary("BACK TO ARTHSAATHI HOME"){startActivity(Intent(this,V5HomeActivity::class.java));finish()},16)}
    private fun qrKhata(){val r=base("QR Khata","Scan → record → balance → repayment; designed to replace a handwritten merchant ledger");add(r,tv("MERCHANT / SHOPKEEPER",12f,muted,true),14);val merchant=edit("Merchant profile ID / mobile *");val customer=edit("Customer profile ID / mobile *");val amount=edit("Credit purchase amount (₹) *").apply{inputType=InputType.TYPE_CLASS_NUMBER or InputType.TYPE_NUMBER_FLAG_DECIMAL};val note=edit("Items / invoice / notes");listOf(merchant,customer,amount,note).forEach{add(r,it)};add(r,button("SCAN CUSTOMER QR / IDENTIFIER",teal){startActivity(Intent(this,QrCreditScannerActivity::class.java))});add(r,button("RECORD CREDIT TRANSACTION",blue){val m=merchant.text.toString().trim();val c=customer.text.toString().trim();val a=amount.text.toString().toDoubleOrNull();if(m.isBlank()||c.isBlank()||a==null||a<=0){Toast.makeText(this,"Merchant, customer and positive amount are required",Toast.LENGTH_LONG).show();return@button};val id="QK-${System.currentTimeMillis()}";store.add("qr_khata",JSONObject().apply{put("id",id);put("merchant",m);put("customer",c);put("amount",a);put("note",note.text.toString().trim());put("status","OPEN");put("createdAt",System.currentTimeMillis());put("updatedAt",System.currentTimeMillis())});V5WorkflowRepository(this).appendAudit(id,"QR_KHATA_CREDIT_RECORDED",m,"customer=$c; amount=$a");Toast.makeText(this,"QR Khata transaction recorded: $id",Toast.LENGTH_LONG).show();amount.setText("");note.setText("")});add(r,button("VIEW KHATA TRANSACTIONS",green){showKhata()});add(r,secondary("BACK"){show("MENU")},16)}
    private fun showKhata(){val rows=store.all("qr_khata");val text=if(rows.isEmpty())"No QR Khata transactions yet." else rows.joinToString("\n\n"){j->"${j.optString("id")}\nMerchant: ${j.optString("merchant")}\nCustomer: ${j.optString("customer")}\n₹${j.optDouble("amount",0.0)} • ${j.optString("status")}\n${j.optString("note")}"};AlertDialog.Builder(this).setTitle("QR Khata").setMessage(text).setPositiveButton("OK",null).show()}
    private fun insurance(){val r=base("Insurance & Benefits","Formal policies + card-linked and government-linked protection + condition alerts");add(r,tv("ADD POLICY / BENEFIT",12f,muted,true),14);val name=edit("Policy / benefit name *");val provider=edit("Insurer / bank / scheme provider");val type=edit("Type: Life / Health / PMSBY / PMJJBY / Card / Other");val expiry=edit("Renewal / expiry date (yyyy-MM-dd)");val condition=edit("Eligibility condition, e.g. 1 transaction per quarter",true);listOf(name,provider,type,expiry,condition).forEach{add(r,it)};add(r,button("SAVE + ACTIVATE CONDITION ALERTS",green){val n=name.text.toString().trim();if(n.isBlank()){Toast.makeText(this,"Policy/benefit name is required",Toast.LENGTH_LONG).show();return@button};val id="INS-${System.currentTimeMillis()}";store.add("insurance",JSONObject().apply{put("id",id);put("name",n);put("provider",provider.text.toString().trim());put("type",type.text.toString().trim());put("expiry",expiry.text.toString().trim());put("condition",condition.text.toString().trim());put("alertsEnabled",true);put("createdAt",System.currentTimeMillis())});Toast.makeText(this,"Insurance/benefit saved. Condition alerts are active.",Toast.LENGTH_LONG).show();name.setText("");condition.setText("")});add(r,button("RUN ELIGIBILITY & RENEWAL CHECK",amber){runInsuranceCheck()});add(r,button("VIEW INSURANCE / BENEFIT REGISTER",blue){showInsurance()});add(r,secondary("BACK"){show("MENU")},16)}
    private fun runInsuranceCheck(){val now=System.currentTimeMillis();val sdf=SimpleDateFormat("yyyy-MM-dd",Locale.US);val alerts=mutableListOf<String>();store.all("insurance").forEach{j->val n=j.optString("name");val d=runCatching{sdf.parse(j.optString("expiry"))?.time}.getOrNull();if(d!=null){val days=(d-now)/86400000L;if(days in 0..30)alerts.add("$n: renewal/expiry in $days days")};val c=j.optString("condition");if(c.isNotBlank())alerts.add("$n: check condition — $c")};AlertDialog.Builder(this).setTitle("Protection alerts").setMessage(if(alerts.isEmpty())"No immediate alerts. Add policy conditions to enable specific checks." else alerts.joinToString("\n\n")).setPositiveButton("OK",null).show()}
    private fun showInsurance(){val rows=store.all("insurance");val text=if(rows.isEmpty())"No policies/benefits recorded." else rows.joinToString("\n\n"){j->"${j.optString("name")}\n${j.optString("type")} • ${j.optString("provider")}\nExpiry: ${j.optString("expiry")}\nCondition: ${j.optString("condition")}"};AlertDialog.Builder(this).setTitle("Insurance & Benefits").setMessage(text).setPositiveButton("OK",null).show()}
    private fun will(){val r=base("Will & Legacy Planner","Create a structured draft linked to nominated assets; obtain legal review before execution");add(r,tv("DRAFT WILL",12f,muted,true),14);val testator=edit("Testator full name *");val beneficiary=edit("Beneficiary / nominee name *");val assetIds=edit("Asset IDs to be given to this beneficiary, comma-separated *",true);val share=edit("Share / instruction, e.g. 100% / specific asset");val executor=edit("Proposed executor");val notes=edit("Special instructions",true);listOf(testator,beneficiary,assetIds,share,executor,notes).forEach{add(r,it)};add(r,button("GENERATE WILL DRAFT",amber){val t=testator.text.toString().trim();val b=beneficiary.text.toString().trim();val a=assetIds.text.toString().trim();if(t.isBlank()||b.isBlank()||a.isBlank()){Toast.makeText(this,"Testator, beneficiary and asset linkage are required",Toast.LENGTH_LONG).show();return@button};val id="WILL-${System.currentTimeMillis()}";val draft="LAST WILL & TESTAMENT — DRAFT\n\nTestator: $t\nBeneficiary: $b\nAssets: $a\nShare / instruction: ${share.text}\nProposed executor: ${executor.text}\nSpecial instructions:\n${notes.text}\n\nPrepared in ArthSaathi as a draft. Legal review, execution, witnessing and applicable requirements must be completed separately.";store.add("wills",JSONObject().apply{put("id",id);put("testator",t);put("beneficiary",b);put("assetIds",a);put("draft",draft);put("status","DRAFT");put("createdAt",System.currentTimeMillis())});AlertDialog.Builder(this).setTitle("Will draft ready").setMessage(draft).setPositiveButton("OK",null).setNeutralButton("LEGAL REVIEW"){_,_->show("LEGAL")}.show()});add(r,button("VIEW WILL DRAFTS",blue){val rows=store.all("wills");val text=if(rows.isEmpty())"No Will drafts." else rows.joinToString("\n\n"){it.optString("draft")};AlertDialog.Builder(this).setTitle("Will drafts").setMessage(text).setPositiveButton("OK",null).show()});add(r,secondary("BACK"){show("MENU")},16)}
    private fun legal(){val r=base("Legal Assistance","Domain-based lawyer directory with contact details; call local professionals directly");add(r,tv("SEARCH / ADD LEGAL PROFESSIONAL",12f,muted,true),14);val name=edit("Lawyer name *");val domain=edit("Domain: banking / insurance / succession / property / consumer / business");val city=edit("City / locality");val phone=edit("Contact number");val address=edit("Office address",true);val expertise=edit("Expertise / years / languages",true);listOf(name,domain,city,phone,address,expertise).forEach{add(r,it)};add(r,button("SAVE LAWYER TO DIRECTORY",red){val n=name.text.toString().trim();if(n.isBlank()||phone.text.toString().trim().isBlank()){Toast.makeText(this,"Lawyer name and contact are required",Toast.LENGTH_LONG).show();return@button};val id="LAW-${System.currentTimeMillis()}";store.add("lawyers",JSONObject().apply{put("id",id);put("name",n);put("domain",domain.text.toString().trim());put("city",city.text.toString().trim());put("phone",phone.text.toString().trim());put("address",address.text.toString().trim());put("expertise",expertise.text.toString().trim());put("verification","PENDING_VERIFICATION");put("createdAt",System.currentTimeMillis())});Toast.makeText(this,"Lawyer saved as pending verification.",Toast.LENGTH_LONG).show();name.setText("");phone.setText("")});add(r,button("VIEW LAWYERS / CALL",blue){showLawyers()});add(r,tv("The app must not display a lawyer as verified until credentials/status are actually checked.",12f,muted),14);add(r,secondary("BACK"){show("MENU")},16)}
    private fun showLawyers(){val rows=store.all("lawyers");if(rows.isEmpty()){AlertDialog.Builder(this).setTitle("Lawyer directory").setMessage("No local professionals added yet. Add a lawyer above to build the directory.").setPositiveButton("OK",null).show();return};val text=rows.joinToString("\n\n"){j->"${j.optString("name")}\n${j.optString("domain")} • ${j.optString("city")}\n${j.optString("expertise")}\n${j.optString("phone")}\n${j.optString("verification")}"};val input=edit("Phone to call (optional)");AlertDialog.Builder(this).setTitle("Lawyer directory").setMessage(text).setView(input).setNegativeButton("CLOSE",null).setPositiveButton("CALL"){_,_->val p=input.text.toString();if(p.isNotBlank())startActivity(Intent(Intent.ACTION_DIAL,Uri.parse("tel:${p.filter{it.isDigit()||it=='+'}}")))}.show()}
    private fun advisor(){val r=base("ArthSaathi AI Advisor","Explainable suggestions from user-entered records; never move money or switch investments automatically");add(r,tv("USER PREFERENCES",12f,muted,true),14);val liquidity=edit("Minimum amount you want readily available (₹)").apply{inputType=InputType.TYPE_CLASS_NUMBER or InputType.TYPE_NUMBER_FLAG_DECIMAL};val risk=Spinner(this).apply{adapter=ArrayAdapter(this@ArthSaathiModulesActivity,android.R.layout.simple_spinner_dropdown_item,arrayOf("Conservative","Moderate","Aggressive"))};val horizon=edit("Investment horizon (years)").apply{inputType=InputType.TYPE_CLASS_NUMBER};add(r,liquidity);add(r,risk);add(r,horizon);add(r,button("SAVE PREFERENCES",blue){getSharedPreferences("arthsaathi_preferences",MODE_PRIVATE).edit().putFloat("liquidity",liquidity.text.toString().toFloatOrNull()?:0f).putString("risk",risk.selectedItem.toString()).putInt("horizon",horizon.text.toString().toIntOrNull()?:0).apply();Toast.makeText(this,"Advisor preferences saved.",Toast.LENGTH_SHORT).show()});add(r,button("RUN AI-STYLE FINANCIAL REVIEW",teal){runAdvisor()});add(r,tv("V6 uses transparent rule-based signals first, so every alert can explain its reason. A future AI/service layer can enrich comparisons after appropriate data connectivity and consent.",12f,muted),14);add(r,secondary("BACK"){show("MENU")},16)}
    private fun runAdvisor(){val pref=getSharedPreferences("arthsaathi_preferences",MODE_PRIVATE);val minLiquidity=pref.getFloat("liquidity",0f).toDouble();val risk=pref.getString("risk","Moderate")?:"Moderate";val suggestions=mutableListOf<String>();val assets=store.all("assets");assets.filter{it.optString("assetSubtype").contains("saving",true)||it.optString("title").contains("saving",true)}.forEach{val v=it.optDouble("estimatedValue",0.0);if(v>=50000&&v>minLiquidity)suggestions.add("Idle-cash review: ${it.optString("title")}: ₹${"%.2f".format(v)} exceeds your stated liquid need of ₹${"%.2f".format(minLiquidity)}. Consider comparing FD or suitable investments for surplus at risk profile '$risk'.")};if(assets.isEmpty())suggestions.add("Add bank/investment assets to enable idle-cash and investment review signals.");store.all("insurance").filter{it.optString("condition").isNotBlank()}.forEach{suggestions.add("Protection condition: ${it.optString("name")} — ${it.optString("condition")}")};store.all("credits").filter{it.optString("status")=="ACTIVE"&&it.optDouble("outstanding",0.0)>0}.forEach{suggestions.add("Credit reminder: ${it.optString("id")} has outstanding ₹${"%.2f".format(it.optDouble("outstanding",0.0))}. Review repayment schedule.")};if(suggestions.isEmpty())suggestions.add("No rule-based alerts right now. Continue adding assets, benefits and credit records to make ArthSaathi more useful.");AlertDialog.Builder(this).setTitle("AI Advisor — explainable review").setMessage(suggestions.joinToString("\n\n")+"\n\nSuggestions are not guaranteed outcomes or personalised investment advice. Confirm facts and consult an appropriate professional before acting.").setPositiveButton("OK",null).show()}
}
