package com.udhaardaar.mvp

import android.content.Intent
import android.graphics.Color
import android.graphics.Typeface
import android.os.Bundle
import android.view.Gravity
import android.view.View
import android.widget.*
import androidx.appcompat.app.AppCompatActivity

/** ArthSaathi V6 command centre: all ten modules are reachable without dead-end navigation. */
class ArthSaathiHomeActivity : AppCompatActivity() {
    private val navy=Color.rgb(18,48,76); private val teal=Color.rgb(0,145,135); private val blue=Color.rgb(38,99,235)
    private val green=Color.rgb(22,137,75); private val amber=Color.rgb(188,122,18); private val red=Color.rgb(190,65,65)
    private val bg=Color.rgb(247,249,252); private val muted=Color.rgb(92,108,124); private val border=Color.rgb(218,226,235)
    private val store by lazy{V5LocalStore(this)}
    private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt()
    private fun card()=android.graphics.drawable.GradientDrawable().apply{setColor(Color.WHITE);setStroke(dp(1),border);cornerRadius=dp(15).toFloat()}
    private fun text(s:String,size:Float,color:Int=navy,bold:Boolean=false)=TextView(this).apply{text=s;textSize=size;setTextColor(color);typeface=Typeface.create("sans-serif",if(bold)Typeface.BOLD else Typeface.NORMAL)}
    private fun action(s:String,accent:Int,click:()->Unit)=TextView(this).apply{text=s;textSize=14f;setTextColor(Color.WHITE);gravity=Gravity.CENTER;typeface=Typeface.DEFAULT_BOLD;minHeight=dp(52);background=android.graphics.drawable.GradientDrawable().apply{setColor(accent);cornerRadius=dp(12).toFloat()};setOnClickListener{click()}}
    private fun row(title:String,sub:String,accent:Int,click:()->Unit):View{val r=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(dp(14),dp(12),dp(10),dp(12));background=card();setOnClickListener{click()}};r.addView(text("●",18f,accent,true),LinearLayout.LayoutParams(dp(30),-2));val b=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};b.addView(text(title,15f,navy,true));b.addView(text(sub,11f,muted),LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(3)});r.addView(b,LinearLayout.LayoutParams(0,-2,1f));r.addView(text("›",26f,accent));return r}
    private fun add(r:LinearLayout,v:View,top:Int=8){r.addView(v,LinearLayout.LayoutParams(-1,-2).apply{setMargins(0,dp(top),0,0)})}
    private lateinit var receive:TextView;private lateinit var pay:TextView;private lateinit var records:TextView
    override fun onCreate(b:Bundle?){super.onCreate(b);render()}
    private fun render(){val prefs=getSharedPreferences("udhaardaar_accounts",MODE_PRIVATE);if(!prefs.getBoolean("logged_in",false)){startActivity(Intent(this,LoginActivity::class.java));finish();return};val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(16),dp(12),dp(16),dp(28));setBackgroundColor(bg)};setContentView(ScrollView(this).apply{isFillViewport=true;addView(root)})
        val head=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(dp(14),dp(12),dp(14),dp(12));background=card()};val logo=ImageView(this).apply{setImageResource(R.drawable.udhaardaar_logo);contentDescription="ArthSaathi logo"};head.addView(logo,LinearLayout.LayoutParams(dp(68),dp(68)));val hb=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};hb.addView(text("ARTHSAATHI",24f,navy,true));hb.addView(text("Your Money. Your Records. Your Rights.",12f,teal,true));hb.addView(text("Financial life, credit and legacy companion",11f,muted),LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(4)});head.addView(hb,LinearLayout.LayoutParams(0,-2,1f).apply{leftMargin=dp(12)});root.addView(head)
        val m=prefs.getString("current_mobile","")?:"";val name=prefs.getString("name_$m","User")?:"User";add(root,text("Welcome, $name",20f,navy,true),14);add(root,text("Know what you owe, own, are owed, are protected by, and may need to claim.",12f,muted),4)
        val metrics=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};receive=metric("TO RECEIVE",green);pay=metric("TO PAY",red);metrics.addView(receive,LinearLayout.LayoutParams(0,dp(82),1f).apply{rightMargin=dp(5)});metrics.addView(pay,LinearLayout.LayoutParams(0,dp(82),1f).apply{leftMargin=dp(5)});root.addView(metrics,LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(14)});records=text("ACTIVE CREDIT RECORDS  0",12f,blue,true);records.setPadding(dp(14),dp(14),dp(14),dp(14));records.background=card();add(root,records,8);updateCounts()
        add(root,text("CREDIT",11f,muted,true),18);add(root,row("Udhaardaar — Informal Credit","Loans • borrower history • DPN • consent • informal score",blue){startActivity(Intent(this,V5InformalCreditActivity::class.java))});add(root,row("QR Khata","Merchant credit without a handwritten ledger",teal){startActivity(Intent(this,ArthSaathiModulesActivity::class.java).putExtra("mode","QR"))});add(root,row("Credit & Repayment Centre","Repayments • overdue • audit • bureau foundation",green){startActivity(Intent(this,V5RepaymentActivity::class.java))})
        add(root,text("PROTECT & VAULT",11f,muted,true),18);add(root,row("Asset Vault","Financial + non-financial assets • evidence • nominee",teal){startActivity(Intent(this,V5AssetVaultActivity::class.java))});add(root,row("Insurance & Benefits","Formal + card-linked + government schemes + conditions",green){startActivity(Intent(this,ArthSaathiModulesActivity::class.java).putExtra("mode","INSURANCE"))});add(root,row("AI Advisor","Explainable alerts for idle cash, investments, benefits and dues",blue){startActivity(Intent(this,ArthSaathiModulesActivity::class.java).putExtra("mode","AI"))})
        add(root,text("CHECK & LEGACY",11f,muted,true),18);add(root,row("ChargeCheck","Sanctioned vs actual lender charges with document/OCR evidence",amber){startActivity(Intent(this,V5ChargeComparisonActivity::class.java))});add(root,row("Will & Legacy Planner","Draft a Will linked to assets and nominees",amber){startActivity(Intent(this,ArthSaathiModulesActivity::class.java).putExtra("mode","WILL"))});add(root,row("Inheritance & Claim Centre","Heirs • evidence • claim lifecycle • settlement",red){startActivity(Intent(this,V5DeathClaimLegalActivity::class.java))});add(root,row("Legal Assistance","Domain-specific lawyer directory and direct contact",red){startActivity(Intent(this,ArthSaathiModulesActivity::class.java).putExtra("mode","LEGAL"))})
        add(root,text("SHARED EXPENSES",11f,muted,true),18);add(root,row("TTMM — Tu Tera, Main Mera","Group expenses • shares • OTP-confirmed recovery • settlement",blue){startActivity(Intent(this,V5TTMMActivity::class.java))});add(root,action("OPEN ALL ARTHSAATHI V6 MODULES",navy){startActivity(Intent(this,ArthSaathiModulesActivity::class.java))},18);add(root,action("LOG OUT",Color.rgb(90,105,120){prefs.edit().clear().apply();startActivity(Intent(this,LoginActivity::class.java));finish()},8)
    }
    private fun metric(label:String,accent:Int)=TextView(this).apply{text="$label\n₹0";textSize=12f;setTextColor(accent);typeface=Typeface.DEFAULT_BOLD;gravity=Gravity.CENTER_VERTICAL;setPadding(dp(14),dp(8),dp(14),dp(8));background=card()}
    private fun updateCounts(){val rows=store.all("credits");var receiveTotal=0.0;var payTotal=0.0;rows.filter{it.optString("status")=="ACTIVE"}.forEach{val v=it.optDouble("outstanding",0.0);if(it.optString("direction")=="Credit Received")payTotal+=v else receiveTotal+=v};receive.text="TO RECEIVE\n₹${"%.2f".format(receiveTotal)}";pay.text="TO PAY\n₹${"%.2f".format(payTotal)}";records.text="ACTIVE CREDIT RECORDS  ${rows.count{it.optString("status")=="ACTIVE"}}"}
}
