package com.udhaardaar.mvp

import android.app.AlertDialog
import android.content.Intent
import android.graphics.Color
import android.graphics.Typeface
import android.graphics.drawable.GradientDrawable
import android.os.Bundle
import android.text.InputFilter
import android.text.InputType
import android.view.Gravity
import android.view.WindowManager
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import kotlin.random.Random

class LoginActivity:AppCompatActivity(){
 private val prefs by lazy{getSharedPreferences("udhaardaar_accounts",MODE_PRIVATE)};private val navy=Color.rgb(16,45,82);private val teal=Color.rgb(12,155,145);private val blue=Color.rgb(42,103,221);private val gold=Color.rgb(211,161,37);private val bg=Color.rgb(246,249,252);private val muted=Color.rgb(92,108,124);private val border=Color.rgb(218,226,235)
 private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt();private fun box(fill:Int=Color.WHITE)=GradientDrawable().apply{setColor(fill);setStroke(dp(1),border);cornerRadius=dp(16).toFloat()}
 private fun input(h:String,digits:Boolean=false)=EditText(this).apply{hint=h;textSize=16f;setTextColor(navy);setHintTextColor(muted);setPadding(dp(15),dp(11),dp(15),dp(11));minHeight=dp(54);background=box();setSingleLine(true);imeOptions=android.view.inputmethod.EditorInfo.IME_ACTION_NEXT;if(digits){inputType=InputType.TYPE_CLASS_NUMBER;filters=arrayOf(InputFilter.LengthFilter(10))}else filters=arrayOf(InputFilter.LengthFilter(80))}
 private fun button(s:String,fill:Int,click:()->Unit)=TextView(this).apply{text=s;textSize=14f;setTextColor(Color.WHITE);gravity=Gravity.CENTER;typeface=Typeface.DEFAULT_BOLD;minHeight=dp(52);background=box(fill);setOnClickListener{click()}}
 override fun onCreate(b:Bundle?){super.onCreate(b);window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE or WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_HIDDEN);if(prefs.getBoolean("logged_in",false)){openHome();return};showLogin()}
 private fun add(r:LinearLayout,v:android.view.View,top:Int=8){r.addView(v,LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(top)})}
 private fun showLogin(){val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(20),dp(18),dp(20),dp(28));setBackgroundColor(bg)};val head=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(dp(12),dp(10),dp(12),dp(10));background=box()};head.addView(ImageView(this).apply{setImageResource(R.drawable.arthsaathi_logo);scaleType=ImageView.ScaleType.CENTER_INSIDE;contentDescription="ArthSaathi logo"},LinearLayout.LayoutParams(dp(68),dp(68)));val b=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};b.addView(TextView(this@LoginActivity).apply{text="ArthSaathi";textSize=25f;setTextColor(navy);typeface=Typeface.create("sans-serif",Typeface.BOLD)});b.addView(TextView(this@LoginActivity).apply{text="Navigate Your Financial Journey";textSize=12f;setTextColor(teal);typeface=Typeface.DEFAULT_BOLD});b.addView(TextView(this@LoginActivity).apply{text="Plan • Protect • Grow • Nominate";textSize=10f;setTextColor(gold);typeface=Typeface.DEFAULT_BOLD});head.addView(b,LinearLayout.LayoutParams(0,-2,1f).apply{leftMargin=dp(12)});r.addView(head);add(r,TextView(this).apply{text="Welcome back";textSize=22f;setTextColor(navy);typeface=Typeface.DEFAULT_BOLD},18);add(r,TextView(this).apply{text="Securely continue your financial journey.";textSize=13f;setTextColor(muted)},4);val m=input("Registered mobile number",true);val p=input("4–6 digit PIN",true).apply{inputType=InputType.TYPE_CLASS_NUMBER or InputType.TYPE_NUMBER_VARIATION_PASSWORD;filters=arrayOf(InputFilter.LengthFilter(6))};add(r,m,16);add(r,p,8);add(r,button("LOGIN WITH PIN + OTP",blue){val x=m.text.toString();if(validMobile(x)&&prefs.getString("pin_$x",null)==p.text.toString())otp("Secure login OTP",x){go(x)}else Toast.makeText(this,"Enter your registered mobile and PIN",Toast.LENGTH_LONG).show()},12);add(r,button("CREATE PROFILE / ACCOUNT",teal){showRegister()},8);add(r,button("RESET PIN WITH OTP",Color.rgb(90,105,120)){val x=m.text.toString();if(validMobile(x)&&prefs.contains("pin_$x"))otp("Reset PIN OTP",x){resetPin(x)}else Toast.makeText(this,"Enter a registered mobile first",Toast.LENGTH_LONG).show()},8);add(r,TextView(this).apply{text="Hindi / हिन्दी";textSize=13f;setTextColor(teal);gravity=Gravity.CENTER;setPadding(0,dp(12),0,dp(12));setOnClickListener{language()}},6);setContentView(ScrollView(this).apply{isFillViewport=true;addView(r)})}
 private fun showRegister(){val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(20),dp(18),dp(20),dp(28));setBackgroundColor(bg)};add(r,TextView(this).apply{text="Create your ArthSaathi profile";textSize=22f;setTextColor(navy);typeface=Typeface.DEFAULT_BOLD},0);add(r,TextView(this).apply{text="One verified profile for your financial records.";textSize=13f;setTextColor(muted)},5);val n=input("Full name");val m=input("Mobile number",true);val p=input("Create 4–6 digit PIN",true).apply{inputType=InputType.TYPE_CLASS_NUMBER or InputType.TYPE_NUMBER_VARIATION_PASSWORD;filters=arrayOf(InputFilter.LengthFilter(6))};add(r,n,16);add(r,m);add(r,p);add(r,button("VERIFY MOBILE + CREATE ACCOUNT",teal){val x=m.text.toString();if(n.text.trim().length>=2&&validMobile(x)&&p.text.length in 4..6)otp("Verify mobile",x){prefs.edit().putString("pin_$x",p.text.toString()).putString("name_$x",n.text.toString().trim()).putBoolean("logged_in",true).putString("current_mobile",x).apply();openHome()}else Toast.makeText(this,"Complete valid profile details",Toast.LENGTH_LONG).show()},14);add(r,button("BACK TO SIGN IN",Color.rgb(90,105,120)){showLogin()},8);setContentView(ScrollView(this).apply{isFillViewport=true;addView(r)})}
 private fun validMobile(x:String)=x.matches(Regex("[6-9][0-9]{9}"));private fun otp(title:String,mobile:String,done:()->Unit){val code=(100000+Random.nextInt(900000)).toString();val e=input("Enter 6-digit OTP",true).apply{filters=arrayOf(InputFilter.LengthFilter(6))};val d=AlertDialog.Builder(this).setTitle(title).setMessage("Demo OTP: $code\nLive SMS gateway can be connected for production.").setView(e).setNegativeButton("CANCEL",null).setPositiveButton("VERIFY",null).create();d.setOnShowListener{d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener{if(e.text.toString()==code){d.dismiss();done()}else e.error="Incorrect OTP"}};d.show()}
 private fun resetPin(x:String){val e=input("New 4–6 digit PIN",true).apply{inputType=InputType.TYPE_CLASS_NUMBER or InputType.TYPE_NUMBER_VARIATION_PASSWORD;filters=arrayOf(InputFilter.LengthFilter(6))};AlertDialog.Builder(this).setTitle("Set new PIN").setView(e).setNegativeButton("CANCEL",null).setPositiveButton("SAVE"){_,_->if(e.text.length in 4..6){prefs.edit().putString("pin_$x",e.text.toString()).apply();Toast.makeText(this,"PIN updated",Toast.LENGTH_LONG).show()}else e.error="PIN must be 4–6 digits"}.show()}
 private fun language(){AlertDialog.Builder(this).setTitle("Language / भाषा").setItems(arrayOf("English","हिन्दी")){_,w->LanguageManager.set(this,if(w==1)LanguageManager.HI else LanguageManager.EN);showLogin()}.show()}
 private fun go(m:String){prefs.edit().putBoolean("logged_in",true).putString("current_mobile",m).apply();openHome()};private fun openHome(){startActivity(Intent(this,V62HomeActivity::class.java).addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP or Intent.FLAG_ACTIVITY_SINGLE_TOP));finish()}
}
