package com.udhaardaar.mvp

import android.app.DatePickerDialog
import android.os.Bundle
import android.view.View
import android.view.WindowManager
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat
import androidx.core.view.updatePadding
import androidx.core.widget.NestedScrollView
import java.text.SimpleDateFormat
import java.util.Calendar
import java.util.Locale
import java.util.UUID

class RegisterCreditV3Activity : AppCompatActivity() {
    private lateinit var db: V3DatabaseHelper; private lateinit var scroll: NestedScrollView; private lateinit var partySpinner: Spinner; private lateinit var typeSpinner: Spinner; private lateinit var directionSpinner: Spinner; private lateinit var methodSpinner: Spinner; private lateinit var periodicitySpinner: Spinner; private lateinit var lendingSpinner
    private lateinit var amount: EditText; private lateinit var roi: EditText; private lateinit var repayment: EditText; private lateinit var start: EditText; private lateinit var end: EditText; private lateinit var invoice: EditText; private lateinit var transactionRef: EditText; private lateinit var notes: EditText; private lateinit var consent: CheckBox; private lateinit var calculation: TextView; private lateinit var history: TextView
    private var partyIds=mutableListOf<Long>(); private var partyPhones=mutableListOf<String>(); private var sessionToken=""; private val df=SimpleDateFormat("dd MMM yyyy",Locale.getDefault())
    override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);setContentView(R.layout.activity_register_credit_v3);db=V3DatabaseHelper(this);scroll=findViewById(R.id.registerScroll);partySpinner=findViewById(R.id.spinnerParty);typeSpinner=findViewById(R.id.spinnerCreditType);directionSpinner=findViewById(R.id.spinnerDirection);methodSpinner=findViewById(R.id.spinnerRepaymentMethod);periodicitySpinner=findViewById(R.id.spinnerPeriodicity);lendingSpinner=findViewById(R.id.spinnerLendingMethod);amount=findViewById(R.id.etCreditAmount);roi=findViewById(R.id.etInterestRate);repayment=findViewById(R.id.etRepaymentAmount);start=findViewById(R.id.etCreditStartDate);end=findViewById(R.id.etCreditEndDate);invoice=findViewById(R.id.etInvoiceNumber);transactionRef=findViewById(R.id.etTransactionReference);notes=findViewById(R.id.etCreditNotes);consent=findViewById(R.id.cbConsent);calculation=findViewById(R.id.tvCalculation);history=findViewById(R.id.tvHistorySummary);setSpinner(typeSpinner,arrayOf("Personal Credit","Business Credit","Trade Credit","Advance","Rental / Lease","Other"));setSpinner(directionSpinner,arrayOf("Credit Given","Credit Received"));setSpinner(methodSpinner,arrayOf("EMI","Principal + Interest","Fixed Repayment","Bullet / Maturity"));setSpinner(periodicitySpinner,arrayOf("Monthly","Weekly","Fortnightly","Quarterly","Half-yearly","Yearly","One-time"));setSpinner(lendingSpinner,arrayOf("Cash","UPI","NEFT","RTGS","IMPS","Bank Transfer","Cheque","Other"));loadParties();sessionToken=UUID.randomUUID().toString();ConsentOtpGate.beginSession(sessionToken);start.setOnClickListener{pickDate(start)};end.setOnClickListener{pickDate(end)};methodSpinner.onItemSelectedListener=simpleListener{calculateRepayment()};periodicitySpinner.onItemSelectedListener=simpleListener{calculateRepayment()};partySpinner.onItemSelectedListener=simpleListener{if(partySpinner.selectedItemPosition in partyIds.indices)showHistory(partyIds[partySpinner.selectedItemPosition])};listOf(amount,roi,repayment,invoice,transactionRef,notes).forEach{f->f.setOnFocusChangeListener{v,has->if(has){bringFieldAboveIme(v);calculateRepayment()}}};consent.setOnCheckedChangeListener{_,checked->ConsentOtpGate.grantConsent(checked)};findViewById<Button>(R.id.btnSaveCreditV3).setOnClickListener{validateAndSave()};installImeSafeScrolling()}
    private fun simpleListener(a:()->Unit)=object:AdapterView.OnItemSelectedListener{override fun onNothingSelected(p:AdapterView<*>?)=Unit;override fun onItemSelected(p:AdapterView<*>?,v:View?,pos:Int,id:Long)=a()}
    private fun installImeSafeScrolling(){val base=scroll.paddingBottom;ViewCompat.setOnApplyWindowInsetsListener(scroll){v,i->v.updatePadding(bottom=base+maxOf(i.getInsets(WindowInsetsCompat.Type.ime()).bottom,i.getInsets(WindowInsetsCompat.Type.systemBars()).bottom)+32);i};ViewCompat.requestApplyInsets(scroll)}
    private fun bringFieldAboveIme(v:View){v.postDelayed({val r=android.graphics.Rect();scroll.getWindowVisibleDisplayFrame(r);val l=IntArray(2);v.getLocationInWindow(l);val d=l[1]+v.height-(r.bottom-32);if(d>0)scroll.smoothScrollBy(0,d+48)},120)}
    private fun setSpinner(s:Spinner,a:Array<String>){s.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,a)}
    private fun loadParties(){partyIds.clear();partyPhones.clear();val n=mutableListOf<String>();db.readableDatabase.rawQuery("SELECT id,name,COALESCE(mobile,'') FROM parties ORDER BY name COLLATE NOCASE",null).use{c->while(c.moveToNext()){partyIds.add(c.getLong(0));n.add(c.getString(1));partyPhones.add(c.getString(2))}};if(n.isEmpty())n.add("No borrower/party available — create a profile first");setSpinner(partySpinner,n.toTypedArray())}
    private fun showHistory(id:Long){var count=0;var active=0;var settled=0;var principal=0.0;var repaid=0.0;db.readableDatabase.rawQuery("SELECT c.principal_amount,c.status,COALESCE((SELECT SUM(r.amount) FROM repayments r WHERE r.credit_id=c.id),0) FROM credits c INNER JOIN credit_parties cp ON cp.credit_id=c.id AND cp.party_id=? AND cp.role='BORROWER' ORDER BY c.start_date DESC",arrayOf(id.toString())).use{c->while(c.moveToNext()){count++;principal+=c.getDouble(0);repaid+=c.getDouble(2);if(c.getString(1)=="ACTIVE")active++ else if(c.getString(1)=="SETTLED")settled++}};history.text=if(count==0)"No previous credit or repayment history available." else "Previous credits: $count\nActive: $active   Settled: $settled\nTotal credit: ${money(principal)}\nTotal repaid: ${money(repaid)}\nCurrent outstanding: ${money((principal-repaid).coerceAtLeast(0.0))}"}
    private fun pickDate(t:EditText){val c=Calendar.getInstance();DatePickerDialog(this,{_,y,m,d->c.set(y,m,d);t.setText(df.format(c.time));bringFieldAboveIme(t)},c.get(Calendar.YEAR),c.get(Calendar.MONTH),c.get(Calendar.DAY_OF_MONTH)).show()}
    private fun periodsPerYear()=when(periodicitySpinner.selectedItem?.toString()){"Weekly"->52;"Fortnightly"->26;"Quarterly"->4;"Half-yearly"->2;"Yearly"->1;"One-time"->1;else->12}
    private fun calculateRepayment(){val p=amount.text.toString().toDoubleOrNull()?:return;val r=roi.text.toString().toDoubleOrNull()?:0.0;if(p<=0||r<0)return;val method=methodSpinner.selectedItem?.toString()?:"EMI";val n=periodsPerYear();if(method=="EMI"){val rate=r/(100.0*n);val emi=if(rate==0.0)p/n else p*rate*Math.pow(1+rate,n.toDouble())/(Math.pow(1+rate,n.toDouble())-1);repayment.setText(String.format(Locale.US,"%.2f",emi));calculation.text="Indicative repayment: ${money(emi)} per ${periodicitySpinner.selectedItem.toString().lowercase(Locale.getDefault())}."}else{calculation.text="Principal: ${money(p)}\nIndicative annual interest: ${money(p*r/100.0)}\nEnter the agreed repayment amount."}}
    private fun validateAndSave(){if(partyIds.isEmpty()||partySpinner.selectedItemPosition !in partyIds.indices)return toast("Create/select a party first");if(!consent.isChecked)return toast("For informal credit, required consent confirmation is mandatory");if(!ConsentOtpGate.isRegistrationAuthorised())return toast("OTP verification is required before registering this informal credit");val partyId=partyIds[partySpinner.selectedItemPosition];if(partyPhones.getOrNull(partySpinner.selectedItemPosition).orEmpty().isBlank())return toast("Selected party has no registered mobile number for OTP verification");val p=amount.text.toString().toDoubleOrNull()?:return field(amount,"Enter a valid amount");val rate=roi.text.toString().toDoubleOrNull()?:0.0;val repay=repayment.text.toString().toDoubleOrNull()?:return field(repayment,"Enter the agreed repayment amount");if(p<=0)return field(amount,"Amount must be greater than zero");if(rate<0||rate>100)return field(roi,"ROI must be between 0% and 100%");if(repay<=0)return field(repayment,"Repayment must be greater than zero");if(start.text.isBlank())return field(start,"Select the start date");if(end.text.isNotBlank()&&!validDateOrder(start.text.toString(),end.text.toString()))return field(end,"End date must be on/after start date");val type=typeSpinner.selectedItem.toString();val direction=if(directionSpinner.selectedItemPosition==0)"GIVEN" else "RECEIVED";val method=methodSpinner.selectedItem.toString().uppercase(Locale.getDefault()).replace(" + ","_").replace(" ","_");val periodicity=periodicitySpinner.selectedItem.toString().uppercase(Locale.getDefault());val now=SimpleDateFormat("yyyy-MM-dd HH:mm:ss",Locale.getDefault()).format(Calendar.getInstance().time);val id=db.addCredit(partyId,type,direction,p,rate,method,repay,periodicity,start.text.toString(),end.text.toString().ifBlank{null},end.text.toString().ifBlank{null},notes.text.toString().trim(),now,0,invoice.text.toString().trim().ifBlank{null},null,lendingSpinner.selectedItem.toString().uppercase(Locale.getDefault()).replace(" ","_"),transactionRef.text.toString().trim().ifBlank{null});if(id<=0)return toast("Unable to register credit. Nothing was saved.");ReminderScheduler.schedule(this,id,start.text.toString(),1);ConsentOtpGate.clearAfterRegistration();toast("Credit registered successfully");finish()}
    private fun validDateOrder(a:String,b:String)=try{!df.parse(b).before(df.parse(a))}catch(_:Exception){false};private fun field(v:EditText,m:String){v.error=m;v.requestFocus();bringFieldAboveIme(v)};private fun toast(s:String)=Toast.makeText(this,s,Toast.LENGTH_LONG).show();private fun money(v:Double)="₹"+String.format(Locale.US,"%,.2f",v)
}
