package com.udhaardaar.mvp

import android.app.AlertDialog
import android.content.Intent
import android.graphics.Color
import android.graphics.drawable.GradientDrawable
import android.net.Uri
import android.os.Bundle
import android.text.InputFilter
import android.text.InputType
import android.view.Gravity
import android.view.View
import android.widget.*
import androidx.activity.OnBackPressedCallback
import androidx.appcompat.app.AppCompatActivity
import java.text.SimpleDateFormat
import java.util.*
import kotlin.math.pow
import kotlin.random.Random

class V32Activity : AppCompatActivity() {
    private lateinit var db: V32DatabaseHelper
    private val prefs by lazy { getSharedPreferences("udhaardaar_v32_session", MODE_PRIVATE) }
    private var pendingOtp=""
    private var selectedPhoto:Uri?=null
    private var currentBack:(()->Unit)?=null
    private val navy=Color.rgb(15,38,71);private val blue=Color.rgb(31,111,235);private val teal=Color.rgb(0,145,135);private val green=Color.rgb(24,145,78);private val red=Color.rgb(205,55,55);private val amber=Color.rgb(232,151,22);private val bg=Color.rgb(246,248,252)
    override fun onCreate(b:Bundle?){super.onCreate(b);db=V32DatabaseHelper(this);onBackPressedDispatcher.addCallback(this,object:OnBackPressedCallback(true){override fun handleOnBackPressed(){if(currentBack!=null)dashboard()else finish()}});if(db.hasUser()&&prefs.getBoolean("logged_in",false))dashboard()else login()}
    private fun dp(x:Int)= (x*resources.displayMetrics.density).toInt()
    private fun bg(fill:Int,stroke:Int=Color.TRANSPARENT,r:Int=16)=GradientDrawable().apply{setColor(fill);cornerRadius=dp(r).toFloat();if(stroke!=Color.TRANSPARENT)setStroke(dp(1),stroke)}
    private fun text(s:String,size:Float=16f,color:Int=Color.DKGRAY)=TextView(this).apply{text=s;textSize=size;setTextColor(color);setPadding(dp(5),dp(5),dp(5),dp(5))}
    private fun input(h:String,max:Int?=null,numeric:Boolean=false)=EditText(this).apply{hint=h;textSize=16f;setPadding(dp(14),dp(8),dp(14),dp(8));background=bg(Color.WHITE,Color.rgb(215,222,232),14);if(numeric)inputType=InputType.TYPE_CLASS_NUMBER or InputType.TYPE_NUMBER_FLAG_DECIMAL;max?.let{filters=arrayOf(InputFilter.LengthFilter(it))}}
    private fun phone(h:String)=input(h,10).apply{inputType=InputType.TYPE_CLASS_PHONE;keyListener=android.text.method.DigitsKeyListener.getInstance("0123456789")}
    private fun button(s:String,color:Int=blue,a:()->Unit)=Button(this).apply{text=s;isAllCaps=false;textSize=14f;setTextColor(Color.WHITE);background=bg(color,color,18);setOnClickListener{a()}}
    private fun root()=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(18),dp(14),dp(18),dp(28));setBackgroundColor(bg)}
    private fun page(title:String,sub:String?=null,back:(()->Unit)?=null):LinearLayout{val r=root();val h=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL};val t=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;layoutParams=LinearLayout.LayoutParams(0,-2,1f)};t.addView(text(title,25f,navy));if(sub!=null)t.addView(text(sub,13f,Color.GRAY));h.addView(t);h.addView(button("HOME",blue){dashboard()},LinearLayout.LayoutParams(dp(76),dp(44)));r.addView(h);r.addView(Space(this).apply{layoutParams=LinearLayout.LayoutParams(1,dp(8))});currentBack=back;return r}
    private fun show(v:View){setContentView(ScrollView(this).apply{isFillViewport=true;setBackgroundColor(bg);addView(v)})}
    private fun login(){val r=root();r.addView(text("UDHAARDAAR",31f,Color.WHITE).apply{gravity=Gravity.CENTER;background=bg(navy,navy,24);setPadding(dp(18),dp(20),dp(18),dp(20))});r.addView(text("Smart informal-credit manager",15f,navy).apply{gravity=Gravity.CENTER});r.addView(Space(this).apply{layoutParams=LinearLayout.LayoutParams(1,dp(12))});val existing=db.hasUser();val name=input("Full name *");val mobile=phone("Mobile number * (10 digits)");val address=input("Full address *");val email=input("Email (optional)");if(!existing){r.addView(text("Create lender / account-owner profile",20f,navy));listOf(name,mobile,address,email).forEach{r.addView(it,LinearLayout.LayoutParams(-1,dp(58)).apply{setMargins(0,dp(4),0,dp(4))})}}else{r.addView(text("Login with registered mobile",20f,navy));r.addView(mobile,LinearLayout.LayoutParams(-1,dp(58)))};val photo=ImageView(this).apply{layoutParams=LinearLayout.LayoutParams(-1,dp(150));setImageResource(android.R.drawable.ic_menu_camera);scaleType=ImageView.ScaleType.CENTER_INSIDE;background=bg(Color.WHITE,Color.rgb(215,222,232),18)};r.addView(photo);r.addView(button("ADD PROFILE PHOTO (OPTIONAL)",teal){pickPhoto(photo)});val otp=input("6-digit OTP",6,true).apply{gravity=Gravity.CENTER;visibility=View.GONE};r.addView(otp);val verify=button("VERIFY OTP",green){if(otp.text.toString()!=pendingOtp||pendingOtp.isBlank()){otp.error="Incorrect OTP";return@button};if(!existing)db.saveUser("USR-${System.currentTimeMillis()}",name.text.toString().trim(),mobile.text.toString(),address.text.toString().trim(),email.text.toString().trim(),selectedPhoto?.toString());prefs.edit().putBoolean("logged_in",true).apply();dashboard()};verify.visibility=View.GONE;r.addView(verify,LinearLayout.LayoutParams(-1,dp(52)));r.addView(button(if(existing)"SEND LOGIN OTP"else"CREATE PROFILE + SEND OTP",blue){if(mobile.text.toString().length!=10||(!existing&&(name.text.isNullOrBlank()||address.text.isNullOrBlank()))){Toast.makeText(this,"Please complete the required fields",Toast.LENGTH_LONG).show();return@button};pendingOtp=Random.nextInt(100000,1000000).toString();otp.visibility=View.VISIBLE;verify.visibility=View.VISIBLE;Toast.makeText(this,"Demo OTP: $pendingOtp\nConnect an SMS provider for live OTP delivery.",Toast.LENGTH_LONG).show()});show(r)}
    private fun dashboard(){val u=db.userData();val r=page("Dashboard","Your credit control centre",::dashboard);r.addView(text("Good day, ${u?.name ?: "Lender"}",22f,navy));r.addView(text("Unique ID: ${u?.id ?: "—"}",12f,Color.GRAY));r.addView(Space(this).apply{layoutParams=LinearLayout.LayoutParams(1,dp(8))});val stats=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};fun stat(v:String,l:String,c:Int,a:()->Unit){val x=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.CENTER;setPadding(dp(6),dp(12),dp(6),dp(12));background=bg(Color.WHITE,Color.rgb(224,229,238),16);setOnClickListener{a()}};x.addView(text(v,20f,c).apply{gravity=Gravity.CENTER});x.addView(text(l,11f,Color.GRAY).apply{gravity=Gravity.CENTER});stats.addView(x,LinearLayout.LayoutParams(0,-2,1f).apply{setMargins(dp(3),0,dp(3),0)})};stat(money(db.totalCredit("Credit Given")),"Credit Given",blue){history("Credit Given")};stat(money(db.totalCredit("Credit Received")),"Credit Taken",teal){history("Credit Received")};r.addView(stats);val stats2=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};stat2(stats2,db.dueCount(false).toString(),"Due",amber){repayments(false)};stat2(stats2,db.dueCount(true).toString(),"Overdue",red){repayments(true)};r.addView(stats2);r.addView(Space(this).apply{layoutParams=LinearLayout.LayoutParams(1,dp(10))});card(r,"＋","Register New Credit","Borrower → terms → guarantor → documents → OTP",blue){creditFlow()};card(r,"⌕","Borrower Profiles","Search/create by name, mobile, PAN or Aadhaar",teal){profiles("BORROWER")};card(r,"▣","Credit History","All credits and repayment records",navy){history(null)};card(r,"₹","Repayment Centre","Due dates, overdue items and payments",green){repayments(false)};card(r,"⌁","Documents & Consent","Digital-document readiness and terms",amber){documents()};card(r,"◎","Lender Profile","Profile, photo and optional bank/NACH",teal){lender()};r.addView(button("LOG OUT",Color.DKGRAY){prefs.edit().putBoolean("logged_in",false).apply();login()});show(r)}
    private fun stat2(parent:LinearLayout,v:String,l:String,c:Int,a:()->Unit){val x=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.CENTER;setPadding(dp(6),dp(10),dp(6),dp(10));background=bg(Color.WHITE,Color.rgb(224,229,238),16);setOnClickListener{a()}};x.addView(text(v,20f,c).apply{gravity=Gravity.CENTER});x.addView(text(l,11f,Color.GRAY).apply{gravity=Gravity.CENTER});parent.addView(x,LinearLayout.LayoutParams(0,-2,1f).apply{setMargins(dp(3),dp(6),dp(3),0)})}
    private fun card(r:LinearLayout,icon:String,title:String,sub:String,c:Int,a:()->Unit){val b=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(dp(14),dp(13),dp(10),dp(13));background=bg(Color.WHITE,Color.rgb(224,229,238),18);elevation=dp(2).toFloat();setOnClickListener{a()}};b.addView(text(icon,23f,c));val t=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;layoutParams=LinearLayout.LayoutParams(0,-2,1f);setPadding(dp(8),0,0,0)};t.addView(text(title,16f,navy));t.addView(text(sub,12f,Color.GRAY));b.addView(t);b.addView(text("›",30f,c));r.addView(b,LinearLayout.LayoutParams(-1,-2).apply{setMargins(0,dp(5),0,dp(5))})}
    private fun profiles(role:String){val r=page(if(role=="BORROWER")"Borrower Profiles"else"Guarantors","Search by name, mobile, PAN, Aadhaar or unique ID",::dashboard);val q=input("Search...");val list=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};fun refresh(){list.removeAllViews();val rows=db.searchProfiles(role,q.text.toString());if(rows.isEmpty())list.addView(text("No matching profile. Create a new one below.",14f,Color.GRAY));rows.forEach{p->card(list,"●",p.name,"${p.mobile} • ${p.id}",blue){if(role=="BORROWER")summary(p.rowId)else profile(role,p.rowId)}}};r.addView(q);r.addView(button("SEARCH",blue){refresh()});r.addView(button("CREATE NEW PROFILE",green){profile(role,null)});r.addView(Space(this).apply{layoutParams=LinearLayout.LayoutParams(1,dp(8))});r.addView(list);refresh();show(r)}
    private fun profile(role:String,id:Long?){val p=id?.let{db.profileData(it)};val r=page(if(role=="BORROWER")"Borrower Profile"else"Guarantor Profile","Required fields are clearly marked",::dashboard);val fields=listOf(input("Full name *").apply{setText(p?.name?:"")},phone("Mobile number * (10 digits)").apply{setText(p?.mobile?:"")},input("Alternate mobile").apply{setText(p?.alternate?:"")},input("Address *").apply{setText(p?.address?:"")},input("City").apply{setText(p?.city?:"")},input("State").apply{setText(p?.state?:"")},input("PIN",6,true).apply{setText(p?.pin?:"")},input("Email").apply{setText(p?.email?:"")},input("PAN").apply{setText(p?.pan?:"")},input("Aadhaar",12,true).apply{setText(p?.aadhaar?:"")},input("Occupation / Business").apply{setText(p?.occupation?:"")},input("Business name").apply{setText(p?.business?:"")},input("GSTIN").apply{setText(p?.gstin?:"")});fields.forEach{r.addView(it,LinearLayout.LayoutParams(-1,dp(56)).apply{setMargins(0,dp(3),0,dp(3))})};val img=ImageView(this).apply{layoutParams=LinearLayout.LayoutParams(-1,dp(150));setImageURI(p?.photo?.let{Uri.parse(it)});if(p?.photo.isNullOrBlank())setImageResource(android.R.drawable.ic_menu_camera);scaleType=ImageView.ScaleType.CENTER_CROP;background=bg(Color.WHITE,Color.LTGRAY,16)};r.addView(img);r.addView(button("PHOTO (OPTIONAL)",teal){pickPhoto(img)});r.addView(button(if(p==null)"SAVE PROFILE"else"UPDATE PROFILE",green){if(fields[0].text.isNullOrBlank()||fields[1].text.toString().length!=10||fields[3].text.isNullOrBlank()){Toast.makeText(this,"Name, 10-digit mobile and address are required",Toast.LENGTH_LONG).show();return@button};val rid=db.upsertProfile(p?.rowId,role,p?.id?:"${if(role=="BORROWER")"BOR"else"GUA"}-${System.currentTimeMillis()}",fields[0].text.toString().trim(),fields[1].text.toString(),fields[2].text.toString(),fields[3].text.toString(),fields[4].text.toString(),fields[5].text.toString(),fields[6].text.toString(),fields[7].text.toString(),fields[8].text.toString().uppercase(),fields[9].text.toString(),fields[10].text.toString(),fields[11].text.toString(),fields[12].text.toString().uppercase(),selectedPhoto?.toString()?:p?.photo);if(rid>0){selectedPhoto=null;profiles(role)}});show(r)}
    private fun summary(id:Long){val p=db.profileData(id)?:return;val s=db.borrowerCreditSummary(id);val r=page("Borrower Summary","Review history before adding new credit",::dashboard);r.addView(text(p.name,25f,navy));r.addView(text("ID: ${p.id} • Mobile: ${p.mobile}",13f,Color.GRAY));r.addView(text("Total credit: ${money(s.total)}\nOutstanding: ${money(s.outstanding)}\nActive: ${s.active} • Overdue: ${s.overdue}",17f,navy).apply{background=bg(Color.WHITE,Color.LTGRAY,16);setPadding(dp(15),dp(15),dp(15),dp(15))});r.addView(button("REGISTER CREDIT FOR THIS BORROWER",blue){creditFlow(id)});r.addView(button("EDIT PROFILE",teal){profile("BORROWER",id)});show(r)}
    private fun creditFlow(preselected:Long?=null){val r=page("Register Credit","Step 1 of 4 • borrower and credit terms",::dashboard);val q=input("Search borrower...");val borrowerBox=TextView(this).apply{setPadding(dp(10),dp(12),dp(10),dp(12));textColor(navy)};var borrower=preselected;preselected?.let{db.profileData(it)?.let{p->borrowerBox.text="Selected: ${p.name} (${p.id})"}};val results=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};fun search(){results.removeAllViews();db.searchProfiles("BORROWER",q.text.toString()).take(5).forEach{p->val b=button("${p.name} • ${p.mobile}",Color.WHITE){borrower=p.rowId;borrowerBox.text="Selected: ${p.name} (${p.id})";results.removeAllViews()};b.setTextColor(navy);results.addView(b)}};r.addView(q);r.addView(button("SEARCH BORROWER",teal){search()});r.addView(results);r.addView(borrowerBox);r.addView(button("CREATE BORROWER PROFILE",green){profile("BORROWER",null)});val type=Spinner(this);type.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,arrayOf("Personal Loan","Trade Credit","Rental / Lease","Advance"));r.addView(text("Credit type",14f,Color.GRAY));r.addView(type);val principal=input("Principal / credit amount *",null,true);val roi=input("ROI % per annum",null,true);val tenor=input("Tenor in months",3,true).apply{setText("1")};val method=Spinner(this);method.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,arrayOf("EMI","Principal + Interest","One-time"));r.addView(principal);r.addView(roi);r.addView(text("Repayment method",14f,Color.GRAY));r.addView(method);r.addView(tenor);val start=input("Start date (DD/MM/YYYY)").apply{setText(SimpleDateFormat("dd/MM/yyyy",Locale.US).format(Date()))};val end=input("End date (DD/MM/YYYY)").apply{setText(start.text.toString())};r.addView(start);r.addView(end);val calc=text("Enter amount, ROI and tenor to calculate",15f,navy);r.addView(calc);r.addView(button("CALCULATE",blue){val p=principal.text.toString().toDoubleOrNull()?:0.0;val rate=(roi.text.toString().toDoubleOrNull()?:0.0)/1200.0;val n=(tenor.text.toString().toIntOrNull()?:1).coerceAtLeast(1);val emi=if(rate==0.0)p/n else p*rate*(1+rate).pow(n)/((1+rate).pow(n)-1);val total=emi*n;calc.text="Estimated instalment: ${money(emi)}\nTotal payable: ${money(total)}"});r.addView(button("CONTINUE → GUARANTOR",green){val b=borrower;if(b==null){Toast.makeText(this,"Select or create a borrower first",Toast.LENGTH_LONG).show();return@button};val p=principal.text.toString().toDoubleOrNull()?:0.0;if(p<=0){principal.error="Enter amount";return@button};guarantorStep(b,type.selectedItem.toString(),p,roi.text.toString().toDoubleOrNull()?:0.0,tenor.text.toString().toIntOrNull()?:1,method.selectedItem.toString(),start.text.toString(),end.text.toString())});show(r)}
    private fun guarantorStep(b:Long,type:String,p:Double,roi:Double,tenor:Int,method:String,start:String,end:String){val r=page("Guarantor","Step 2 of 4 • guarantor is optional",::dashboard);val choice=Spinner(this);choice.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,arrayOf("No guarantor","Guarantor available"));r.addView(text("Is a guarantor available?",18f,navy));r.addView(choice);val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};r.addView(box);var gid:Long?=null;choice.onItemSelectedListener=object:AdapterView.OnItemSelectedListener{override fun onNothingSelected(p:AdapterView<*>?){};override fun onItemSelected(p:AdapterView<*>?,v:View?,pos:Int,id:Long){box.removeAllViews();gid=null;if(pos==1){val q=input("Search guarantor");box.addView(q);box.addView(button("SEARCH GUARANTOR",teal){box.removeViews(2,box.childCount-2);db.searchProfiles("GUARANTOR",q.text.toString()).take(5).forEach{x->box.addView(button("${x.name} • ${x.mobile}",Color.WHITE){gid=x.rowId;Toast.makeText(this@V32Activity,"Selected ${x.name}",Toast.LENGTH_SHORT).show()})}});box.addView(button("CREATE GUARANTOR PROFILE",green){profile("GUARANTOR",null)})}}};r.addView(button("CONTINUE → DOCUMENTS",green){documentStep(b,gid,type,p,roi,tenor,method,start,end)});show(r)}
    private fun documentStep(b:Long,g:Long?,type:String,p:Double,roi:Double,tenor:Int,method:String,start:String,end:String){val r=page("Documents & Consent","Step 3 of 4 • review before OTP",::dashboard);r.addView(text("Digital credit record",20f,navy));r.addView(text("The app will record the credit terms, repayment schedule and OTP consent status. A promissory note/document can be attached in the document centre.",14f,Color.DKGRAY));val consent=CheckBox(this).apply{text="I have reviewed the terms and consent to digital record creation"};r.addView(consent);val invoice=input("Invoice/GSTIN reference (optional)");r.addView(invoice);r.addView(button("CONTINUE → OTP CONFIRMATION",green){if(!consent.isChecked){Toast.makeText(this,"Please confirm consent to continue",Toast.LENGTH_LONG).show();return@button};otpConfirm(b,g,type,p,roi,tenor,method,start,end,invoice.text.toString())});show(r)}
    private fun otpConfirm(b:Long,g:Long?,type:String,p:Double,roi:Double,tenor:Int,method:String,start:String,end:String,invoice:String){val r=page("OTP Confirmation","Step 4 of 4 • final registration",::dashboard);val otp=input("Enter 6-digit OTP",6,true).apply{gravity=Gravity.CENTER};pendingOtp=Random.nextInt(100000,1000000).toString();r.addView(text("OTP sent for consent. Demo OTP: $pendingOtp",15f,navy));r.addView(otp);r.addView(button("CONFIRM & REGISTER CREDIT",green){if(otp.text.toString()!=pendingOtp){otp.error="Incorrect OTP";return@button};val rate=roi/1200.0;val emi=if(method=="One-time")p else if(rate==0.0)p/tenor else p*rate*(1+rate).pow(tenor)/((1+rate).pow(tenor)-1);val payable=emi*if(method=="One-time")1 else tenor;val interest=(payable-p).coerceAtLeast(0.0);val id=db.addCredit(b,g,type,"Credit Given",p,roi,tenor,method,emi,interest,payable,start,end,0.0,"",null,invoice,false,end,0);if(id>0){AlertDialog.Builder(this).setTitle("Credit Registered").setMessage("Credit ID created successfully.\n${db.creditDetail(id)?.creditId ?: ""}").setPositiveButton("VIEW HISTORY"){_,_->history(null)}.setNegativeButton("DASHBOARD"){_,_->dashboard()}.show()}else Toast.makeText(this,"Could not register credit",Toast.LENGTH_LONG).show()});show(r)}
    private fun history(direction:String?){val r=page("Credit History","Full registered-credit view",::dashboard);val rows=db.credits(direction);if(rows.isEmpty())r.addView(text("No credits registered yet.",15f,Color.GRAY));rows.forEach{c->val paid=db.paidForCredit(c.id);card(r,"₹",c.borrowerName,"${c.creditId} • ${c.type}\nPrincipal ${money(c.amount)} • Outstanding ${money((c.payable-paid).coerceAtLeast(0.0))}\n${c.method} • ${c.status}",if(c.status=="ACTIVE")blue:red){AlertDialog.Builder(this).setTitle(c.creditId).setMessage("Borrower: ${c.borrowerName}\nAmount: ${money(c.amount)}\nROI: ${c.roi}%\nTotal payable: ${money(c.payable)}\nPaid: ${money(paid)}\nStart: ${c.start}\nEnd: ${c.end}").setPositiveButton("OK",null).show()}};show(r)}
    private fun repayments(overdue:Boolean){val r=page(if(overdue)"Overdue Payments"else"Repayment Centre","Record payments without losing history",::dashboard);val rows=db.schedules(overdue);if(rows.isEmpty())r.addView(text("No ${if(overdue)"overdue"else"pending"} schedules.",15f,Color.GRAY));rows.forEach{s->card(r,"₹",s.creditId,"Due ${s.dueDate} • ${money(s.amount)} • ${s.status}",if(s.status=="OVERDUE")red:green){val e=input("Payment amount",null,true).apply{setText(s.amount.toString())};AlertDialog.Builder(this).setTitle("Record repayment").setView(e).setPositiveButton("SAVE"){_,_->val a=e.text.toString().toDoubleOrNull()?:0.0;if(a>0&&db.recordPayment(s.id,a)){Toast.makeText(this,"Payment recorded",Toast.LENGTH_SHORT).show();repayments(overdue)}}.setNegativeButton("CANCEL",null).show()}};show(r)}
    private fun documents(){val r=page("Documents & Consent","Document readiness centre",::dashboard);r.addView(text("Digital documentation",23f,navy));r.addView(text("Keep credit terms, consent status, promissory-note references and supporting files linked to the credit record.",15f));r.addView(button("SELECT DOCUMENT / INVOICE",teal){startActivity(Intent(Intent.ACTION_OPEN_DOCUMENT).apply{type="application/pdf";addCategory(Intent.CATEGORY_OPENABLE)})});r.addView(button("PROMISSORY NOTE — READY FOR ATTACHMENT",blue){Toast.makeText(this,"Template-ready workflow. Legal review should be completed before production use.",Toast.LENGTH_LONG).show()});r.addView(button("BACK TO DASHBOARD",green){dashboard()});show(r)}
    private fun lender(){val u=db.userData();val r=page("Lender Profile","Profile and optional banking/NACH details",::dashboard);r.addView(text(u?.name?:"",24f,navy));r.addView(text("Unique ID: ${u?.id ?: "—"}\nMobile: ${u?.mobile ?: "—"}\nAddress: ${u?.address ?: "—"}",15f));r.addView(button("BANK / NACH DETAILS (OPTIONAL)",teal){bankForm(u?.id?:"")});r.addView(button("DASHBOARD",blue){dashboard()});show(r)}
    private fun bankForm(owner:String){val r=page("Bank / NACH","Optional payment mandate information",::lender);val h=input("Account holder");val b=input("Bank name");val a=input("Account number");val i=input("IFSC");val u=input("UPI ID");val n=CheckBox(this).apply{text="NACH enabled"};listOf(h,b,a,i,u).forEach{r.addView(it,LinearLayout.LayoutParams(-1,dp(56)).apply{setMargins(0,dp(4),0,dp(4))})};r.addView(n);r.addView(button("SAVE",green){if(db.saveBank("LENDER",owner,h.text.toString(),b.text.toString(),a.text.toString(),i.text.toString(),u.text.toString(),n.isChecked)>0){Toast.makeText(this,"Bank details saved",Toast.LENGTH_SHORT).show();lender()}});show(r)}
    private fun pickPhoto(target:ImageView){startActivityForResult(Intent(Intent.ACTION_GET_CONTENT).apply{type="image/*";addCategory(Intent.CATEGORY_OPENABLE)},901);target.tag="photo"}
    override fun onActivityResult(requestCode:Int,resultCode:Int,data:Intent?){super.onActivityResult(requestCode,resultCode,data);if(requestCode==901&&resultCode==RESULT_OK){selectedPhoto=data?.data}}
    private fun money(x:Double)=String.format(Locale.US,"₹%,.2f",x)
}
