package com.udhaardaar.mvp

import android.content.ContentValues
import android.content.Context
import android.database.Cursor
import android.database.sqlite.SQLiteDatabase
import android.database.sqlite.SQLiteOpenHelper
import java.text.SimpleDateFormat
import java.util.Calendar
import java.util.Date
import java.util.Locale

class V32DatabaseHelper(context: Context) : SQLiteOpenHelper(context, "udhaardaar_v32.db", null, 4) {
    data class User(val id:String,val name:String,val mobile:String,val address:String,val email:String,val photo:String?)
    data class ProfileRow(val rowId:Long,val id:String,val name:String,val mobile:String,val alternate:String="",val address:String="",val city:String="",val state:String="",val pin:String="",val email:String="",val pan:String="",val aadhaar:String="",val occupation:String="",val business:String="",val gstin:String="",val photo:String?)
    data class CreditRow(val id:Long,val creditId:String,val borrowerName:String,val borrowerId:String,val type:String,val direction:String,val amount:Double,val roi:Double,val method:String,val installment:Double,val interest:Double,val payable:Double,val start:String,val end:String,val dueDate:String,val gstin:String,val invoiceUri:String,val nach:Boolean,val status:String)
    data class ScheduleRow(val id:Long,val creditId:String,val dueDate:String,val amount:Double,val status:String)
    data class Summary(val total:Double,val outstanding:Double,val active:Int,val overdue:Int)

    override fun onCreate(db:SQLiteDatabase){
        db.execSQL("CREATE TABLE user_profile(id INTEGER PRIMARY KEY AUTOINCREMENT,unique_id TEXT UNIQUE NOT NULL,name TEXT NOT NULL,mobile TEXT NOT NULL,address TEXT,email TEXT,photo_uri TEXT,created_at TEXT NOT NULL)")
        db.execSQL("CREATE TABLE profiles(id INTEGER PRIMARY KEY AUTOINCREMENT,unique_id TEXT UNIQUE NOT NULL,role TEXT NOT NULL,name TEXT NOT NULL,mobile TEXT NOT NULL,alternate_mobile TEXT,address TEXT,city TEXT,state TEXT,pin TEXT,email TEXT,pan TEXT,aadhaar TEXT,occupation TEXT,business_name TEXT,gstin TEXT,photo_uri TEXT,created_at TEXT NOT NULL)")
        db.execSQL("CREATE TABLE credits(id INTEGER PRIMARY KEY AUTOINCREMENT,credit_id TEXT UNIQUE NOT NULL,borrower_id INTEGER NOT NULL,guarantor_id INTEGER,credit_type TEXT NOT NULL,direction TEXT NOT NULL,principal REAL NOT NULL DEFAULT 0,roi REAL NOT NULL DEFAULT 0,tenor_months INTEGER NOT NULL DEFAULT 1,repayment_method TEXT NOT NULL,installment REAL NOT NULL DEFAULT 0,total_interest REAL NOT NULL DEFAULT 0,total_payable REAL NOT NULL DEFAULT 0,start_date TEXT NOT NULL,end_date TEXT NOT NULL,otp_verified INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'ACTIVE',created_at TEXT NOT NULL,invoice_amount REAL NOT NULL DEFAULT 0,gstin TEXT,invoice_uri TEXT,invoice_text TEXT,nach_enabled INTEGER NOT NULL DEFAULT 0,due_date TEXT,due_day INTEGER DEFAULT 0,terms_version TEXT DEFAULT 'V3.2.2')")
        db.execSQL("CREATE TABLE repayments(id INTEGER PRIMARY KEY AUTOINCREMENT,credit_id INTEGER NOT NULL,amount REAL NOT NULL,principal_component REAL NOT NULL DEFAULT 0,interest_component REAL NOT NULL DEFAULT 0,repayment_date TEXT NOT NULL)")
        db.execSQL("CREATE TABLE repayment_schedule(id INTEGER PRIMARY KEY AUTOINCREMENT,credit_id INTEGER NOT NULL,installment_no INTEGER NOT NULL,due_date TEXT NOT NULL,amount REAL NOT NULL,paid_amount REAL NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'DUE')")
        db.execSQL("CREATE TABLE bank_accounts(id INTEGER PRIMARY KEY AUTOINCREMENT,owner_type TEXT NOT NULL,owner_id TEXT NOT NULL,holder_name TEXT,bank_name TEXT,account_number TEXT,ifsc TEXT,upi TEXT,nach_enabled INTEGER DEFAULT 0,created_at TEXT NOT NULL)")
        db.execSQL("CREATE TABLE activity_log(id INTEGER PRIMARY KEY AUTOINCREMENT,actor_id TEXT,profile_id INTEGER,credit_id INTEGER,activity_type TEXT NOT NULL,description TEXT,created_at TEXT NOT NULL)")
    }
    override fun onUpgrade(db:SQLiteDatabase,oldVersion:Int,newVersion:Int){
        if(oldVersion<4){
            runCatching{db.execSQL("ALTER TABLE credits ADD COLUMN terms_version TEXT DEFAULT 'V3.2.2'")}
            runCatching{db.execSQL("CREATE TABLE IF NOT EXISTS repayment_schedule(id INTEGER PRIMARY KEY AUTOINCREMENT,credit_id INTEGER NOT NULL,installment_no INTEGER NOT NULL,due_date TEXT NOT NULL,amount REAL NOT NULL,paid_amount REAL NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'DUE')")}
            runCatching{db.execSQL("CREATE TABLE IF NOT EXISTS bank_accounts(id INTEGER PRIMARY KEY AUTOINCREMENT,owner_type TEXT NOT NULL,owner_id TEXT NOT NULL,holder_name TEXT,bank_name TEXT,account_number TEXT,ifsc TEXT,upi TEXT,nach_enabled INTEGER DEFAULT 0,created_at TEXT NOT NULL)")}
            runCatching{db.execSQL("CREATE TABLE IF NOT EXISTS activity_log(id INTEGER PRIMARY KEY AUTOINCREMENT,actor_id TEXT,profile_id INTEGER,credit_id INTEGER,activity_type TEXT NOT NULL,description TEXT,created_at TEXT NOT NULL)")}
        }
    }
    private fun now()=SimpleDateFormat("yyyy-MM-dd HH:mm:ss",Locale.US).format(Date())
    private fun fmt(d:Date)=SimpleDateFormat("yyyy-MM-dd",Locale.US).format(d)
    private fun parseDate(s:String):Date=runCatching{SimpleDateFormat("yyyy-MM-dd",Locale.US).parse(s)!!}.getOrElse{Date()}
    fun hasUser():Boolean=readableDatabase.rawQuery("SELECT 1 FROM user_profile LIMIT 1",null).use{it.moveToFirst()}
    fun userData():User?=readableDatabase.rawQuery("SELECT unique_id,name,mobile,address,email,photo_uri FROM user_profile LIMIT 1",null).use{if(!it.moveToFirst())null else User(it.getString(0),it.getString(1),it.getString(2),it.getString(3)?:"",it.getString(4)?:"",it.getString(5))}
    fun saveUser(id:String,name:String,mobile:String,address:String,email:String,photo:String?):Long{val v=ContentValues().apply{put("unique_id",id);put("name",name);put("mobile",mobile);put("address",address);put("email",email);put("photo_uri",photo);put("created_at",now())};return writableDatabase.insert("user_profile",null,v)}
    fun upsertProfile(rowId:Long?,role:String,id:String,name:String,mobile:String,alternate:String,address:String,city:String,state:String,pin:String,email:String,pan:String,aadhaar:String,occupation:String,business:String,gstin:String,photo:String?):Long{val v=ContentValues().apply{put("unique_id",id);put("role",role);put("name",name);put("mobile",mobile);put("alternate_mobile",alternate);put("address",address);put("city",city);put("state",state);put("pin",pin);put("email",email);put("pan",pan);put("aadhaar",aadhaar);put("occupation",occupation);put("business_name",business);put("gstin",gstin);put("photo_uri",photo);put("created_at",now())};return if(rowId==null)writableDatabase.insert("profiles",null,v)else{writableDatabase.update("profiles",v,"id=?",arrayOf(rowId.toString()));rowId}}
    private fun profileFrom(c:Cursor)=ProfileRow(c.getLong(0),c.getString(1),c.getString(2),c.getString(3),c.getString(4)?:"",c.getString(5)?:"",c.getString(6)?:"",c.getString(7)?:"",c.getString(8)?:"",c.getString(9)?:"",c.getString(10)?:"",c.getString(11)?:"",c.getString(12)?:"",c.getString(13)?:"",c.getString(14)?:"",c.getString(15))
    fun searchProfiles(role:String,q:String):List<ProfileRow>{val out=mutableListOf<ProfileRow>();val t="%${q.trim()}%";readableDatabase.rawQuery("SELECT id,unique_id,name,mobile,alternate_mobile,address,city,state,pin,email,pan,aadhaar,occupation,business_name,gstin,photo_uri FROM profiles WHERE role=? AND(name LIKE ? OR mobile LIKE ? OR pan LIKE ? OR aadhaar LIKE ? OR unique_id LIKE ? OR gstin LIKE ?) ORDER BY name COLLATE NOCASE",arrayOf(role,t,t,t,t,t,t)).use{while(it.moveToNext())out.add(profileFrom(it))};return out}
    fun profileData(id:Long):ProfileRow?=readableDatabase.rawQuery("SELECT id,unique_id,name,mobile,alternate_mobile,address,city,state,pin,email,pan,aadhaar,occupation,business_name,gstin,photo_uri FROM profiles WHERE id=?",arrayOf(id.toString())).use{if(!it.moveToFirst())null else profileFrom(it)}
    fun addCredit(borrower:Long,guarantor:Long?,type:String,direction:String,principal:Double,roi:Double,tenor:Int,method:String,installment:Double,interest:Double,payable:Double,start:String,end:String,invoiceAmount:Double,gstin:String,invoiceUri:String?,invoiceText:String,nach:Boolean,dueDate:String,dueDay:Int):Long{val v=ContentValues().apply{put("credit_id","CR-${System.currentTimeMillis()}");put("borrower_id",borrower);if(guarantor==null)putNull("guarantor_id")else put("guarantor_id",guarantor);put("credit_type",type);put("direction",direction);put("principal",principal);put("roi",roi);put("tenor_months",tenor);put("repayment_method",method);put("installment",installment);put("total_interest",interest);put("total_payable",payable);put("start_date",start);put("end_date",end);put("otp_verified",1);put("status","ACTIVE");put("created_at",now());put("invoice_amount",invoiceAmount);put("gstin",gstin);put("invoice_uri",invoiceUri);put("invoice_text",invoiceText);put("nach_enabled",if(nach)1 else 0);put("due_date",dueDate);put("due_day",dueDay);put("terms_version","V3.2.2")};return writableDatabase.insert("credits",null,v)}
    fun createSchedule(creditId:Long,type:String,start:String,end:String,amount:Double,count:Int,dueDay:Int){val base=Calendar.getInstance();base.time=parseDate(start);val n=if(type=="Trade Credit"||type=="Advance")1 else count.coerceIn(1,240);for(i in 1..n){val x=base.clone() as Calendar;if(i>1)x.add(Calendar.MONTH,i-1);if(type=="Rental / Lease"&&dueDay in 1..31)x.set(Calendar.DAY_OF_MONTH,minOf(dueDay,x.getActualMaximum(Calendar.DAY_OF_MONTH)));if(type=="Trade Credit"||type=="Advance")x.time=parseDate(end);val v=ContentValues().apply{put("credit_id",creditId);put("installment_no",i);put("due_date",fmt(x.time));put("amount",amount);put("paid_amount",0.0);put("status",if(x.time.before(Date()))"OVERDUE"else"DUE")};writableDatabase.insert("repayment_schedule",null,v)}}
    private fun creditFrom(c:Cursor)=CreditRow(c.getLong(0),c.getString(1),c.getString(2),c.getString(3),c.getString(4),c.getString(5),c.getDouble(6),c.getDouble(7),c.getString(8),c.getDouble(9),c.getDouble(10),c.getDouble(11),c.getString(12),c.getString(13),c.getString(14),c.getString(15),c.getString(16),c.getInt(17)==1,c.getString(18))
    fun credits(direction:String?=null):List<CreditRow>{val out=mutableListOf<CreditRow>();val sql="SELECT c.id,c.credit_id,p.name,p.unique_id,c.credit_type,c.direction,c.principal,c.roi,c.repayment_method,c.installment,c.total_interest,c.total_payable,c.start_date,c.end_date,COALESCE(c.due_date,c.end_date),COALESCE(c.gstin,''),COALESCE(c.invoice_uri,''),c.nach_enabled,c.status FROM credits c JOIN profiles p ON p.id=c.borrower_id "+if(direction==null)""else"WHERE c.direction=? "+"ORDER BY c.id DESC";readableDatabase.rawQuery(sql,if(direction==null)null else arrayOf(direction)).use{while(it.moveToNext())out.add(creditFrom(it))};return out}
    fun creditsForBorrower(id:Long)=credits().filter{borrowerRow(it.id)==id}
    private fun borrowerRow(id:Long):Long=readableDatabase.rawQuery("SELECT borrower_id FROM credits WHERE id=?",arrayOf(id.toString())).use{if(it.moveToFirst())it.getLong(0)else -1L}
    fun creditDetail(id:Long):CreditRow?=readableDatabase.rawQuery("SELECT c.id,c.credit_id,p.name,p.unique_id,c.credit_type,c.direction,c.principal,c.roi,c.repayment_method,c.installment,c.total_interest,c.total_payable,c.start_date,c.end_date,COALESCE(c.due_date,c.end_date),COALESCE(c.gstin,''),COALESCE(c.invoice_uri,''),c.nach_enabled,c.status FROM credits c JOIN profiles p ON p.id=c.borrower_id WHERE c.id=?",arrayOf(id.toString())).use{if(!it.moveToFirst())null else creditFrom(it)}
    fun paidForCredit(id:Long):Double=readableDatabase.rawQuery("SELECT COALESCE(SUM(amount),0) FROM repayments WHERE credit_id=?",arrayOf(id.toString())).use{it.moveToFirst();it.getDouble(0)}
    fun borrowerCreditSummary(id:Long):Summary{var total=0.0;var outstanding=0.0;var active=0;var overdue=0;creditsForBorrower(id).forEach{total+=it.amount;outstanding+=(it.payable-paidForCredit(it.id)).coerceAtLeast(0.0);if(it.status=="ACTIVE")active++;if(dueCountForCredit(it.id,true)>0)overdue++};return Summary(total,outstanding,active,overdue)}
    private fun updateDueStatuses(){writableDatabase.execSQL("UPDATE repayment_schedule SET status='OVERDUE' WHERE due_date<? AND status='DUE'",arrayOf(fmt(Date())))}
    private fun dueCountForCredit(id:Long,overdue:Boolean)=readableDatabase.rawQuery("SELECT COUNT(*) FROM repayment_schedule WHERE credit_id=? AND status=?",arrayOf(id.toString(),if(overdue)"OVERDUE"else"DUE")).use{it.moveToFirst();it.getInt(0)}
    fun dueCount(overdue:Boolean):Int{updateDueStatuses();return readableDatabase.rawQuery("SELECT COUNT(*) FROM repayment_schedule WHERE status=?",arrayOf(if(overdue)"OVERDUE"else"DUE")).use{it.moveToFirst();it.getInt(0)}}
    fun totalCredit(direction:String):Double=readableDatabase.rawQuery("SELECT COALESCE(SUM(CASE WHEN credit_type='Rental / Lease' THEN installment*tenor_months ELSE principal END),0) FROM credits WHERE direction=?",arrayOf(direction)).use{it.moveToFirst();it.getDouble(0)}
    fun schedules(creditId:Long?,overdueOnly:Boolean):List<ScheduleRow>{updateDueStatuses();val out=mutableListOf<ScheduleRow>();val where=when{creditId!=null&&overdueOnly->"WHERE s.credit_id=? AND s.status='OVERDUE'";creditId!=null->"WHERE s.credit_id=?";overdueOnly->"WHERE s.status='OVERDUE'";else->"WHERE s.status IN('DUE','OVERDUE')"};val args=if(creditId==null)null else arrayOf(creditId.toString());readableDatabase.rawQuery("SELECT s.id,c.credit_id,s.due_date,s.amount,s.status FROM repayment_schedule s JOIN credits c ON c.id=s.credit_id $where ORDER BY s.due_date",args).use{while(it.moveToNext())out.add(ScheduleRow(it.getLong(0),it.getString(1),it.getString(2),it.getDouble(3),it.getString(4)))};return out}
    fun creditIdByCode(code:String):Long=readableDatabase.rawQuery("SELECT id FROM credits WHERE credit_id=?",arrayOf(code)).use{if(it.moveToFirst())it.getLong(0)else -1L}
    fun nextSchedule(id:Long)=schedules(id,false).firstOrNull()
    fun futureCredits():List<Long>{val out=mutableListOf<Long>();readableDatabase.rawQuery("SELECT DISTINCT credit_id FROM repayment_schedule WHERE status='DUE'",null).use{while(it.moveToNext())out.add(it.getLong(0))};return out}
    fun recordPayment(scheduleId:Long,creditId:Long,amount:Double){val v=ContentValues().apply{put("credit_id",creditId);put("amount",amount);put("principal_component",amount);put("interest_component",0.0);put("repayment_date",now())};writableDatabase.insert("repayments",null,v);readableDatabase.rawQuery("SELECT amount,paid_amount FROM repayment_schedule WHERE id=?",arrayOf(scheduleId.toString())).use{if(it.moveToFirst()){val paid=it.getDouble(1)+amount;val status=if(paid+0.005>=it.getDouble(0))"PAID"else"DUE";writableDatabase.update("repayment_schedule",ContentValues().apply{put("paid_amount",paid);put("status",status)},"id=?",arrayOf(scheduleId.toString()))}}}
    fun saveBank(type:String,ownerId:String,holder:String,bank:String,account:String,ifsc:String,upi:String,nach:Boolean){val v=ContentValues().apply{put("owner_type",type);put("owner_id",ownerId);put("holder_name",holder);put("bank_name",bank);put("account_number",account);put("ifsc",ifsc);put("upi",upi);put("nach_enabled",if(nach)1 else 0);put("created_at",now())};writableDatabase.insert("bank_accounts",null,v)}
    fun log(actor:String,profile:Long?,credit:Long?,type:String,description:String){val v=ContentValues().apply{put("actor_id",actor);if(profile==null)putNull("profile_id")else put("profile_id",profile);if(credit==null)putNull("credit_id")else put("credit_id",credit);put("activity_type",type);put("description",description);put("created_at",now())};writableDatabase.insert("activity_log",null,v)}
}
