package com.udhaardaar.mvp

import android.content.ContentValues
import android.content.Context
import android.database.sqlite.SQLiteDatabase
import android.database.sqlite.SQLiteOpenHelper
import java.text.SimpleDateFormat
import java.util.*

class V32DatabaseHelper(context: Context) : SQLiteOpenHelper(context, "udhaardaar_v32.db", null, 4) {
    data class User(val id:String,val name:String,val mobile:String,val address:String,val email:String,val photo:String?)
    data class ProfileRow(val rowId:Long,val id:String,val name:String,val mobile:String,val alternate:String,val address:String,val city:String,val state:String,val pin:String,val email:String,val pan:String,val aadhaar:String,val occupation:String,val business:String,val gstin:String,val photo:String?)
    data class CreditRow(val id:Long,val creditId:String,val borrowerName:String,val borrowerId:String,val type:String,val direction:String,val amount:Double,val roi:Double,val method:String,val installment:Double,val interest:Double,val payable:Double,val start:String,val end:String,val dueDate:String,val gstin:String,val invoiceUri:String,val nach:Boolean,val status:String)
    data class ScheduleRow(val id:Long,val creditId:String,val dueDate:String,val amount:Double,val status:String)
    data class Summary(val total:Double,val outstanding:Double,val active:Int,val overdue:Int)
    private fun now()=SimpleDateFormat("yyyy-MM-dd HH:mm:ss",Locale.US).format(Date())
    private fun parseDate(s:String):Date=runCatching{SimpleDateFormat("dd/MM/yyyy",Locale.US).parse(s)!!}.getOrElse{Date()}
    private fun fmt(d:Date)=SimpleDateFormat("dd/MM/yyyy",Locale.US).format(d)
    override fun onCreate(db:SQLiteDatabase){
        db.execSQL("CREATE TABLE user_profile(id INTEGER PRIMARY KEY AUTOINCREMENT,unique_id TEXT UNIQUE NOT NULL,name TEXT NOT NULL,mobile TEXT NOT NULL,address TEXT,email TEXT,photo_uri TEXT,created_at TEXT NOT NULL)")
        db.execSQL("CREATE TABLE profiles(id INTEGER PRIMARY KEY AUTOINCREMENT,unique_id TEXT UNIQUE NOT NULL,role TEXT NOT NULL,name TEXT NOT NULL,mobile TEXT NOT NULL,alternate_mobile TEXT,address TEXT,city TEXT,state TEXT,pin TEXT,email TEXT,pan TEXT,aadhaar TEXT,occupation TEXT,business_name TEXT,gstin TEXT,photo_uri TEXT,created_at TEXT NOT NULL)")
        db.execSQL("CREATE TABLE credits(id INTEGER PRIMARY KEY AUTOINCREMENT,credit_id TEXT UNIQUE NOT NULL,borrower_id INTEGER NOT NULL,guarantor_id INTEGER,credit_type TEXT NOT NULL,direction TEXT NOT NULL,principal REAL NOT NULL,roi REAL NOT NULL,tenor_months INTEGER NOT NULL,repayment_method TEXT NOT NULL,installment REAL NOT NULL,total_interest REAL NOT NULL,total_payable REAL NOT NULL,start_date TEXT NOT NULL,end_date TEXT NOT NULL,otp_verified INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'ACTIVE',created_at TEXT NOT NULL,invoice_amount REAL DEFAULT 0,gstin TEXT,invoice_uri TEXT,invoice_text TEXT,nach_enabled INTEGER DEFAULT 0,due_date TEXT,due_day INTEGER DEFAULT 0,terms_version TEXT DEFAULT 'V3.2.2')")
        db.execSQL("CREATE TABLE repayments(id INTEGER PRIMARY KEY AUTOINCREMENT,credit_id INTEGER NOT NULL,amount REAL NOT NULL,principal_component REAL NOT NULL,interest_component REAL NOT NULL,repayment_date TEXT NOT NULL)")
        db.execSQL("CREATE TABLE repayment_schedule(id INTEGER PRIMARY KEY AUTOINCREMENT,credit_id INTEGER NOT NULL,installment_no INTEGER NOT NULL,due_date TEXT NOT NULL,amount REAL NOT NULL,paid_amount REAL NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'DUE')")
        db.execSQL("CREATE TABLE bank_accounts(id INTEGER PRIMARY KEY AUTOINCREMENT,owner_type TEXT NOT NULL,owner_id TEXT NOT NULL,holder_name TEXT,bank_name TEXT,account_number TEXT,ifsc TEXT,upi TEXT,nach_enabled INTEGER DEFAULT 0,created_at TEXT NOT NULL)")
    }
    override fun onUpgrade(db:SQLiteDatabase,oldVersion:Int,newVersion:Int){
        if(oldVersion<4){ listOf("bank_accounts","repayment_schedule","repayments","credits","profiles","user_profile").forEach{db.execSQL("DROP TABLE IF EXISTS $it")}; onCreate(db) }
    }
    fun hasUser()=readableDatabase.rawQuery("SELECT 1 FROM user_profile LIMIT 1",null).use{it.moveToFirst()}
    fun userData():User?=readableDatabase.rawQuery("SELECT unique_id,name,mobile,address,email,photo_uri FROM user_profile LIMIT 1",null).use{c->if(c.moveToFirst())User(c.getString(0),c.getString(1),c.getString(2),c.getString(3) ?: "",c.getString(4) ?: "",c.getString(5))else null}
    fun saveUser(id:String,name:String,mobile:String,address:String,email:String,photo:String?):Long=ContentValues().apply{put("unique_id",id);put("name",name);put("mobile",mobile);put("address",address);put("email",email);put("photo_uri",photo);put("created_at",now())}.let{writableDatabase.insert("user_profile",null,it)}
    fun upsertProfile(rowId:Long?,role:String,id:String,name:String,mobile:String,alternate:String,address:String,city:String,state:String,pin:String,email:String,pan:String,aadhaar:String,occupation:String,business:String,gstin:String,photo:String?):Long{val v=ContentValues().apply{put("unique_id",id);put("role",role);put("name",name);put("mobile",mobile);put("alternate_mobile",alternate);put("address",address);put("city",city);put("state",state);put("pin",pin);put("email",email);put("pan",pan);put("aadhaar",aadhaar);put("occupation",occupation);put("business_name",business);put("gstin",gstin);put("photo_uri",photo);put("created_at",now())};return if(rowId==null)writableDatabase.insert("profiles",null,v)else{writableDatabase.update("profiles",v,"id=?",arrayOf(rowId.toString()));rowId}}
    private fun profileFrom(c:android.database.Cursor)=ProfileRow(c.getLong(0),c.getString(1),c.getString(2),c.getString(3),c.getString(4) ?: "",c.getString(5) ?: "",c.getString(6) ?: "",c.getString(7) ?: "",c.getString(8) ?: "",c.getString(9) ?: "",c.getString(10) ?: "",c.getString(11) ?: "",c.getString(12) ?: "",c.getString(13) ?: "",c.getString(14) ?: "",c.getString(15))
    fun searchProfiles(role:String,q:String):List<ProfileRow>{val out=mutableListOf<ProfileRow>();val t="%${q.trim()}%";readableDatabase.rawQuery("SELECT id,unique_id,name,mobile,alternate_mobile,address,city,state,pin,email,pan,aadhaar,occupation,business_name,gstin,photo_uri FROM profiles WHERE role=? AND (name LIKE ? OR mobile LIKE ? OR pan LIKE ? OR aadhaar LIKE ? OR unique_id LIKE ? OR gstin LIKE ?) ORDER BY name",arrayOf(role,t,t,t,t,t,t)).use{c->while(c.moveToNext())out.add(profileFrom(c))};return out}
    fun profileData(id:Long):ProfileRow?=readableDatabase.rawQuery("SELECT id,unique_id,name,mobile,alternate_mobile,address,city,state,pin,email,pan,aadhaar,occupation,business_name,gstin,photo_uri FROM profiles WHERE id=?",arrayOf(id.toString())).use{c->if(c.moveToFirst())profileFrom(c)else null}
    fun addCredit(borrower:Long,guarantor:Long?,type:String,direction:String,principal:Double,roi:Double,tenor:Int,method:String,installment:Double,interest:Double,payable:Double,start:String,end:String,invoiceAmount:Double,gstin:String,invoiceUri:String?,invoiceText:String,nach:Boolean,dueDate:String,dueDay:Int):Long{val v=ContentValues().apply{put("credit_id","CR-${System.currentTimeMillis()}");put("borrower_id",borrower);if(guarantor==null)putNull("guarantor_id")else put("guarantor_id",guarantor);put("credit_type",type);put("direction",direction);put("principal",principal);put("roi",roi);put("tenor_months",tenor);put("repayment_method",method);put("installment",installment);put("total_interest",interest);put("total_payable",payable);put("start_date",start);put("end_date",end);put("otp_verified",1);put("status","ACTIVE");put("created_at",now());put("invoice_amount",invoiceAmount);put("gstin",gstin);put("invoice_uri",invoiceUri);put("invoice_text",invoiceText);put("nach_enabled",if(nach)1 else 0);put("due_date",dueDate);put("due_day",dueDay)};val id=writableDatabase.insert("credits",null,v);if(id>0)createSchedule(id,start,end,installment,if(method=="One-time")1 else tenor);return id}
    private fun createSchedule(creditId:Long,start:String,end:String,amount:Double,count:Int){val cal=Calendar.getInstance();cal.time=parseDate(start);for(i in 1..count.coerceIn(1,240)){if(i>1)cal.add(Calendar.MONTH,1);val d=if(count==1)parseDate(end)else cal.time;writableDatabase.insert("repayment_schedule",null,ContentValues().apply{put("credit_id",creditId);put("installment_no",i);put("due_date",fmt(d));put("amount",amount);put("status",if(d.before(Date()))"OVERDUE"else"DUE")})}}
    private fun creditFrom(c:android.database.Cursor)=CreditRow(c.getLong(0),c.getString(1),c.getString(2),c.getString(3),c.getString(4),c.getString(5),c.getDouble(6),c.getDouble(7),c.getString(8),c.getDouble(9),c.getDouble(10),c.getDouble(11),c.getString(12),c.getString(13),c.getString(14),c.getString(15) ?: "",c.getString(16) ?: "",c.getInt(17)==1,c.getString(18))
    fun credits(direction:String?=null):List<CreditRow>{val out=mutableListOf<CreditRow>();val sql="SELECT c.id,c.credit_id,p.name,p.unique_id,c.credit_type,c.direction,c.principal,c.roi,c.repayment_method,c.installment,c.total_interest,c.total_payable,c.start_date,c.end_date,COALESCE(c.due_date,c.end_date),c.gstin,c.invoice_uri,c.nach_enabled,c.status FROM credits c JOIN profiles p ON p.id=c.borrower_id ${if(direction!=null)"WHERE c.direction=?"else""} ORDER BY c.id DESC";readableDatabase.rawQuery(sql,if(direction!=null)arrayOf(direction)else null).use{c->while(c.moveToNext())out.add(creditFrom(c))};return out}
    fun creditDetail(id:Long)=credits().firstOrNull{it.id==id}
    fun paidForCredit(id:Long)=readableDatabase.rawQuery("SELECT COALESCE(SUM(amount),0) FROM repayments WHERE credit_id=?",arrayOf(id.toString())).use{c->c.moveToFirst();c.getDouble(0)}
    fun borrowerCreditSummary(id:Long):Summary{val list=credits().filter{borrowerId(it.id)==id};return Summary(list.sumOf{it.amount},list.sumOf{(it.payable-paidForCredit(it.id)).coerceAtLeast(0.0)},list.count{it.status=="ACTIVE"},list.count{dueCountForCredit(it.id)>0})}
    private fun borrowerId(id:Long)=readableDatabase.rawQuery("SELECT borrower_id FROM credits WHERE id=?",arrayOf(id.toString())).use{c->if(c.moveToFirst())c.getLong(0)else -1}
    private fun dueCountForCredit(id:Long)=readableDatabase.rawQuery("SELECT COUNT(*) FROM repayment_schedule WHERE credit_id=? AND status IN('DUE','OVERDUE')",arrayOf(id.toString())).use{c->c.moveToFirst();c.getInt(0)}
    fun dueCount(overdue:Boolean)=readableDatabase.rawQuery("SELECT COUNT(*) FROM repayment_schedule WHERE status=?",arrayOf(if(overdue)"OVERDUE"else"DUE")).use{c->c.moveToFirst();c.getInt(0)}
    fun totalCredit(direction:String)=readableDatabase.rawQuery("SELECT COALESCE(SUM(principal),0) FROM credits WHERE direction=?",arrayOf(direction)).use{c->c.moveToFirst();c.getDouble(0)}
    fun schedules(overdueOnly:Boolean=false):List<ScheduleRow>{val out=mutableListOf<ScheduleRow>();val where=if(overdueOnly)"WHERE s.status='OVERDUE'"else"WHERE s.status IN('DUE','OVERDUE')";readableDatabase.rawQuery("SELECT s.id,c.credit_id,s.due_date,s.amount,s.status FROM repayment_schedule s JOIN credits c ON c.id=s.credit_id $where ORDER BY s.due_date",null).use{c->while(c.moveToNext())out.add(ScheduleRow(c.getLong(0),c.getString(1),c.getString(2),c.getDouble(3),c.getString(4)))};return out}
    fun recordPayment(scheduleId:Long,amount:Double):Boolean{val c=readableDatabase.rawQuery("SELECT credit_id,amount,paid_amount FROM repayment_schedule WHERE id=?",arrayOf(scheduleId.toString()));if(!c.moveToFirst()){c.close();return false};val creditId=c.getLong(0);val due=c.getDouble(1);val paid=c.getDouble(2)+amount;c.close();writableDatabase.insert("repayments",null,ContentValues().apply{put("credit_id",creditId);put("amount",amount);put("principal_component",amount);put("interest_component",0.0);put("repayment_date",now())});writableDatabase.update("repayment_schedule",ContentValues().apply{put("paid_amount",paid);put("status",if(paid+0.005>=due)"PAID"else"DUE")},"id=?",arrayOf(scheduleId.toString()));return true}
    fun saveBank(ownerType:String,ownerId:String,holder:String,bank:String,account:String,ifsc:String,upi:String,nach:Boolean)=ContentValues().apply{put("owner_type",ownerType);put("owner_id",ownerId);put("holder_name",holder);put("bank_name",bank);put("account_number",account);put("ifsc",ifsc);put("upi",upi);put("nach_enabled",if(nach)1 else 0);put("created_at",now())}.let{writableDatabase.insert("bank_accounts",null,it)}
}
