package com.udhaardaar.mvp

import android.content.ContentValues
import android.content.Context
import android.database.sqlite.SQLiteDatabase
import android.database.sqlite.SQLiteOpenHelper

class V3DatabaseHelper(context: Context) : SQLiteOpenHelper(context, "udhaardaar_v3.db", null, 8) {
    override fun onConfigure(db: SQLiteDatabase) { super.onConfigure(db); db.setForeignKeyConstraintsEnabled(true) }
    override fun onCreate(db: SQLiteDatabase) {
        db.execSQL("CREATE TABLE parties(id INTEGER PRIMARY KEY AUTOINCREMENT,party_type TEXT NOT NULL DEFAULT 'PERSON',name TEXT NOT NULL,mobile TEXT,email TEXT,address TEXT,pincode TEXT,city TEXT,state TEXT,aadhaar TEXT,pan TEXT,gstin TEXT,business_name TEXT,photo_uri TEXT,notes TEXT,created_at TEXT NOT NULL)")
        db.execSQL("CREATE TABLE credits(id INTEGER PRIMARY KEY AUTOINCREMENT,credit_type TEXT NOT NULL,direction TEXT NOT NULL DEFAULT 'GIVEN',principal_amount REAL NOT NULL,interest_rate REAL NOT NULL DEFAULT 0,repayment_method TEXT NOT NULL,repayment_amount REAL NOT NULL DEFAULT 0,periodicity TEXT,start_date TEXT NOT NULL,end_date TEXT,next_due_date TEXT,grace_days INTEGER NOT NULL DEFAULT 0,lending_method TEXT DEFAULT 'OTHER',transaction_reference TEXT,invoice_number TEXT,invoice_uri TEXT,status TEXT NOT NULL DEFAULT 'ACTIVE',notes TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)")
        db.execSQL("CREATE TABLE credit_parties(id INTEGER PRIMARY KEY AUTOINCREMENT,credit_id INTEGER NOT NULL,party_id INTEGER NOT NULL,role TEXT NOT NULL,FOREIGN KEY(credit_id) REFERENCES credits(id) ON DELETE CASCADE,FOREIGN KEY(party_id) REFERENCES parties(id) ON DELETE RESTRICT,UNIQUE(credit_id,party_id,role))")
        db.execSQL("CREATE TABLE repayments(id INTEGER PRIMARY KEY AUTOINCREMENT,credit_id INTEGER NOT NULL,repayment_date TEXT NOT NULL,amount REAL NOT NULL,principal_component REAL NOT NULL DEFAULT 0,interest_component REAL NOT NULL DEFAULT 0,payment_mode TEXT,reference_number TEXT,notes TEXT,created_at TEXT NOT NULL,actor_party_id INTEGER NOT NULL,FOREIGN KEY(credit_id) REFERENCES credits(id) ON DELETE CASCADE,FOREIGN KEY(actor_party_id) REFERENCES parties(id) ON DELETE RESTRICT)")
        db.execSQL("CREATE TABLE guarantors(id INTEGER PRIMARY KEY AUTOINCREMENT,party_id INTEGER NOT NULL,relationship TEXT,consent_status TEXT NOT NULL DEFAULT 'PENDING',created_at TEXT NOT NULL,FOREIGN KEY(party_id) REFERENCES parties(id) ON DELETE RESTRICT)")
        db.execSQL("CREATE TABLE credit_guarantors(id INTEGER PRIMARY KEY AUTOINCREMENT,credit_id INTEGER NOT NULL,guarantor_id INTEGER NOT NULL,FOREIGN KEY(credit_id) REFERENCES credits(id) ON DELETE CASCADE,FOREIGN KEY(guarantor_id) REFERENCES guarantors(id) ON DELETE RESTRICT,UNIQUE(credit_id,guarantor_id))")
        db.execSQL("CREATE TABLE documents(id INTEGER PRIMARY KEY AUTOINCREMENT,credit_id INTEGER,party_id INTEGER,document_type TEXT NOT NULL,document_name TEXT,document_uri TEXT,verification_status TEXT NOT NULL DEFAULT 'PENDING',created_at TEXT NOT NULL,FOREIGN KEY(credit_id) REFERENCES credits(id) ON DELETE CASCADE,FOREIGN KEY(party_id) REFERENCES parties(id) ON DELETE RESTRICT)")
        db.execSQL("CREATE TABLE consents(id INTEGER PRIMARY KEY AUTOINCREMENT,credit_id INTEGER NOT NULL,party_id INTEGER NOT NULL,consent_type TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'PENDING',otp_verified INTEGER NOT NULL DEFAULT 0,consented_at TEXT,created_at TEXT NOT NULL,FOREIGN KEY(credit_id) REFERENCES credits(id) ON DELETE CASCADE,FOREIGN KEY(party_id) REFERENCES parties(id) ON DELETE RESTRICT)")
        db.execSQL("CREATE TABLE credit_access(id INTEGER PRIMARY KEY AUTOINCREMENT,credit_id INTEGER NOT NULL,party_id INTEGER NOT NULL,role TEXT NOT NULL,can_view INTEGER NOT NULL DEFAULT 0,can_repay INTEGER NOT NULL DEFAULT 0,can_edit INTEGER NOT NULL DEFAULT 0,consent_required INTEGER NOT NULL DEFAULT 1,FOREIGN KEY(credit_id) REFERENCES credits(id) ON DELETE CASCADE,FOREIGN KEY(party_id) REFERENCES parties(id) ON DELETE RESTRICT,UNIQUE(credit_id,party_id,role))")
        db.execSQL("CREATE TABLE activity_log(id INTEGER PRIMARY KEY AUTOINCREMENT,credit_id INTEGER,party_id INTEGER,activity_type TEXT NOT NULL,description TEXT,created_at TEXT NOT NULL,FOREIGN KEY(credit_id) REFERENCES credits(id) ON DELETE CASCADE,FOREIGN KEY(party_id) REFERENCES parties(id) ON DELETE RESTRICT)")
        db.execSQL("CREATE TABLE credit_payment_meta(credit_id INTEGER PRIMARY KEY,lending_method TEXT NOT NULL DEFAULT 'OTHER',transaction_reference TEXT,FOREIGN KEY(credit_id) REFERENCES credits(id) ON DELETE CASCADE)")
        createIndexes(db)
    }
    private fun createIndexes(db: SQLiteDatabase) { listOf("CREATE INDEX IF NOT EXISTS idx_parties_mobile ON parties(mobile)","CREATE INDEX IF NOT EXISTS idx_parties_pan ON parties(pan)","CREATE INDEX IF NOT EXISTS idx_parties_gstin ON parties(gstin)","CREATE INDEX IF NOT EXISTS idx_parties_aadhaar ON parties(aadhaar)","CREATE INDEX IF NOT EXISTS idx_credit_parties_credit ON credit_parties(credit_id)","CREATE INDEX IF NOT EXISTS idx_credit_parties_party ON credit_parties(party_id)","CREATE INDEX IF NOT EXISTS idx_repayments_credit ON repayments(credit_id)","CREATE INDEX IF NOT EXISTS idx_access_credit_party ON credit_access(credit_id,party_id)") .forEach(db::execSQL) }
    override fun onUpgrade(db: SQLiteDatabase, oldVersion: Int, newVersion: Int) {
        if (oldVersion < 6) db.execSQL("CREATE TABLE IF NOT EXISTS credit_parties(id INTEGER PRIMARY KEY AUTOINCREMENT,credit_id INTEGER NOT NULL,party_id INTEGER NOT NULL,role TEXT NOT NULL,FOREIGN KEY(credit_id) REFERENCES credits(id) ON DELETE CASCADE,FOREIGN KEY(party_id) REFERENCES parties(id) ON DELETE RESTRICT,UNIQUE(credit_id,party_id,role))")
        if (oldVersion < 7) db.execSQL("CREATE TABLE IF NOT EXISTS credit_access(id INTEGER PRIMARY KEY AUTOINCREMENT,credit_id INTEGER NOT NULL,party_id INTEGER NOT NULL,role TEXT NOT NULL,can_view INTEGER NOT NULL DEFAULT 0,can_repay INTEGER NOT NULL DEFAULT 0,can_edit INTEGER NOT NULL DEFAULT 0,consent_required INTEGER NOT NULL DEFAULT 1,FOREIGN KEY(credit_id) REFERENCES credits(id) ON DELETE CASCADE,FOREIGN KEY(party_id) REFERENCES parties(id) ON DELETE RESTRICT,UNIQUE(credit_id,party_id,role))")
        if (oldVersion < 8) { if (!hasColumn(db,"credits","lending_method")) db.execSQL("ALTER TABLE credits ADD COLUMN lending_method TEXT DEFAULT 'OTHER'"); if (!hasColumn(db,"credits","transaction_reference")) db.execSQL("ALTER TABLE credits ADD COLUMN transaction_reference TEXT"); db.execSQL("CREATE TABLE IF NOT EXISTS credit_payment_meta(credit_id INTEGER PRIMARY KEY,lending_method TEXT NOT NULL DEFAULT 'OTHER',transaction_reference TEXT,FOREIGN KEY(credit_id) REFERENCES credits(id) ON DELETE CASCADE)") }
    }
    private fun hasColumn(db:SQLiteDatabase,t:String,c:String)=db.rawQuery("PRAGMA table_info($t)",null).use{x->while(x.moveToNext())if(x.getString(1)==c)return true;false}
    private fun now():String=java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss",java.util.Locale.US).format(java.util.Date())

    fun addCreditBetween(lenderPartyId:Long,borrowerPartyId:Long,creditType:String,principalAmount:Double,interestRate:Double,repaymentMethod:String,repaymentAmount:Double,periodicity:String?,startDate:String,endDate:String?,nextDueDate:String?,notes:String?,createdAt:String,graceDays:Int=0,invoiceNumber:String?=null,invoiceUri:String?=null,lendingMethod:String="OTHER",transactionReference:String?=null):Long {
        if(lenderPartyId<=0||borrowerPartyId<=0||lenderPartyId==borrowerPartyId||principalAmount<=0||interestRate<0||repaymentAmount<=0)return -1L
        val db=writableDatabase;db.beginTransaction();return try{val id=db.insertOrThrow("credits",null,ContentValues().apply{put("credit_type",creditType);put("direction","GIVEN");put("principal_amount",principalAmount);put("interest_rate",interestRate);put("repayment_method",repaymentMethod);put("repayment_amount",repaymentAmount);put("periodicity",periodicity);put("start_date",startDate);put("end_date",endDate);put("next_due_date",nextDueDate);put("grace_days",graceDays);put("lending_method",lendingMethod);put("transaction_reference",transactionReference);put("invoice_number",invoiceNumber);put("invoice_uri",invoiceUri);put("status","ACTIVE");put("notes",notes);put("created_at",createdAt);put("updated_at",createdAt)});db.insertOrThrow("credit_parties",null,ContentValues().apply{put("credit_id",id);put("party_id",lenderPartyId);put("role","LENDER")});db.insertOrThrow("credit_parties",null,ContentValues().apply{put("credit_id",id);put("party_id",borrowerPartyId);put("role","BORROWER")});db.insertOrThrow("credit_access",null,ContentValues().apply{put("credit_id",id);put("party_id",lenderPartyId);put("role","LENDER");put("can_view",1);put("can_repay",1);put("can_edit",1);put("consent_required",1)});db.insertOrThrow("credit_access",null,ContentValues().apply{put("credit_id",id);put("party_id",borrowerPartyId);put("role","BORROWER");put("can_view",1);put("can_repay",1);put("can_edit",0);put("consent_required",1)});db.insertOrThrow("activity_log",null,ContentValues().apply{put("credit_id",id);put("party_id",lenderPartyId);put("activity_type","CREDIT_CREATED");put("description","Credit relationship registered");put("created_at",createdAt)});db.setTransactionSuccessful();id}catch(_:Exception){-1L}finally{db.endTransaction()}}

    @Deprecated("Use addCreditBetween when both sides are known")
    fun addCredit(partyId:Long,creditType:String,direction:String,principalAmount:Double,interestRate:Double,repaymentMethod:String,repaymentAmount:Double,periodicity:String?,startDate:String,endDate:String?,nextDueDate:String?,notes:String?,createdAt:String,graceDays:Int=0,invoiceNumber:String?=null,invoiceUri:String?=null,lendingMethod:String="OTHER",transactionReference:String?=null):Long {
        if(partyId<=0||principalAmount<=0||interestRate<0||repaymentAmount<=0)return -1L
        val db=writableDatabase;db.beginTransaction();return try{val id=db.insertOrThrow("credits",null,ContentValues().apply{put("credit_type",creditType);put("direction",direction);put("principal_amount",principalAmount);put("interest_rate",interestRate);put("repayment_method",repaymentMethod);put("repayment_amount",repaymentAmount);put("periodicity",periodicity);put("start_date",startDate);put("end_date",endDate);put("next_due_date",nextDueDate);put("grace_days",graceDays);put("lending_method",lendingMethod);put("transaction_reference",transactionReference);put("invoice_number",invoiceNumber);put("invoice_uri",invoiceUri);put("status","ACTIVE");put("notes",notes);put("created_at",createdAt);put("updated_at",createdAt)});val role=if(direction=="GIVEN")"BORROWER" else "LENDER";db.insertOrThrow("credit_parties",null,ContentValues().apply{put("credit_id",id);put("party_id",partyId);put("role",role)});db.insertOrThrow("credit_access",null,ContentValues().apply{put("credit_id",id);put("party_id",partyId);put("role",role);put("can_view",1);put("can_repay",1);put("can_edit",0);put("consent_required",1)});db.insert("credit_payment_meta",null,ContentValues().apply{put("credit_id",id);put("lending_method",lendingMethod);put("transaction_reference",transactionReference)});db.insert("activity_log",null,ContentValues().apply{put("credit_id",id);put("party_id",partyId);put("activity_type","CREDIT_CREATED");put("description","Credit registered");put("created_at",createdAt)});db.setTransactionSuccessful();id}catch(_:Exception){-1L}finally{db.endTransaction()}}

    fun setLendingMethod(creditId:Long,method:String,reference:String?){writableDatabase.insertWithOnConflict("credit_payment_meta",null,ContentValues().apply{put("credit_id",creditId);put("lending_method",method);put("transaction_reference",reference)},SQLiteDatabase.CONFLICT_REPLACE);writableDatabase.execSQL("UPDATE credits SET lending_method=?,transaction_reference=?,updated_at=? WHERE id=?",arrayOf(method,reference,now(),creditId))}
    fun canView(creditId:Long,actorPartyId:Long,consentVerified:Boolean)=authorised(creditId,actorPartyId,"can_view",consentVerified)
    fun canUpdateRepayment(creditId:Long,actorPartyId:Long,consentVerified:Boolean)=authorised(creditId,actorPartyId,"can_repay",consentVerified)
    private fun authorised(creditId:Long,partyId:Long,column:String,consentVerified:Boolean)=readableDatabase.rawQuery("SELECT $column,consent_required FROM credit_access WHERE credit_id=? AND party_id=? LIMIT 1",arrayOf(creditId.toString(),partyId.toString())).use{it.moveToFirst()&&it.getInt(0)==1&&(it.getInt(1)==0||consentVerified)}
    fun addRepaymentAuthorized(creditId:Long,actorPartyId:Long,repaymentDate:String,amount:Double,principalComponent:Double,interestComponent:Double,paymentMode:String?,referenceNumber:String?,notes:String?,createdAt:String,consentVerified:Boolean):Long{if(amount<=0||!canUpdateRepayment(creditId,actorPartyId,consentVerified))return -1L;val db=writableDatabase;db.beginTransaction();return try{val id=db.insertOrThrow("repayments",null,ContentValues().apply{put("credit_id",creditId);put("repayment_date",repaymentDate);put("amount",amount);put("principal_component",principalComponent.coerceAtLeast(0.0));put("interest_component",interestComponent.coerceAtLeast(0.0));put("payment_mode",paymentMode);put("reference_number",referenceNumber);put("notes",notes);put("created_at",createdAt);put("actor_party_id",actorPartyId)});db.insertOrThrow("activity_log",null,ContentValues().apply{put("credit_id",creditId);put("party_id",actorPartyId);put("activity_type","REPAYMENT_RECORDED");put("description","Authorised repayment recorded");put("created_at",createdAt)});db.setTransactionSuccessful();id}finally{db.endTransaction()}}
}
