package com.udhaardaar.mvp

import android.content.ContentValues
import android.content.Context
import android.database.sqlite.SQLiteDatabase
import android.database.sqlite.SQLiteOpenHelper

/** Single V3 persistence layer. Sensitive mutations are authorised and auditable. */
class V3DatabaseHelper(context: Context) : SQLiteOpenHelper(context, "udhaardaar_v3.db", null, 5) {
    override fun onConfigure(db: SQLiteDatabase) { super.onConfigure(db); db.setForeignKeyConstraintsEnabled(true) }
    override fun onCreate(db: SQLiteDatabase) {
        db.execSQL("CREATE TABLE parties(id INTEGER PRIMARY KEY AUTOINCREMENT,party_type TEXT NOT NULL DEFAULT 'PERSON',name TEXT NOT NULL,mobile TEXT,email TEXT,address TEXT,pincode TEXT,city TEXT,state TEXT,aadhaar TEXT,pan TEXT,gstin TEXT,business_name TEXT,photo_uri TEXT,notes TEXT,created_at TEXT NOT NULL)")
        db.execSQL("CREATE TABLE credits(id INTEGER PRIMARY KEY AUTOINCREMENT,party_id INTEGER NOT NULL,credit_type TEXT NOT NULL,direction TEXT NOT NULL DEFAULT 'GIVEN',principal_amount REAL NOT NULL,interest_rate REAL NOT NULL DEFAULT 0,repayment_method TEXT NOT NULL,repayment_amount REAL NOT NULL DEFAULT 0,periodicity TEXT,start_date TEXT NOT NULL,end_date TEXT,next_due_date TEXT,grace_days INTEGER NOT NULL DEFAULT 0,invoice_number TEXT,invoice_uri TEXT,status TEXT NOT NULL DEFAULT 'ACTIVE',notes TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(party_id) REFERENCES parties(id))")
        db.execSQL("CREATE TABLE repayments(id INTEGER PRIMARY KEY AUTOINCREMENT,credit_id INTEGER NOT NULL,repayment_date TEXT NOT NULL,amount REAL NOT NULL,principal_component REAL NOT NULL DEFAULT 0,interest_component REAL NOT NULL DEFAULT 0,payment_mode TEXT,reference_number TEXT,notes TEXT,created_at TEXT NOT NULL,actor_party_id INTEGER NOT NULL,FOREIGN KEY(credit_id) REFERENCES credits(id),FOREIGN KEY(actor_party_id) REFERENCES parties(id))")
        db.execSQL("CREATE TABLE guarantors(id INTEGER PRIMARY KEY AUTOINCREMENT,party_id INTEGER NOT NULL,relationship TEXT,consent_status TEXT NOT NULL DEFAULT 'PENDING',created_at TEXT NOT NULL,FOREIGN KEY(party_id) REFERENCES parties(id))")
        db.execSQL("CREATE TABLE credit_guarantors(id INTEGER PRIMARY KEY AUTOINCREMENT,credit_id INTEGER NOT NULL,guarantor_id INTEGER NOT NULL,FOREIGN KEY(credit_id) REFERENCES credits(id),FOREIGN KEY(guarantor_id) REFERENCES guarantors(id),UNIQUE(credit_id,guarantor_id))")
        db.execSQL("CREATE TABLE documents(id INTEGER PRIMARY KEY AUTOINCREMENT,credit_id INTEGER,party_id INTEGER,document_type TEXT NOT NULL,document_name TEXT,document_uri TEXT,verification_status TEXT NOT NULL DEFAULT 'PENDING',created_at TEXT NOT NULL,FOREIGN KEY(credit_id) REFERENCES credits(id),FOREIGN KEY(party_id) REFERENCES parties(id))")
        db.execSQL("CREATE TABLE consents(id INTEGER PRIMARY KEY AUTOINCREMENT,credit_id INTEGER NOT NULL,party_id INTEGER NOT NULL,consent_type TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'PENDING',otp_verified INTEGER NOT NULL DEFAULT 0,consented_at TEXT,created_at TEXT NOT NULL,FOREIGN KEY(credit_id) REFERENCES credits(id),FOREIGN KEY(party_id) REFERENCES parties(id))")
        db.execSQL("CREATE TABLE credit_access(id INTEGER PRIMARY KEY AUTOINCREMENT,credit_id INTEGER NOT NULL,party_id INTEGER NOT NULL,role TEXT NOT NULL,can_view INTEGER NOT NULL DEFAULT 0,can_repay INTEGER NOT NULL DEFAULT 0,can_edit INTEGER NOT NULL DEFAULT 0,consent_required INTEGER NOT NULL DEFAULT 1,FOREIGN KEY(credit_id) REFERENCES credits(id),FOREIGN KEY(party_id) REFERENCES parties(id),UNIQUE(credit_id,party_id,role))")
        db.execSQL("CREATE TABLE activity_log(id INTEGER PRIMARY KEY AUTOINCREMENT,credit_id INTEGER,party_id INTEGER,activity_type TEXT NOT NULL,description TEXT,created_at TEXT NOT NULL,FOREIGN KEY(credit_id) REFERENCES credits(id),FOREIGN KEY(party_id) REFERENCES parties(id))")
        createIndexes(db)
    }
    private fun createIndexes(db: SQLiteDatabase) { listOf("CREATE INDEX IF NOT EXISTS idx_parties_mobile ON parties(mobile)","CREATE INDEX IF NOT EXISTS idx_parties_pan ON parties(pan)","CREATE INDEX IF NOT EXISTS idx_parties_gstin ON parties(gstin)","CREATE INDEX IF NOT EXISTS idx_parties_aadhaar ON parties(aadhaar)","CREATE INDEX IF NOT EXISTS idx_credits_party ON credits(party_id)","CREATE INDEX IF NOT EXISTS idx_repayments_credit ON repayments(credit_id)","CREATE INDEX IF NOT EXISTS idx_access_credit_party ON credit_access(credit_id,party_id)").forEach(db::execSQL) }
    override fun onUpgrade(db: SQLiteDatabase, oldVersion: Int, newVersion: Int) { if(oldVersion<4){db.execSQL("CREATE TABLE IF NOT EXISTS credit_access(id INTEGER PRIMARY KEY AUTOINCREMENT,credit_id INTEGER NOT NULL,party_id INTEGER NOT NULL,role TEXT NOT NULL,can_view INTEGER NOT NULL DEFAULT 0,can_repay INTEGER NOT NULL DEFAULT 0,can_edit INTEGER NOT NULL DEFAULT 0,consent_required INTEGER NOT NULL DEFAULT 1)");db.execSQL("CREATE TABLE IF NOT EXISTS activity_log(id INTEGER PRIMARY KEY AUTOINCREMENT,credit_id INTEGER,party_id INTEGER,activity_type TEXT NOT NULL,description TEXT,created_at TEXT NOT NULL)")}; if(oldVersion<5)addColumn(db,"repayments","actor_party_id","INTEGER NOT NULL DEFAULT -1"); createIndexes(db) }
    private fun addColumn(db:SQLiteDatabase,table:String,column:String,type:String){try{db.execSQL("ALTER TABLE $table ADD COLUMN $column $type")}catch(_:Exception){}}
    fun canView(creditId:Long,actorPartyId:Long,consentVerified:Boolean):Boolean=readableDatabase.rawQuery("SELECT can_view,consent_required FROM credit_access WHERE credit_id=? AND party_id=? LIMIT 1",arrayOf(creditId.toString(),actorPartyId.toString())).use{it.moveToFirst()&&it.getInt(0)==1&&(it.getInt(1)==0||consentVerified)}
    fun canUpdateRepayment(creditId:Long,actorPartyId:Long,consentVerified:Boolean):Boolean=readableDatabase.rawQuery("SELECT can_repay,consent_required FROM credit_access WHERE credit_id=? AND party_id=? LIMIT 1",arrayOf(creditId.toString(),actorPartyId.toString())).use{it.moveToFirst()&&it.getInt(0)==1&&(it.getInt(1)==0||consentVerified)}
    fun addRepaymentAuthorized(creditId:Long,actorPartyId:Long,repaymentDate:String,amount:Double,principalComponent:Double,interestComponent:Double,paymentMode:String?,referenceNumber:String?,notes:String?,createdAt:String,consentVerified:Boolean):Long{require(amount>0&&canUpdateRepayment(creditId,actorPartyId,consentVerified)){"Repayment not authorised"};val db=writableDatabase;db.beginTransaction();return try{val id=db.insertOrThrow("repayments",null,ContentValues().apply{put("credit_id",creditId);put("repayment_date",repaymentDate);put("amount",amount);put("principal_component",principalComponent.coerceAtLeast(0.0));put("interest_component",interestComponent.coerceAtLeast(0.0));put("payment_mode",paymentMode);put("reference_number",referenceNumber);put("notes",notes);put("created_at",createdAt);put("actor_party_id",actorPartyId)});db.insert("activity_log",null,ContentValues().apply{put("credit_id",creditId);put("party_id",actorPartyId);put("activity_type","REPAYMENT_RECORDED");put("description","Authorised repayment recorded");put("created_at",createdAt)});db.setTransactionSuccessful();id}finally{db.endTransaction()}}
}
