package com.udhaardaar.mvp

import android.app.*
import android.content.*
import android.graphics.Color
import android.graphics.drawable.GradientDrawable
import android.net.Uri
import android.os.Bundle
import android.text.InputFilter
import android.text.InputType
import android.view.*
import android.view.inputmethod.EditorInfo
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import java.io.BufferedReader
import java.io.InputStreamReader
import java.text.SimpleDateFormat
import java.util.*
import kotlin.math.pow
import kotlin.random.Random

class V4HomeActivity:AppCompatActivity(){
 private lateinit var db:V32DatabaseHelper
 private val p by lazy{getSharedPreferences("udhaardaar_accounts",MODE_PRIVATE)}
 private val blue=Color.rgb(25,111,220);private val teal=Color.rgb(0,145,135);private val green=Color.rgb(25,145,78);private val navy=Color.rgb(24,58,92);private val amber=Color.rgb(220,145,20);private val red=Color.rgb(190,55,55);private val bg=Color.rgb(238,248,253)
 private var photoUri:Uri?=null;private var docUri:Uri?=null;private var otp="";private var fileKind=""
 private fun dp(x:Int)=(x*resources.displayMetrics.density).toInt();private fun gd(c:Int=Color.WHITE,s:Int=Color.rgb(190,210,225))=GradientDrawable().apply{setColor(c);setStroke(dp(1),s);cornerRadius=dp(16).toFloat()};private fun t(x:String,z:Float=16f,c:Int=navy)=TextView(this).apply{text=x;textSize=z;setTextColor(c);setPadding(dp(4),dp(4),dp(4),dp(4))};private fun e(h:String,max:Int=0,num:Boolean=false)=EditText(this).apply{hint=h;textSize=16f;setSingleLine(true);setPadding(dp(13),dp(8),dp(13),dp(8));background=gd();if(max>0)filters=arrayOf(InputFilter.LengthFilter(max));if(num)inputType=InputType.TYPE_CLASS_NUMBER;imeOptions=EditorInfo.IME_ACTION_NEXT};private fun b(x:String,c:Int=blue,a:()->Unit)=Button(this).apply{text=x;isAllCaps=false;textSize=14f;setTextColor(Color.WHITE);background=gd(c,c);setOnClickListener{a()}};private fun put(r:LinearLayout,v:View,h:Int=54){r.addView(v,LinearLayout.LayoutParams(-1,dp(h)).apply{setMargins(0,dp(3),0,dp(3))})};private fun show(r:LinearLayout){setContentView(ScrollView(this).apply{isFillViewport=true;addView(r)});window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE)};private fun toast(x:String)=Toast.makeText(this,x,Toast.LENGTH_LONG).show();private fun money(x:Double)="₹"+String.format(Locale.US,"%,.2f",x)
 override fun onCreate(s:Bundle?){super.onCreate(s);db=V32DatabaseHelper(this);if(p.getBoolean("logged_in",false)&&!p.getString("current_mobile","").isNullOrBlank())home()else{startActivity(Intent(this,LoginActivity::class.java));finish()}}
 override fun onResume(){super.onResume();window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE)}
 override fun onBackPressed(){home()}
 private fun header(r:LinearLayout,title:String,sub:String){val h=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;padding(dp(8),dp(6),dp(8),dp(6));background=gd()};h.addView(ImageView(this).apply{layoutParams=LinearLayout.LayoutParams(dp(48),dp(48));setImageResource(R.drawable.udhaardaar_logo)});val z=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;layoutParams=LinearLayout.LayoutParams(0,-2,1f)};z.addView(t("Udhaardaar",20f));z.addView(t(title,17f,blue));z.addView(t(sub,11f,Color.DKGRAY));h.addView(z);h.addView(b("HOME",blue){home()},LinearLayout.LayoutParams(dp(72),dp(44)));r.addView(h);r.addView(Space(this),LinearLayout.LayoutParams(1,dp(8)))}
 private fun page(title:String,sub:String)=root().also{header(it,title,sub)};private fun root()=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;padding(dp(16),dp(12),dp(16),dp(30));setBackgroundColor(bg)}
 private fun home(){if(!p.getBoolean("logged_in",false)){startActivity(Intent(this,LoginActivity::class.java));finish();return};val r=page("Dashboard","Simple V4 home — choose the module you need");val m=p.getString("current_mobile","")?:("");val c=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;padding(dp(10),dp(8),dp(10),dp(8));background=gd()};val u=p.getString("photo_$m","");c.addView(photo(u,68));val z=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;layoutParams=LinearLayout.LayoutParams(0,-2,1f)};z.addView(t("Welcome, ${p.getString("name_$m","User")}",20f));z.addView(t("Mobile: $m",12f,Color.DKGRAY));c.addView(z);r.addView(c);r.addView(Space(this),LinearLayout.LayoutParams(1,dp(8)));metric(r,"Credit given",money(db.totalCredit("Credit Given")),blue){credits("Credit Given")};metric(r,"Credit received",money(db.totalCredit("Credit Received")),teal){credits("Credit Received")};metric(r,"Due / overdue","${db.dueCount(false)} / ${db.dueCount(true)}",amber){repay(false)};action(r,"＋","Informal credit","Personal • Business • Trade • Advance • Other",blue){informal()};action(r,"⌂","Rental / Lease","Dedicated rent, deposit, escalation, due date and agreement",teal){rental()};action(r,"🏦","Formal loan / bank credit","Sanction letter + statement + charges/ROI comparison; no consent",navy){formal()};action(r,"⌕","Borrower profiles","Photo + PIN city/state + PAN/Aadhaar/GST validation",teal){profiles()};action(r,"₹","Repayment centre","Due, overdue and repayment recording",green){repay(false)};action(r,"▤","Documents & consent","Digital documents and consent records",amber){docs()};action(r,"◎","My profile","Account photo and details",teal){owner()};put(r,b("LOGOUT",Color.rgb(90,110,125)){p.edit().putBoolean("logged_in",false).remove("current_mobile").apply();startActivity(Intent(this,LoginActivity::class.java).addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP));finish()},50);show(r)}
 private fun metric(r:LinearLayout,a:String,v:String,c:Int,click:()->Unit){val x=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;padding(dp(11),dp(7),dp(11),dp(7));background=gd(Color.WHITE,c);setOnClickListener{click()}};x.addView(t(a,13f,Color.DKGRAY));x.addView(t(v,20f,c));r.addView(x);r.addView(Space(this),LinearLayout.LayoutParams(1,dp(6)))};private fun action(r:LinearLayout,ic:String,a:String,s:String,c:Int,click:()->Unit){val x=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;padding(dp(10),dp(8),dp(8),dp(8));background=gd();setOnClickListener{click()}};x.addView(t(ic,22f,c),LinearLayout.LayoutParams(dp(42),dp(48)));val z=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;layoutParams=LinearLayout.LayoutParams(0,-2,1f)};z.addView(t(a,16f));z.addView(t(s,11f,Color.DKGRAY));x.addView(z);x.addView(t("›",26f,c));r.addView(x);r.addView(Space(this),LinearLayout.LayoutParams(1,dp(6)))}
 private fun photo(uri:String?,n:Int)=ImageView(this).apply{layoutParams=LinearLayout.LayoutParams(dp(n),dp(n));scaleType=ImageView.ScaleType.CENTER_CROP;background=gd();if(!uri.isNullOrBlank())try{setImageURI(Uri.parse(uri))}catch(_:Exception){}}
 private fun profiles(){val r=page("Borrower Profiles","Create or search verified counterparty profiles");val q=e("Name / mobile / PAN / Aadhaar / GSTIN / unique ID");val list=LinearLayout(this);put(r,q);put(r,b("SEARCH",blue){fillProfiles(q,list)},50);put(r,b("CREATE NEW BORROWER PROFILE",green){profile(null)},50);r.addView(list);fillProfiles(q,list);put(r,b("BACK",Color.DKGRAY){home()},50);show(r)}
 private fun fillProfiles(q:EditText,list:LinearLayout){list.removeAllViews();val rows=db.searchProfiles("BORROWER",q.text.toString());if(rows.isEmpty())list.addView(t("No borrower found."));rows.forEach{x->action(list,"●",x.name,"${x.mobile} • ${x.id}",blue){summary(x.rowId)}}}
 private fun profile(id:Long?){val old=id?.let{db.profileData(it)};photoUri=old?.photo?.let{Uri.parse(it)};val r=page("Borrower Profile","Mandatory format validation + profile photo");val im=photo(old?.photo,92);r.addView(im);put(r,b("ADD / CHANGE PHOTO",teal){pickPhoto(im)},50);val n=e("Full name *");val m=e("Mobile * (10 digits)",10,true);val a=e("Alternate mobile",10,true);val ad=e("Full address *");val pin=e("PIN code * (6 digits)",6,true);val city=e("City");val state=e("State");val pan=e("PAN (ABCDE1234F)");val aad=e("Aadhaar (12 digits)",12,true);val gst=e("GSTIN (15 characters, optional)");old?.let{n.setText(it.name);m.setText(it.mobile);a.setText(it.alternate);ad.setText(it.address);pin.setText(it.pin);city.setText(it.city);state.setText(it.state);pan.setText(it.pan);aad.setText(it.aadhaar);gst.setText(it.gstin)};listOf(n,m,a,ad,pin,city,state,pan,aad,gst).forEach{put(r,it)};next(n,m,a,ad,pin,city,state,pan,aad,gst);pin.setOnEditorActionListener{_,act,_->if(act==EditorInfo.IME_ACTION_NEXT&&pin.text.length==6){pinLookup(pin.text.toString(),city,state);city.requestFocus();true}else false};put(r,b(if(old==null)"SAVE PROFILE" else "UPDATE PROFILE",green){val P=pan.text.toString().trim().uppercase(Locale.US);val A=aad.text.toString();val G=gst.text.toString().trim().uppercase(Locale.US);if(n.text.trim().length<2||m.text.length!=10||ad.text.trim().length<5||pin.text.length!=6){toast("Name, address, mobile and 6-digit PIN are required");return@b};if(a.text.isNotBlank()&&a.text.length!=10){toast("Alternate mobile must be 10 digits");return@b};if(P.isNotBlank()&&!Regex("^[A-Z]{5}[0-9]{4}[A-Z]$").matches(P)){toast("Invalid PAN format");return@b};if(A.isNotBlank()&&!Regex("^[2-9][0-9]{11}$").matches(A)){toast("Invalid Aadhaar format");return@b};if(G.isNotBlank()&&!Regex("^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$").matches(G)){toast("Invalid GSTIN format");return@b};val uid=old?.id?:"BOR-${System.currentTimeMillis()}";db.upsertProfile(old?.rowId,"BORROWER",uid,n.text.trim().toString(),m.text.toString(),a.text.toString(),ad.text.trim().toString(),city.text.trim().toString(),state.text.trim().toString(),pin.text.toString(),P,A,G,photoUri?.toString()?:old?.photo);toast("Profile saved: $uid");profiles()},54);put(r,b("BACK",Color.DKGRAY){profiles()},50);show(r)}
 private fun next(vararg x:EditText){for(i in 0 until x.size-1)x[i].setOnEditorActionListener{_,a,_->if(a==EditorInfo.IME_ACTION_NEXT){x[i+1].requestFocus();true}else false}}
 private fun pinLookup(pin:String,city:EditText,state:EditText){Thread{try{val c=java.net.URL("https://api.postalpincode.in/pincode/$pin").openConnection() as java.net.HttpURLConnection;c.connectTimeout=5000;c.readTimeout=5000;val s=BufferedReader(InputStreamReader(c.inputStream)).use{it.readText()};val x=Regex("\"Name\"\\s*:\\s*\"([^\"]+)\".*?\"State\"\\s*:\\s*\"([^\"]+)\"").find(s);runOnUiThread{if(x!=null){city.setText(x.groupValues[1]);state.setText(x.groupValues[2])}else toast("PIN not found")}}catch(_:Exception){runOnUiThread{toast("PIN lookup unavailable; enter city/state manually")}}}.start()}
 private fun summary(id:Long){val x=db.profileData(id)?:return;val s=db.borrowerSummary(id);val r=page("Borrower Summary","Existing exposure before new credit");r.addView(photo(x.photo,88));r.addView(t(x.name,22f));r.addView(t("${x.id} • ${x.mobile}"));r.addView(t("PAN ${x.pan.ifBlank{"—"}} • Aadhaar ${if(x.aadhaar.isBlank())"—" else "format valid"}"));r.addView(t("Total ${money(s.total)} • Outstanding ${money(s.outstanding)} • Overdue ${s.overdue}"));put(r,b("REGISTER INFORMAL CREDIT",blue){informal(id)},54);put(r,b("BACK",Color.DKGRAY){profiles()},50);show(r)}
 private fun informal(pre:Long?=null){val bs=db.searchProfiles("BORROWER","");if(bs.isEmpty()){toast("Create borrower profile first");profile(null);return};val r=page("Informal Credit","OTP consent + digital document before final registration");val bo=Spinner(this);bo.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,bs.map{"${it.name} • ${it.mobile}"});pre?.let{val i=bs.indexOfFirst{x->x.rowId==it};if(i>=0)bo.setSelection(i)};val type=Spinner(this);type.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,arrayOf("Personal Credit","Business Credit","Trade Credit","Advance","Other"));val dir=Spinner(this);dir.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,arrayOf("Credit Given","Credit Received"));val amt=e("Principal / amount *");val roi=e("Annual ROI %");val months=e("Tenor months *",3,true).apply{setText("12")};val method=Spinner(this);method.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,arrayOf("EMI","Principal + Interest","Bullet / Full payment"));put(r,t("Borrower *"));put(r,bo);put(r,t("Credit type"));put(r,type);put(r,t("Direction"));put(r,dir);put(r,amt);put(r,roi);put(r,months);put(r,t("Repayment method"));put(r,method);put(r,b("UPLOAD SUPPORTING DOCUMENT / INVOICE",teal){pickDoc("SUPPORTING_DOCUMENT")},52);put(r,b("REVIEW + OTP CONSENT + REGISTER",green){val p0=amt.text.toString().toDoubleOrNull();val rate=roi.text.toString().toDoubleOrNull()?:0.0;val n=months.text.toString().toIntOrNull()?:0;if(p0==null||p0<=0||n !in 1..240){toast("Enter valid amount and tenor");return@b};val q=rate/1200;val ins=if(method.selectedItem.toString()=="EMI"&&q>0)p0*q*(1+q).pow(n)/((1+q).pow(n)-1) else p0/n;val interest=if(method.selectedItem.toString()=="EMI")ins*n-p0 else p0*rate*n/1200;val start=today();val end=SimpleDateFormat("yyyy-MM-dd",Locale.US).format(Calendar.getInstance().apply{add(Calendar.MONTH,n)}.time);consent(bs[bo.selectedItemPosition].rowId,type.selectedItem.toString(),dir.selectedItem.toString(),p0,rate,n,method.selectedItem.toString(),ins,interest,p0+interest,start,end)},54);put(r,b("BACK",Color.DKGRAY){home()},50);show(r)}
 private fun consent(borrower:Long,type:String,dir:String,p:Double,rate:Double,n:Int,method:String,ins:Double,int:Double,pay:Double,start:String,end:String){otp=Random.nextInt(100000,1000000).toString();val inpt=e("6-digit OTP",6,true);val d=AlertDialog.Builder(this).setTitle("Informal credit consent").setMessage("Principal ${money(p)}\nROI $rate%\nMethod $method\nInstallment ${money(ins)}\nTotal payable ${money(pay)}\nPeriod $start to $end\n\nBoth parties must consent to these informal-credit terms.").setView(inpt).setNegativeButton("CANCEL",null).setPositiveButton("CONFIRM",null).create();d.setOnShowListener{toast("Demo OTP: $otp");d.getButton(-1).setOnClickListener{if(inpt.text.toString()!=otp){inpt.error="Incorrect OTP";return@setOnClickListener};val id=db.addCredit(borrower,null,type,dir,p,rate,n,method,ins,int,pay,start,end,"",docUri?.toString(),true);db.createSchedule(id,ins,n,end);db.saveConsent(id,"OTP_VERIFIED","INFORMAL_CREDIT_CONSENT");docUri?.let{db.saveDocument(id,"SUPPORTING_DOCUMENT",it.toString())};d.dismiss();toast("Registered only after OTP consent");home()}};d.show()}
 private fun rental(){val bs=db.searchProfiles("BORROWER","");if(bs.isEmpty()){toast("Create tenant profile first");profile(null);return};val r=page("Rental / Lease","Dedicated lease module — not personal credit");val ten=Spinner(this);ten.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,bs.map{"${it.name} • ${it.mobile}"});val prop=e("Property / premises *");val owner=e("Landlord / owner *");val rent=e("Monthly rent *");val dep=e("Security deposit *");val start=e("Lease start YYYY-MM-DD *");val end=e("Lease end YYYY-MM-DD *");val freq=Spinner(this);freq.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,arrayOf("Monthly","Quarterly","Yearly"));val due=e("Rent due day 1–31",2,true);val esc=e("Annual escalation %");val notice=e("Notice period days",3,true);val util=e("Utilities / maintenance responsibility");put(r,t("Tenant / counterparty"));put(r,ten);listOf(prop,owner,rent,dep,start,end,due,esc,notice,util).forEach{put(r,it)};put(r,t("Rent frequency"));put(r,freq);put(r,b("UPLOAD LEASE AGREEMENT",teal){pickDoc("LEASE_AGREEMENT")},52);put(r,b("SAVE LEASE",green){val rv=rent.text.toString().toDoubleOrNull();val n=months(start.text.toString(),end.text.toString());if(prop.text.trim().length<3||owner.text.trim().length<2||rv==null||rv<=0||n<=0){toast("Complete property, owner, rent and valid dates");return@b};val id=db.addCredit(bs[ten.selectedItemPosition].rowId,null,"Rental / Lease","Credit Given",rv,esc.text.toString().toDoubleOrNull()?:0.0,n,"Rental • ${freq.selectedItem}",rv,rv*n,rv*n,start.text.toString(),end.text.toString(),"",docUri?.toString(),false);db.createSchedule(id,rv,n,end.text.toString());docUri?.let{db.saveDocument(id,"LEASE_AGREEMENT",it.toString())};toast("Lease saved with separate rental terms");home()},54);put(r,b("BACK",Color.DKGRAY){home()},50);show(r)}
 private fun months(a:String,b:String):Int=try{val f=SimpleDateFormat("yyyy-MM-dd",Locale.US);val x=Calendar.getInstance();x.time=f.parse(a)!!;val y=Calendar.getInstance();y.time=f.parse(b)!!;((y.get(Calendar.YEAR)-x.get(Calendar.YEAR))*12+y.get(Calendar.MONTH)-x.get(Calendar.MONTH)).coerceAtLeast(0)}catch(_:Exception){0}
 private fun formal(){val r=page("Formal Loan / Bank Credit","No counterparty consent. Upload sanction letter + statement and compare terms.");val bank=e("Bank / NBFC / lender *");val acct=e("Loan account number");val sanc=e("Sanction amount *");val roi=e("Sanctioned ROI % *");val fee=e("Processing fee");val other=e("Other charges");val tenure=e("Tenure months",3,true);val emi=e("Sanctioned EMI");listOf(bank,acct,sanc,roi,fee,other,tenure,emi).forEach{put(r,it)};put(r,b("UPLOAD SANCTION LETTER",teal){pickDoc("SANCTION_LETTER")},52);put(r,b("UPLOAD STATEMENT OF ACCOUNT",navy){pickDoc("STATEMENT_OF_ACCOUNT")},52);put(r,b("ANALYSE CHARGES + ROI",green){val s=sanc.text.toString().toDoubleOrNull();val rr=roi.text.toString().toDoubleOrNull();if(bank.text.trim().length<2||s==null||rr==null){toast("Enter lender, sanction amount and ROI");return@b};val ocr=readDoc(docUri);val pr=Regex("(?i)(?:roi|rate of interest|interest rate)[^0-9]{0,20}([0-9]{1,2}(?:\\.[0-9]+)?)\\s*%?").find(ocr)?.groupValues?.get(1)?.toDoubleOrNull();val pf=Regex("(?i)(?:processing fee|processing charges)[^0-9]{0,20}([0-9,]+(?:\\.[0-9]+)?)").find(ocr)?.groupValues?.get(1)?.replace(",","")?.toDoubleOrNull();val msg="SANCTIONED\nROI $rr%\nProcessing fee ${money(fee.text.toString().toDoubleOrNull()?:0.0)}\nOther charges ${money(other.text.toString().toDoubleOrNull()?:0.0)}\n\nSTATEMENT / DOCUMENT ANALYSIS\nDetected ROI ${pr?.let{"$it%"}?:"Not detected"}\nDetected processing fee ${pf?.let{money(it)}?:"Not detected"}\n\n${if(pr!=null&&kotlin.math.abs(pr-rr)>0.01)"⚠ ROI discrepancy detected" else "No ROI discrepancy detected from extracted text."}\n\nFormal loans do not use counterparty OTP consent.";AlertDialog.Builder(this).setTitle("Charge comparison").setMessage(msg).setPositiveButton("OK",null).show()},54);put(r,b("BACK",Color.DKGRAY){home()},50);show(r)}
 private fun readDoc(u:Uri?):String=try{if(u==null)return"";BufferedReader(InputStreamReader(contentResolver.openInputStream(u)!!)).use{it.readText()}}catch(_:Exception){""}
 private fun docs(){val r=page("Documents & Consent","Digital evidence register");r.addView(t("Informal credits require OTP consent before saving. Formal loans are recorded without counterparty consent. Rental agreements are stored as lease documents."));put(r,b("UPLOAD GENERAL DOCUMENT",teal){pickDoc("GENERAL_DOCUMENT")},52);put(r,b("BACK",Color.DKGRAY){home()},50);show(r)}
 private fun credits(dir:String?){val r=page("Credit History",dir?:"All transactions");val rows=db.credits(dir);if(rows.isEmpty())r.addView(t("No credit records."));rows.forEach{x->action(r,"₹",x.creditId,"${x.borrowerName} • ${x.type} • ${money(x.amount)}",blue){detail(x.id)}};put(r,b("BACK",Color.DKGRAY){home()},50);show(r)}
 private fun detail(id:Long){val x=db.creditDetail(id)?:return;val r=page(x.creditId,"Transaction details");listOf("Borrower: ${x.borrowerName}","Type: ${x.type}","Direction: ${x.direction}","Principal: ${money(x.amount)}","ROI: ${x.roi}%","Method: ${x.method}","Payable: ${money(x.payable)}","Period: ${x.start} to ${x.end}").forEach{r.addView(t(it))};put(r,b("REPAYMENT SCHEDULE",green){repay(false)},52);put(r,b("BACK",Color.DKGRAY){credits(null)},50);show(r)}
 private fun repay(over:Boolean){val r=page("Repayment Centre",if(over)"Overdue" else "Due / upcoming");val rows=db.schedules(null,over);if(rows.isEmpty())r.addView(t("No payments."));rows.forEach{s->action(r,"₹",s.creditId,"Due ${s.dueDate} • ${money(s.amount)} • ${s.status}",if(s.status=="OVERDUE")red else green){val inpt=e("Payment amount");inpt.setText(String.format(Locale.US,"%.2f",s.amount));AlertDialog.Builder(this).setTitle("Record repayment").setView(inpt).setNegativeButton("CANCEL",null).setPositiveButton("SAVE"){_,_->val v=db.recordPayment(s.id,s.creditDbId,inpt.text.toString().toDoubleOrNull()?:0.0);toast(if(v>0)"Repayment recorded" else "No outstanding amount");repay(false)}.show()}};put(r,b("BACK",Color.DKGRAY){home()},50);show(r)}
 private fun owner(){val m=p.getString("current_mobile","")?:"";val r=page("My Profile","Account owner");r.addView(photo(p.getString("photo_$m",""),110));r.addView(t(p.getString("name_$m","User")?:"User",22f));r.addView(t("Mobile: $m"));r.addView(t("Address: ${p.getString("address_$m","")}"));r.addView(t("Email: ${p.getString("email_$m","").ifBlank{"—"}}"));put(r,b("CHANGE PHOTO",teal){pickAccountPhoto()},50);put(r,b("BACK",Color.DKGRAY){home()},50);show(r)}
 private fun pickPhoto(img:ImageView){startActivityForResult(Intent(Intent.ACTION_OPEN_DOCUMENT).apply{type="image/*";addCategory(Intent.CATEGORY_OPENABLE);addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION or Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION)},1001);photoTarget=img};private var photoTarget:ImageView?=null;private fun pickAccountPhoto(){startActivityForResult(Intent(Intent.ACTION_OPEN_DOCUMENT).apply{type="image/*";addCategory(Intent.CATEGORY_OPENABLE);addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION or Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION)},1002)};private fun pickDoc(kind:String){fileKind=kind;startActivityForResult(Intent(Intent.ACTION_OPEN_DOCUMENT).apply{type="application/pdf";addCategory(Intent.CATEGORY_OPENABLE);addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION or Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION)},2001)}
 override fun onActivityResult(req:Int,res:Int,d:Intent?){super.onActivityResult(req,res,d);if(res!=RESULT_OK||d?.data==null)return;val u=d.data!!;try{contentResolver.takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION)}catch(_:Exception){};when(req){1001->{photoUri=u;photoTarget?.setImageURI(u)};1002->{val m=p.getString("current_mobile","")?:"";p.edit().putString("photo_$m",u.toString()).apply();toast("Profile photo updated")};2001->{docUri=u;toast("Document selected: $fileKind")}}}
 private fun today()=SimpleDateFormat("yyyy-MM-dd",Locale.US).format(Date())
}
