package com.udhaardaar.mvp

import android.app.*
import android.content.*
import android.graphics.Color
import android.graphics.drawable.GradientDrawable
import android.net.Uri
import android.os.Bundle
import android.text.InputFilter
import android.text.InputType
import android.view.*
import android.view.inputmethod.EditorInfo
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import java.io.BufferedReader
import java.io.InputStreamReader
import java.text.SimpleDateFormat
import java.util.*
import kotlin.math.pow
import kotlin.random.Random

class V4HomeActivity:AppCompatActivity(){
 private lateinit var db:V32DatabaseHelper
 private val p by lazy{getSharedPreferences("udhaardaar_accounts",MODE_PRIVATE)}
 private val blue=Color.rgb(25,111,220);private val teal=Color.rgb(0,145,135);private val green=Color.rgb(25,145,78);private val navy=Color.rgb(24,58,92);private val amber=Color.rgb(220,145,20);private val red=Color.rgb(190,55,55);private val bg=Color.rgb(238,248,253)
 private var photoUri:Uri?=null;private var docUri:Uri?=null;private var otp="";private var photoTarget:ImageView?=null;private var docType=""
 private fun dp(x:Int)=(x*resources.displayMetrics.density).toInt()
 private fun box(c:Int=Color.WHITE,s:Int=Color.rgb(190,210,225))=GradientDrawable().apply{setColor(c);setStroke(dp(1),s);cornerRadius=dp(16).toFloat()}
 private fun tv(s:String,z:Float=16f,c:Int=navy)=TextView(this).apply{text=s;textSize=z;setTextColor(c);setPadding(dp(4),dp(4),dp(4),dp(4))}
 private fun ed(h:String,max:Int=0,num:Boolean=false)=EditText(this).apply{hint=h;textSize=16f;setSingleLine(true);setPadding(dp(13),dp(8),dp(13),dp(8));background=box();if(max>0)filters=arrayOf(InputFilter.LengthFilter(max));if(num)inputType=InputType.TYPE_CLASS_NUMBER;imeOptions=EditorInfo.IME_ACTION_NEXT}
 private fun btn(s:String,c:Int=blue,a:()->Unit)=Button(this).apply{text=s;isAllCaps=false;textSize=14f;setTextColor(Color.WHITE);background=box(c,c);setOnClickListener{a()}}
 private fun root()=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(16),dp(12),dp(16),dp(30));setBackgroundColor(bg)}
 private fun put(r:LinearLayout,v:View,h:Int=54){r.addView(v,LinearLayout.LayoutParams(-1,dp(h)).apply{setMargins(0,dp(3),0,dp(3))})}
 private fun show(r:LinearLayout){setContentView(ScrollView(this).apply{isFillViewport=true;addView(r)});window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE)}
 private fun page(title:String,sub:String)=root().also{r->val h=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(dp(8),dp(6),dp(8),dp(6));background=box()};h.addView(ImageView(this).apply{layoutParams=LinearLayout.LayoutParams(dp(48),dp(48));setImageResource(R.drawable.udhaardaar_logo)});val z=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;layoutParams=LinearLayout.LayoutParams(0,-2,1f)};z.addView(tv("Udhaardaar",20f));z.addView(tv(title,17f,blue));z.addView(tv(sub,11f,Color.DKGRAY));h.addView(z);h.addView(btn("HOME",blue){home()},LinearLayout.LayoutParams(dp(72),dp(44)));r.addView(h);r.addView(Space(this),LinearLayout.LayoutParams(1,dp(8)))}
 private fun money(x:Double)="₹"+String.format(Locale.US,"%,.2f",x);private fun toast(s:String)=Toast.makeText(this,s,Toast.LENGTH_LONG).show();private fun today()=SimpleDateFormat("yyyy-MM-dd",Locale.US).format(Date())
 override fun onCreate(s:Bundle?){super.onCreate(s);db=V32DatabaseHelper(this);if(p.getBoolean("logged_in",false)&&!p.getString("current_mobile","").isNullOrBlank())home()else{startActivity(Intent(this,LoginActivity::class.java));finish()}}
 override fun onResume(){super.onResume();window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE)}
 override fun onBackPressed(){home()}
 private fun home(){if(!p.getBoolean("logged_in",false)){startActivity(Intent(this,LoginActivity::class.java));finish();return};val m=p.getString("current_mobile","")?:"";val r=page("Dashboard","One clear home for V4");val card=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(dp(10),dp(8),dp(10),dp(8));background=box()};card.addView(photo(p.getString("photo_$m",""),68));val z=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;layoutParams=LinearLayout.LayoutParams(0,-2,1f)};z.addView(tv("Welcome, ${p.getString("name_$m","User")}",20f));z.addView(tv("Mobile: $m",12f,Color.DKGRAY));card.addView(z);r.addView(card);r.addView(Space(this),LinearLayout.LayoutParams(1,dp(8)));metric(r,"Credit given",money(db.totalCredit("Credit Given")),blue){credits("Credit Given")};metric(r,"Credit received",money(db.totalCredit("Credit Received")),teal){credits("Credit Received")};metric(r,"Due / overdue","${db.dueCount(false)} / ${db.dueCount(true)}",amber){repay(false)};action(r,"＋","Informal credit","Personal • Business • Trade • Advance • Other",blue){informal()};action(r,"⌂","Rental / Lease","Separate rent, deposit, escalation and lease fields",teal){rental()};action(r,"🏦","Formal loan","Sanction letter + statement + charge comparison; no consent",navy){formal()};action(r,"⌕","Borrower profiles","Photo, PIN lookup, PAN/Aadhaar/GST validation",teal){profiles()};action(r,"₹","Repayment centre","Due, overdue and payment recording",green){repay(false)};action(r,"▤","Documents & consent","Upload and review digital evidence",amber){docs()};action(r,"◎","My profile","Account photo and details",teal){owner()};put(r,btn("LOGOUT",Color.rgb(90,110,125)){p.edit().putBoolean("logged_in",false).remove("current_mobile").apply();startActivity(Intent(this,LoginActivity::class.java).addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP or Intent.FLAG_ACTIVITY_SINGLE_TOP));finish()},50);show(r)}
 private fun metric(r:LinearLayout,a:String,v:String,c:Int,click:()->Unit){val x=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(11),dp(7),dp(11),dp(7));background=box(Color.WHITE,c);setOnClickListener{click()}};x.addView(tv(a,13f,Color.DKGRAY));x.addView(tv(v,20f,c));r.addView(x);r.addView(Space(this),LinearLayout.LayoutParams(1,dp(6)))}
 private fun action(r:LinearLayout,i:String,a:String,s:String,c:Int,click:()->Unit){val x=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(dp(10),dp(8),dp(8),dp(8));background=box();setOnClickListener{click()}};x.addView(tv(i,22f,c),LinearLayout.LayoutParams(dp(42),dp(48)));val z=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;layoutParams=LinearLayout.LayoutParams(0,-2,1f)};z.addView(tv(a,16f));z.addView(tv(s,11f,Color.DKGRAY));x.addView(z);x.addView(tv("›",26f,c));r.addView(x);r.addView(Space(this),LinearLayout.LayoutParams(1,dp(6)))}
 private fun photo(u:String?,n:Int)=ImageView(this).apply{layoutParams=LinearLayout.LayoutParams(dp(n),dp(n));scaleType=ImageView.ScaleType.CENTER_CROP;background=box();if(!u.isNullOrBlank())try{setImageURI(Uri.parse(u))}catch(_:Exception){}}
 private fun profiles(){val r=page("Borrower Profiles","Search or create a complete borrower profile");val q=ed("Name / mobile / PAN / Aadhaar / GSTIN / unique ID");val list=LinearLayout(this);put(r,q);put(r,btn("SEARCH",blue){list.removeAllViews();val rows=db.searchProfiles("BORROWER",q.text.toString());if(rows.isEmpty())list.addView(tv("No borrower found."));rows.forEach{x->action(list,"●",x.name,"${x.mobile} • ${x.id}",blue){summary(x.rowId)}}},50);put(r,btn("CREATE NEW PROFILE",green){profile(null)},50);r.addView(list);put(r,btn("BACK",Color.DKGRAY){home()},50);show(r)}
 private fun profile(id:Long?){val old=id?.let{db.profileData(it)};photoUri=old?.photo?.let{Uri.parse(it)};val r=page("Borrower Profile","Validated identity + photo + automatic PIN city/state");val im=photo(old?.photo,92);r.addView(im);put(r,btn("ADD / CHANGE PHOTO",teal){pickPhoto(im)},50);val n=ed("Full name *");val m=ed("Mobile * (10 digits)",10,true);val alt=ed("Alternate mobile",10,true);val ad=ed("Full address *");val pin=ed("PIN code * (6 digits)",6,true);val city=ed("City");val state=ed("State");val pan=ed("PAN (ABCDE1234F)");val aad=ed("Aadhaar (12 digits)",12,true);val gst=ed("GSTIN (15 characters, optional)");old?.let{n.setText(it.name);m.setText(it.mobile);alt.setText(it.alternate);ad.setText(it.address);pin.setText(it.pin);city.setText(it.city);state.setText(it.state);pan.setText(it.pan);aad.setText(it.aadhaar);gst.setText(it.gstin)};listOf(n,m,alt,ad,pin,city,state,pan,aad,gst).forEach{put(r,it)};next(n,m,alt,ad,pin,city,state,pan,aad,gst);pin.setOnEditorActionListener{_,a,_->if(a==EditorInfo.IME_ACTION_NEXT&&pin.text.length==6){pinLookup(pin.text.toString(),city,state);city.requestFocus();true}else false};put(r,btn(if(old==null)"SAVE PROFILE" else "UPDATE PROFILE",green){val P=pan.text.toString().trim().uppercase(Locale.US);val A=aad.text.toString();val G=gst.text.toString().trim().uppercase(Locale.US);if(n.text.trim().length<2||m.text.length!=10||ad.text.trim().length<5||pin.text.length!=6){toast("Name, address, mobile and 6-digit PIN are required");return@btn};if(alt.text.isNotBlank()&&alt.text.length!=10){toast("Alternate mobile must be 10 digits");return@btn};if(P.isNotBlank()&&!Regex("^[A-Z]{5}[0-9]{4}[A-Z]$").matches(P)){toast("Invalid PAN format");return@btn};if(A.isNotBlank()&&!Regex("^[2-9][0-9]{11}$").matches(A)){toast("Invalid Aadhaar format");return@btn};if(G.isNotBlank()&&!Regex("^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$").matches(G)){toast("Invalid GSTIN format");return@btn};db.upsertProfile(old?.rowId,"BORROWER",old?.id?:"BOR-${System.currentTimeMillis()}",n.text.trim().toString(),m.text.toString(),alt.text.toString(),ad.text.trim().toString(),city.text.trim().toString(),state.text.trim().toString(),pin.text.toString(),P,A,G,photoUri?.toString()?:old?.photo);toast("Profile saved");profiles()},54);put(r,btn("BACK",Color.DKGRAY){profiles()},50);show(r)}
 private fun next(vararg x:EditText){for(i in 0 until x.size-1)x[i].setOnEditorActionListener{_,a,_->if(a==EditorInfo.IME_ACTION_NEXT){x[i+1].requestFocus();true}else false}}
 private fun pinLookup(pin:String,city:EditText,state:EditText){Thread{try{val c=java.net.URL("https://api.postalpincode.in/pincode/$pin").openConnection() as java.net.HttpURLConnection;c.connectTimeout=5000;c.readTimeout=5000;val s=BufferedReader(InputStreamReader(c.inputStream)).use{it.readText()};val x=Regex("\"Name\"\\s*:\\s*\"([^\"]+)\".*?\"State\"\\s*:\\s*\"([^\"]+)\"").find(s);runOnUiThread{if(x!=null){city.setText(x.groupValues[1]);state.setText(x.groupValues[2])}else toast("PIN not found")}}catch(_:Exception){runOnUiThread{toast("PIN lookup unavailable; enter city/state manually")}}}.start()}
 private fun summary(id:Long){val x=db.profileData(id)?:return;val s=db.borrowerSummary(id);val r=page("Borrower Summary","Existing exposure before new credit");r.addView(photo(x.photo,88));r.addView(tv(x.name,22f));r.addView(tv("${x.id} • ${x.mobile}"));r.addView(tv("PAN ${x.pan.ifBlank{"—"}} • Aadhaar ${if(x.aadhaar.isBlank())"—" else "format valid"}"));r.addView(tv("Total ${money(s.total)} • Outstanding ${money(s.outstanding)} • Overdue ${s.overdue}"));put(r,btn("REGISTER INFORMAL CREDIT",blue){informal(id)},54);put(r,btn("BACK",Color.DKGRAY){profiles()},50);show(r)}
 private fun informal(pre:Long?=null){val bs=db.searchProfiles("BORROWER","");if(bs.isEmpty()){toast("Create borrower profile first");profile(null);return};val r=page("Informal Credit","OTP consent is mandatory before final registration");val bo=Spinner(this);bo.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,bs.map{"${it.name} • ${it.mobile}"});pre?.let{val i=bs.indexOfFirst{x->x.rowId==it};if(i>=0)bo.setSelection(i)};val type=Spinner(this);type.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,arrayOf("Personal Credit","Business Credit","Trade Credit","Advance","Other"));val dir=Spinner(this);dir.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,arrayOf("Credit Given","Credit Received"));val amt=ed("Principal / amount *");val roi=ed("Annual ROI %");val n=ed("Tenor months *",3,true).apply{setText("12")};val method=Spinner(this);method.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,arrayOf("EMI","Principal + Interest","Bullet / Full payment"));put(r,tv("Borrower *"));put(r,bo);put(r,tv("Credit type"));put(r,type);put(r,tv("Direction"));put(r,dir);put(r,amt);put(r,roi);put(r,n);put(r,tv("Repayment method"));put(r,method);put(r,btn("UPLOAD INVOICE / SUPPORTING DOCUMENT",teal){pickDoc("SUPPORTING_DOCUMENT")},52);put(r,btn("REVIEW + OTP CONSENT + REGISTER",green){val a=amt.text.toString().toDoubleOrNull();val rate=roi.text.toString().toDoubleOrNull()?:0.0;val mo=n.text.toString().toIntOrNull()?:0;if(a==null||a<=0||mo !in 1..240){toast("Enter valid amount and tenor");return@btn};val q=rate/1200;val inst=if(method.selectedItem.toString()=="EMI"&&q>0)a*q*(1+q).pow(mo)/((1+q).pow(mo)-1) else a/mo;val interest=if(method.selectedItem.toString()=="EMI")inst*mo-a else a*rate*mo/1200;val st=today();val en=SimpleDateFormat("yyyy-MM-dd",Locale.US).format(Calendar.getInstance().apply{add(Calendar.MONTH,mo)}.time);consent(bs[bo.selectedItemPosition].rowId,type.selectedItem.toString(),dir.selectedItem.toString(),a,rate,mo,method.selectedItem.toString(),inst,interest,a+interest,st,en)},54);put(r,btn("BACK",Color.DKGRAY){home()},50);show(r)}
 private fun consent(borrower:Long,type:String,dir:String,a:Double,rate:Double,n:Int,method:String,inst:Double,int:Double,pay:Double,st:String,en:String){otp=Random.nextInt(100000,1000000).toString();val input=ed("Enter 6-digit OTP",6,true);val d=AlertDialog.Builder(this).setTitle("Digital consent").setMessage("Principal ${money(a)}\nROI $rate%\nMethod $method\nInstallment ${money(inst)}\nTotal payable ${money(pay)}\nPeriod $st to $en\n\nInformal credits require counterparty consent.").setView(input).setNegativeButton("CANCEL",null).setPositiveButton("CONFIRM",null).create();d.setOnShowListener{toast("Demo OTP: $otp");d.getButton(-1).setOnClickListener{if(input.text.toString()!=otp){input.error="Incorrect OTP";return@setOnClickListener};val id=db.addCredit(borrower,null,type,dir,a,rate,n,method,inst,int,pay,st,en,"",docUri?.toString(),true);db.createSchedule(id,inst,n,en);db.saveConsent(id,"OTP_VERIFIED","INFORMAL_CREDIT_CONSENT");docUri?.let{db.saveDocument(id,"SUPPORTING_DOCUMENT",it.toString())};d.dismiss();toast("Credit registered after OTP consent");home()}};d.show()}
 private fun rental(){val bs=db.searchProfiles("BORROWER","");if(bs.isEmpty()){toast("Create tenant profile first");profile(null);return};val r=page("Rental / Lease","Dedicated lease module — not personal credit");val ten=Spinner(this);ten.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,bs.map{"${it.name} • ${it.mobile}"});val prop=ed("Property / premises *");val owner=ed("Landlord / owner *");val rent=ed("Monthly rent *");val dep=ed("Security deposit *");val st=ed("Lease start YYYY-MM-DD *");val en=ed("Lease end YYYY-MM-DD *");val freq=Spinner(this);freq.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,arrayOf("Monthly","Quarterly","Yearly"));val due=ed("Rent due day 1–31",2,true);val esc=ed("Annual escalation %");val notice=ed("Notice period days",3,true);val util=ed("Utilities / maintenance responsibility");put(r,tv("Tenant / counterparty"));put(r,ten);listOf(prop,owner,rent,dep,st,en,due,esc,notice,util).forEach{put(r,it)};put(r,tv("Rent frequency"));put(r,freq);put(r,btn("UPLOAD LEASE AGREEMENT",teal){pickDoc("LEASE_AGREEMENT")},52);put(r,btn("SAVE LEASE",green){val rv=rent.text.toString().toDoubleOrNull();val mm=months(st.text.toString(),en.text.toString());if(prop.text.trim().length<3||owner.text.trim().length<2||rv==null||rv<=0||mm<=0){toast("Complete property, owner, rent and valid dates");return@btn};val id=db.addCredit(bs[ten.selectedItemPosition].rowId,null,"Rental / Lease","Credit Given",rv,esc.text.toString().toDoubleOrNull()?:0.0,mm,"Rental • ${freq.selectedItem}",rv,rv*mm,rv*mm,st.text.toString(),en.text.toString(),"",docUri?.toString(),false);db.createSchedule(id,rv,mm,en.text.toString());docUri?.let{db.saveDocument(id,"LEASE_AGREEMENT",it.toString())};toast("Separate rental lease saved");home()},54);put(r,btn("BACK",Color.DKGRAY){home()},50);show(r)}
 private fun months(a:String,b:String)=try{val f=SimpleDateFormat("yyyy-MM-dd",Locale.US);val x=Calendar.getInstance();x.time=f.parse(a)!!;val y=Calendar.getInstance();y.time=f.parse(b)!!;((y.get(Calendar.YEAR)-x.get(Calendar.YEAR))*12+y.get(Calendar.MONTH)-x.get(Calendar.MONTH)).coerceAtLeast(0)}catch(_:Exception){0}
 private fun formal(){val r=page("Formal Loan / Bank Credit","No counterparty consent. Upload sanction letter and statement and compare charges.");val bank=ed("Bank / NBFC / lender *");val acct=ed("Loan account number");val sanc=ed("Sanction amount *");val rate=ed("Sanctioned ROI % *");val fee=ed("Processing fee");val other=ed("Other charges");val tenure=ed("Tenure months",3,true);val emi=ed("Sanctioned EMI");listOf(bank,acct,sanc,rate,fee,other,tenure,emi).forEach{put(r,it)};put(r,btn("UPLOAD SANCTION LETTER",teal){pickDoc("SANCTION_LETTER")},52);put(r,btn("UPLOAD STATEMENT OF ACCOUNT",navy){pickDoc("STATEMENT_OF_ACCOUNT")},52);put(r,btn("COMPARE + SAVE REVIEW",green){val s=sanc.text.toString().toDoubleOrNull();val rr=rate.text.toString().toDoubleOrNull();if(bank.text.trim().length<2||s==null||rr==null){toast("Enter lender, sanction amount and ROI");return@btn};val x=fee.text.toString().toDoubleOrNull()?:0.0;val y=other.text.toString().toDoubleOrNull()?:0.0;AlertDialog.Builder(this).setTitle("Formal loan charge comparison").setMessage("SANCTIONED\nROI: $rr%\nProcessing fee: ${money(x)}\nOther charges: ${money(y)}\nTenure: ${tenure.text}\nEMI: ${emi.text}\n\nDocuments selected: sanction letter + statement.\n\nNo counterparty OTP consent is required for formal bank credit.").setPositiveButton("OK",null).show();toast("Formal loan review completed")},54);put(r,btn("BACK",Color.DKGRAY){home()},50);show(r)}
 private fun docs(){val r=page("Documents & Consent","Digital evidence and consent rules");r.addView(tv("Informal credits: OTP consent before registration. Formal bank credits: no counterparty consent. Rental: lease agreement stored separately."));put(r,btn("UPLOAD GENERAL DOCUMENT",teal){pickDoc("GENERAL_DOCUMENT")},52);put(r,btn("BACK",Color.DKGRAY){home()},50);show(r)}
 private fun credits(dir:String?){val r=page("Credit History",dir?:"All transactions");val rows=db.credits(dir);if(rows.isEmpty())r.addView(tv("No records."));rows.forEach{x->action(r,"₹",x.creditId,"${x.borrowerName} • ${x.type} • ${money(x.amount)}",blue){detail(x.id)}};put(r,btn("BACK",Color.DKGRAY){home()},50);show(r)}
 private fun detail(id:Long){val x=db.creditDetail(id)?:return;val r=page(x.creditId,"Transaction details");listOf("Borrower: ${x.borrowerName}","Type: ${x.type}","Direction: ${x.direction}","Principal: ${money(x.amount)}","ROI: ${x.roi}%","Method: ${x.method}","Payable: ${money(x.payable)}","Period: ${x.start} to ${x.end}").forEach{r.addView(tv(it))};put(r,btn("REPAYMENT SCHEDULE",green){repay(false)},52);put(r,btn("BACK",Color.DKGRAY){credits(null)},50);show(r)}
 private fun repay(over:Boolean){val r=page("Repayment Centre",if(over)"Overdue" else "Due / upcoming");val rows=db.schedules(null,over);if(rows.isEmpty())r.addView(tv("No payments."));rows.forEach{s->action(r,"₹",s.creditId,"Due ${s.dueDate} • ${money(s.amount)} • ${s.status}",if(s.status=="OVERDUE")red else green){val i=ed("Payment amount");i.setText(String.format(Locale.US,"%.2f",s.amount));AlertDialog.Builder(this).setTitle("Record repayment").setView(i).setNegativeButton("CANCEL",null).setPositiveButton("SAVE"){_,_->val v=db.recordPayment(s.id,s.creditDbId,i.text.toString().toDoubleOrNull()?:0.0);toast(if(v>0)"Repayment recorded" else "No outstanding amount");repay(false)}.show()}};put(r,btn("BACK",Color.DKGRAY){home()},50);show(r)}
 private fun owner(){val m=p.getString("current_mobile","")?:"";val r=page("My Profile","Account owner");r.addView(photo(p.getString("photo_$m",""),110));r.addView(tv(p.getString("name_$m","User")?:"User",22f));r.addView(tv("Mobile: $m"));r.addView(tv("Address: ${p.getString("address_$m","")}"));put(r,btn("CHANGE PHOTO",teal){pickAccountPhoto()},50);put(r,btn("BACK",Color.DKGRAY){home()},50);show(r)}
 private fun pickPhoto(im:ImageView){photoTarget=im;startActivityForResult(Intent(Intent.ACTION_OPEN_DOCUMENT).apply{type="image/*";addCategory(Intent.CATEGORY_OPENABLE);addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION or Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION)},1001)}
 private fun pickAccountPhoto(){startActivityForResult(Intent(Intent.ACTION_OPEN_DOCUMENT).apply{type="image/*";addCategory(Intent.CATEGORY_OPENABLE);addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION or Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION)},1002)}
 private fun pickDoc(k:String){docType=k;startActivityForResult(Intent(Intent.ACTION_OPEN_DOCUMENT).apply{type="application/pdf";addCategory(Intent.CATEGORY_OPENABLE);addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION or Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION)},2001)}
 override fun onActivityResult(req:Int,res:Int,d:Intent?){super.onActivityResult(req,res,d);if(res!=RESULT_OK||d?.data==null)return;val u=d.data!!;try{contentResolver.takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION)}catch(_:Exception){};when(req){1001->{photoUri=u;photoTarget?.setImageURI(u)};1002->{val m=p.getString("current_mobile","")?:"";p.edit().putString("photo_$m",u.toString()).apply();toast("Profile photo updated")};2001->{docUri=u;toast("Selected $docType")}}}
}
