package com.udhaardaar.mvp

import android.app.AlertDialog
import android.os.Bundle
import android.text.InputType
import android.view.WindowManager
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import org.json.JSONObject
import java.text.SimpleDateFormat
import java.util.*

class V5BorrowerActivity:AppCompatActivity(){
 private val store by lazy{V5LocalStore(this)};private val repo by lazy{V5WorkflowRepository(this)};private val consent by lazy{V5OtpConsentService(this)}
 private lateinit var query:EditText;private lateinit var result:LinearLayout
 private fun e(h:String)=EditText(this@V5BorrowerActivity).apply{hint=h;setSingleLine(true);setPadding(14,10,14,10)}
 private fun add(r:LinearLayout,v:android.view.View,h:Int=54){r.addView(v,LinearLayout.LayoutParams(-1,h).apply{setMargins(0,5,0,5)})}
 override fun onCreate(b:Bundle?){super.onCreate(b);window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);show()}
 private fun show(){val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(22,18,22,30)};add(r,TextView(this).apply{text="UDHAARDAAR V5 • Borrower & Party Profiles";textSize=23f},62);add(r,TextView(this).apply{text="Search by name, mobile, PAN, Aadhaar, GSTIN or unique ID. History/exposure requires user consent.";textSize=13f},72);query=e("Search party / borrower");add(r,query);add(r,Button(this).apply{text="SEARCH PROFILES";setOnClickListener{search(query.text.toString())}});add(r,Button(this).apply{text="CREATE NEW BORROWER / PARTY";setOnClickListener{createDialog()}});add(r,Button(this).apply{text="LOAD 12 QA SAMPLE PROFILES";setOnClickListener{seed();search("")}});result=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};add(r,result,0);add(r,Button(this).apply{text="BACK";setOnClickListener{finish()}});setContentView(ScrollView(this).apply{isFillViewport=true;addView(r)})}
 private fun search(q:String){val x=q.trim().lowercase(Locale.getDefault());val p=store.all("profiles").filter{z->x.isEmpty()||listOf("id","name","mobile","pan","aadhaar","gstin").any{z.optString(it).lowercase(Locale.getDefault()).contains(x)}};result.removeAllViews();if(p.isEmpty()){result.addView(TextView(this).apply{text="No matching profile. Create a new borrower / party.";setPadding(4,14,4,14)});return};p.forEach{z->val b=Button(this).apply{text="${z.optString("name")} [${z.optString("id")}]\nMobile: ${z.optString("mobile")} • PIN: ${z.optString("pin")}\nTAP TO SELECT / REQUEST CONSENTED HISTORY";setOnClickListener{selectOrHistory(z)}};result.addView(b,LinearLayout.LayoutParams(-1,88).apply{setMargins(0,4,0,4)})}}
 private fun selectOrHistory(p:JSONObject){val options=arrayOf("SELECT FOR CREDIT REGISTRATION","REQUEST USER CONSENT / VIEW HISTORY");AlertDialog.Builder(this).setTitle(p.optString("name")).setItems(options){_,which->if(which==0){setResult(RESULT_OK,android.content.Intent().putExtra("profileId",p.optString("id")).putExtra("profileName",p.optString("name")));finish()}else requestHistoryConsent(p)}.setNegativeButton("CANCEL",null).show()}
 private fun requestHistoryConsent(p:JSONObject){val cid=consent.issue("HISTORY-${p.optString("id")}-${System.currentTimeMillis()}","BORROWER_CREDIT_HISTORY_CONSENT",p.optString("name"));val code=store.find("consents",cid)?.optString("otp","")?:"";val input=e("Enter 6-digit OTP");AlertDialog.Builder(this).setTitle("Borrower consent required").setMessage("Credit history, exposure and score are private.\nDemo OTP: $code").setView(input).setNegativeButton("CANCEL",null).setPositiveButton("VERIFY",null).create().also{d->d.setOnShowListener{d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener{if(consent.verify(cid,input.text.toString())){showHistory(p);d.dismiss()}else input.error="Incorrect OTP"}};d.show()}}
 private fun showHistory(p:JSONObject){val credits=store.all("credits").filter{it.optString("borrower").equals(p.optString("name"),true)||it.optString("borrower")==p.optString("id")};val receivable=credits.filter{it.optString("direction")=="Credit Given"}.sumOf{it.optDouble("outstanding",0.0)};val payable=credits.filter{it.optString("direction")=="Credit Received"}.sumOf{it.optDouble("outstanding",0.0)};val closed=credits.count{it.optString("status")=="CLOSED"};AlertDialog.Builder(this).setTitle("Consented borrower history").setMessage("${p.optString("name")}\nUnique ID: ${p.optString("id")}\n\nCredits: ${credits.size}\nReceivable: ₹${"%.2f".format(receivable)}\nPayable: ₹${"%.2f".format(payable)}\nClosed: $closed\n\n"+credits.joinToString("\n"){c->"${c.optString("type")} • ${c.optString("direction")} • ₹${c.optDouble("principal",0.0)} • Outstanding ₹${c.optDouble("outstanding",0.0)} • ${c.optString("status")}"}).setPositiveButton("OK",null).show()}
 private fun createDialog(){val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(20,5,20,5)};val n=e("Full name / business name *");val m=e("Mobile *").apply{inputType=InputType.TYPE_CLASS_PHONE};val pan=e("PAN");val aad=e("Aadhaar");val gst=e("GSTIN");val pin=e("PIN code");val city=e("City (auto-filled)");val state=e("State (auto-filled)");city.isFocusable=false;state.isFocusable=false;listOf(n,m,pan,aad,gst,pin,city,state).forEach{box.addView(it)};pin.setOnFocusChangeListener{_,has->if(has&&pin.text.length==6)resolvePin(pin.text.toString(),city,state)};AlertDialog.Builder(this).setTitle("Create borrower / party").setView(box).setNegativeButton("CANCEL",null).setPositiveButton("SAVE",null).create().also{d->d.setOnShowListener{d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener{val ns=n.text.toString().trim();val ms=m.text.toString().trim();if(ns.length<2||!V5Validation.mobile(ms)){m.error="Valid 10-digit mobile required";return@setOnClickListener};if(!V5Validation.pan(pan.text.toString())||!V5Validation.aadhaar(aad.text.toString())||!V5Validation.gstin(gst.text.toString())||!V5Validation.pin(pin.text.toString())){Toast.makeText(this@V5BorrowerActivity,"Invalid identity or PIN format",Toast.LENGTH_LONG).show();return@setOnClickListener};val id="UDH-${SimpleDateFormat("yyyy",Locale.US).format(Date())}-${System.currentTimeMillis().toString().takeLast(8)}";repo.saveProfile(V5Profile(id,"BORROWER",ns,ms,pan.text.toString().trim().uppercase(),aad.text.toString().trim(),gst.text.toString().trim().uppercase(),null,city.text.toString(),state.text.toString(),pin.text.toString()));repo.appendAudit(id,"BORROWER_PROFILE_CREATED",id,"identity/address captured");d.dismiss();query.setText(id);search(id)}};d.show()}}
 private fun resolvePin(pin:String,city:EditText,state:EditText){if(!V5Validation.pin(pin))return;Thread{try{val c=java.net.URL("https://api.postalpincode.in/pincode/$pin").openConnection() as java.net.HttpURLConnection;c.connectTimeout=5000;c.readTimeout=5000;val text=c.inputStream.bufferedReader().use{it.readText()};val a=org.json.JSONArray(text);val first=a.optJSONObject(0)?.optJSONArray("PostOffice")?.optJSONObject(0);runOnUiThread{city.setText(first?.optString("District","")?:"");state.setText(first?.optString("State","")?:"")};c.disconnect()}catch(_:Exception){}}.start()}
 private fun seed(){repeat(12){i->repo.saveProfile(V5Profile("QA-${i+1}","BORROWER","QA Borrower ${i+1}","9${String.format("%09d",i+1)}",null,null,null,null,"QA City","QA State","11000${i+1}"))};Toast.makeText(this,"12 QA profiles added",Toast.LENGTH_SHORT).show()}
}
