package com.udhaardaar.mvp

import android.app.AlertDialog
import android.content.Intent
import android.net.Uri
import android.os.Bundle
import android.view.WindowManager
import android.widget.*
import org.json.JSONObject
import java.util.Locale

class V5ChargeComparisonActivity : androidx.appcompat.app.AppCompatActivity() {
    private var sanctionUri: Uri? = null
    private var statementUri: Uri? = null
    private lateinit var sanctionRoi: EditText
    private lateinit var actualRoi: EditText
    private lateinit var sanctionedFees: EditText
    private lateinit var actualFees: EditText
    private lateinit var findings: EditText
    private val store by lazy { V5LocalStore(this) }
    private val repo by lazy { V5WorkflowRepository(this) }
    private fun e(h:String)=EditText(this).apply{hint=h;setSingleLine(true)}
    private fun add(r:LinearLayout,v:android.view.View,h:Int=56){r.addView(v,LinearLayout.LayoutParams(-1,h).apply{setMargins(0,5,0,5)})}
    override fun onCreate(b:Bundle?){super.onCreate(b);window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);show()}
    private fun show(){val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(20,16,20,28)};add(r,TextView(this).apply{text="UDHAARDAAR V5 • Sanction vs Statement Analysis";textSize=22f},68);add(r,TextView(this).apply{text="Upload the sanction letter and account statement, review extracted/entered charges, then produce a printable comparison report.";textSize=13f},70);add(r,Button(this).apply{text="UPLOAD / SCAN SANCTION LETTER";setOnClickListener{pick(10)}});add(r,Button(this).apply{text="UPLOAD / SCAN ACCOUNT STATEMENT";setOnClickListener{pick(11)}});sanctionRoi=e("Sanctioned ROI % (from sanction letter)");actualRoi=e("Actual/debited ROI % (from statement)");sanctionedFees=e("Sanctioned / agreed fees & charges ₹");actualFees=e("Actual/debited fees & charges ₹");findings=e("Additional observations / charge heads (optional)");listOf(sanctionRoi,actualRoi,sanctionedFees,actualFees,findings).forEach{add(r,it)};add(r,Button(this).apply{text="COMPARE ACTUAL VS DEBITED / SANCTIONED CHARGES";setOnClickListener{compare()}},62);add(r,Button(this).apply{text="VIEW / PRINT LAST REPORT";setOnClickListener{printLast()}},58);add(r,Button(this).apply{text="BACK";setOnClickListener{finish()}},50);setContentView(ScrollView(this).apply{isFillViewport=true;addView(r)})}
    private fun pick(code:Int){startActivityForResult(Intent(Intent.ACTION_OPEN_DOCUMENT).apply{type="application/pdf";putExtra(Intent.EXTRA_MIME_TYPES,arrayOf("application/pdf","image/jpeg","image/png"));addCategory(Intent.CATEGORY_OPENABLE)},code)}
    @Deprecated("Android callback retained for API 23") override fun onActivityResult(requestCode:Int,resultCode:Int,data:Intent?){super.onActivityResult(requestCode,resultCode,data);if(resultCode==RESULT_OK){if(requestCode==10)sanctionUri=data?.data else if(requestCode==11)statementUri=data?.data;Toast.makeText(this,if(requestCode==10)"Sanction letter captured" else "Account statement captured",Toast.LENGTH_SHORT).show()}}
    private fun d(s:String)=s.toDoubleOrNull()?:0.0
    private fun compare(){if(sanctionUri==null||statementUri==null){Toast.makeText(this,"Please capture both sanction letter and account statement first",Toast.LENGTH_LONG).show();return};val sr=d(sanctionRoi.text.toString());val ar=d(actualRoi.text.toString());val sf=d(sanctionedFees.text.toString());val af=d(actualFees.text.toString());val variance=af-sf;val findingsList=mutableListOf<String>();if(ar>sr)findingsList.add("Actual ROI is higher than sanctioned ROI by %.2f percentage points.".format(Locale.US,ar-sr));if(variance>0)findingsList.add("Debited charges exceed agreed/sanctioned charges by ₹%.2f.".format(Locale.US,variance));if(variance<0)findingsList.add("Debited charges are lower than agreed/sanctioned charges by ₹%.2f.".format(Locale.US,-variance));if(findings.text.isNotBlank())findingsList.add(findings.text.toString());val id="CMP-${System.currentTimeMillis()}";store.replace("charge_comparisons",JSONObject().apply{put("id",id);put("type","SANCTION_STATEMENT_CHARGE_COMPARISON");put("sanctionDocumentUri",sanctionUri.toString());put("statementDocumentUri",statementUri.toString());put("sanctionedRoi",sr);put("actualRoi",ar);put("sanctionedFees",sf);put("actualFees",af);put("variance",variance);put("findings",findingsList.joinToString(" | "));put("createdAt",System.currentTimeMillis())});repo.appendAudit(id,"CHARGE_COMPARISON_CREATED",id,"sanction-vs-statement; timestamp=${System.currentTimeMillis()}");showReport(id,sr,ar,sf,af,variance,findingsList)}
    private fun showReport(id:String,sr:Double,ar:Double,sf:Double,af:Double,v:Double,f:List<String>){val msg="CHARGE COMPARISON REPORT\n\nReport: $id\n\nSanctioned ROI: %.2f%%\nActual/debited ROI: %.2f%%\nROI variance: %.2f pp\n\nAgreed/sanctioned charges: ₹%.2f\nActual/debited charges: ₹%.2f\nCharge variance: ₹%.2f\n\nFindings:\n%s\n\nSource documents: sanction letter + account statement\nGenerated: %s".format(Locale.US,sr,ar,ar-sr,sf,af,v,f.joinToString("\n• ",prefix="• "),java.text.SimpleDateFormat("yyyy-MM-dd HH:mm",Locale.US).format(java.util.Date()));AlertDialog.Builder(this).setTitle("Comparison complete").setMessage(msg).setPositiveButton("PRINT",null).setNegativeButton("CLOSE",null).create().apply{setOnShowListener{getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener{printText(msg)}}}.show()}
    private fun printLast(){val x=store.all("charge_comparisons");if(x.isEmpty()){Toast.makeText(this,"No comparison report yet",Toast.LENGTH_SHORT).show();return};val j=x.last();showReport(j.optString("id"),j.optDouble("sanctionedRoi"),j.optDouble("actualRoi"),j.optDouble("sanctionedFees"),j.optDouble("actualFees"),j.optDouble("variance"),listOf(j.optString("findings")))}
    private fun printText(text:String){val pm=getSystemService(PRINT_SERVICE) as android.print.PrintManager;pm.print("Udhaardaar charge comparison",PrintDocumentAdapterWrapper(text),null)}
}
private class PrintDocumentAdapterWrapper(private val text:String):android.print.PrintDocumentAdapter(){override fun onLayout(oldAttributes:android.print.PrintAttributes?,newAttributes:android.print.PrintAttributes?,cancellationSignal:android.os.CancellationSignal?,callback:android.print.PrintDocumentAdapter.LayoutResultCallback?,extras:android.os.Bundle?){callback?.onLayoutFinished(android.print.PrintDocumentInfo.Builder("charge-comparison.txt").setContentType(android.print.PrintDocumentInfo.CONTENT_TYPE_DOCUMENT).build(),true)};override fun onWrite(pages:Array<android.print.PageRange>?,destination:android.os.ParcelFileDescriptor?,cancellationSignal:android.os.CancellationSignal?,callback:android.print.PrintDocumentAdapter.WriteResultCallback?){try{android.os.ParcelFileDescriptor.AutoCloseOutputStream(destination!!).use{it.write(text.toByteArray(Charsets.UTF_8))};callback?.onWriteFinished(arrayOf(android.print.PageRange.ALL_PAGES))}catch(e:Exception){callback?.onWriteFailed(e.message)}}}
