package com.udhaardaar.mvp

import android.app.AlertDialog
import android.content.Intent
import android.graphics.BitmapFactory
import android.graphics.pdf.PdfRenderer
import android.net.Uri
import android.os.Bundle
import android.view.WindowManager
import android.widget.*
import org.json.JSONObject
import java.util.Locale

class V5ChargeComparisonActivity : androidx.appcompat.app.AppCompatActivity() {
 private var sanctionUri:Uri?=null;private var statementUri:Uri?=null
 private lateinit var sanctionRoi:EditText;private lateinit var actualRoi:EditText;private lateinit var sanctionedFees:EditText;private lateinit var actualFees:EditText;private lateinit var findings:EditText
 private val store by lazy{V5LocalStore(this)};private val repo by lazy{V5WorkflowRepository(this)}
 private fun e(h:String)=EditText(this).apply{hint=h;setSingleLine(true)};private fun add(r:LinearLayout,v:android.view.View,h:Int=56){r.addView(v,LinearLayout.LayoutParams(-1,h).apply{setMargins(0,5,0,5)})}
 override fun onCreate(b:Bundle?){super.onCreate(b);window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);show()}
 private fun show(){val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(20,16,20,28)};add(r,TextView(this).apply{text="UDHAARDAAR V5 • Sanction vs Statement Analysis";textSize=22f},68);add(r,TextView(this).apply{text="Import/scan → real OCR → review/correct → compare → print";textSize=13f},58);add(r,Button(this).apply{text="SCAN SANCTION LETTER + OCR";setOnClickListener{pick(10)}});add(r,Button(this).apply{text="SCAN ACCOUNT STATEMENT + OCR";setOnClickListener{pick(11)}});sanctionRoi=e("Sanctioned ROI % — review/edit");actualRoi=e("Actual/debited ROI % — review/edit");sanctionedFees=e("Sanctioned/agreed charges ₹");actualFees=e("Actual/debited charges ₹");findings=e("OCR extraction + reviewer observations");listOf(sanctionRoi,actualRoi,sanctionedFees,actualFees,findings).forEach{add(r,it)};add(r,Button(this).apply{text="COMPARE";setOnClickListener{compare()}},62);add(r,Button(this).apply{text="VIEW / PRINT LAST REPORT";setOnClickListener{printLast()}},58);add(r,Button(this).apply{text="BACK";setOnClickListener{finish()}},50);setContentView(ScrollView(this).apply{isFillViewport=true;addView(r)})}
 private fun pick(c:Int){startActivityForResult(Intent(Intent.ACTION_OPEN_DOCUMENT).apply{type="application/pdf";putExtra(Intent.EXTRA_MIME_TYPES,arrayOf("application/pdf","image/jpeg","image/png"));addCategory(Intent.CATEGORY_OPENABLE)},c)}
 @Deprecated("API 23 compatibility") override fun onActivityResult(c:Int,r:Int,d:Intent?){super.onActivityResult(c,r,d);if(r==RESULT_OK){val u=d?.data;if(c==10)sanctionUri=u else if(c==11)statementUri=u;if(u!=null)runOcr(u,if(c==10)"SANCTION" else "STATEMENT")}}
 private fun bitmapFrom(u:Uri)=try{val mime=contentResolver.getType(u).orEmpty();if(mime=="application/pdf"||u.toString().lowercase().endsWith(".pdf")){contentResolver.openFileDescriptor(u,"r")?.use{p->PdfRenderer(p).use{r->if(r.pageCount>0)r.openPage(0).use{page->android.graphics.Bitmap.createBitmap(page.width.coerceAtLeast(1),page.height.coerceAtLeast(1),android.graphics.Bitmap.Config.ARGB_8888).also{page.render(it,null,null,PdfRenderer.Page.RENDER_MODE_FOR_DISPLAY)}}else null}}}else contentResolver.openInputStream(u)?.use{BitmapFactory.decodeStream(it)}}catch(_:Exception){null}
 private fun runOcr(u:Uri,label:String){val b=bitmapFrom(u)?:run{Toast.makeText(this,"Unable to read document",Toast.LENGTH_LONG).show();return};Toast.makeText(this,"OCR processing…",Toast.LENGTH_SHORT).show();V5OcrService(this).extract(b,{text,confidence->runOnUiThread{val s="OCR $label confidence ${"%.0f".format(Locale.US,confidence*100)}%\n\n$text";findings.setText(s);AlertDialog.Builder(this).setTitle("Review OCR extraction").setMessage(s.take(7000)).setPositiveButton("USE / EDIT",null).show()}},{x->runOnUiThread{Toast.makeText(this,"OCR failed: ${x.message}",Toast.LENGTH_LONG).show()}})}
 private fun d(s:String)=s.toDoubleOrNull()?:0.0
 private fun compare(){if(sanctionUri==null||statementUri==null){Toast.makeText(this,"Both documents are required",Toast.LENGTH_LONG).show();return};val sr=d(sanctionRoi.text.toString());val ar=d(actualRoi.text.toString());val sf=d(sanctionedFees.text.toString());val af=d(actualFees.text.toString());val v=af-sf;val fs=mutableListOf<String>();if(ar>sr)fs.add("Actual ROI exceeds sanctioned ROI by %.2f pp.".format(Locale.US,ar-sr));if(v>0)fs.add("Debited charges exceed agreed charges by ₹%.2f.".format(Locale.US,v));if(v<0)fs.add("Debited charges are lower by ₹%.2f.".format(Locale.US,-v));if(findings.text.isNotBlank())fs.add(findings.text.toString());val id="CMP-${System.currentTimeMillis()}";store.replace("charge_comparisons",JSONObject().apply{put("id",id);put("sanctionDocumentUri",sanctionUri.toString());put("statementDocumentUri",statementUri.toString());put("sanctionedRoi",sr);put("actualRoi",ar);put("sanctionedFees",sf);put("actualFees",af);put("variance",v);put("findings",fs.joinToString(" | "));put("ocrReviewed",true);put("createdAt",System.currentTimeMillis())});repo.appendAudit(id,"CHARGE_COMPARISON_CREATED",id,"OCR extracted, reviewed and compared");showReport(id,sr,ar,sf,af,v,fs)}
 private fun showReport(id:String,sr:Double,ar:Double,sf:Double,af:Double,v:Double,f:List<String>){val msg="CHARGE COMPARISON REPORT\n\n$id\nSanctioned ROI: %.2f%%\nActual ROI: %.2f%%\nROI variance: %.2f pp\n\nAgreed charges: ₹%.2f\nActual charges: ₹%.2f\nCharge variance: ₹%.2f\n\nReviewed findings:\n%s".format(Locale.US,sr,ar,ar-sr,sf,af,v,f.joinToString("\n• ",prefix="• "));AlertDialog.Builder(this).setTitle("Comparison complete").setMessage(msg).setPositiveButton("PRINT",null).setNegativeButton("CLOSE",null).create().apply{setOnShowListener{getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener{printText(msg)}}}.show()}
 private fun printLast(){val x=store.all("charge_comparisons");if(x.isEmpty()){Toast.makeText(this,"No report yet",Toast.LENGTH_SHORT).show();return};val j=x.last();showReport(j.optString("id"),j.optDouble("sanctionedRoi"),j.optDouble("actualRoi"),j.optDouble("sanctionedFees"),j.optDouble("actualFees"),j.optDouble("variance"),listOf(j.optString("findings")))}
 private fun printText(t:String){(getSystemService(PRINT_SERVICE) as android.print.PrintManager).print("Udhaardaar charge comparison",PrintDocumentAdapterWrapper(t),null)}
}
private class PrintDocumentAdapterWrapper(private val text:String):android.print.PrintDocumentAdapter(){override fun onLayout(o:android.print.PrintAttributes?,n:android.print.PrintAttributes?,c:android.os.CancellationSignal?,cb:android.print.PrintDocumentAdapter.LayoutResultCallback?,e:Bundle?){cb?.onLayoutFinished(android.print.PrintDocumentInfo.Builder("charge-comparison.txt").setContentType(android.print.PrintDocumentInfo.CONTENT_TYPE_DOCUMENT).build(),true)};override fun onWrite(p:Array<android.print.PageRange>?,d:android.os.ParcelFileDescriptor?,c:android.os.CancellationSignal?,cb:android.print.PrintDocumentAdapter.WriteResultCallback?){try{android.os.ParcelFileDescriptor.AutoCloseOutputStream(d!!).use{it.write(text.toByteArray(Charsets.UTF_8))};cb?.onWriteFinished(arrayOf(android.print.PageRange.ALL_PAGES))}catch(e:Exception){cb?.onWriteFailed(e.message)}}}
