package com.udhaardaar.mvp

import android.app.AlertDialog
import android.app.DatePickerDialog
import android.content.Intent
import android.graphics.Color
import android.os.Bundle
import android.view.View
import android.view.ViewGroup
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import org.json.JSONObject
import java.text.SimpleDateFormat
import java.util.*
import kotlin.math.pow

/** Guided V5 flow: borrower -> terms -> schedule -> guarantor -> document preview -> OTP consent -> registration. */
class V5CreditRegistrationActivity:AppCompatActivity(){
 private val store by lazy{V5LocalStore(this)};private val otp by lazy{V5OtpConsentService(this)};private var profiles=emptyList<JSONObject>();private val consents=mutableMapOf<String,String>();private var docsReady=false;private var guarantorAdded=false;private var pendingCreditId="";private lateinit var borrower:Spinner;private lateinit var amount:EditText;private lateinit var roi:EditText;private lateinit var tenor:Spinner;private lateinit var method:Spinner;private lateinit var start:EditText;private lateinit var end:EditText;private lateinit var gName:EditText;private lateinit var gMobile:EditText;private lateinit var history:TextView;private lateinit var status:TextView
 private val bg=Color.rgb(238,248,253);private val navy=Color.rgb(24,58,92);private val blue=Color.rgb(25,111,220);private val teal=Color.rgb(0,145,135);private val green=Color.rgb(25,145,78);private val amber=Color.rgb(210,135,15);private val red=Color.rgb(190,55,55)
 private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt();private fun box(c:Int=Color.WHITE)=android.graphics.drawable.GradientDrawable().apply{setColor(c);setStroke(dp(1),Color.rgb(205,218,228));cornerRadius=dp(14).toFloat()};private fun tv(s:String,z:Float=14f,c:Int=navy)=TextView(this).apply{text=s;textSize=z;setTextColor(c);includeFontPadding=true;setPadding(dp(2),dp(2),dp(2),dp(2))};private fun e(h:String)=EditText(this).apply{hint=h;textSize=15f;setSingleLine(true);minHeight=dp(50);setPadding(dp(12),dp(7),dp(12),dp(7));background=box();imeOptions=android.view.inputmethod.EditorInfo.IME_ACTION_NEXT;setOnFocusChangeListener{v,has->if(has)v.post{v.requestRectangleOnScreen(android.graphics.Rect(0,0,v.width,v.height),true)}}};private fun add(r:LinearLayout,v:View){r.addView(v,LinearLayout.LayoutParams(-1,ViewGroup.LayoutParams.WRAP_CONTENT).apply{setMargins(0,dp(4),0,dp(4))})};private fun btn(s:String,c:Int,fn:()->Unit)=Button(this).apply{text=s;isAllCaps=false;textSize=14f;setTextColor(Color.WHITE);background=box(c);minHeight=dp(50);setPadding(dp(12),dp(6),dp(12),dp(6));setOnClickListener{fn()}}
 override fun onCreate(b:Bundle?){super.onCreate(b);window.setSoftInputMode(android.view.WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);show()}
 private fun show(){val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(16),dp(14),dp(16),dp(24));setBackgroundColor(bg)};add(r,tv("UDHAARDAAR V5",12f,teal));add(r,tv("Credit Registration",22f));add(r,tv("1 Borrower → 2 Terms → 3 Schedule → 4 Documents → 5 OTP consent → 6 Register",12f,Color.DKGRAY));profiles=store.all("profiles").filter{it.optString("type").isBlank()||it.optString("type").uppercase(Locale.US) in setOf("BORROWER","BUSINESS","BUYER","SELLER")};borrower=Spinner(this);refreshBorrowers();borrower.onItemSelectedListener=object:AdapterView.OnItemSelectedListener{override fun onItemSelected(p:AdapterView<*>?,v:View?,pos:Int,id:Long){profiles.getOrNull(pos)?.let{showHistory(it)}};override fun onNothingSelected(p:AdapterView<*>?) {}};add(r,tv("BORROWER",12f,blue));add(r,borrower);add(r,btn("FIND / CREATE / SELECT BORROWER",teal){startActivityForResult(Intent(this,V5PartyActivity::class.java),6101)})
  val direction=Spinner(this);direction.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,listOf("Credit Given","Credit Received"));val type=Spinner(this);type.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,listOf("Personal Credit","Business Credit","Trade Credit","Advance","Other"));add(r,tv("DIRECTION",12f,blue));add(r,direction);add(r,tv("CREDIT TYPE",12f,blue));add(r,type);history=tv("Select borrower to see credit history.",13f);history.background=box();history.setPadding(dp(12),dp(10),dp(12),dp(10));add(r,history)
  amount=e("Principal / credit amount ₹ *");roi=e("Annual ROI %");add(r,amount);add(r,roi);tenor=Spinner(this);tenor.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,arrayOf(1,3,6,9,12,18,24,36,48,60).map{"$it months"});add(r,tv("REPAYMENT PERIOD",12f,blue));add(r,tenor);method=Spinner(this);method.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,arrayOf("EMI","Principal + Interest","Bullet — Principal Only","Bullet — Monthly Interest","Bullet — Principal + Interest at End"));add(r,tv("REPAYMENT METHOD",12f,blue));add(r,method)
  start=e("Start date *");end=e("End date — auto calculated");end.isFocusable=false;add(r,start);add(r,end);add(r,btn("PICK START DATE",teal){pickDate(start)});tenor.onItemSelectedListener=object:AdapterView.OnItemSelectedListener{override fun onItemSelected(p:AdapterView<*>?,v:View?,pos:Int,id:Long){updateEnd()};override fun onNothingSelected(p:AdapterView<*>?) {}}
  gName=e("Guarantor name (optional)");gMobile=e("Guarantor mobile (required if added)");add(r,gName);add(r,gMobile);add(r,btn("ADD / VALIDATE GUARANTOR",red){if(gName.text.trim().length<2){gName.error="Enter guarantor name";return@btn};if(!Regex("^[6-9][0-9]{9}$").matches(gMobile.text.trim())){gMobile.error="Enter valid 10-digit mobile";return@btn};guarantorAdded=true;status.text="Guarantor added. Separate guarantee will be included."})
  status=tv("Create the document packet to review the actual entered terms before OTP consent.",13f,Color.DKGRAY);status.background=box();status.setPadding(dp(12),dp(8),dp(12),dp(8));add(r,status);add(r,btn("CREATE + PREVIEW DIGITAL DOCUMENTS",amber){prepareDocuments(type.selectedItem.toString())});add(r,btn("CONSENT: LENDER",blue){requestConsent("LENDER","Account owner")});add(r,btn("CONSENT: BORROWER",teal){val p=profiles.getOrNull(borrower.selectedItemPosition);if(p==null)toast("Select borrower first")else requestConsent("BORROWER",p.optString("name"))});add(r,btn("CONSENT: GUARANTOR",red){if(!guarantorAdded)toast("Add guarantor first or leave it blank")else requestConsent("GUARANTOR",gName.text.toString())});add(r,btn("CONFIRM & REGISTER CREDIT",green){register(direction.selectedItem.toString(),type.selectedItem.toString())});add(r,btn("BACK",navy){finish()});showRoot(r)}
 private fun refreshBorrowers(){borrower.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,if(profiles.isEmpty())listOf("No borrower profiles yet — use FIND / CREATE")else profiles.map{"${it.optString("name")} • ${it.optString("mobile")}"})}
 override fun onActivityResult(req:Int,res:Int,data:Intent?){super.onActivityResult(req,res,data);if(req==6101&&res==RESULT_OK){val id=data?.getStringExtra("profileId").orEmpty();val idx=profiles.indexOfFirst{it.optString("id")==id};if(idx>=0)borrower.setSelection(idx);else{profiles=store.all("profiles").filter{it.optString("id")==id};refreshBorrowers();if(profiles.isNotEmpty())borrower.setSelection(0)}}}
 private fun showRoot(r:LinearLayout){setContentView(ScrollView(this).apply{isFillViewport=true;isSmoothScrollingEnabled=true;addView(r)});window.setSoftInputMode(android.view.WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE)}
 private fun showHistory(p:JSONObject){val id=p.optString("id");val cs=store.all("credits").filter{it.optString("borrowerProfileId")==id};val rs=store.all("repayments");var outstanding=0.0;var paid=0.0;cs.forEach{val principal=it.optDouble("amount",0.0);val rr=rs.filter{x->x.optString("creditId")==it.optString("id")};paid+=rr.sumOf{x->x.optDouble("amount",0.0)};outstanding+=it.optDouble("outstanding",it.optDouble("totalPayable",principal))};history.text="CREDIT HISTORY\nCredits: ${cs.size}\nTotal repaid: ₹${String.format(Locale.US,"%,.2f",paid)}\nCurrent outstanding: ₹${String.format(Locale.US,"%,.2f",outstanding)}"}
 private fun calc(a:Double,rate:Double,months:Int,mode:String):Triple<Double,Double,Int>{val interest=a*rate*months/1200.0;return when{mode=="EMI"&&rate>0->{val q=rate/1200.0;val emi=a*q*(1+q).pow(months)/((1+q).pow(months)-1);Triple(emi,emi*months-a,months)};mode=="EMI"->{Triple(a/months,0.0,months)};mode=="Principal + Interest"->{Triple(a+interest,interest,1)};mode.contains("Monthly Interest")->Triple(a*rate/1200.0,interest,months);else->Triple(a+if(mode.contains("Principal + Interest"))interest else 0.0,if(mode.contains("Principal + Interest"))interest else 0.0,1)}}
 private fun prepareDocuments(type:String){val p=profiles.getOrNull(borrower.selectedItemPosition);val a=amount.text.toString().toDoubleOrNull();val rate=roi.text.toString().toDoubleOrNull()?:0.0;if(p==null){toast("Select borrower first");return};if(a==null||a<=0){amount.error="Enter a positive amount";return};if(rate<0){roi.error="ROI cannot be negative";return};if(start.text.isBlank()||end.text.isBlank()){toast("Select start date; end date will be calculated");return};pendingCreditId="CR-${System.currentTimeMillis()}";val months=tenor.selectedItem.toString().split(" ")[0].toInt();val c=calc(a,rate,months,method.selectedItem.toString());val total=a+c.second;val content=V5GuarantorAndDocuments.generateDpnTemplate(pendingCreditId,p.optString("name"),"Account owner",a,rate,method.selectedItem.toString(),c.first,c.third,start.text.toString(),end.text.toString(),c.second,total);store.replace("documents",JSONObject().apply{put("id","DPN-$pendingCreditId");put("type","Demand Promissory Note");put("creditId",pendingCreditId);put("borrowerProfileId",p.optString("id"));put("content",content);put("status","DRAFT");put("createdAt",System.currentTimeMillis())});if(guarantorAdded)store.replace("documents",JSONObject().apply{put("id","GUA-$pendingCreditId");put("type","Guarantor Guarantee");put("creditId",pendingCreditId);put("borrowerProfileId",p.optString("id"));put("content",V5GuarantorAndDocuments.generateGuaranteeTemplate(pendingCreditId,V5GuarantorAndDocuments.GuarantorProfile("G-$pendingCreditId",gName.text.toString(),gMobile.text.toString(),""),p.optString("name"),a));put("status","DRAFT");put("createdAt",System.currentTimeMillis())});docsReady=true;status.text="DOCUMENTS READY — review below before consent";val all=store.all("documents").filter{it.optString("creditId")==pendingCreditId};val msg=all.joinToString("\n\n"){it.optString("content")};AlertDialog.Builder(this).setTitle("DRAFT DOCUMENT PREVIEW — REVIEW").setMessage(msg).setPositiveButton("I HAVE REVIEWED",null).show()}
 private fun requestConsent(party:String,recipient:String){if(!docsReady||pendingCreditId.isBlank()){toast("Create and review the document packet first");return};val id=otp.issue(pendingCreditId,"CREDIT_${party}_CONSENT",recipient);val code=store.find("consents",id)?.optString("otp","")?:"";val input=e("Enter 6-digit OTP");val d=AlertDialog.Builder(this).setTitle("$party CONSENT OTP").setMessage("Borrower/lender consent is required.\nDemo OTP: $code\nLive SMS gateway is required for production delivery.").setView(input).setNegativeButton("CANCEL",null).setPositiveButton("VERIFY",null).create();d.setOnShowListener{d.getButton(-1).setOnClickListener{if(otp.verify(id,input.text.toString())){consents[party]=id;status.text="$party consent VERIFIED";d.dismiss()}else input.error="Incorrect OTP"}};d.show()}
 private fun register(direction:String,type:String){val p=profiles.getOrNull(borrower.selectedItemPosition);val a=amount.text.toString().toDoubleOrNull()?:0.0;if(p==null){toast("Select borrower");return};if(!docsReady||pendingCreditId.isBlank()){toast("Create and review documents first");return};if(!consents.containsKey("LENDER")||!consents.containsKey("BORROWER")){toast("Lender and borrower OTP consent are required");return};if(guarantorAdded&&!consents.containsKey("GUARANTOR")){toast("Guarantor OTP consent is required");return};val months=tenor.selectedItem.toString().split(" ")[0].toInt();val rate=roi.text.toString().toDoubleOrNull()?:0.0;val c=calc(a,rate,months,method.selectedItem.toString());val total=a+c.second;val cid=pendingCreditId;store.replace("credits",JSONObject().apply{put("id",cid);put("borrowerProfileId",p.optString("id"));put("borrower",p.optString("name"));put("direction",direction);put("creditType",type);put("amount",a);put("roi",rate);put("interest",c.second);put("tenorMonths",months);put("repaymentMethod",method.selectedItem.toString());put("installmentAmount",c.first);put("installments",c.third);put("totalPayable",total);put("start",start.text.toString());put("end",end.text.toString());put("status","ACTIVE");put("outstanding",total);put("lenderConsent",consents["LENDER"]);put("borrowerConsent",consents["BORROWER"]);put("guarantor",if(guarantorAdded)gName.text.toString() else "");put("guarantorMobile",if(guarantorAdded)gMobile.text.toString() else "");put("guarantorConsent",consents["GUARANTOR"]?:"");put("registeredAt",System.currentTimeMillis())});store.all("documents").filter{it.optString("creditId")==cid}.forEach{it.put("status","EXECUTED");it.put("executedAt",System.currentTimeMillis());it.put("executedVersion",1);it.put("executionAudit","OTP_VERIFIED");it.put("documentHash",V5ConsentAndScore.sha256(it.optString("content").toByteArray(Charsets.UTF_8)));store.replace("documents",it)};store.add("audit",JSONObject().apply{put("id","AUD-${System.currentTimeMillis()}");put("entityId",cid);put("event","CREDIT_REGISTERED_AFTER_ALL_REQUIRED_OTP_CONSENTS");put("at",System.currentTimeMillis())});toast("Credit registered successfully after document review and required OTP consent");startActivity(Intent(this,V5HomeActivity::class.java).addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP));finish()}
 private fun pickDate(t:EditText){val c=Calendar.getInstance();DatePickerDialog(this,{_,y,m,d->t.setText(String.format(Locale.US,"%02d %s %04d",d,SimpleDateFormat("MMM",Locale.US).format(Calendar.getInstance().apply{set(Calendar.MONTH,m)}.time),y));updateEnd()},c.get(Calendar.YEAR),c.get(Calendar.MONTH),c.get(Calendar.DAY_OF_MONTH)).show()};private fun updateEnd(){if(!::start.isInitialized||start.text.isBlank())return;try{val c=Calendar.getInstance();c.time=SimpleDateFormat("dd MMM yyyy",Locale.US).parse(start.text.toString())!!;c.add(Calendar.MONTH,tenor.selectedItem.toString().split(" ")[0].toInt());end.setText(SimpleDateFormat("dd MMM yyyy",Locale.US).format(c.time))}catch(_:Exception){}};private fun toast(s:String)=Toast.makeText(this,s,Toast.LENGTH_LONG).show()
}
