package com.udhaardaar.mvp

import android.app.AlertDialog
import android.content.Intent
import android.net.Uri
import android.os.Bundle
import android.view.WindowManager
import android.widget.*
import org.json.JSONObject
import java.text.SimpleDateFormat
import java.util.*

class V5DeathClaimLegalActivity : androidx.appcompat.app.AppCompatActivity() {
    private val store by lazy { V5LocalStore(this) }
    private val repo by lazy { V5WorkflowRepository(this) }
    private lateinit var deceased: EditText; private lateinit var claimant: EditText; private lateinit var relationship: EditText; private lateinit var institution: EditText; private lateinit var notes: EditText
    private var deathCert: Uri?=null; private var identity: Uri?=null; private var nomination: Uri?=null; private var willDoc: Uri?=null
    private fun e(h:String)=EditText(this).apply{hint=h;setSingleLine(true)}
    private fun add(r:LinearLayout,v:android.view.View,h:Int=55){r.addView(v,LinearLayout.LayoutParams(-1,h).apply{setMargins(0,5,0,5)})}
    override fun onCreate(b:Bundle?){super.onCreate(b);window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);show()}
    private fun show(){val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(20,16,20,28)};add(r,TextView(this).apply{text="UDHAARDAAR V5 • Death Claim Legal Assistance";textSize=22f},68);add(r,TextView(this).apply{text="One case file for financial assets, non-financial assets and liabilities after death. Organise evidence, claims, follow-ups and printable legal-support bundles.";textSize=13f},78);deceased=e("Deceased profile ID / name *");claimant=e("Claimant / legal heir profile ID *");relationship=e("Relationship / capacity");institution=e("Bank / insurer / authority / counterparty");notes=e("Case notes / disputed items / instructions");listOf(deceased,claimant,relationship,institution,notes).forEach{add(r,it)};add(r,Button(this).apply{text="CAPTURE DEATH CERTIFICATE";setOnClickListener{pick(10)}});add(r,Button(this).apply{text="CAPTURE CLAIMANT ID / KYC";setOnClickListener{pick(11)}});add(r,Button(this).apply{text="CAPTURE NOMINATION / BENEFICIARY PROOF";setOnClickListener{pick(12)}});add(r,Button(this).apply{text="CAPTURE WILL / SUCCESSION DOCUMENT";setOnClickListener{pick(13)}});add(r,Button(this).apply{text="SCAN VAULT & CREATE CLAIM CHECKLIST";setOnClickListener{createCase()}},62);add(r,Button(this).apply{text="VIEW CASE / PRINT BUNDLE";setOnClickListener{viewLast()}},58);add(r,Button(this).apply{text="BACK";setOnClickListener{finish()}},50);setContentView(ScrollView(this).apply{isFillViewport=true;addView(r)})}
    private fun pick(c:Int){startActivityForResult(Intent(Intent.ACTION_OPEN_DOCUMENT).apply{type="application/pdf";putExtra(Intent.EXTRA_MIME_TYPES,arrayOf("application/pdf","image/jpeg","image/png"));addCategory(Intent.CATEGORY_OPENABLE)},c)}
    @Deprecated("Android callback retained for API 23") override fun onActivityResult(c:Int,r:Int,d:Intent?){super.onActivityResult(c,r,d);if(r==RESULT_OK){when(c){10->deathCert=d?.data;11->identity=d?.data;12->nomination=d?.data;13->willDoc=d?.data};Toast.makeText(this,"Document captured",Toast.LENGTH_SHORT).show()}}
    private fun createCase(){val d=deceased.text.toString().trim();val c=claimant.text.toString().trim();if(d.isEmpty()||c.isEmpty()){Toast.makeText(this,"Deceased and claimant are required",Toast.LENGTH_LONG).show();return};val id="DCL-${System.currentTimeMillis()}";val vault=store.all("assets");val relevant=vault.joinToString("\n"){x->"• ${x.optString("title")} — ${x.optString("category")} — ${x.optString("assetSubtype")} — ref ${x.optString("accountOrReference")}"};val checklist=listOf("Death certificate","Claimant KYC / identity","Nomination / beneficiary proof","Will / succession document if applicable","Bank / investment statements","Insurance policy / certificate","Property title / registration papers","Vehicle ownership / RC","Loan/liability statements and closure/NOC","Heirship / succession certificate where applicable","Authority-specific claim forms","Tax / dues clearance where applicable");val j=JSONObject().apply{put("id",id);put("type","DEATH_CLAIM_LEGAL_CASE");put("deceased",d);put("claimant",c);put("relationship",relationship.text.toString());put("institution",institution.text.toString());put("deathCertificate",deathCert?.toString()?:"");put("claimantIdentity",identity?.toString()?:"");put("nominationProof",nomination?.toString()?:"");put("willDocument",willDoc?.toString()?:"");put("checklist",checklist.joinToString(" | "));put("vaultSnapshot",relevant);put("notes",notes.text.toString());put("status","OPEN");put("createdAt",System.currentTimeMillis());put("updatedAt",System.currentTimeMillis())};store.replace("death_claim_cases",j);repo.appendAudit(id,"DEATH_CLAIM_CASE_CREATED",c,"vault assets/liabilities scanned; timestamp=${System.currentTimeMillis()}");report(id,j,checklist,relevant)}
    private fun report(id:String,j:JSONObject,check:List<String>,vault:String){val msg="DEATH CLAIM CASE\n\nCase: $id\nDeceased: ${j.optString("deceased")}\nClaimant: ${j.optString("claimant")}\nRelationship: ${j.optString("relationship")}\nInstitution: ${j.optString("institution")}\n\nVAULT ITEMS FOUND\n${if(vault.isBlank())"No vault records found." else vault}\n\nCLAIM CHECKLIST\n${check.joinToString("\n• ",prefix="• ")}\n\nStatus: OPEN\nGenerated: ${SimpleDateFormat("yyyy-MM-dd HH:mm",Locale.US).format(Date())}\n\nThis is an organisational/legal-support record, not legal advice.";AlertDialog.Builder(this).setTitle("Death claim case created").setMessage(msg).setPositiveButton("PRINT",null).setNegativeButton("CLOSE",null).create().apply{setOnShowListener{getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener{printText(msg)}}}.show()}
    private fun viewLast(){val xs=store.all("death_claim_cases");if(xs.isEmpty()){Toast.makeText(this,"No death claim case yet",Toast.LENGTH_SHORT).show();return};val j=xs.last();report(j.optString("id"),j,j.optString("checklist").split(" | "),j.optString("vaultSnapshot"))}
    private fun printText(text:String){(getSystemService(PRINT_SERVICE) as android.print.PrintManager).print("Udhaardaar death claim case",DeathClaimPrintAdapter(text),null)}
}
private class DeathClaimPrintAdapter(private val text:String):android.print.PrintDocumentAdapter(){override fun onLayout(o:android.print.PrintAttributes?,n:android.print.PrintAttributes?,c:android.os.CancellationSignal?,cb:android.print.PrintDocumentAdapter.LayoutResultCallback?,e:Bundle?){cb?.onLayoutFinished(android.print.PrintDocumentInfo.Builder("death-claim-case.txt").setContentType(android.print.PrintDocumentInfo.CONTENT_TYPE_DOCUMENT).build(),true)};override fun onWrite(p:Array<android.print.PageRange>?,d:android.os.ParcelFileDescriptor?,c:android.os.CancellationSignal?,cb:android.print.PrintDocumentAdapter.WriteResultCallback?){try{android.os.ParcelFileDescriptor.AutoCloseOutputStream(d!!).use{it.write(text.toByteArray(Charsets.UTF_8))};cb?.onWriteFinished(arrayOf(android.print.PageRange.ALL_PAGES))}catch(x:Exception){cb?.onWriteFailed(x.message)}}}
