package com.udhaardaar.mvp

import android.app.AlertDialog
import android.content.Intent
import android.net.Uri
import android.os.Bundle
import android.view.WindowManager
import android.widget.*
import org.json.JSONArray
import org.json.JSONObject
import java.text.SimpleDateFormat
import java.util.*

class V5DeathClaimLegalActivity : androidx.appcompat.app.AppCompatActivity() {
 private val store by lazy{V5LocalStore(this)};private val repo by lazy{V5WorkflowRepository(this)}
 private lateinit var deceased:EditText;private lateinit var claimant:EditText;private lateinit var relationship:EditText;private lateinit var institution:EditText;private lateinit var heirs:EditText;private lateinit var notes:EditText
 private var deathCert:Uri?=null;private var identity:Uri?=null;private var nomination:Uri?=null;private var willDoc:Uri?=null
 private fun e(h:String,multi:Boolean=false)=EditText(this).apply{hint=h;setSingleLine(!multi);if(multi){minLines=3;gravity=android.view.Gravity.TOP}};private fun add(r:LinearLayout,v:android.view.View,h:Int=55){r.addView(v,LinearLayout.LayoutParams(-1,h).apply{setMargins(0,5,0,5)})}
 override fun onCreate(b:Bundle?){super.onCreate(b);window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);show()}
 private fun show(){val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(20,16,20,28)};add(r,TextView(this).apply{text="UDHAARDAAR V5 • Inheritance & Claim Centre";textSize=22f},68);add(r,TextView(this).apply{text="Case → heirs/nominees → evidence → claim processing → settlement/closure";textSize=13f},58);deceased=e("Deceased profile ID / name *");claimant=e("Primary claimant / legal heir profile ID *");relationship=e("Relationship / capacity");institution=e("Bank / insurer / authority / counterparty");heirs=e("Heir / nominee relationships — one per line: profileId|relationship|share",true);notes=e("Case notes / disputed items / instructions",true);listOf(deceased,claimant,relationship,institution,heirs,notes).forEach{add(r,it)};add(r,Button(this).apply{text="CAPTURE DEATH CERTIFICATE";setOnClickListener{pick(10)}});add(r,Button(this).apply{text="CAPTURE CLAIMANT KYC";setOnClickListener{pick(11)}});add(r,Button(this).apply{text="CAPTURE NOMINATION / BENEFICIARY PROOF";setOnClickListener{pick(12)}});add(r,Button(this).apply{text="CAPTURE WILL / SUCCESSION DOCUMENT";setOnClickListener{pick(13)}});add(r,Button(this).apply{text="CREATE / UPDATE CLAIM CASE";setOnClickListener{createCase()}},62);add(r,Button(this).apply{text="ADVANCE LAST CASE STATUS";setOnClickListener{advanceLast()}},58);add(r,Button(this).apply{text="VIEW / PRINT LAST BUNDLE";setOnClickListener{viewLast()}},58);add(r,Button(this).apply{text="BACK";setOnClickListener{finish()}},50);setContentView(ScrollView(this).apply{isFillViewport=true;addView(r)})}
 private fun pick(c:Int){startActivityForResult(Intent(Intent.ACTION_OPEN_DOCUMENT).apply{type="application/pdf";putExtra(Intent.EXTRA_MIME_TYPES,arrayOf("application/pdf","image/jpeg","image/png"));addCategory(Intent.CATEGORY_OPENABLE)},c)}
 @Deprecated("API 23") override fun onActivityResult(c:Int,r:Int,d:Intent?){super.onActivityResult(c,r,d);if(r==RESULT_OK){when(c){10->deathCert=d?.data;11->identity=d?.data;12->nomination=d?.data;13->willDoc=d?.data};Toast.makeText(this,"Evidence captured",Toast.LENGTH_SHORT).show()}}
 private fun heirArray():JSONArray{val a=JSONArray();heirs.text.toString().lines().forEach{val x=it.split("|",limit=3);if(x.size>=2&&x[0].trim().isNotBlank())a.put(JSONObject().apply{put("profileId",x[0].trim());put("relationship",x[1].trim());put("share",if(x.size==3)x[2].trim() else "")})};return a}
 private fun createCase(){val d=deceased.text.toString().trim();val c=claimant.text.toString().trim();if(d.isEmpty()||c.isEmpty()){Toast.makeText(this,"Deceased and claimant are required",Toast.LENGTH_LONG).show();return};val id="DCL-${System.currentTimeMillis()}";val checklist=listOf("Death certificate","Claimant KYC","Nomination/beneficiary proof","Will/succession document","Financial statements/policies","Property/vehicle title","Liability/loan statements","Heirship/succession certificate where applicable","Authority claim forms","Tax/dues clearance");val vault=store.all("assets").joinToString("\n"){x->"• ${x.optString("title")} — ${x.optString("category")} — ${x.optString("assetSubtype")}"};val j=JSONObject().apply{put("id",id);put("type","DEATH_CLAIM_LEGAL_CASE");put("deceased",d);put("claimant",c);put("relationship",relationship.text.toString());put("institution",institution.text.toString());put("heirs",heirArray());put("deathCertificate",deathCert?.toString()?:(""));put("claimantIdentity",identity?.toString()?:(""));put("nominationProof",nomination?.toString()?:(""));put("willDocument",willDoc?.toString()?:(""));put("checklist",checklist.joinToString(" | "));put("vaultSnapshot",vault);put("notes",notes.text.toString());put("status","OPEN");put("createdAt",System.currentTimeMillis());put("updatedAt",System.currentTimeMillis())};store.replace("death_claim_cases",j);repo.appendAudit(id,"DEATH_CLAIM_CASE_CREATED",c,"heirs, nominees, evidence and vault linked");report(id,j,checklist,vault)}
 private fun advanceLast(){val xs=store.all("death_claim_cases");if(xs.isEmpty()){Toast.makeText(this,"No case",Toast.LENGTH_SHORT).show();return};val j=xs.last();val next=when(j.optString("status")){"OPEN"->"EVIDENCE_REVIEW";"EVIDENCE_REVIEW"->"CLAIM_SUBMITTED";"CLAIM_SUBMITTED"->"UNDER_PROCESSING";"UNDER_PROCESSING"->"SETTLEMENT_PENDING";"SETTLEMENT_PENDING"->"CLOSED";else->"CLOSED"};j.put("status",next);j.put("updatedAt",System.currentTimeMillis());store.replace("death_claim_cases",j);repo.appendAudit(j.optString("id"),"DEATH_CLAIM_STATUS_CHANGED",j.optString("claimant"),"status=$next");Toast.makeText(this,"Case status: $next",Toast.LENGTH_LONG).show()}
 private fun report(id:String,j:JSONObject,check:List<String>,vault:String){val heirsText=j.optJSONArray("heirs")?.let{a->(0 until a.length()).joinToString("\n"){k->val h=a.optJSONObject(k);"• ${h?.optString("profileId")} — ${h?.optString("relationship")} — ${h?.optString("share")}"}}?:"None recorded";val msg="INHERITANCE / CLAIM CASE\n\nCase: $id\nStatus: ${j.optString("status")}\nDeceased: ${j.optString("deceased")}\nPrimary claimant: ${j.optString("claimant")}\nRelationship: ${j.optString("relationship")}\nInstitution: ${j.optString("institution")}\n\nHEIRS / NOMINEES\n$heirsText\n\nVAULT\n${if(vault.isBlank())"No vault records." else vault}\n\nCHECKLIST\n${check.joinToString("\n• ",prefix="• ")}\n\nGenerated: ${SimpleDateFormat("yyyy-MM-dd HH:mm",Locale.US).format(Date())}\nThis is organisational/legal-support functionality, not legal advice.";AlertDialog.Builder(this).setTitle("Claim case").setMessage(msg).setPositiveButton("PRINT",null).setNegativeButton("CLOSE",null).create().apply{setOnShowListener{getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener{printText(msg)}}}.show()}
 private fun viewLast(){val x=store.all("death_claim_cases");if(x.isEmpty()){Toast.makeText(this,"No case",Toast.LENGTH_SHORT).show();return};val j=x.last();report(j.optString("id"),j,j.optString("checklist").split(" | "),j.optString("vaultSnapshot"))}
 private fun printText(t:String){(getSystemService(PRINT_SERVICE) as android.print.PrintManager).print("Udhaardaar inheritance claim",DeathClaimPrintAdapter(t),null)}
}
private class DeathClaimPrintAdapter(private val text:String):android.print.PrintDocumentAdapter(){override fun onLayout(o:android.print.PrintAttributes?,n:android.print.PrintAttributes?,c:android.os.CancellationSignal?,cb:android.print.PrintDocumentAdapter.LayoutResultCallback?,e:Bundle?){cb?.onLayoutFinished(android.print.PrintDocumentInfo.Builder("inheritance-claim.txt").setContentType(android.print.PrintDocumentInfo.CONTENT_TYPE_DOCUMENT).build(),true)};override fun onWrite(p:Array<android.print.PageRange>?,d:android.os.ParcelFileDescriptor?,c:android.os.CancellationSignal?,cb:android.print.PrintDocumentAdapter.WriteResultCallback?){try{android.os.ParcelFileDescriptor.AutoCloseOutputStream(d!!).use{it.write(text.toByteArray(Charsets.UTF_8))};cb?.onWriteFinished(arrayOf(android.print.PageRange.ALL_PAGES))}catch(x:Exception){cb?.onWriteFailed(x.message)}}}
