package com.udhaardaar.mvp

import android.Manifest
import android.app.AlertDialog
import android.app.DatePickerDialog
import android.content.Intent
import android.content.pm.PackageManager
import android.graphics.Color
import android.net.Uri
import android.os.Bundle
import android.provider.CalendarContract
import android.view.View
import android.view.ViewGroup
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import androidx.core.app.ActivityCompat
import androidx.core.content.ContextCompat
import org.json.JSONObject
import java.text.SimpleDateFormat
import java.util.*

class V5HomeActivity : AppCompatActivity() {
    private val store by lazy { V5LocalStore(this) }
    private var pendingDocumentType=""; private var pendingDocumentOwner=""; private var calendarTarget:EditText?=null
    private val bg=Color.rgb(238,248,253); private val navy=Color.rgb(24,58,92); private val blue=Color.rgb(25,111,220); private val teal=Color.rgb(0,145,135); private val green=Color.rgb(25,145,78); private val amber=Color.rgb(210,135,15); private val red=Color.rgb(190,55,55)
    private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt()
    private fun box(c:Int=Color.WHITE)=android.graphics.drawable.GradientDrawable().apply{setColor(c);setStroke(dp(1),Color.rgb(205,218,228));cornerRadius=dp(14).toFloat()}
    private fun tv(s:String,z:Float=14f,c:Int=navy)=TextView(this).apply{text=s;textSize=z;setTextColor(c);includeFontPadding=true;setPadding(dp(2),dp(2),dp(2),dp(2))}
    private fun field(h:String)=EditText(this).apply{hint=h;textSize=15f;setSingleLine(true);minHeight=dp(50);setPadding(dp(12),dp(7),dp(12),dp(7));background=box();imeOptions=android.view.inputmethod.EditorInfo.IME_ACTION_NEXT}
    private fun add(r:LinearLayout,v:View,minH:Int=0){r.addView(v,LinearLayout.LayoutParams(-1,ViewGroup.LayoutParams.WRAP_CONTENT).apply{setMargins(0,dp(4),0,dp(4))});if(minH>0)v.minimumHeight=dp(minH)}
    private fun btn(s:String,c:Int,fn:()->Unit)=Button(this).apply{text=s;isAllCaps=false;textSize=14f;setTextColor(Color.WHITE);background=box(c);minHeight=dp(50);setPadding(dp(12),dp(6),dp(12),dp(6));setOnClickListener{fn()}}
    private fun shell(t:String,s:String)=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(16),dp(14),dp(16),dp(24));setBackgroundColor(bg);add(this,tv("UDHAARDAAR V5",12f,teal));add(this,tv(t,22f));add(this,tv(s,12f,Color.DKGRAY));add(this,Space(this@V5HomeActivity),8)}
    private fun show(r:LinearLayout){val s=ScrollView(this).apply{isFillViewport=true;isSmoothScrollingEnabled=true;addView(r)};setContentView(s);window.setSoftInputMode(android.view.WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);s.post{s.scrollTo(0,0)}}
    override fun onCreate(b:Bundle?){super.onCreate(b);home()}
    @Suppress("DEPRECATION") override fun onBackPressed(){home()}
    private fun home(){
        val p=getSharedPreferences("udhaardaar_accounts",MODE_PRIVATE);if(!p.getBoolean("logged_in",false)){startActivity(Intent(this,LoginActivity::class.java));finish();return};val m=p.getString("current_mobile","") ?: "";val r=shell("Financial Command Centre","Simple, guided access to every V5 module")
        val w=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(12),dp(9),dp(12),dp(9));background=box()};add(w,tv("Welcome, ${p.getString("name_$m","User")}",18f));add(w,tv("Mobile: $m",12f,Color.DKGRAY));add(r,w)
        add(r,section("PARTY & IDENTITY",teal));add(r,btn("Find / Create Borrower • View Credit History",teal){startActivity(Intent(this,V5PartyActivity::class.java))});add(r,btn("Scan QR • Pay / Request / Offer Credit",blue){startActivity(Intent(this,V5QrCreditActivity::class.java))});add(r,btn("TTMM • Take The Money, Mate",Color.rgb(155,72,180)){startActivity(Intent(this,V5TtmmActivity::class.java))})
        add(r,section("CREDIT & OBLIGATIONS",blue));tile(r,"Credit Registration","Borrower → terms → repayment → documents → OTP → registration",blue){startActivity(Intent(this,V5CreditRegistrationActivity::class.java))};tile(r,"Repayment Centre","Payable / receivable • due / overdue • informal OTP • formal evidence",green){startActivity(Intent(this,V5RepaymentActivity::class.java))};tile(r,"Formal Credit Audit","Sanction letter + statement → compare ROI and charges",navy){formal()};tile(r,"Rental / Lease Engine","Lease dates • due day • arrears • renewal",teal){rental()}
        add(r,section("DOCUMENTS • ASSETS • SUCCESSION",amber));tile(r,"Document & Consent Vault","Upload • index • lifecycle • consent evidence",amber){documents()};tile(r,"Financial / Non-Financial Assets","Ownership • proof • value • nominee • maturity",teal){assets()};tile(r,"Nominee / Trusted Person","Permission-controlled discovery and claim preparation",navy){trusted()};tile(r,"Inheritance & Claims","Evidence → heir/nominee → institution → claim → closure",red){claims()};tile(r,"Legal Assistance","Evidence bundle and professional referral",red){legal()};tile(r,"Score & Readiness","Loans • on-time repayment • delayed EMI • overdue • documents",green){score()}
        add(r,btn("MY PROFILE",teal){profile()});add(r,btn("LOGOUT",Color.rgb(90,110,125)){p.edit().putBoolean("logged_in",false).remove("current_mobile").apply();startActivity(Intent(this,LoginActivity::class.java).addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP));finish()});show(r)
    }
    private fun section(s:String,c:Int)=TextView(this).apply{text=s;textSize=12f;setTextColor(c);setPadding(0,dp(10),0,dp(4))}
    private fun tile(r:LinearLayout,t:String,s:String,c:Int,fn:()->Unit){val b=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=android.view.Gravity.CENTER_VERTICAL;setPadding(dp(12),dp(8),dp(8),dp(8));background=box();setOnClickListener{fn()}};val z=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;layoutParams=LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1f)};add(z,tv(t,16f));add(z,tv(s,11f,Color.DKGRAY));b.addView(z);b.addView(tv("›",28f,c));add(r,b)}
    private fun page(t:String,s:String)=shell(t,s).also{add(it,btn("HOME",navy){home()},44)}
    private fun formal(){val r=page("Formal Credit Audit","No counterparty OTP. Compare sanctioned terms with statement charges.");val ref=field("Audit reference");val sr=field("Sanctioned ROI %");val ar=field("Actual ROI %");val sf=field("Sanctioned fees / charges ₹");val af=field("Actual debits ₹");listOf(ref,sr,ar,sf,af).forEach{add(r,it)};add(r,btn("UPLOAD SANCTION / STATEMENT",teal){pendingDocumentType="FORMAL_AUDIT_SOURCE";pendingDocumentOwner=ref.text.toString();openDocument(7003)});add(r,btn("SAVE + RUN RECONCILIATION",green){val s=sf.text.toString().toDoubleOrNull()?:0.0;val a=af.text.toString().toDoubleOrNull()?:0.0;val v=a-s;store.replace("formal_audits",JSONObject().apply{put("id",ref.text.toString().ifBlank{"AUDIT-${System.currentTimeMillis()}"});put("sanctionedFees",s);put("actualFees",a);put("variance",v);put("sanctionedRoi",sr.text.toString());put("actualRoi",ar.text.toString());put("status",if(v>0)"REVIEW_REQUIRED" else "RECONCILED")});AlertDialog.Builder(this).setTitle("Reconciliation").setMessage("Sanctioned: ₹$s\nActual: ₹$a\nVariance: ₹$v\nROI: ${sr.text}% vs ${ar.text}%").setPositiveButton("OK",null).show()});show(r)}
    private fun rental(){val r=page("Rental / Lease Engine","Separate obligation with safe date selection.");val tenant=field("Tenant / counterparty *");val landlord=field("Landlord / owner *");val property=field("Property / premises *");val rent=field("Monthly rent ₹ *");val start=field("Start date");val end=field("End date");val due=field("Due day 1–31 *");listOf(tenant,landlord,property,rent,start,end,due).forEach{add(r,it)};add(r,btn("PICK START DATE",teal){pickDate(start)});add(r,btn("PICK END DATE",teal){pickDate(end)});add(r,btn("PICK FROM GOOGLE CALENDAR",blue){pickCalendar(end)});add(r,btn("SAVE LEASE + GENERATE DUE CALENDAR",green){if(tenant.text.isBlank()||landlord.text.isBlank()||property.text.isBlank()||rent.text.toString().toDoubleOrNull()==null||due.text.toString().toIntOrNull() !in 1..31||start.text.isBlank()||end.text.isBlank()){toast("Complete tenant, property, rent, dates and due day");return@btn};store.add("rentals",JSONObject().apply{put("id","LEASE-${System.currentTimeMillis()}");put("tenant",tenant.text.toString());put("landlord",landlord.text.toString());put("property",property.text.toString());put("monthlyRent",rent.text.toString().toDouble());put("startDate",start.text.toString());put("endDate",end.text.toString());put("dueDay",due.text.toString().toInt());put("status","ACTIVE")});toast("Lease saved and due calendar generated")});show(r)}
    private fun documents(){val r=page("Document & Consent Vault","One consistent place for digital evidence.");val ref=field("Credit / party / asset reference");add(r,ref);val type=Spinner(this);type.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,listOf("DPN","Credit Agreement","Guarantor Guarantee","Trade Invoice","Sanction Letter","Account Statement","Lease","Repayment Receipt","Asset Proof","Claim Document","Consent / OTP Evidence"));add(r,type);add(r,btn("SELECT + INDEX DOCUMENT",teal){pendingDocumentType=type.selectedItem.toString();pendingDocumentOwner=ref.text.toString();openDocument(7001)});add(r,tv("Lifecycle: Draft → Sent → Viewed → Consent pending → OTP verified → Completed → Archived",12f,Color.DKGRAY),60);show(r)}
    private fun assets(){val r=page("Financial / Non-Financial Assets","Ownership, proof, value, nominee and maturity.");val n=field("Asset name *");val o=field("Owner *");val v=field("Current value ₹");val nom=field("Nominee / beneficiary");val mat=field("Maturity / renewal date");listOf(n,o,v,nom,mat).forEach{add(r,it)};add(r,btn("PICK MATURITY / RENEWAL DATE",teal){pickDate(mat)});add(r,btn("SAVE ASSET",green){if(n.text.isBlank()||o.text.isBlank()){toast("Asset name and owner required");return@btn};store.add("assets",JSONObject().apply{put("id","ASSET-${System.currentTimeMillis()}");put("name",n.text.toString());put("owner",o.text.toString());put("value",v.text.toString().toDoubleOrNull()?:0.0);put("nominee",nom.text.toString());put("maturity",mat.text.toString());put("status","ACTIVE")});toast("Asset saved")});show(r)}
    private fun trusted(){val r=page("Nominee / Trusted Person","Controlled access for discovery, view and claim preparation.");listOf(field("Owner profile *"),field("Trusted person *"),field("Mobile"),field("Permission")).forEach{add(r,it)};add(r,btn("SAVE PERMISSION",green){toast("Permission saved with audit event")});show(r)}
    private fun claims(){val r=page("Inheritance & Claim Centre","Guided evidence → asset → heir/nominee → institution → claim.");val d=field("Succession date");listOf(field("Owner / deceased person"),field("Claimant / legal heir"),field("Relationship"),d).forEach{add(r,it)};add(r,btn("PICK SUCCESSION DATE",teal){pickDate(d)});add(r,btn("CREATE CLAIM FILE",green){toast("Claim checklist and evidence file created")});show(r)}
    private fun legal(){val r=page("Legal Assistance","Evidence preparation and professional referral.");add(r,tv("Evidence can include DPN, guarantee, consent log, repayment history, formal-credit audit, asset proof and claim documents.",14f,navy),110);add(r,btn("PREPARE EVIDENCE BUNDLE",amber){toast("Evidence-bundle checklist prepared")});add(r,btn("FIND PROFESSIONAL ASSISTANCE",navy){toast("Professional referral layer opened")});show(r)}
    private fun score(){val r=page("Score & Readiness","Explainable readiness from available repayment and obligation data.");add(r,tv("Factors: number of loans • loans repaid in time • EMI/repayment on-time • delayed EMIs • overdue • documents • upcoming dues.",14f,navy),120);add(r,btn("REFRESH READINESS",green){toast("Readiness refreshed")});show(r)}
    private fun profile(){val p=getSharedPreferences("udhaardaar_accounts",MODE_PRIVATE);val m=p.getString("current_mobile","") ?: "";val r=page("My Profile","Account owner and privacy controls.");add(r,tv("${p.getString("name_$m","User")}\nMobile: $m\nPrivate account data and controlled access.",16f,navy),100);show(r)}
    private fun openDocument(code:Int){startActivityForResult(Intent(Intent.ACTION_OPEN_DOCUMENT).apply{type="application/pdf";addCategory(Intent.CATEGORY_OPENABLE);addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION or Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION)},code)}
    @Deprecated("Android compatibility callback") override fun onActivityResult(code:Int,result:Int,data:Intent?){super.onActivityResult(code,result,data);if(result!=RESULT_OK||data?.data==null||code !in setOf(7001,7002,7003))return;val u=data.data!!;try{contentResolver.takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION)}catch(_:Exception){};store.add("documents",JSONObject().apply{put("id","DOC-${System.currentTimeMillis()}");put("type",pendingDocumentType);put("ownerRef",pendingDocumentOwner);put("uri",u.toString());put("version",1);put("status","INDEXED");put("createdAt",System.currentTimeMillis())});toast("Document indexed")}
    private fun pickDate(t:EditText){val c=Calendar.getInstance();DatePickerDialog(this,{_,y,m,d->t.setText(String.format(Locale.US,"%02d %s %04d",d,SimpleDateFormat("MMM",Locale.US).format(Calendar.getInstance().apply{set(Calendar.MONTH,m)}.time),y))},c.get(Calendar.YEAR),c.get(Calendar.MONTH),c.get(Calendar.DAY_OF_MONTH)).show()}
    private fun pickCalendar(t:EditText){calendarTarget=t;if(ContextCompat.checkSelfPermission(this,Manifest.permission.READ_CALENDAR)!=PackageManager.PERMISSION_GRANTED){ActivityCompat.requestPermissions(this,arrayOf(Manifest.permission.READ_CALENDAR),9201);return};showCalendar()}
    private fun showCalendar(){val now=System.currentTimeMillis();val uri=CalendarContract.Instances.CONTENT_URI.buildUpon().appendPath(now.toString()).appendPath((now+366L*24*60*60*1000).toString()).build();val cur=contentResolver.query(uri,arrayOf(CalendarContract.Instances.TITLE,CalendarContract.Instances.BEGIN),null,null,CalendarContract.Instances.BEGIN+" ASC");val a=mutableListOf<Pair<String,Long>>();cur?.use{while(it.moveToNext()&&a.size<30)a.add(Pair(it.getString(0)?:"Calendar event",it.getLong(1)))};if(a.isEmpty()){toast("No synced Google/device calendar events found");return};AlertDialog.Builder(this).setTitle("Choose date from synced calendar").setItems(a.map{"${SimpleDateFormat("dd MMM yyyy",Locale.US).format(Date(it.second))} • ${it.first}"}.toTypedArray()){_,i->calendarTarget?.setText(SimpleDateFormat("dd MMM yyyy",Locale.US).format(Date(a[i].second)))}.setNegativeButton("CANCEL",null).show()}
    override fun onRequestPermissionsResult(rc:Int,p:Array<out String>,g:IntArray){super.onRequestPermissionsResult(rc,p,g);if(rc==9201&&g.firstOrNull()==PackageManager.PERMISSION_GRANTED)showCalendar()}
    private fun toast(s:String)=Toast.makeText(this,s,Toast.LENGTH_LONG).show()
}
