package com.udhaardaar.mvp

import android.app.AlertDialog
import android.app.DatePickerDialog
import android.content.Intent
import android.os.Bundle
import android.text.InputType
import android.view.View
import android.view.WindowManager
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import com.journeyapps.barcodescanner.ScanContract
import com.journeyapps.barcodescanner.ScanOptions
import org.json.JSONObject
import java.text.SimpleDateFormat
import java.util.*
import kotlin.math.pow

class V5InformalCreditActivity:AppCompatActivity(){
 private val repo by lazy{V5WorkflowRepository(this)};private val consent by lazy{V5OtpConsentService(this)}
 private val scanner=registerForActivityResult(ScanContract()){r->if(!r.contents.isNullOrBlank()){qrRaw=r.contents;applyQr(r.contents)}}
 private var qrRaw="";private var documentConsentId="";private var selectedProfileId="";private var draftCreditId=""
 private lateinit var name:EditText;private lateinit var vendor:EditText;private lateinit var invoice:EditText;private lateinit var date:EditText;private lateinit var principal:EditText;private lateinit var roi:EditText;private lateinit var start:EditText;private lateinit var end:EditText;private lateinit var tenor:EditText;private lateinit var type:Spinner;private lateinit var direction:Spinner;private lateinit var method:Spinner;private lateinit var scroll:ScrollView
 private fun e(h:String)=EditText(this).apply{hint=h;setSingleLine(true);setPadding(16,10,16,10);imeOptions=android.view.inputmethod.EditorInfo.IME_ACTION_NEXT}
 private fun put(r:LinearLayout,v:View,h:Int=58){r.addView(v,LinearLayout.LayoutParams(-1,h).apply{setMargins(0,5,0,5)})}
 override fun onCreate(b:Bundle?){super.onCreate(b);window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);show()}
 override fun onActivityResult(requestCode:Int,resultCode:Int,data:Intent?){super.onActivityResult(requestCode,resultCode,data)}
 override fun onResume(){super.onResume()}
 private fun show(){val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(24,18,24,28)};scroll=ScrollView(this).apply{isFillViewport=true;isSmoothScrollingEnabled=true;addView(r)};r.addView(TextView(this).apply{text="Udhaardaar V5 • Informal Credit";textSize=23f});r.addView(TextView(this).apply{text="1 Identify party → 2 scan/import → 3 terms → 4 document consent → 5 counterparty OTP → 6 register";textSize=13f})
  put(r,Button(this).apply{text="SCAN QR — AUTO-FILL CREDIT";setOnClickListener{scanner.launch(ScanOptions().apply{setDesiredBarcodeFormats(ScanOptions.QR_CODE);setPrompt("Scan credit / invoice QR code");setBeepEnabled(true);setOrientationLocked(false)})}})
  name=e("Borrower / party name or profile ID *");vendor=e("Vendor / seller (from QR when available)");invoice=e("Invoice / bill number (from QR when available)");date=e("Invoice / transaction date");type=Spinner(this).apply{adapter=ArrayAdapter(this@V5InformalCreditActivity,android.R.layout.simple_spinner_dropdown_item,arrayOf("Personal Credit","Business Credit","Trade Credit","Advance","Other"))};direction=Spinner(this).apply{adapter=ArrayAdapter(this@V5InformalCreditActivity,android.R.layout.simple_spinner_dropdown_item,arrayOf("Credit Given","Credit Received"))};method=Spinner(this).apply{adapter=ArrayAdapter(this@V5InformalCreditActivity,android.R.layout.simple_spinner_dropdown_item,arrayOf("EMI","Principal + Interest","Bullet / Full payment"))};principal=e("Principal / invoice amount *").apply{inputType=InputType.TYPE_CLASS_NUMBER or InputType.TYPE_NUMBER_FLAG_DECIMAL};roi=e("Annual ROI %").apply{inputType=InputType.TYPE_CLASS_NUMBER or InputType.TYPE_NUMBER_FLAG_DECIMAL};tenor=e("Repayment period in months *").apply{setText("12");inputType=InputType.TYPE_CLASS_NUMBER};start=e("Start date * (tap to select)");end=e("End date (auto-calculated)");end.isFocusable=false;end.isClickable=false
  listOf<View>(name,vendor,invoice,date,type,direction,principal,roi,method,tenor,start,end).forEach{put(r,it)};start.setText(today());date.setText(today());updateEnd()
  start.setOnClickListener{pickDate(start)};date.setOnClickListener{pickDate(date)};tenor.setOnFocusChangeListener{_,_->updateEnd()};tenor.setOnEditorActionListener{_,_,_->updateEnd();false};put(r,Button(this).apply{text="CALCULATE END DATE";setOnClickListener{updateEnd()}},50)
  put(r,Button(this).apply{text="BORROWER PROFILES / SEARCH / CREATE";setOnClickListener{startActivityForResult(Intent(this@V5InformalCreditActivity,V5BorrowerActivity::class.java),7001)}},58)
  put(r,Button(this).apply{text="DPN / GUARANTOR CONSENT WORKFLOW";setOnClickListener{ensureDraft();startActivity(Intent(this@V5InformalCreditActivity,V5GuarantorConsentActivity::class.java).putExtra("creditId",draftCreditId))}},58)
  put(r,Button(this).apply{text="CREATE / REVIEW DOCUMENT + GET CONSENT";setOnClickListener{startDocumentConsent()}},58)
  put(r,Button(this).apply{text="SEND OTP CONSENT + REGISTER";setOnClickListener{if(documentConsentId.isBlank()){Toast.makeText(this,"Document must be created, reviewed and consented before credit registration",Toast.LENGTH_LONG).show();startDocumentConsent()}else registerAfterConsent()}},58);put(r,Button(this).apply{text="BACK";setOnClickListener{finish()}},58)
  listOf<View>(name,vendor,invoice,date,principal,roi,tenor,start).forEach{it.setOnFocusChangeListener{v,has->if(has)v.post{scroll.smoothScrollTo(0,(v.bottom-scroll.height/3).coerceAtLeast(0))}}};setContentView(scroll)
 }
 private fun ensureDraft(){if(draftCreditId.isBlank())draftCreditId="CR-DRAFT-${System.currentTimeMillis()}"}
 private fun today()=SimpleDateFormat("yyyy-MM-dd",Locale.US).format(Date())
 private fun pickDate(target:EditText){val base=runCatching{SimpleDateFormat("yyyy-MM-dd",Locale.US).parse(target.text.toString())}.getOrNull()?:Date();val c=Calendar.getInstance().apply{time=base};DatePickerDialog(this,{_,y,m,d->target.setText(String.format(Locale.US,"%04d-%02d-%02d",y,m+1,d));if(target===start)updateEnd()},c.get(Calendar.YEAR),c.get(Calendar.MONTH),c.get(Calendar.DAY_OF_MONTH)).show()}
 private fun updateEnd(){val months=tenor.text.toString().toIntOrNull()?:return;val sd=runCatching{SimpleDateFormat("yyyy-MM-dd",Locale.US).parse(start.text.toString())}.getOrNull()?:return;val c=Calendar.getInstance();c.time=sd;c.add(Calendar.MONTH,months);end.setText(SimpleDateFormat("yyyy-MM-dd",Locale.US).format(c.time))}
 private fun applyQr(raw:String){try{val j=JSONObject(raw);name.setText(first(j,"party","vendor","vendor_name","seller","supplier","merchant"));vendor.setText(first(j,"vendor","vendor_name","seller","supplier","merchant","party"));invoice.setText(first(j,"invoice","invoice_no","invoice_number","bill_no","bill_number"));date.setText(first(j,"date","invoice_date","transaction_date"));principal.setText(first(j,"amount","total","total_amount","invoice_amount","grand_total"))}catch(_:Exception){raw.split('&','\n',';').mapNotNull{p->p.split('=',':',limit=2).takeIf{x->x.size==2}?.let{x->x[0].trim().lowercase() to x[1].trim()}}.toMap().let{m->vendor.setText(m["vendor"]?:m["seller"]?:m["supplier"]?:"");name.setText(m["party"]?:vendor.text);invoice.setText(m["invoice"]?:m["invoice_no"]?:"");date.setText(m["date"]?:m["invoice_date"]?:"");principal.setText(m["amount"]?:m["total"]?:m["total_amount"]?:"")}};Toast.makeText(this,"QR data captured. Review all fields before consent.",Toast.LENGTH_LONG).show()}
 private fun first(j:JSONObject,vararg keys:String)=keys.firstNotNullOfOrNull{if(j.has(it)&&!j.isNull(it))j.optString(it).takeIf{v->v.isNotBlank()}else null}?:""
 private fun startDocumentConsent(){ensureDraft();val party=name.text.toString().trim();val p=principal.text.toString().trim().toDoubleOrNull();val months=tenor.text.toString().toIntOrNull()?:0;if(party.length<2||p==null||p<=0||months !in 1..240){Toast.makeText(this,"Enter valid party, amount and repayment period first",Toast.LENGTH_LONG).show();return};updateEnd();val docId="DPN-${System.currentTimeMillis()}";val content="UDHAARDAAR DIGITAL CREDIT DOCUMENT\nVersion: 1\nDraft Credit: $draftCreditId\nParty: $party\nType: ${type.selectedItem}\nDirection: ${direction.selectedItem}\nPrincipal: ₹$p\nROI: ${roi.text}%\nMethod: ${method.selectedItem}\nStart: ${start.text}\nEnd: ${end.text}\nVendor: ${vendor.text}\nInvoice: ${invoice.text}\nCreated: ${System.currentTimeMillis()}";V5LocalStore(this).add("documents",JSONObject().apply{put("id",docId);put("creditId",draftCreditId);put("type","DIGITAL_CREDIT_DPN");put("status","CONSENT_PENDING");put("version",1);put("createdAt",System.currentTimeMillis());put("creditParty",party);put("content",content)});documentConsentId=consent.issue(docId,"DIGITAL_CREDIT_DOCUMENT_CONSENT",party);val otp=V5LocalStore(this).find("consents",documentConsentId)?.optString("otp","")?:"";val input=e("Enter 6-digit document-consent OTP");val d=AlertDialog.Builder(this).setTitle("Review digital document before credit").setMessage(content+"\n\nDemo OTP: $otp\nProduction SMS gateway is required for live OTP delivery.").setView(input).setNegativeButton("CANCEL",null).setPositiveButton("CONSENT",null).create();d.setOnShowListener{d.getButton(-1).setOnClickListener{if(consent.verify(documentConsentId,input.text.toString())){V5LocalStore(this).find("documents",docId)?.let{it.put("status","COMPLETED");it.put("consentedAt",System.currentTimeMillis());V5LocalStore(this).replace("documents",it)};repo.appendAudit(docId,"DIGITAL_CREDIT_DOCUMENT_CONSENTED_BEFORE_REGISTRATION",party,"creditId=$draftCreditId; version=1");Toast.makeText(this,"Digital document consent completed. Credit may now be registered after counterparty OTP.",Toast.LENGTH_LONG).show();d.dismiss()}else input.error="Incorrect OTP"}};d.show()}
 private fun registerAfterConsent(){ensureDraft();val p=principal.text.toString().trim().toDoubleOrNull();val months=tenor.text.toString().toIntOrNull()?:0;val rate=roi.text.toString().trim().removeSuffix("%").toDoubleOrNull()?:0.0;if(selectedProfileId.isBlank()){Toast.makeText(this,"Select a borrower profile before registration",Toast.LENGTH_LONG).show();return};if(name.text.trim().length<2||p==null||p<=0||months !in 1..240||rate<0||rate>100){Toast.makeText(this,"Complete valid party, amount, ROI (0–100%) and repayment period",Toast.LENGTH_LONG).show();return};val pty=name.text.toString();updateEnd();val q=rate/1200.0;val inst=if(method.selectedItem.toString()=="EMI"&&q>0)p*q*(1+q).pow(months)/((1+q).pow(months)-1) else p/months;val total=when(method.selectedItem.toString()){"EMI"->if(q>0)inst*months else p;"Principal + Interest"->p+p*rate*months/1200.0;else->p+p*rate*months/1200.0};val id=draftCreditId;val cid=consent.issue(id,"INFORMAL_CREDIT_BORROWER_CONSENT",pty);val otp=V5LocalStore(this).find("consents",cid)?.optString("otp","")?:"";val input=e("Enter 6-digit OTP");val d=AlertDialog.Builder(this).setTitle("Counterparty consent").setMessage("Digital document already consented.\nDemo OTP: $otp\nConfirm only after reviewing final credit terms.").setView(input).setNegativeButton("CANCEL",null).setPositiveButton("CONFIRM",null).create();d.setOnShowListener{d.getButton(-1).setOnClickListener{if(consent.verify(cid,input.text.toString())){repo.saveCredit(id,selectedProfileId,type.selectedItem.toString(),direction.selectedItem.toString(),p,rate,method.selectedItem.toString(),start.text.toString(),end.text.toString(),vendor.text.toString(),invoice.text.toString(),qrRaw,cid,System.currentTimeMillis(),total);val c=V5LocalStore(this).find("credits",id);c?.put("borrowerName",pty);c?.put("documentConsentId",documentConsentId);c?.put("borrowerProfileId",selectedProfileId);c?.let{V5LocalStore(this).replace("credits",it)};repo.appendAudit(id,"CREDIT_REGISTERED_AFTER_DOCUMENT_AND_COUNTERPARTY_CONSENT",pty,"profileId=$selectedProfileId; documentConsent=$documentConsentId; totalPayable=$total");Toast.makeText(this,"Document consent and counterparty OTP verified; credit registered",Toast.LENGTH_LONG).show();d.dismiss();finish()}else input.error="Incorrect OTP"}};d.show()}}
 override fun onActivityResult(requestCode:Int,resultCode:Int,data:Intent?){super.onActivityResult(requestCode,resultCode,data);if(requestCode==7001&&resultCode==RESULT_OK){selectedProfileId=data?.getStringExtra("profileId").orEmpty();val selectedName=data?.getStringExtra("profileName").orEmpty();if(selectedName.isNotBlank())name.setText(selectedName);Toast.makeText(this,"Borrower profile selected: $selectedName",Toast.LENGTH_SHORT).show()}}
}
