package com.udhaardaar.mvp

import android.app.AlertDialog
import android.graphics.Color
import android.os.Bundle
import android.view.View
import android.view.ViewGroup
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import org.json.JSONObject
import java.io.BufferedReader
import java.io.InputStreamReader
import java.net.HttpURLConnection
import java.net.URL
import java.util.Locale

class V5PartyActivity:AppCompatActivity(){
 private val store by lazy{V5LocalStore(this)};private val bg=Color.rgb(238,248,253);private val navy=Color.rgb(24,58,92);private val teal=Color.rgb(0,145,135);private val green=Color.rgb(25,145,78);private val blue=Color.rgb(25,111,220)
 private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt();private fun box()=android.graphics.drawable.GradientDrawable().apply{setColor(Color.WHITE);setStroke(dp(1),Color.rgb(205,218,228));cornerRadius=dp(14).toFloat()};private fun e(h:String)=EditText(this).apply{hint=h;textSize=15f;setSingleLine(true);minHeight=dp(50);setPadding(dp(12),dp(7),dp(12),dp(7));background=box();imeOptions=android.view.inputmethod.EditorInfo.IME_ACTION_NEXT};private fun add(r:LinearLayout,v:View){r.addView(v,LinearLayout.LayoutParams(-1,ViewGroup.LayoutParams.WRAP_CONTENT).apply{setMargins(0,dp(4),0,dp(4))})};private fun b(s:String,c:Int,fn:()->Unit)=Button(this).apply{text=s;isAllCaps=false;textSize=14f;setTextColor(Color.WHITE);background=box().apply{setColor(c)};minHeight=dp(50);setOnClickListener{fn()}}
 override fun onCreate(x:Bundle?){super.onCreate(x);window.setSoftInputMode(android.view.WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);show()}
 private fun show(){val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(16),dp(14),dp(16),dp(24));setBackgroundColor(bg)};add(r,TextView(this).apply{text="UDHAARDAAR V5";textSize=12f;setTextColor(teal)});add(r,TextView(this).apply{text="Party & Borrower Identity";textSize=22f;setTextColor(navy)});add(r,TextView(this).apply{text="Search by exact name, mobile, PAN, Aadhaar, GSTIN or profile ID. Select a result to continue credit registration.";textSize=12f})
  val search=e("Name / mobile / PAN / Aadhaar / GSTIN / ID");add(r,search);add(r,b("SEARCH PROFILE",teal){searchProfiles(search.text.toString())});add(r,TextView(this).apply{text="CREATE / UPDATE PROFILE";textSize=17f;setTextColor(navy)})
  val type=Spinner(this);type.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,listOf("BORROWER","LENDER","SELLER","BUYER","GUARANTOR","NOMINEE","LEGAL HEIR","TRUSTED PERSON","BUSINESS","BANK/NBFC"));add(r,type)
  val name=e("Full name / legal entity *");val mobile=e("Mobile *");val pan=e("PAN (optional)");val aad=e("Aadhaar (12 digits, optional)");val gst=e("GSTIN (optional)");val pin=e("PIN code (6 digits)");val city=e("City — auto-filled from PIN");val state=e("State — auto-filled from PIN");listOf(name,mobile,pan,aad,gst,pin,city,state).forEach{add(r,it)}
  add(r,b("LOOK UP PIN",blue){lookupPin(pin,city,state)});pin.setOnFocusChangeListener{_,has->if(!has&&pin.text.toString().length==6)lookupPin(pin,city,state)}
  add(r,b("SAVE PROFILE",green){val n=name.text.toString().trim();val m=mobile.text.toString().trim();val p=pan.text.toString().trim().uppercase(Locale.US);val a=aad.text.toString().trim();val g=gst.text.toString().trim().uppercase(Locale.US);val pc=pin.text.toString().trim();if(n.length<2){name.error="Name required";return@b};if(!V5Validation.mobile(m)){mobile.error="Valid 10-digit mobile required";return@b};if(p.isNotEmpty()&&!V5Validation.pan(p)){pan.error="Invalid PAN";return@b};if(a.isNotEmpty()&&!V5Validation.aadhaar(a)){aad.error="Invalid Aadhaar";return@b};if(g.isNotEmpty()&&!V5Validation.gstin(g)){gst.error="Invalid GSTIN";return@b};if(pc.isNotEmpty()&&!V5Validation.pin(pc)){pin.error="Invalid PIN";return@b};val old=store.all("profiles").firstOrNull{it.optString("mobile")==m||(p.isNotEmpty()&&it.optString("pan").equals(p,true))};val id=old?.optString("id")?.takeIf{it.isNotBlank()}?:"P-${System.currentTimeMillis()}";val obj=JSONObject().apply{put("id",id);put("type",type.selectedItem.toString());put("name",n);put("mobile",m);put("pan",p);put("aadhaar",a);put("gstin",g);put("pin",pc);put("city",city.text.toString().trim());put("state",state.text.toString().trim());put("verified",old?.optBoolean("verified",false)?:false);put("createdAt",old?.optLong("createdAt",System.currentTimeMillis())?:System.currentTimeMillis());put("updatedAt",System.currentTimeMillis())};store.replace("profiles",obj);toast(if(old==null)"Profile created successfully" else "Profile updated successfully");selectAndReturn(obj)})
  add(r,b("BACK",navy){finish()});setContentView(ScrollView(this).apply{isFillViewport=true;addView(r)})}
 private fun searchProfiles(q0:String){val q=q0.trim();if(q.isBlank()){toast("Enter a name, mobile, PAN, Aadhaar, GSTIN or ID");return};val hits=store.all("profiles").filter{p->listOf("id","name","mobile","pan","aadhaar","gstin").any{k->p.optString(k).contains(q,true)}};if(hits.isEmpty()){toast("No such user found");return};val labels=hits.map{"${it.optString("name")} • ${it.optString("type")}\n${it.optString("mobile")} • ID ${it.optString("id")}"}.toTypedArray();AlertDialog.Builder(this).setTitle("Select user").setSingleChoiceItems(labels,-1){d,which->d.dismiss();selectAndReturn(hits[which])}.setNegativeButton("CANCEL",null).show()}
 private fun selectAndReturn(p:JSONObject){setResult(RESULT_OK,android.content.Intent().apply{putExtra("profileId",p.optString("id"));putExtra("profileName",p.optString("name"));putExtra("profileMobile",p.optString("mobile"))});finish()}
 private fun lookupPin(pin:EditText,city:EditText,state:EditText){val p=pin.text.toString();if(!V5Validation.pin(p)){pin.error="Enter 6-digit PIN";return};Thread{try{val c=URL("https://api.postalpincode.in/pincode/$p").openConnection() as HttpURLConnection;c.connectTimeout=5000;c.readTimeout=5000;val s=BufferedReader(InputStreamReader(c.inputStream)).use{it.readText()};c.disconnect();val m=Regex("\\\"Name\\\"\\s*:\\s*\\\"([^\\\"]+)\\\".*?\\\"State\\\"\\s*:\\s*\\\"([^\\\"]+)\\\"").find(s);runOnUiThread{if(m!=null){city.setText(m.groupValues[1]);state.setText(m.groupValues[2]);toast("City and state filled automatically")}else toast("PIN not found — enter city/state manually")}}catch(_:Exception){runOnUiThread{toast("PIN lookup unavailable — enter city/state manually")}}}.start()}
 private fun toast(s:String)=Toast.makeText(this,s,Toast.LENGTH_LONG).show()
}
