package com.udhaardaar.mvp

import android.app.AlertDialog
import android.content.Intent
import android.net.Uri
import android.os.Bundle
import android.view.WindowManager
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import org.json.JSONObject
import java.text.SimpleDateFormat
import java.util.*

class V5RentalLeaseActivity : AppCompatActivity(){
 private val store by lazy{V5LocalStore(this)};private val repo by lazy{V5WorkflowRepository(this)};private var uri:Uri?=null
 private lateinit var tenant:EditText;private lateinit var landlord:EditText;private lateinit var rent:EditText;private lateinit var start:EditText;private lateinit var period:EditText;private lateinit var status:TextView
 private fun f(h:String)=EditText(this).apply{hint=h;setSingleLine(true);setPadding(14,10,14,10)}
 private fun add(r:LinearLayout,v:android.view.View,h:Int=56){r.addView(v,LinearLayout.LayoutParams(-1,h).apply{setMargins(0,5,0,5)})}
 override fun onCreate(b:Bundle?){super.onCreate(b);window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(22,18,22,30)};add(r,TextView(this).apply{text="UDHAARDAAR V5 • Rental / Lease";textSize=23f},62);add(r,TextView(this).apply{text="Separate module • agreement capture → review → consent → rental record";textSize=13f},62);tenant=f("Tenant / lessee profile ID or name *");landlord=f("Landlord / lessor profile ID or name *");rent=f("Monthly rent / lease amount ₹ *");start=f("Lease start date YYYY-MM-DD *");period=f("Lease period in months *").apply{setText("12")};listOf(tenant,landlord,rent,start,period).forEach{add(r,it)};start.setText(SimpleDateFormat("yyyy-MM-dd",Locale.US).format(Date()));status=TextView(this).apply{text="Agreement not captured"};add(r,status,60);add(r,Button(this).apply{text="SCAN / IMPORT RENT AGREEMENT";setOnClickListener{pick()}},58);add(r,Button(this).apply{text="REVIEW AGREEMENT + REGISTER";setOnClickListener{review()}},58);add(r,Button(this).apply{text="BACK";setOnClickListener{finish()}},54);setContentView(ScrollView(this).apply{isFillViewport=true;addView(r)})}
 private fun pick(){startActivityForResult(Intent(Intent.ACTION_OPEN_DOCUMENT).apply{addCategory(Intent.CATEGORY_OPENABLE);type="*/*";putExtra(Intent.EXTRA_MIME_TYPES,arrayOf("application/pdf","image/jpeg","image/png"))},7001)}
 @Deprecated("compatibility") override fun onActivityResult(c:Int,r:Int,d:Intent?){super.onActivityResult(c,r,d);if(c==7001&&r==RESULT_OK){uri=d?.data;status.text="Captured: ${uri?.lastPathSegment ?: "agreement"}. Review required."}}
 private fun review(){val t=tenant.text.toString().trim();val l=landlord.text.toString().trim();val amount=rent.text.toString().toDoubleOrNull();val months=period.text.toString().toIntOrNull()?:0;if(t.length<2||l.length<2||amount==null||amount<=0||months !in 1..240||uri==null){Toast.makeText(this,"Complete parties, rent, period and agreement capture first",Toast.LENGTH_LONG).show();return};val id="RENT-${System.currentTimeMillis()}";val doc="RENT-DOC-${System.currentTimeMillis()}";val now=System.currentTimeMillis();store.add("documents",JSONObject().apply{put("id",doc);put("type","RENT_AGREEMENT");put("uri",uri.toString());put("status","REVIEW_PENDING");put("version",1);put("createdAt",now)});AlertDialog.Builder(this).setTitle("Review rental agreement").setMessage("Tenant: $t\nLandlord: $l\nRent: ₹$amount\nPeriod: $months months\nDocument: $doc\n\nConfirm the imported/scanned agreement has been reviewed before consent.").setNegativeButton("CANCEL",null).setPositiveButton("REQUEST CONSENT"){_,_->consent(id,doc,t,l,amount,months)}.show()}
 private fun consent(id:String,doc:String,t:String,l:String,amount:Double,months:Int){val svc=V5OtpConsentService(this);val cid=svc.issue(id,"RENTAL_LEASE_CONSENT","$t/$l");val code=store.find("consents",cid)?.optString("otp","")?:"";val input=f("6-digit consent OTP");AlertDialog.Builder(this).setTitle("Tenant / landlord consent").setMessage("Demo OTP: $code").setView(input).setNegativeButton("CANCEL",null).setPositiveButton("CONFIRM",null).create().also{d->d.setOnShowListener{d.getButton(-1).setOnClickListener{if(svc.verify(cid,input.text.toString())){val now=System.currentTimeMillis();store.find("documents",doc)?.let{x->x.put("status","COMPLETED");x.put("consentId",cid);x.put("consentedAt",now);store.replace("documents",x)};store.add("rental_leases",JSONObject().apply{put("id",id);put("tenant",t);put("landlord",l);put("monthlyRent",amount);put("startDate",start.text.toString());put("periodMonths",months);put("agreementDocumentId",doc);put("consentId",cid);put("status","ACTIVE");put("createdAt",now);put("updatedAt",now)});repo.appendAudit(id,"RENTAL_LEASE_REGISTERED_AFTER_CONSENT",t,"landlord=$l; document=$doc; timestamp=$now");Toast.makeText(this@V5RentalLeaseActivity,"Rental / lease registered after consent",Toast.LENGTH_LONG).show();d.dismiss();finish()}else input.error="Incorrect OTP"}};d.show()}}
}
