package com.udhaardaar.mvp

import android.app.AlertDialog
import android.app.DatePickerDialog
import android.graphics.Color
import android.os.Bundle
import android.view.View
import android.view.ViewGroup
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import org.json.JSONObject
import java.text.SimpleDateFormat
import java.util.*

class V5RepaymentActivity:AppCompatActivity(){
 private val service by lazy{V5RepaymentService(this)};private val store by lazy{V5LocalStore(this)};private val bg=Color.rgb(238,248,253);private val navy=Color.rgb(24,58,92);private val teal=Color.rgb(0,145,135);private val green=Color.rgb(25,145,78)
 private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt();private fun box()=android.graphics.drawable.GradientDrawable().apply{setColor(Color.WHITE);setStroke(dp(1),Color.rgb(205,218,228));cornerRadius=dp(14).toFloat()};private fun e(h:String)=EditText(this).apply{hint=h;textSize=15f;setSingleLine(true);minHeight=dp(50);setPadding(dp(12),dp(7),dp(12),dp(7));background=box();imeOptions=android.view.inputmethod.EditorInfo.IME_ACTION_NEXT};private fun add(r:LinearLayout,v:View){r.addView(v,LinearLayout.LayoutParams(-1,ViewGroup.LayoutParams.WRAP_CONTENT).apply{setMargins(0,dp(4),0,dp(4))})};private fun b(s:String,c:Int,fn:()->Unit)=Button(this).apply{text=s;isAllCaps=false;textSize=14f;setTextColor(Color.WHITE);background=box().apply{setColor(c)};minHeight=dp(50);setOnClickListener{fn()}}
 override fun onCreate(x:Bundle?){super.onCreate(x);window.setSoftInputMode(android.view.WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);show()}
 private fun show(){val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(16),dp(14),dp(16),dp(24));setBackgroundColor(bg)};add(r,TextView(this).apply{text="UDHAARDAAR V5";textSize=12f;setTextColor(teal)});add(r,TextView(this).apply{text="Repayment Centre";textSize=22f;setTextColor(navy)});add(r,TextView(this).apply{text="Informal: counterparty OTP. Formal: bank/account evidence, no counterparty OTP.";textSize=12f})
  val kind=Spinner(this);kind.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,listOf("INFORMAL","FORMAL"));val direction=Spinner(this);direction.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,listOf("PAYABLE","RECEIVABLE"));val mode=Spinner(this);mode.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,listOf("EMI","PRINCIPAL_PLUS_INTEREST","BULLET_PRINCIPAL_ONLY","BULLET_INTEREST_MONTHLY","BULLET_PRINCIPAL_PLUS_INTEREST_AT_END"));val credit=e("Credit ID *");val counter=e("Counterparty *");val amount=e("Repayment amount ₹ *");val date=e("Payment date");val ref=e("Transaction reference");val evidence=e("Bank / account evidence reference");add(r,kind);add(r,direction);add(r,mode);listOf(credit,counter,amount,date,ref,evidence).forEach{add(r,it)};add(r,b("PICK PAYMENT DATE",teal){pickDate(date)})
  add(r,b("RECORD REPAYMENT",green){val a=amount.text.toString().toDoubleOrNull();if(credit.text.isBlank()||counter.text.isBlank()||a==null||a<=0||date.text.isBlank()){toast("Complete credit, counterparty, amount and date");return@b};if(kind.selectedItem.toString()=="FORMAL"&&evidence.text.isBlank()){toast("Formal repayment requires bank/account evidence");return@b};if(kind.selectedItem.toString()=="INFORMAL"){val party=if(direction.selectedItem.toString()=="PAYABLE")"LENDER" else "BORROWER";val req=service.request(credit.text.toString(),party,a,date.text.toString(),mode.selectedItem.toString(),ref.text.toString(),evidence.text.toString());val code=store.find("repayment_requests",req)?.optString("otp","")?:"";val input=e("Enter counterparty OTP");val d=AlertDialog.Builder(this).setTitle("Counterparty consent required").setMessage("Demo OTP: $code\nProduction SMS provider is required for live delivery.").setView(input).setNegativeButton("CANCEL",null).setPositiveButton("CONFIRM",null).create();d.setOnShowListener{d.getButton(-1).setOnClickListener{if(service.confirm(req,input.text.toString(),code)){d.dismiss();toast("Informal repayment confirmed after OTP");show()}else input.error="Incorrect OTP"}};d.show()}else{store.add("repayments",JSONObject().apply{put("id","RP-${System.currentTimeMillis()}");put("creditId",credit.text.toString());put("counterparty",counter.text.toString());put("amount",a);put("date",date.text.toString());put("method",mode.selectedItem.toString());put("direction",direction.selectedItem.toString());put("evidence",evidence.text.toString());put("status","CONFIRMED_FORMAL");put("consent","NOT_REQUIRED");put("createdAt",System.currentTimeMillis())});toast("Formal repayment recorded from evidence")}})
  add(r,TextView(this).apply{text="Dashboard filters: All • Payable • Receivable • Due • Overdue • Pending Consent • Settled";textSize=12f;setTextColor(navy);background=box();setPadding(dp(10),dp(8),dp(10),dp(8))});add(r,b("VIEW SAVED REPAYMENTS",navy){val a=store.all("repayments")+store.all("repayment_requests");val msg=a.sortedByDescending{it.optLong("createdAt",0)}.joinToString("\n\n"){j->"${j.optString("creditId","-")} • ${j.optString("direction","-")} • ₹${j.optDouble("amount",0.0)}\n${j.optString("date","")} • ${j.optString("status","")}"}.ifBlank{"No repayment records yet"};AlertDialog.Builder(this).setTitle("Repayment details").setMessage(msg).setPositiveButton("OK",null).show()});add(r,b("BACK",navy){finish()});setContentView(ScrollView(this).apply{isFillViewport=true;addView(r)})}
 private fun pickDate(t:EditText){val c=Calendar.getInstance();DatePickerDialog(this,{_,y,m,d->t.setText(String.format(Locale.US,"%02d %s %04d",d,SimpleDateFormat("MMM",Locale.US).format(Calendar.getInstance().apply{set(Calendar.MONTH,m)}.time),y))},c.get(Calendar.YEAR),c.get(Calendar.MONTH),c.get(Calendar.DAY_OF_MONTH)).show()};private fun toast(s:String)=Toast.makeText(this,s,Toast.LENGTH_LONG).show()
}
