package com.udhaardaar.mvp
import android.app.AlertDialog
import android.graphics.Color
import android.os.Bundle
import android.view.View
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import org.json.JSONObject

class V5RepaymentActivity:AppCompatActivity(){
 private val service by lazy{V5RepaymentService(this)};private val store by lazy{V5LocalStore(this)}
 private fun e(h:String)=EditText(this).apply{hint=h;setSingleLine(true);textSize=14f};private fun add(r:LinearLayout,v:View,h:Int=50){r.addView(v,LinearLayout.LayoutParams(-1,h).apply{setMargins(0,3,0,3)})}
 override fun onCreate(b:Bundle?){super.onCreate(b);show()}
 private fun show(){val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(18,12,18,18)};r.addView(TextView(this).apply{text="UDHAARDAAR V5 • REPAYMENT CENTRE";textSize=21f;setTextColor(Color.rgb(24,58,92))});r.addView(TextView(this).apply{text="Informal: counterparty OTP. Formal: bank/account evidence, no counterparty OTP.";textSize=12f})
  val credit=e("Credit ID *");val counter=e("Counterparty *");val amount=e("Repayment amount *");val date=e("Payment date YYYY-MM-DD *");val ref=e("Transaction reference");val evidence=e("Bank/account statement evidence reference");val kind=Spinner(this);kind.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,listOf("INFORMAL","FORMAL"));val mode=Spinner(this);mode.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,listOf("EMI","PRINCIPAL_PLUS_INTEREST","BULLET_PRINCIPAL_ONLY","BULLET_INTEREST_MONTHLY","BULLET_PRINCIPAL_PLUS_INTEREST_AT_END"));val direction=Spinner(this);direction.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,listOf("PAYABLE","RECEIVABLE"));listOf(credit,counter,amount,date,ref,evidence).forEach{add(r,it)};add(r,kind,50);add(r,mode,50);add(r,direction,50)
  add(r,Button(this).apply{text="RECORD REPAYMENT";setOnClickListener{val a=amount.text.toString().toDoubleOrNull();if(credit.text.isBlank()||counter.text.isBlank()||a==null||a<=0||date.text.isBlank()){toast("Complete required fields");return@setOnClickListener};if(kind.selectedItem.toString()=="FORMAL"&&evidence.text.isBlank()){toast("Formal repayment requires bank/account evidence");return@setOnClickListener};val id="RP-${System.currentTimeMillis()}";if(kind.selectedItem.toString()=="INFORMAL"){val req=service.request(credit.text.toString(),"LENDER",a,date.text.toString(),mode.selectedItem.toString(),ref.text.toString(),evidence.text.toString());val otp=store.find("repayment_requests",req)?.optString("otp","")?:"";val input=e("Counterparty OTP");val d=AlertDialog.Builder(this@V5RepaymentActivity).setTitle("Counterparty consent").setMessage("Demo OTP: $otp\nLive SMS provider required for production.").setView(input).setNegativeButton("CANCEL",null).setPositiveButton("CONFIRM",null).create();d.setOnShowListener{d.getButton(-1).setOnClickListener{if(service.confirm(req,input.text.toString(),otp)){toast("Informal repayment CONFIRMED");d.dismiss()}else input.error="Incorrect OTP"}};d.show()}else{store.add("repayments",JSONObject().apply{put("id",id);put("creditId",credit.text.toString());put("counterparty",counter.text.toString());put("amount",a);put("date",date.text.toString());put("method",mode.selectedItem.toString());put("direction",direction.selectedItem.toString());put("evidence",evidence.text.toString());put("status","CONFIRMED_FORMAL");put("consent","NOT_REQUIRED");put("createdAt",System.currentTimeMillis())});toast("Formal repayment recorded from evidence; counterparty OTP not required")}}});add(r,TextView(this).apply{text="FILTERS: All • Payable • Receivable • Due • Overdue • Pending Consent • Settled";textSize=12f},55);add(r,Button(this).apply{text="VIEW SAVED REPAYMENTS";setOnClickListener{val a=store.all("repayments");val p=store.all("repayment_requests");val msg=(a+p).joinToString("\n"){it.toString()}.ifBlank{"No repayments recorded"};AlertDialog.Builder(this@V5RepaymentActivity).setTitle("Repayment history").setMessage(msg).setPositiveButton("OK",null).show()}});add(r,Button(this).apply{text="BACK";setOnClickListener{finish()}});setContentView(ScrollView(this).apply{addView(r)})}
 private fun toast(s:String)=Toast.makeText(this,s,Toast.LENGTH_LONG).show()
}
