package com.udhaardaar.mvp

import android.app.AlertDialog
import android.os.Bundle
import android.view.View
import android.view.WindowManager
import android.widget.*
import org.json.JSONObject

class V5SupportWorkflowsActivity : androidx.appcompat.app.AppCompatActivity() {
 private val store by lazy { V5LocalStore(this) }; private val consent by lazy { V5OtpConsentService(this) }
 private fun e(h:String)=EditText(this).apply{hint=h;setSingleLine(true);setPadding(14,10,14,10)}
 private fun add(r:LinearLayout,v:View,h:Int=56){r.addView(v,LinearLayout.LayoutParams(-1,h).apply{setMargins(0,5,0,5)})}
 override fun onCreate(b:Bundle?){super.onCreate(b);window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);show()}
 private fun show(){val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(20,16,20,28)};add(r,TextView(this).apply{text="UDHAARDAAR V5 • Support & Protection";textSize=23f},62);when(intent.getStringExtra("mode") ?: "ACCESS"){"LEGAL"->legal(r);"NOTIFICATIONS"->readiness(r);"NOMINEE"->nominee(r);else->access(r)};add(r,Button(this).apply{text="BACK TO HOME";setOnClickListener{finish()}},54);setContentView(ScrollView(this).apply{isFillViewport=true;addView(r)})}
 private fun access(r:LinearLayout){add(r,TextView(this).apply{text="Controlled access: request → OTP consent → scoped grant → revoke/expiry";textSize=13f},55);val owner=e("Owner profile ID *");val person=e("Trusted person profile ID *");val scope=e("Scope * (comma separated: ASSETS,LIABILITIES,CLAIMS,DOCUMENTS)");val expiry=e("Expiry date (YYYY-MM-DD, optional)");add(r,owner);add(r,person);add(r,scope);add(r,expiry);add(r,Button(this).apply{text="REQUEST + CONSENT ACCESS";setOnClickListener{if(owner.text.isBlank()||person.text.isBlank()||scope.text.isBlank()){toast("Owner, trusted person and scope are required");return@setOnClickListener};val id="ACC-${System.currentTimeMillis()}";store.add("access_requests",JSONObject().apply{put("id",id);put("ownerProfileId",owner.text.toString().trim());put("trustedPersonProfileId",person.text.toString().trim());put("scope",scope.text.toString().trim().uppercase());put("expiry",expiry.text.toString().trim());put("status","CONSENT_PENDING");put("createdAt",System.currentTimeMillis())});val cid=consent.issue(id,"TRUSTED_ACCESS",person.text.toString().trim());val code=store.find("consents",cid)?.optString("otp","")?:"";val input=e("Enter OTP");AlertDialog.Builder(this@V5SupportWorkflowsActivity).setTitle("Trusted access consent").setMessage("Demo OTP: $code").setView(input).setNegativeButton("CANCEL",null).setPositiveButton("CONFIRM",null).create().also{d->d.setOnShowListener{d.getButton(-1).setOnClickListener{if(consent.verify(cid,input.text.toString())){val q=store.find("access_requests",id)!!;q.put("status","ACTIVE");q.put("consentId",cid);q.put("consentedAt",System.currentTimeMillis());store.replace("access_requests",q);store.add("access_grants",JSONObject().apply{put("id","GRANT-${System.currentTimeMillis()}");put("accessRequestId",id);put("ownerProfileId",owner.text.toString().trim());put("trustedPersonProfileId",person.text.toString().trim());put("scope",scope.text.toString().trim().uppercase());put("expiry",expiry.text.toString().trim());put("status","ACTIVE");put("createdAt",System.currentTimeMillis())});store.add("audit",JSONObject().apply{put("id","AUD-${System.currentTimeMillis()}");put("entityId",id);put("event","CONTROLLED_ACCESS_GRANTED");put("at",System.currentTimeMillis())});toast("Scoped controlled access activated");d.dismiss()}else input.error="Incorrect OTP"}};d.show()}}},60);add(r,Button(this).apply{text="REVOKE ACTIVE ACCESS";setOnClickListener{val grants=store.all("access_grants").filter{it.optString("status")=="ACTIVE"};if(grants.isEmpty())toast("No active grant")else{val g=grants.last();g.put("status","REVOKED");g.put("revokedAt",System.currentTimeMillis());store.replace("access_grants",g);store.find("access_requests",g.optString("accessRequestId"))?.let{it.put("status","REVOKED");store.replace("access_requests",it)};toast("Access revoked and audited")}}},60)}
 private fun nominee(r:LinearLayout){add(r,TextView(this).apply{text="Nominee / beneficiary: relationship + asset/claim linkage + OTP consent";textSize=13f},55);val owner=e("Owner profile ID *");val nominee=e("Nominee / beneficiary profile ID *");val asset=e("Asset / liability ID (optional)");val relationship=e("Relationship / capacity");val percent=e("Share % (optional)");add(r,owner);add(r,nominee);add(r,asset);add(r,relationship);add(r,percent);add(r,Button(this).apply{text="SAVE NOMINEE + GET CONSENT";setOnClickListener{if(owner.text.isBlank()||nominee.text.isBlank()){toast("Owner and nominee are required");return@setOnClickListener};val id="NOM-${System.currentTimeMillis()}";val cid=consent.issue(id,"NOMINEE_CONSENT",nominee.text.toString().trim());val code=store.find("consents",cid)?.optString("otp","")?:"";val input=e("Nominee OTP");AlertDialog.Builder(this@V5SupportWorkflowsActivity).setTitle("Nominee consent").setMessage("Demo OTP: $code").setView(input).setPositiveButton("CONFIRM",null).setNegativeButton("CANCEL",null).create().also{d->d.setOnShowListener{d.getButton(-1).setOnClickListener{if(consent.verify(cid,input.text.toString())){store.add("nominees",JSONObject().apply{put("id",id);put("ownerProfileId",owner.text.toString().trim());put("nomineeProfileId",nominee.text.toString().trim());put("assetId",asset.text.toString().trim());put("relationship",relationship.text.toString().trim());put("sharePercent",percent.text.toString().trim());put("consentId",cid);put("status","ACTIVE");put("createdAt",System.currentTimeMillis())});store.add("audit",JSONObject().apply{put("id","AUD-${System.currentTimeMillis()}");put("entityId",id);put("event","NOMINEE_REGISTERED_WITH_CONSENT");put("at",System.currentTimeMillis())});toast("Nominee saved with consent and relationship");d.dismiss()}else input.error="Incorrect OTP"}};d.show()}}},60)}
 private fun legal(r:LinearLayout){add(r,TextView(this).apply{text="Legal support: case lifecycle + evidence/document linkage";textSize=13f},50);val subject=e("Case subject / profile ID *");val type=e("Case type");val evidence=e("Evidence/document IDs (comma separated)");val notes=e("Facts / assistance required *");add(r,subject);add(r,type);add(r,evidence);add(r,notes);add(r,Button(this).apply{text="CREATE LEGAL CASE";setOnClickListener{if(subject.text.isBlank()||notes.text.isBlank()){toast("Subject and facts are required");return@setOnClickListener};val id="LEG-${System.currentTimeMillis()}";store.add("legal_cases",JSONObject().apply{put("id",id);put("subject",subject.text.toString());put("caseType",type.text.toString());put("evidenceIds",evidence.text.toString());put("notes",notes.text.toString());put("status","OPEN");put("createdAt",System.currentTimeMillis());put("updatedAt",System.currentTimeMillis())});store.add("audit",JSONObject().apply{put("id","AUD-${System.currentTimeMillis()}");put("entityId",id);put("event","LEGAL_CASE_CREATED");put("at",System.currentTimeMillis())});toast("Legal support case created")}},60);add(r,Button(this).apply{text="ADVANCE LAST CASE → IN REVIEW";setOnClickListener{val x=store.all("legal_cases").lastOrNull();if(x==null)toast("No case")else{x.put("status","IN_REVIEW");x.put("updatedAt",System.currentTimeMillis());store.replace("legal_cases",x);toast("Case moved to IN_REVIEW")}}},60)}
 private fun readiness(r:LinearLayout){add(r,TextView(this).apply{text="Readiness centre • actionable items from credits, assets, liabilities and claims";textSize=13f},55);val items=store.all("credits").filter{it.optString("status")!="CLOSED"}.map{"CREDIT DUE: ${it.optString("id")} • outstanding ₹${it.optDouble("outstanding",0.0)}"}+store.all("assets").filter{it.optString("category")=="LIABILITY"}.map{"LIABILITY: ${it.optString("title")} • ₹${it.optDouble("outstandingLiability",it.optDouble("estimatedValue",0.0))}"}+store.all("death_claim_cases").filter{it.optString("status")!="CLOSED"}.map{"CLAIM FOLLOW-UP: ${it.optString("id")} • ${it.optString("status","OPEN")}"};val alertText=if(items.isEmpty())"No actionable items currently."else items.joinToString("\n\n");add(r,TextView(this).apply{setText(alertText);textSize=15f},200);add(r,Button(this).apply{text="CREATE / REFRESH ALERT QUEUE";setOnClickListener{store.add("notifications",JSONObject().apply{put("id","NTF-${System.currentTimeMillis()}");put("message",alertText);put("status","PENDING");put("createdAt",System.currentTimeMillis())});toast("Actionable readiness alert queue refreshed")}},60);add(r,Button(this).apply{text="MARK LAST ALERT DONE";setOnClickListener{store.all("notifications").lastOrNull()?.let{it.put("status","DONE");it.put("completedAt",System.currentTimeMillis());store.replace("notifications",it);toast("Alert completed")}}},60)}
 private fun toast(s:String)=Toast.makeText(this,s,Toast.LENGTH_LONG).show()
}
