package com.udhaardaar.mvp

import android.app.AlertDialog
import android.os.Bundle
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import org.json.JSONObject

/** TTMM = Tu Tera, Main Mera. Shared expense recovery; every participant is profile-linked. */
class V5TTMMActivity:AppCompatActivity(){
 private val store by lazy{V5LocalStore(this)};private val otp by lazy{V5OtpConsentService(this)}
 private lateinit var payer:EditText;private lateinit var recipients:EditText;private lateinit var amount:EditText;private lateinit var purpose:EditText;private lateinit var status:TextView
 private fun e(h:String,multi:Boolean=false)=EditText(this).apply{hint=h;setSingleLine(!multi);if(multi){minLines=3;gravity=android.view.Gravity.TOP};setPadding(18,12,18,12)}
 private fun b(t:String,a:()->Unit)=Button(this).apply{text=t;setOnClickListener{a()}}
 override fun onCreate(s:Bundle?){super.onCreate(s);render()}
 private fun render(){val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(24,18,24,28)};root.addView(TextView(this).apply{text="TU TERA, MAIN MERA";textSize=25f});root.addView(TextView(this).apply{text="Temporary shared-expense recovery • profile-linked • OTP based • no DPN/loan";textSize=14f});payer=e("Payer profile ID *");recipients=e("Participant profile shares — one per line: PROFILE_ID=250",true);amount=e("Total amount paid to vendor (₹) *");purpose=e("Expense / vendor / reason");listOf(payer,recipients,amount,purpose).forEach{root.addView(it,LinearLayout.LayoutParams(-1,if(it===recipients)150 else 58).apply{setMargins(0,5,0,5)})};root.addView(b("CALCULATE / REQUEST OTP"){issue()});status=TextView(this).apply{textSize=14f;setPadding(0,18,0,8)};root.addView(status);root.addView(b("VIEW TTMM ENTRIES"){showEntries()});root.addView(b("SETTLE / CONFIRM RECOVERY"){settleDialog()});root.addView(b("BACK"){finish()});setContentView(ScrollView(this).apply{isFillViewport=true;addView(root)})}
 private fun parseShares(): List<Pair<String,Double>> = recipients.text.toString().lines().mapNotNull{line->val x=line.split("=",limit=2);if(x.size!=2)null else x[0].trim().takeIf{it.isNotBlank()}?.let{n->x[1].trim().toDoubleOrNull()?.let{v->n to v}}}.filter{it.second>0}
 private fun issue(){val p=payer.text.toString().trim();val a=amount.text.toString().toDoubleOrNull();val rows=parseShares();val total=rows.sumOf{it.second};if(p.isBlank()||a==null||a<=0||rows.isEmpty()||total<=0||total>a){status.text="Valid payer profile, amount and participant shares are required.";return};val allIds=listOf(p)+rows.map{it.first};if(allIds.any{store.find("profiles",it)==null}){status.text="Every payer/participant must be an existing profile ID.";return};val id="TTMM-${System.currentTimeMillis()}";val cid=otp.issue(id,"TTMM_SHARE","COUNTERPARTIES");val code=store.find("consents",cid)?.optString("otp","")?:"";val input=e("Enter counterparty OTP");AlertDialog.Builder(this).setTitle("Confirm TTMM sharing").setMessage("Payer: $p\nFriends owe: ₹${"%.2f".format(total)}\nPayer share: ₹${"%.2f".format(a-total)}\nDemo OTP: $code").setView(input).setNegativeButton("CANCEL",null).setPositiveButton("CONFIRM"){_,_->if(otp.verify(cid,input.text.toString().trim())){store.add("ttmm_entries",JSONObject().apply{put("id",id);put("payerProfileId",p);put("participantShares",rows.joinToString("|"){it.first+"="+it.second});put("totalAmount",a);put("participantShareTotal",total);put("payerShare",a-total);put("purpose",purpose.text.toString().trim());put("consentId",cid);put("status","REGISTERED");put("settledAmount",0.0);put("createdAt",System.currentTimeMillis());put("updatedAt",System.currentTimeMillis())});V5WorkflowRepository(this@V5TTMMActivity).appendAudit(id,"TTMM_ENTRY_REGISTERED","COUNTERPARTIES","OTP confirmed; participants are profile-linked");status.text="TTMM entry registered. Receivable ₹${"%.2f".format(total)}."}else status.text="Incorrect OTP. Nothing registered."}.show()}
 private fun settleDialog(){val rows=store.all("ttmm_entries").filter{it.optString("status")=="REGISTERED"||it.optString("status")=="PARTIALLY_SETTLED"};if(rows.isEmpty()){status.text="No outstanding TTMM entries.";return};val labels=rows.mapIndexed{i,j->"$i: ${j.optString("id")} • ${j.optString("payerProfileId")} • ₹${"%.2f".format(j.optDouble("participantShareTotal",0.0)-j.optDouble("settledAmount",0.0))}"};val input=e("Entry number");AlertDialog.Builder(this).setTitle("TTMM recovery").setMessage(labels.joinToString("\n")).setView(input).setNegativeButton("CANCEL",null).setPositiveButton("NEXT"){_,_->val idx=input.text.toString().toIntOrNull();if(idx==null||idx !in rows.indices)status.text="Invalid entry number" else confirmSettlement(rows[idx])}.show()}
 private fun confirmSettlement(j:JSONObject){val outstanding=j.optDouble("participantShareTotal",0.0)-j.optDouble("settledAmount",0.0);val amountInput=e("Amount recovered now (₹)");AlertDialog.Builder(this).setTitle("Confirm recovery").setMessage("Outstanding: ₹${"%.2f".format(outstanding)}\nCounterparty OTP required.").setView(amountInput).setNegativeButton("CANCEL",null).setPositiveButton("REQUEST OTP"){_,_->val pay=amountInput.text.toString().toDoubleOrNull();if(pay==null||pay<=0||pay>outstanding){status.text="Invalid recovery amount"}else{val cid=otp.issue(j.optString("id"),"TTMM_RECOVERY","COUNTERPARTY");val code=store.find("consents",cid)?.optString("otp","")?:"";val input=e("Enter counterparty OTP");AlertDialog.Builder(this@V5TTMMActivity).setTitle("OTP confirmation").setMessage("Recovery ₹${"%.2f".format(pay)}\nDemo OTP: $code").setView(input).setNegativeButton("CANCEL",null).setPositiveButton("CONFIRM"){_,_->if(otp.verify(cid,input.text.toString().trim())){val settled=j.optDouble("settledAmount",0.0)+pay;j.put("settledAmount",settled);j.put("status",if(settled+0.005>=j.optDouble("participantShareTotal",0.0))"SETTLED" else "PARTIALLY_SETTLED");j.put("updatedAt",System.currentTimeMillis());store.replace("ttmm_entries",j);V5WorkflowRepository(this@V5TTMMActivity).appendAudit(j.optString("id"),"TTMM_RECOVERY_CONFIRMED","COUNTERPARTY","OTP confirmed recovery ₹$pay");status.text="Recovery confirmed. Remaining ₹${"%.2f".format(j.optDouble("participantShareTotal",0.0)-settled)}."}else status.text="Incorrect OTP. Recovery not recorded."}.show()}}.show()}
 private fun showEntries(){val rows=store.all("ttmm_entries");val text=if(rows.isEmpty())"No TTMM entries yet." else rows.joinToString("\n\n"){j->"${j.optString("id")}\nPayer: ${j.optString("payerProfileId")}\nParticipants: ${j.optString("participantShares")}\nTotal: ₹${j.optDouble("totalAmount",0.0)}\nSettled: ₹${j.optDouble("settledAmount",0.0)}\nStatus: ${j.optString("status")}\n${j.optString("purpose")}"};AlertDialog.Builder(this).setTitle("TTMM Entries").setMessage(text).setPositiveButton("OK",null).show()}
}
