package com.udhaardaar.mvp

import android.app.AlertDialog
import android.content.Intent
import android.graphics.Color
import android.graphics.Typeface
import android.net.Uri
import android.os.Bundle
import android.text.InputType
import android.view.Gravity
import android.view.WindowManager
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import org.json.JSONObject
import java.text.SimpleDateFormat
import java.util.*

/** V6.1 rectification centre. Transaction parties are profile IDs only; names are accepted only at profile creation. */
class V61RectifiedActivity : AppCompatActivity() {
    private val store by lazy { V5LocalStore(this) }
    private val consent by lazy { V5OtpConsentService(this) }
    private val prefs by lazy { getSharedPreferences("udhaardaar_accounts", MODE_PRIVATE) }
    private val navy=Color.rgb(18,48,76); private val teal=Color.rgb(0,145,135); private val blue=Color.rgb(38,99,235)
    private val green=Color.rgb(22,137,75); private val amber=Color.rgb(188,122,18); private val red=Color.rgb(190,65,65)
    private val bg=Color.rgb(247,249,252); private val muted=Color.rgb(92,108,124); private val border=Color.rgb(218,226,235)
    private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt()
    private fun box(fill:Int=Color.WHITE)=android.graphics.drawable.GradientDrawable().apply{setColor(fill);setStroke(dp(1),border);cornerRadius=dp(14).toFloat()}
    private fun tv(s:String,size:Float=14f,color:Int=navy,bold:Boolean=false)=TextView(this).apply{text=s;textSize=size;setTextColor(color);typeface=Typeface.create("sans-serif",if(bold)Typeface.BOLD else Typeface.NORMAL)}
    private fun edit(h:String,multi:Boolean=false)=EditText(this).apply{hint=h;textSize=15f;setTextColor(navy);setHintTextColor(muted);setPadding(dp(14),dp(10),dp(14),dp(10));background=box();setSingleLine(!multi);if(multi){minLines=4;gravity=Gravity.TOP};imeOptions=android.view.inputmethod.EditorInfo.IME_ACTION_NEXT}
    private fun btn(s:String,c:Int=blue,click:()->Unit)=TextView(this).apply{text=s;textSize=14f;setTextColor(Color.WHITE);gravity=Gravity.CENTER;typeface=Typeface.DEFAULT_BOLD;minHeight=dp(52);background=box(c);setOnClickListener{click()}}
    private fun lp(top:Int=8)=LinearLayout.LayoutParams(-1,-2).apply{setMargins(0,dp(top),0,0)}
    private fun add(r:LinearLayout,v:android.view.View,top:Int=8){r.addView(v,lp(top))}
    private fun toast(s:String){Toast.makeText(this,s,Toast.LENGTH_LONG).show()}

    override fun onCreate(b:Bundle?){super.onCreate(b);window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);ensureSelfProfile();render()}
    private fun ensureSelfProfile(){val m=prefs.getString("current_mobile","")?:return;if(m.isBlank())return;val existing=store.all("profiles").firstOrNull{it.optString("mobile")==m};if(existing==null){store.add("profiles",JSONObject().apply{put("id","USR-$m");put("role","USER");put("name",prefs.getString("name_$m","User"));put("mobile",m);put("createdAt",System.currentTimeMillis())})}}
    private fun selfId():String{val m=prefs.getString("current_mobile","")?:"";return store.all("profiles").firstOrNull{it.optString("mobile")==m}?.optString("id").orEmpty()}
    private fun header(r:LinearLayout,title:String){val h=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(dp(12),dp(10),dp(12),dp(10));background=box()};val photo=ImageView(this).apply{setImageResource(R.drawable.udhaardaar_logo);scaleType=ImageView.ScaleType.CENTER_CROP;setPadding(dp(4),dp(4),dp(4),dp(4));setOnClickListener{pickPhoto()}};val m=prefs.getString("current_mobile","")?:"";prefs.getString("photo_$m",null)?.let{runCatching{photo.setImageURI(Uri.parse(it))}};h.addView(photo,LinearLayout.LayoutParams(dp(58),dp(58)));val b=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};b.addView(tv("ARTHSAATHI",13f,teal,true));b.addView(tv(title,21f,navy,true),lp(3));b.addView(tv("V6.1 • secure profile-linked records",10f,muted),lp(3));h.addView(b,LinearLayout.LayoutParams(0,-2,1f).apply{leftMargin=dp(10)});r.addView(h)}
    private fun shell(title:String):LinearLayout{val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(16),dp(12),dp(16),dp(90));setBackgroundColor(bg)};header(r,title);return r}
    private fun render(){if(!prefs.getBoolean("logged_in",false)){startActivity(Intent(this,LoginActivity::class.java));finish();return};val r=shell("V6.1 Rectified Financial Centre");add(r,tv("Identity-first transactions • consented history • keyboard-safe forms",12f,muted),10)
        add(r,btn("1  PROFILE SEARCH & CREATE",blue){profilePicker("Select registered profile"){}},12)
        add(r,btn("2  REGISTER CREDIT / UDHAAR",green){creditFlow()},6)
        add(r,btn("3  REPAYMENT CENTRE",teal){repaymentCentre()},6)
        add(r,btn("4  QR KHATA — DUE DATE + PARTIAL/FULL REPAYMENT",teal){qrKhata()},6)
        add(r,btn("5  ASSET & LIABILITY VAULT",blue){vault()},6)
        add(r,btn("6  INSURANCE & GOVERNMENT BENEFITS",green){insurance()},6)
        add(r,btn("7  DPN / WILL — PREVIEW THEN CONSENT OTP",amber){documents()},6)
        add(r,btn("8  INHERITANCE & CLAIM CENTRE",red){claims()},6)
        add(r,btn("9  LEGAL ASSISTANCE DIRECTORY",red){legal()},6)
        add(r,btn("10 TTMM — GROUP EXPENSES & SETTLEMENT",blue){ttmm()},6)
        add(r,btn("11 AI ADVISOR — AUTHORIZED RECORD REVIEW",teal){advisor()},6)
        add(r,btn("12 SETTINGS / PROFILE PHOTO",Color.rgb(90,105,120)){settings()},6)
        add(r,tv("No QA sample loader is included in production V6.1. Every transaction below requires registered profile IDs; free-text party names are deliberately rejected.",11f,muted),16)
        add(r,btn("LOG OUT",Color.rgb(90,105,120)){prefs.edit().putBoolean("logged_in",false).apply();startActivity(Intent(this,LoginActivity::class.java));finish()},10)
        setContentView(ScrollView(this).apply{isFillViewport=true;addView(r)})}
    private fun pickPhoto(){startActivityForResult(Intent(Intent.ACTION_OPEN_DOCUMENT).apply{type="image/*";addCategory(Intent.CATEGORY_OPENABLE)},4101)}
    override fun onActivityResult(rc:Int,res:Int,data:Intent?){super.onActivityResult(rc,res,data);if(rc==4101&&res==RESULT_OK){val u=data?.data?:return;val m=prefs.getString("current_mobile","")?:"";runCatching{contentResolver.takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION)};prefs.edit().putString("photo_$m",u.toString()).apply();render()}}

    private fun profilePicker(title:String,onSelected:(JSONObject)->Unit){val q=edit("Search name / mobile / PAN / Aadhaar / GSTIN / profile ID");val list=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};val wrap=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(12),dp(4),dp(12),dp(8));addView(q,lp(4));addView(list,lp(8))};val d=AlertDialog.Builder(this).setTitle(title).setView(wrap).setNegativeButton("CANCEL",null).create();fun refresh(){list.removeAllViews();val x=q.text.toString().trim().lowercase(Locale.getDefault());val rows=store.all("profiles").filter{p->x.isEmpty()||listOf("id","name","mobile","pan","aadhaar","gstin").any{p.optString(it).lowercase(Locale.getDefault()).contains(x)}};if(rows.isEmpty()){list.addView(tv("No such user found",15f,red,true));list.addView(tv("Only registered profiles can be used in transactions. Create a new profile instead.",12f,muted));list.addView(btn("CREATE NEW PROFILE",green){d.dismiss();createProfile(onSelected)},lp(8));return};rows.take(12).forEach{p->list.addView(btn("${p.optString("name")}  •  ${p.optString("id")}\n${p.optString("mobile")}",blue){d.dismiss();onSelected(p)},lp(4))}}
        q.addTextChangedListener(object:android.text.TextWatcher{override fun beforeTextChanged(s:CharSequence?,st:Int,c:Int,a:Int){};override fun onTextChanged(s:CharSequence?,st:Int,b:Int,c:Int){refresh()};override fun afterTextChanged(e:android.text.Editable?){}});refresh();d.show()}
    private fun createProfile(onCreated:(JSONObject)->Unit){val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(10),0,dp(10),0)};val n=edit("Full name / business name *");val m=edit("Mobile number *").apply{inputType=InputType.TYPE_CLASS_PHONE};val pan=edit("PAN (optional)");val aad=edit("Aadhaar (optional)");val gst=edit("GSTIN (optional)");listOf(n,m,pan,aad,gst).forEach{r.addView(it,lp(5))};val d=AlertDialog.Builder(this).setTitle("Create registered profile").setView(r).setNegativeButton("CANCEL",null).setPositiveButton("SAVE",null).create();d.setOnShowListener{d.getButton(-1).setOnClickListener{val name=n.text.toString().trim();val mob=m.text.toString().trim();if(name.length<2){n.error="Enter at least 2 characters for the profile name";return@setOnClickListener};if(!V5Validation.mobile(mob)){m.error="Mobile: enter a valid 10-digit Indian mobile number";return@setOnClickListener};if(store.all("profiles").any{it.optString("mobile")==mob}){m.error="Mobile: this number is already registered";return@setOnClickListener};val id="USR-${System.currentTimeMillis()}";val p=JSONObject().apply{put("id",id);put("role","USER");put("name",name);put("mobile",mob);put("pan",pan.text.toString().trim().uppercase());put("aadhaar",aad.text.toString().trim());put("gstin",gst.text.toString().trim().uppercase());put("createdAt",System.currentTimeMillis())};store.add("profiles",p);d.dismiss();onCreated(p)}};d.show()}

    private fun creditFlow(){var lender:JSONObject?=null;var borrower:JSONObject?=null;val choose=AlertDialog.Builder(this).setTitle("Register credit — select registered parties").setMessage("Lender and borrower must be registered profiles. No name-only transaction is permitted.").setNegativeButton("CANCEL",null).setPositiveButton("CONTINUE",null).create();choose.setOnShowListener{choose.getButton(-1).setOnClickListener{choose.dismiss();profilePicker("Select LENDER profile"){lender=it;profilePicker("Select BORROWER profile"){borrower=it;creditTerms(lender!!,borrower!!)}}}};choose.show()}
    private fun creditTerms(l:JSONObject,b:JSONObject){if(l.optString("id")==b.optString("id")){toast("Lender and borrower must be different registered profiles");return};val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(10),0,dp(10),0)};val amount=edit("Principal amount ₹ *").apply{inputType=InputType.TYPE_CLASS_NUMBER or InputType.TYPE_NUMBER_FLAG_DECIMAL};val roi=edit("Interest rate % (0 if none)").apply{inputType=InputType.TYPE_CLASS_NUMBER or InputType.TYPE_NUMBER_FLAG_DECIMAL};val due=edit("First / final due date YYYY-MM-DD *");val method=Spinner(this).apply{adapter=ArrayAdapter(this@V61RectifiedActivity,android.R.layout.simple_spinner_dropdown_item,arrayOf("EMI","Principal + Interest","Bullet / single payment"))};val period=Spinner(this).apply{adapter=ArrayAdapter(this@V61RectifiedActivity,android.R.layout.simple_spinner_dropdown_item,arrayOf("Monthly","Quarterly","Half-yearly","Yearly","One-time"))};val note=edit("Purpose / notes",true);listOf(tv("LENDER: ${l.optString("name")} [${l.optString("id")} ]",13f,green,true),tv("BORROWER: ${b.optString("name")} [${b.optString("id")} ]",13f,blue,true),amount,roi,due,tv("Repayment method",12f,muted,true),method,tv("Periodicity",12f,muted,true),period,note).forEach{r.addView(it,lp(5))};val d=AlertDialog.Builder(this).setTitle("Credit terms").setView(r).setNegativeButton("CANCEL",null).setPositiveButton("REVIEW + CONSENT",null).create();d.setOnShowListener{d.getButton(-1).setOnClickListener{val a=amount.text.toString().toDoubleOrNull();val rr=roi.text.toString().toDoubleOrNull()?:0.0;val date=due.text.toString().trim();if(a==null||a<=0){amount.error="Amount: enter a positive principal amount";return@setOnClickListener};if(rr<0){roi.error="Interest rate: cannot be negative";return@setOnClickListener};if(!date.matches(Regex("\\d{4}-\\d{2}-\\d{2}"))){due.error="Due date: use YYYY-MM-DD";return@setOnClickListener};d.dismiss();consentAndSaveCredit(l,b,a,rr,date,method.selectedItem.toString(),period.selectedItem.toString(),note.text.toString().trim())}};d.show()}
    private fun consentAndSaveCredit(l:JSONObject,b:JSONObject,a:Double,roi:Double,due:String,method:String,period:String,note:String){val id="CR-${System.currentTimeMillis()}";val cid=consent.issue(id,"CREDIT_CONSENT",b.optString("id"));val code=store.find("consents",cid)?.optString("otp","")?:"";val input=edit("Enter counterparty consent OTP");val msg="Credit: ₹${"%.2f".format(a)}\nLender: ${l.optString("name")} [${l.optString("id")}]\nBorrower: ${b.optString("name")} [${b.optString("id")}]\nDue: $due\nMethod: $method • $period\n\nDemo OTP: $code";val d=AlertDialog.Builder(this).setTitle("Consent required before registration").setMessage(msg).setView(input).setNegativeButton("CANCEL",null).setPositiveButton("CONFIRM",null).create();d.setOnShowListener{d.getButton(-1).setOnClickListener{if(!consent.verify(cid,input.text.toString())){input.error="Consent OTP: incorrect code";return@setOnClickListener};store.add("credits",JSONObject().apply{put("id",id);put("lenderId",l.optString("id"));put("borrowerId",b.optString("id"));put("direction","Credit Given");put("principal",a);put("interestRate",roi);put("repaymentMethod",method);put("periodicity",period);put("dueDate",due);put("outstanding",a);put("status","ACTIVE");put("notes",note);put("consentId",cid);put("createdAt",System.currentTimeMillis())});store.add("audit",JSONObject().apply{put("id","AUD-${System.currentTimeMillis()}");put("entityId",id);put("event","V61_CREDIT_REGISTERED_WITH_CONSENT");put("at",System.currentTimeMillis())});d.dismiss();toast("Credit registered successfully: $id")}};d.show()}

    private fun repaymentCentre(){val self=selfId();val rows=store.all("credits").filter{it.optString("lenderId")==self||it.optString("borrowerId")==self};if(rows.isEmpty()){toast("No credit accounts are linked to your registered profile");return};val list=rows.map{"${it.optString("id")} • ${it.optString("repaymentMethod")} • due ${it.optString("dueDate")} • outstanding ₹${"%.2f".format(it.optDouble("outstanding",0.0))}"}.toTypedArray();AlertDialog.Builder(this).setTitle("Credit Given / Credit Received — your related accounts").setItems(list){_,which->recordRepayment(rows[which])}.setNegativeButton("CANCEL",null).show()}
    private fun recordRepayment(c:JSONObject){val max=c.optDouble("outstanding",0.0);if(max<=0){toast("This account is already fully repaid");return};val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(10),0,dp(10),0)};val amt=edit("Repayment amount ₹ (max ${"%.2f".format(max)})").apply{inputType=InputType.TYPE_CLASS_NUMBER or InputType.TYPE_NUMBER_FLAG_DECIMAL};val due=edit("Due EMI / due date YYYY-MM-DD");val note=edit("Repayment note");r.addView(amt,lp(5));r.addView(due,lp(5));r.addView(note,lp(5));val d=AlertDialog.Builder(this).setTitle("Record repayment with counterparty consent").setView(r).setNegativeButton("CANCEL",null).setPositiveButton("GET CONSENT OTP",null).create();d.setOnShowListener{d.getButton(-1).setOnClickListener{val x=amt.text.toString().toDoubleOrNull();if(x==null||x<=0||x>max){amt.error="Repayment amount: enter a value from 0.01 to ${"%.2f".format(max)}";return@setOnClickListener};val other=if(c.optString("lenderId")==selfId())c.optString("borrowerId") else c.optString("lenderId");val cid=consent.issue(c.optString("id"),"REPAYMENT_CONSENT",other);val code=store.find("consents",cid)?.optString("otp","")?:"";val otp=edit("Consent OTP");val od=AlertDialog.Builder(this@V61RectifiedActivity).setTitle("Counterparty consent").setMessage("Demo OTP: $code").setView(otp).setNegativeButton("CANCEL",null).setPositiveButton("CONFIRM",null).create();od.setOnShowListener{od.getButton(-1).setOnClickListener{if(!consent.verify(cid,otp.text.toString())){otp.error="Incorrect consent OTP";return@setOnClickListener};val newOut=(max-x).coerceAtLeast(0.0);c.put("outstanding",newOut);if(newOut==0.0)c.put("status","CLOSED");store.replace("credits",c);store.add("repayments",JSONObject().apply{put("id","RP-${System.currentTimeMillis()}");put("creditId",c.optString("id"));put("amount",x);put("dueDate",due.text.toString().trim());put("note",note.text.toString().trim());put("consentId",cid);put("createdAt",System.currentTimeMillis())});od.dismiss();d.dismiss();toast("Repayment recorded. Outstanding: ₹${"%.2f".format(newOut)}")}};od.show()}};d.show()}

    private fun qrKhata(){val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(10),0,dp(10),0)};val merchant=edit("Merchant profile — SELECT registered user");val customer=edit("Customer profile — SELECT registered user");val amount=edit("Credit amount ₹ *").apply{inputType=InputType.TYPE_CLASS_NUMBER or InputType.TYPE_NUMBER_FLAG_DECIMAL};val due=edit("Due date YYYY-MM-DD *");val note=edit("Invoice / item / notes",true);val selected= arrayOfNulls<JSONObject>(2);val mbtn=btn("SELECT MERCHANT",teal){profilePicker("Select merchant"){selected[0]=it;merchant.setText("${it.optString("name")} [${it.optString("id")}]")}};val cbtn=btn("SELECT CUSTOMER",teal){profilePicker("Select customer"){selected[1]=it;customer.setText("${it.optString("name")} [${it.optString("id")}]")}};listOf(mbtn,cbtn,merchant,customer,amount,due,note).forEach{r.addView(it,lp(5))};val d=AlertDialog.Builder(this).setTitle("QR Khata — profile-linked ledger").setView(r).setNegativeButton("CANCEL",null).setPositiveButton("SAVE KHATA",null).create();d.setOnShowListener{d.getButton(-1).setOnClickListener{val x=amount.text.toString().toDoubleOrNull();if(selected[0]==null||selected[1]==null){toast("Select both merchant and customer from registered profiles");return@setOnClickListener};if(x==null||x<=0){amount.error="Credit amount: enter a positive amount";return@setOnClickListener};if(!due.text.toString().trim().matches(Regex("\\d{4}-\\d{2}-\\d{2}"))){due.error="Due date: use YYYY-MM-DD";return@setOnClickListener};val id="QK-${System.currentTimeMillis()}";store.add("qr_khata",JSONObject().apply{put("id",id);put("merchantId",selected[0]!!.optString("id"));put("customerId",selected[1]!!.optString("id"));put("amount",x);put("outstanding",x);put("dueDate",due.text.toString().trim());put("note",note.text.toString().trim());put("status","OPEN");put("createdAt",System.currentTimeMillis())});d.dismiss();toast("QR Khata saved: $id")}};d.show()}

    private fun vault(){val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(10),0,dp(10),0)};val type=Spinner(this).apply{adapter=ArrayAdapter(this@V61RectifiedActivity,android.R.layout.simple_spinner_dropdown_item,arrayOf("Bank Account","FD","Mutual Fund","Shares","Property","Gold","Insurance","Loan Liability","Other Asset"))};val title=edit("Asset / liability title *");val value=edit("Current value / outstanding ₹ *").apply{inputType=InputType.TYPE_CLASS_NUMBER or InputType.TYPE_NUMBER_FLAG_DECIMAL};val account=edit("Account / reference (non-sensitive)");val owner=edit("Owner profile — SELECT registered profile");var ownerP:JSONObject?=null;val ob=btn("SELECT OWNER PROFILE",teal){profilePicker("Select asset owner"){ownerP=it;owner.setText("${it.optString("name")} [${it.optString("id")}]")}};listOf(ob,owner,type,title,value,account).forEach{r.addView(it,lp(5))};val d=AlertDialog.Builder(this).setTitle("Asset & Liability Vault").setView(r).setNegativeButton("CANCEL",null).setPositiveButton("SAVE",null).create();d.setOnShowListener{d.getButton(-1).setOnClickListener{val v=value.text.toString().toDoubleOrNull();if(ownerP==null){toast("Select a registered owner profile");return@setOnClickListener};if(title.text.toString().trim().isBlank()){title.error="Title: enter an asset/liability title";return@setOnClickListener};if(v==null||v<0){value.error="Value: enter zero or a positive amount";return@setOnClickListener};store.add("assets",JSONObject().apply{put("id","AST-${System.currentTimeMillis()}");put("ownerProfileId",ownerP!!.optString("id"));put("category",type.selectedItem.toString());put("title",title.text.toString().trim());put("estimatedValue",v);put("reference",account.text.toString().trim());put("createdAt",System.currentTimeMillis())});d.dismiss();toast("Vault record saved")}};d.show()}

    private fun insurance(){val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(10),0,dp(10),0)};var insurer:JSONObject?=null;var insured:JSONObject?=null;val i1=edit("Insurer — registered profile");val i2=edit("Insured — registered profile");val policy=edit("Policy number *");val sum=edit("Sum insured ₹ *").apply{inputType=InputType.TYPE_CLASS_NUMBER or InputType.TYPE_NUMBER_FLAG_DECIMAL};val prem=edit("Premium amount ₹ *").apply{inputType=InputType.TYPE_CLASS_NUMBER or InputType.TYPE_NUMBER_FLAG_DECIMAL};val due=edit("Next premium due YYYY-MM-DD *");val debit=edit("Debit account / bank reference");val term=Spinner(this).apply{adapter=ArrayAdapter(this@V61RectifiedActivity,android.R.layout.simple_spinner_dropdown_item,arrayOf("Monthly","Quarterly","Half-yearly","Yearly","Single premium"))};val b1=btn("SELECT INSURER",teal){profilePicker("Select insurer"){insurer=it;i1.setText("${it.optString("name")} [${it.optString("id")}]")}};val b2=btn("SELECT INSURED",teal){profilePicker("Select insured"){insured=it;i2.setText("${it.optString("name")} [${it.optString("id")}]")}};listOf(b1,i1,b2,i2,policy,sum,prem,due,tv("Premium payment terms",12f,muted,true),term,debit).forEach{r.addView(it,lp(5))};val d=AlertDialog.Builder(this).setTitle("Insurance & Benefits — full policy timeline").setView(r).setNegativeButton("CANCEL",null).setPositiveButton("SAVE POLICY",null).create();d.setOnShowListener{d.getButton(-1).setOnClickListener{val s=sum.text.toString().toDoubleOrNull();val p=prem.text.toString().toDoubleOrNull();if(insurer==null||insured==null){toast("Select insurer and insured from registered profiles");return@setOnClickListener};if(policy.text.toString().trim().isBlank()){policy.error="Policy number: required";return@setOnClickListener};if(s==null||s<=0){sum.error="Sum insured: enter a positive amount";return@setOnClickListener};if(p==null||p<0){prem.error="Premium: enter zero or a positive amount";return@setOnClickListener};if(!due.text.toString().trim().matches(Regex("\\d{4}-\\d{2}-\\d{2}"))){due.error="Due date: use YYYY-MM-DD";return@setOnClickListener};val id="INS-${System.currentTimeMillis()}";store.add("insurance",JSONObject().apply{put("id",id);put("insurerProfileId",insurer!!.optString("id"));put("insuredProfileId",insured!!.optString("id"));put("policyNumber",policy.text.toString().trim());put("sumInsured",s);put("premium",p);put("premiumTerms",term.selectedItem.toString());put("nextDueDate",due.text.toString().trim());put("debitAccount",debit.text.toString().trim());put("timeline","Policy start → premium due cycle → renewal/expiry → claim/settlement");put("status","ACTIVE");put("createdAt",System.currentTimeMillis())});d.dismiss();toast("Policy saved with premium timeline")}};d.show()}

    private fun documents(){val type=Spinner(this).apply{adapter=ArrayAdapter(this@V61RectifiedActivity,android.R.layout.simple_spinner_dropdown_item,arrayOf("DPN — Demand Promissory Note","Will — Last Will & Testament"))};val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(10),0,dp(10),0)};val maker=edit("Maker / testator — registered profile");val other=edit("Payee / beneficiary — registered profile");val amount=edit("Amount ₹ (DPN only)").apply{inputType=InputType.TYPE_CLASS_NUMBER or InputType.TYPE_NUMBER_FLAG_DECIMAL};val asset=edit("Asset IDs / bequest instructions (Will)",true);var mp:JSONObject?=null;var op:JSONObject?=null;val bm=btn("SELECT MAKER / TESTATOR",teal){profilePicker("Select maker/testator"){mp=it;maker.setText("${it.optString("name")} [${it.optString("id")}]")}};val bo=btn("SELECT PAYEE / BENEFICIARY",teal){profilePicker("Select payee/beneficiary"){op=it;other.setText("${it.optString("name")} [${it.optString("id")}]")}};listOf(type,bm,maker,bo,other,amount,asset).forEach{r.addView(it,lp(5))};val d=AlertDialog.Builder(this).setTitle("Professional draft — preview before consent").setView(r).setNegativeButton("CANCEL",null).setPositiveButton("PREPARE DRAFT",null).create();d.setOnShowListener{d.getButton(-1).setOnClickListener{if(mp==null||op==null){toast("Select both parties from registered profiles");return@setOnClickListener};val isDpn=type.selectedItemPosition==0;val a=amount.text.toString().toDoubleOrNull()?:0.0;if(isDpn&&a<=0){amount.error="DPN amount: enter a positive amount";return@setOnClickListener};val title=if(isDpn)"DEMAND PROMISSORY NOTE" else "LAST WILL & TESTAMENT";val draft=if(isDpn)"DEMAND PROMISSORY NOTE\\n\\nMaker: ${mp!!.optString("name")} [${mp!!.optString("id")}]\\nPayee: ${op!!.optString("name")} [${op!!.optString("id")}]\\nPrincipal: ₹${"%.2f".format(a)}\\nDate: ${SimpleDateFormat("dd-MM-yyyy",Locale.US).format(Date())}\\n\\nThe maker acknowledges the demand obligation subject to the executed legal instrument." else "LAST WILL & TESTAMENT — DRAFT\\n\\nTestator: ${mp!!.optString("name")} [${mp!!.optString("id")}]\\nBeneficiary: ${op!!.optString("name")} [${op!!.optString("id")}]\\nBequests / asset instructions:\\n${asset.text}\\n\\nThis is a draft for review. Execution, witnesses and applicable legal requirements remain necessary.";d.dismiss();previewConsent(title,draft,mp!!.optString("id"),if(isDpn)"DPN" else "WILL")}};d.show()}
    private fun previewConsent(title:String,draft:String,subject:String,kind:String){val cid=consent.issue("${kind}-${System.currentTimeMillis()}","$kind-EXECUTION-CONSENT",subject);val code=store.find("consents",cid)?.optString("otp","")?:"";val input=edit("Consent OTP");AlertDialog.Builder(this).setTitle(title+" — FINAL PREVIEW").setMessage(draft+"\n\nDemo OTP: $code").setView(input).setNegativeButton("CANCEL",null).setPositiveButton("CONSENT + SAVE",null).create().also{d->d.setOnShowListener{d.getButton(-1).setOnClickListener{if(!consent.verify(cid,input.text.toString())){input.error="Incorrect OTP";return@setOnClickListener};store.add(if(kind=="DPN")"dpn" else "wills",JSONObject().apply{put("id","$kind-${System.currentTimeMillis()}");put("draft",draft);put("consentId",cid);put("status","CONSENTED_DRAFT");put("createdAt",System.currentTimeMillis())});d.dismiss();toast("$title saved after consent")}};d.show()}}

    private fun claims(){val self=selfId();val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(10),0,dp(10),0)};val claimant=edit("Claimant — registered profile");var cp:JSONObject?=null;val asset=edit("Asset / policy / credit ID *");val notes=edit("Claim details",true);val b=btn("SELECT CLAIMANT",teal){profilePicker("Select claimant"){cp=it;claimant.setText("${it.optString("name")} [${it.optString("id")}]")}};r.addView(b,lp(5));r.addView(claimant,lp(5));r.addView(asset,lp(5));r.addView(notes,lp(5));val d=AlertDialog.Builder(this).setTitle("Inheritance & Claim Centre").setView(r).setNegativeButton("CANCEL",null).setPositiveButton("REGISTER CLAIM",null).create();d.setOnShowListener{d.getButton(-1).setOnClickListener{if(cp==null){toast("Select a registered claimant profile");return@setOnClickListener};if(asset.text.toString().trim().isBlank()){asset.error="Claim reference: required";return@setOnClickListener};store.add("death_claim_cases",JSONObject().apply{put("id","CLM-${System.currentTimeMillis()}");put("claimantProfileId",cp!!.optString("id"));put("ownerProfileId",self);put("referenceId",asset.text.toString().trim());put("notes",notes.text.toString().trim());put("status","OPEN");put("createdAt",System.currentTimeMillis())});d.dismiss();toast("Claim registered and linked to inheritance centre")}};d.show()}

    private fun legal(){val rows=store.all("lawyers");val text=if(rows.isEmpty())"No lawyer records are available yet. A directory administrator must add and verify local professionals before they are shown as verified." else rows.joinToString("\n\n"){j->"${j.optString("name")}\\n${j.optString("address")}\\n${j.optString("domain")} • ${j.optString("expertise")}\\nExperience: ${j.optString("experience","Not supplied")}\\nContact: ${j.optString("phone")}\\nStatus: ${j.optString("verification","PENDING_VERIFICATION")}"};AlertDialog.Builder(this).setTitle("Legal Assistance — lawyer directory").setMessage(text).setPositiveButton("OK",null).setNeutralButton("ADD PROFESSIONAL"){_,_->addLawyer()}.show()}
    private fun addLawyer(){val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(10),0,dp(10),0)};val n=edit("Lawyer name *");val addr=edit("Office address",true);val domain=edit("Domain / expertise");val exp=edit("Experience / years");val phone=edit("Contact number *");listOf(n,addr,domain,exp,phone).forEach{r.addView(it,lp(5))};AlertDialog.Builder(this).setTitle("Add lawyer — pending verification").setView(r).setNegativeButton("CANCEL",null).setPositiveButton("SAVE"){_,_->val nn=n.text.toString().trim();val pp=phone.text.toString().trim();if(nn.isNotBlank()&&pp.isNotBlank())store.add("lawyers",JSONObject().apply{put("id","LAW-${System.currentTimeMillis()}");put("name",nn);put("address",addr.text.toString().trim());put("domain",domain.text.toString().trim());put("expertise",domain.text.toString().trim());put("experience",exp.text.toString().trim());put("phone",pp);put("verification","PENDING_VERIFICATION");put("createdAt",System.currentTimeMillis())})}.show()}

    private fun ttmm(){val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(10),0,dp(10),0)};val group=edit("Event / group name *");val members=edit("Registered member profile IDs (comma separated) *",true);val bill=edit("Total bill ₹ *").apply{inputType=InputType.TYPE_CLASS_NUMBER or InputType.TYPE_NUMBER_FLAG_DECIMAL};val pay=edit("Payment entries: profileId=amount, one per line",true);listOf(group,members,bill,pay).forEach{r.addView(it,lp(5))};val d=AlertDialog.Builder(this).setTitle("TTMM — WhatsApp-like event group").setView(r).setNegativeButton("CANCEL",null).setPositiveButton("CREATE / CALCULATE",null).create();d.setOnShowListener{d.getButton(-1).setOnClickListener{val ids=members.text.toString().split(",","\\n").map{it.trim()}.filter{it.isNotBlank()};val registered=store.all("profiles").map{it.optString("id")}.toSet();if(ids.isEmpty()||ids.any{it !in registered}){members.error="Members: every ID must belong to a registered profile";return@setOnShowListener};val total=bill.text.toString().toDoubleOrNull();if(total==null||total<0){bill.error="Total bill: enter zero or a positive amount";return@setOnShowListener};val id="TT-${System.currentTimeMillis()}";store.add("ttmm_groups",JSONObject().apply{put("id",id);put("name",group.text.toString().trim());put("memberIds",ids.joinToString(","));put("totalBill",total);put("payments",pay.text.toString().trim());put("status","OPEN");put("createdAt",System.currentTimeMillis())});d.dismiss();ttmmSummary(id,ids,total,pay.text.toString())}};d.show()}
    private fun ttmmSummary(id:String,ids:List<String>,total:Double,payments:String){val paid=mutableMapOf<String,Double>();payments.lines().forEach{val x=it.split("=");if(x.size==2)paid[x[0].trim()]=x[1].trim().toDoubleOrNull()?:0.0};val share=if(ids.isEmpty())0.0 else total/ids.size;val text=ids.joinToString("\n"){p->"$p • share ₹${"%.2f".format(share)} • paid ₹${"%.2f".format(paid[p]?:0.0)} • balance ₹${"%.2f".format((share-(paid[p]?:0.0)).coerceAtLeast(0.0))}"};AlertDialog.Builder(this).setTitle("TTMM allocation").setMessage("Group: $id\n\n$text\n\nMembers with a positive balance are borrowers for their share. Record settlement through consent OTP.").setPositiveButton("OK",null).setNeutralButton("CONSENT GROUP CREDIT"){_,_->groupConsent(id,ids)}.show()}
    private fun groupConsent(groupId:String,ids:List<String>){if(ids.isEmpty()){toast("No members");return};fun next(i:Int){if(i>=ids.size){store.find("ttmm_groups",groupId)?.let{it.put("consentStatus","ALL_MEMBERS_CONSENTED");store.replace("ttmm_groups",it)};toast("All member consents captured for $groupId");return};val cid=consent.issue(groupId,"TTMM_MEMBER_CONSENT",ids[i]);val code=store.find("consents",cid)?.optString("otp","")?:"";val inp=edit("Member ${i+1}/${ids.size} OTP");val d=AlertDialog.Builder(this).setTitle("TTMM member consent").setMessage("Profile: ${ids[i]}\nDemo OTP: $code").setView(inp).setNegativeButton("CANCEL",null).setPositiveButton("VERIFY",null).create();d.setOnShowListener{d.getButton(-1).setOnClickListener{if(consent.verify(cid,inp.text.toString())){d.dismiss();next(i+1)}else inp.error="Incorrect OTP"}};d.show()};next(0)}

    private fun advisor(){val self=selfId();val assets=store.all("assets").filter{it.optString("ownerProfileId")==self};val credits=store.all("credits").filter{it.optString("lenderId")==self||it.optString("borrowerId")==self};val insurance=store.all("insurance").filter{it.optString("insuredProfileId")==self};val out=credits.sumOf{it.optDouble("outstanding",0.0)};val assetValue=assets.sumOf{it.optDouble("estimatedValue",0.0)};val lines=mutableListOf<String>();if(assetValue>0)lines.add("Authorized assets total ₹${"%.2f".format(assetValue)}. Review liquidity, diversification and nominee coverage before deploying surplus.");if(out>0)lines.add("Related credit exposure is ₹${"%.2f".format(out)}. Review due dates and avoid committing cash needed for repayments.");if(insurance.isEmpty())lines.add("No insured policies are linked to this profile. Review appropriate protection needs.") else lines.add("${insurance.size} linked insurance/benefit record(s) found; check premium due dates and sum insured.");if(lines.isEmpty())lines.add("Add profile-linked assets, credit and protection records to enable explainable advice.");AlertDialog.Builder(this).setTitle("AI Advisor — authorized data only").setMessage(lines.joinToString("\n\n")+"\n\nThis is a rule-based decision aid, not guaranteed investment advice. No money is moved automatically.").setPositiveButton("OK",null).show()}

    private fun settings(){val m=prefs.getString("current_mobile","")?:"";val name=prefs.getString("name_$m","User")?:"User";AlertDialog.Builder(this).setTitle("Settings").setMessage("Profile: $name\nMobile: $m\nSession persistence: enabled\nProfile photo: ${if(prefs.contains("photo_$m"))"set" else "not set"}\nProduction OTP/SMS gateway: required for live delivery.").setPositiveButton("CHANGE PHOTO"){_,_->pickPhoto()}.setNegativeButton("CLOSE",null).show()}
}
