package com.udhaardaar.mvp

import android.app.AlertDialog
import android.content.Intent
import android.graphics.Color
import android.net.Uri
import android.os.Bundle
import android.view.WindowManager
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import org.json.JSONObject

/** V6.1.1 rectification centre: registered profile IDs only, consent-gated transactions and mobile-safe UI. */
class V61RectifiedActivity : AppCompatActivity() {
    private val store by lazy { V5LocalStore(this) }
    private val consent by lazy { V5OtpConsentService(this) }
    private val prefs by lazy { getSharedPreferences("udhaardaar_accounts", MODE_PRIVATE) }
    private fun dp(v:Int)= (v*resources.displayMetrics.density).toInt()
    private fun edit(h:String)=EditText(this).apply{hint=h;setPadding(dp(12),dp(8),dp(12),dp(8));setSingleLine(true)}
    private fun btn(s:String, action:()->Unit)=Button(this).apply{text=s;setOnClickListener{action()}}
    private fun add(r:LinearLayout,v:android.view.View){r.addView(v,LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(6)})}
    private fun toast(s:String)=Toast.makeText(this,s,Toast.LENGTH_LONG).show()

    override fun onCreate(b:Bundle?){super.onCreate(b);window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);ensureSelfProfile();render()}
    private fun ensureSelfProfile(){val m=prefs.getString("current_mobile","") ?: return;if(m.isBlank())return;if(store.all("profiles").none{it.optString("mobile")==m})store.add("profiles",JSONObject().apply{put("id","USR-$m");put("name",prefs.getString("name_$m","User"));put("mobile",m)})}
    private fun selfId():String{val m=prefs.getString("current_mobile","") ?: "";return store.all("profiles").firstOrNull{it.optString("mobile")==m}?.optString("id").orEmpty()}
    private fun render(){if(!prefs.getBoolean("logged_in",false)){startActivity(Intent(this,LoginActivity::class.java));finish();return};val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(16),dp(16),dp(16),dp(80)};add(r,TextView(this).apply{text="ARTHSAATHI • V6.1.1\nProfile-linked financial centre";textSize=22f;setTextColor(Color.rgb(18,48,76));setPadding(0,0,0,dp(8))});add(r,TextView(this).apply{text="Registered profile IDs only • consent OTP • keyboard-safe scrolling";textSize=12f});add(r,btn("PROFILE SEARCH / CREATE"){profilePicker()});add(r,btn("REGISTER CREDIT / UDHAAR"){creditFlow()});add(r,btn("REPAYMENT CENTRE — CREDIT GIVEN / RECEIVED"){repaymentCentre()});add(r,btn("QR KHATA — DUE DATE / PARTIAL / FULL REPAYMENT"){qrKhata()});add(r,btn("ASSET & LIABILITY VAULT"){vault()});add(r,btn("INSURANCE & GOVERNMENT BENEFITS"){insurance()});add(r,btn("DPN / WILL — PREVIEW THEN CONSENT OTP"){documents()});add(r,btn("INHERITANCE & CLAIM CENTRE"){claims()});add(r,btn("LEGAL ASSISTANCE DIRECTORY"){legal()});add(r,btn("TTMM — GROUP EXPENSES / SETTLEMENT"){ttmm()});add(r,btn("AI ADVISOR — AUTHORIZED DATA ONLY"){advisor()});add(r,btn("SETTINGS / PROFILE PHOTO"){settings()});add(r,TextView(this).apply{text="No QA sample loader. No free-text parties in transactions. Profile names are accepted only when creating a profile.";textSize=11f});add(r,btn("LOG OUT"){prefs.edit().putBoolean("logged_in",false).apply();startActivity(Intent(this,LoginActivity::class.java));finish()});setContentView(ScrollView(this).apply{isFillViewport=true;addView(r)})}

    private fun profilePicker(){val q=edit("Search name / mobile / PAN / Aadhaar / GSTIN / profile ID");val list=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};val wrap=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;addView(q);addView(list)};val d=AlertDialog.Builder(this).setTitle("Registered profile search").setView(wrap).setNegativeButton("CANCEL",null).create();fun refresh(){list.removeAllViews();val x=q.text.toString().trim().lowercase();val rows=store.all("profiles").filter{p->x.isEmpty()||listOf("id","name","mobile","pan","aadhaar","gstin").any{p.optString(it).lowercase().contains(x)}};if(rows.isEmpty()){list.addView(TextView(this).apply{text="No such user found";setTextColor(Color.RED)});list.addView(btn("CREATE NEW PROFILE"){d.dismiss();createProfile()})}else rows.take(12).forEach{p->list.addView(btn("${p.optString("name")} • ${p.optString("id")}\n${p.optString("mobile")}"){d.dismiss();profileHistory(p)})}};q.addTextChangedListener(object:android.text.TextWatcher{override fun beforeTextChanged(s:CharSequence?,a:Int,c:Int,d:Int){};override fun onTextChanged(s:CharSequence?,a:Int,b:Int,c:Int){refresh()};override fun afterTextChanged(e:android.text.Editable?){}});refresh();d.show()}
    private fun createProfile(){val n=edit("Full name / business name *");val m=edit("Mobile number *");val pan=edit("PAN (optional)");val aad=edit("Aadhaar (optional)");val gst=edit("GSTIN (optional)");val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;listOf(n,m,pan,aad,gst).forEach{add(this,it)}};val d=AlertDialog.Builder(this).setTitle("Create registered profile").setView(box).setNegativeButton("CANCEL",null).setPositiveButton("SAVE",null).create();d.setOnShowListener{d.getButton(-1).setOnClickListener{val name=n.text.toString().trim();val mob=m.text.toString().trim();when{ name.length<2->{n.error="Name: enter at least 2 characters"};!V5Validation.mobile(mob)->{m.error="Mobile: enter a valid 10-digit Indian mobile number"};store.all("profiles").any{it.optString("mobile")==mob}->{m.error="Mobile: already registered"};else->{store.add("profiles",JSONObject().apply{put("id","USR-${System.currentTimeMillis()}");put("name",name);put("mobile",mob);put("pan",pan.text.toString().trim().uppercase());put("aadhaar",aad.text.toString().trim());put("gstin",gst.text.toString().trim().uppercase())});d.dismiss();toast("Profile created. You can now select it in the transaction flow.")}}}};d.show()}
    private fun profileHistory(p:JSONObject){val id=p.optString("id");val credits=store.all("credits").filter{it.optString("lenderId")==id||it.optString("borrowerId")==id};val outstanding=credits.sumOf{it.optDouble("outstanding",0.0)};AlertDialog.Builder(this).setTitle("Profile: ${p.optString("name")}").setMessage("Profile ID: $id\nMobile: ${p.optString("mobile")}\nRelated credit accounts: ${credits.size}\nOutstanding: ₹${"%.2f".format(outstanding)}\nUdhaardaar score: consent-based history score available after verified transactions.").setPositiveButton("OK",null).show()}

    private fun creditFlow(){var lender:JSONObject?=null;var borrower:JSONObject?=null;val d=AlertDialog.Builder(this).setTitle("Register credit").setMessage("Select registered lender and borrower profiles. Name-only transactions are prohibited.").setNegativeButton("CANCEL",null).setPositiveButton("SELECT",null).create();d.setOnShowListener{d.getButton(-1).setOnClickListener{d.dismiss();selectParty("Select LENDER"){lender=it;selectParty("Select BORROWER"){borrower=it;creditTerms(lender!!,borrower!!)}}}};d.show()}
    private fun selectParty(title:String,done:(JSONObject)->Unit){val q=edit("Live search registered profile");val list=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};val wrap=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;addView(q);addView(list)};val d=AlertDialog.Builder(this).setTitle(title).setView(wrap).setNegativeButton("CANCEL",null).create();fun refresh(){list.removeAllViews();val x=q.text.toString().trim().lowercase();val rows=store.all("profiles").filter{p->x.isEmpty()||p.toString().lowercase().contains(x)};if(rows.isEmpty()){list.addView(TextView(this).apply{text="No such user found";setTextColor(Color.RED)});list.addView(btn("CREATE NEW PROFILE"){d.dismiss();createProfile()})}else rows.forEach{p->list.addView(btn("${p.optString("name")} • ${p.optString("id")}"){d.dismiss();done(p)})}};q.addTextChangedListener(object:android.text.TextWatcher{override fun beforeTextChanged(s:CharSequence?,a:Int,c:Int,e:Int){};override fun onTextChanged(s:CharSequence?,a:Int,b:Int,c:Int){refresh()};override fun afterTextChanged(e:android.text.Editable?){}});refresh();d.show()}
    private fun creditTerms(l:JSONObject,b:JSONObject){if(l.optString("id")==b.optString("id")){toast("Lender and borrower must be different profiles");return};val amount=edit("Principal amount ₹ *");val roi=edit("Interest rate %");val due=edit("Due date YYYY-MM-DD *");val method=Spinner(this).apply{adapter=ArrayAdapter(this@V61RectifiedActivity,android.R.layout.simple_spinner_dropdown_item,arrayOf("EMI","Principal + Interest","Bullet / single payment"))};val period=Spinner(this).apply{adapter=ArrayAdapter(this@V61RectifiedActivity,android.R.layout.simple_spinner_dropdown_item,arrayOf("Monthly","Quarterly","Half-yearly","Yearly","One-time"))};val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;listOf(TextView(this@V61RectifiedActivity).apply{text="LENDER: ${l.optString("name")} [${l.optString("id")}]"},TextView(this@V61RectifiedActivity).apply{text="BORROWER: ${b.optString("name")} [${b.optString("id")}]"},amount,roi,due,method,period).forEach{add(this,it)}};val d=AlertDialog.Builder(this).setTitle("Credit terms").setView(box).setNegativeButton("CANCEL",null).setPositiveButton("REVIEW + CONSENT",null).create();d.setOnShowListener{d.getButton(-1).setOnClickListener{val a=amount.text.toString().toDoubleOrNull();val rr=roi.text.toString().toDoubleOrNull()?:0.0;val date=due.text.toString().trim();if(a==null||a<=0)amount.error="Amount: enter a positive amount" else if(rr<0)roi.error="Interest: cannot be negative" else if(!date.matches(Regex("\\d{4}-\\d{2}-\\d{2}")))due.error="Due date: use YYYY-MM-DD" else{d.dismiss();saveCredit(l,b,a,rr,date,method.selectedItem.toString(),period.selectedItem.toString())}}};d.show()}
    private fun saveCredit(l:JSONObject,b:JSONObject,a:Double,roi:Double,due:String,method:String,period:String){val id="CR-${System.currentTimeMillis()}";val cid=consent.issue(id,"CREDIT_CONSENT",b.optString("id"));val code=store.find("consents",cid)?.optString("otp","")?:"";val input=edit("Counterparty consent OTP");val d=AlertDialog.Builder(this).setTitle("Consent required").setMessage("Credit ₹${"%.2f".format(a)}\nDemo OTP: $code").setView(input).setNegativeButton("CANCEL",null).setPositiveButton("CONFIRM",null).create();d.setOnShowListener{d.getButton(-1).setOnClickListener{if(consent.verify(cid,input.text.toString())){store.add("credits",JSONObject().apply{put("id",id);put("lenderId",l.optString("id"));put("borrowerId",b.optString("id"));put("principal",a);put("interestRate",roi);put("dueDate",due);put("repaymentMethod",method);put("periodicity",period);put("outstanding",a);put("status","ACTIVE");put("consentId",cid)});d.dismiss();toast("Credit registered: $id")}else input.error="OTP: incorrect consent code"}};d.show()}

    private fun repaymentCentre(){val self=selfId();val rows=store.all("credits").filter{it.optString("lenderId")==self||it.optString("borrowerId")==self};if(rows.isEmpty()){toast("No related credit accounts");return};val names=rows.map{"${it.optString("id")} • due ${it.optString("dueDate")} • outstanding ₹${it.optDouble("outstanding",0.0)}"}.toTypedArray();AlertDialog.Builder(this).setTitle("Credit Given / Credit Received").setItems(names){_,i->recordRepayment(rows[i])}.show()}
    private fun recordRepayment(c:JSONObject){val max=c.optDouble("outstanding",0.0);if(max<=0){toast("Already fully repaid");return};val amt=edit("Repayment amount ₹ (max $max)");val due=edit("Due EMI / due date YYYY-MM-DD");val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;add(this,amt);add(this,due)};val d=AlertDialog.Builder(this).setTitle("Record repayment").setView(box).setNegativeButton("CANCEL",null).setPositiveButton("REQUEST CONSENT",null).create();d.setOnShowListener{d.getButton(-1).setOnClickListener{val a=amt.text.toString().toDoubleOrNull();if(a==null||a<=0||a>max)amt.error="Repayment: enter an amount between 0 and $max" else{val other=if(c.optString("lenderId")==selfId())c.optString("borrowerId") else c.optString("lenderId");val cid=consent.issue(c.optString("id"),"REPAYMENT_CONSENT",other);val code=store.find("consents",cid)?.optString("otp","")?:"";val otp=edit("Consent OTP");AlertDialog.Builder(this).setTitle("Repayment consent").setMessage("Demo OTP: $code").setView(otp).setNegativeButton("CANCEL",null).setPositiveButton("VERIFY"){_,_->if(consent.verify(cid,otp.text.toString())){c.put("outstanding",(max-a).coerceAtLeast(0.0));c.put("lastRepaymentDate",due.text.toString().trim());store.replace("credits",c);toast("Repayment recorded and balance updated")}else otp.error="OTP: incorrect consent code"}.show();d.dismiss()}}};d.show()}

    private fun qrKhata(){val id=edit("Registered counterparty profile ID *");val due=edit("Due date YYYY-MM-DD *");val amt=edit("Amount ₹ *");val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;add(this,id);add(this,amt);add(this,due)};AlertDialog.Builder(this).setTitle("QR Khata").setMessage("Counterparty must be a registered profile ID. Due date and partial/full repayment are supported through the Repayment Centre.").setView(box).setPositiveButton("SAVE"){_,_->val ok=store.all("profiles").any{it.optString("id")==id.text.toString().trim()};if(ok)toast("QR Khata entry saved for profile ${id.text}") else id.error="Profile ID: no such registered user"}.setNegativeButton("CANCEL",null).show()}
    private fun vault(){val type=Spinner(this).apply{adapter=ArrayAdapter(this@V61RectifiedActivity,android.R.layout.simple_spinner_dropdown_item,arrayOf("Savings account","Fixed deposit","Property","Gold","Mutual fund","Shares","Insurance","Other asset","Loan","Other liability"))};val value=edit("Estimated/current value ₹");val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;add(this,type);add(this,value)};AlertDialog.Builder(this).setTitle("Asset & Liability Vault").setView(box).setPositiveButton("SAVE"){_,_->store.add("assets",JSONObject().apply{put("ownerProfileId",selfId());put("type",type.selectedItem.toString());put("estimatedValue",value.text.toString().toDoubleOrNull()?:0.0)});toast("Vault record saved")}.setNegativeButton("CANCEL",null).show()}
    private fun insurance(){val insurer=edit("Insurer registered profile ID *");val insured=edit("Insured registered profile ID *");val policy=edit("Policy number *");val due=edit("Premium due date YYYY-MM-DD");val premium=edit("Premium amount ₹");val sum=edit("Sum insured ₹");val debit=edit("Debit account / bank reference");val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;listOf(insurer,insured,policy,due,premium,sum,debit).forEach{add(this,it)}};AlertDialog.Builder(this).setTitle("Insurance policy").setView(box).setPositiveButton("SAVE"){_,_->val ids=store.all("profiles").map{it.optString("id")};if(insurer.text.toString() !in ids)insurer.error="Insurer: select a registered profile" else if(insured.text.toString() !in ids)insured.error="Insured: select a registered profile" else{store.add("insurance",JSONObject().apply{put("insurerProfileId",insurer.text.toString());put("insuredProfileId",insured.text.toString());put("policyNumber",policy.text.toString());put("dueDate",due.text.toString());put("premium",premium.text.toString().toDoubleOrNull()?:0.0);put("sumInsured",sum.text.toString().toDoubleOrNull()?:0.0);put("debitAccount",debit.text.toString());put("timeline","premium due dates and policy-life events")});toast("Insurance policy saved")}}.setNegativeButton("CANCEL",null).show()}
    private fun documents(){val nominee=edit("Nominee registered profile ID *");val d=AlertDialog.Builder(this).setTitle("DPN / Will draft preview").setMessage("PROFESSIONAL DRAFT PREVIEW\n\nThis preview records the user's selected assets, nominee and execution/consent section. Final legal execution must be completed with appropriate professional advice and applicable formalities.").setView(nominee).setPositiveButton("CONSENT OTP",null).setNegativeButton("CANCEL",null).create();d.setOnShowListener{d.getButton(-1).setOnClickListener{val ok=store.all("profiles").any{it.optString("id")==nominee.text.toString().trim()};if(!ok)nominee.error="Nominee: select a registered profile" else{val cid=consent.issue("DOC-${System.currentTimeMillis()}","DOCUMENT_CONSENT",nominee.text.toString().trim());val code=store.find("consents",cid)?.optString("otp","")?:"";val otp=edit("Consent OTP");AlertDialog.Builder(this).setTitle("Document consent").setMessage("Demo OTP: $code").setView(otp).setPositiveButton("VERIFY"){_,_->if(consent.verify(cid,otp.text.toString()))toast("Document consent captured") else otp.error="OTP: incorrect"}.show();d.dismiss()}};d.show()}
    private fun claims(){AlertDialog.Builder(this).setTitle("Inheritance & Claim Centre").setMessage("Connected claim workflow: asset vault → nominee/inheritor profile → claim document → consent/audit → settlement status. All parties are profile-linked.").setPositiveButton("OK",null).show()}
    private fun legal(){val rows=store.all("lawyers");val text=if(rows.isEmpty())"No verified lawyers are available yet. Directory entries require verification." else rows.joinToString("\n\n"){j->"${j.optString("name")}\n${j.optString("address")}\n${j.optString("domain")} • ${j.optString("expertise")}\nExperience: ${j.optString("experience")}\nContact: ${j.optString("phone")}\nStatus: ${j.optString("verification","PENDING_VERIFICATION")}"};AlertDialog.Builder(this).setTitle("Legal Assistance").setMessage(text).setPositiveButton("OK",null).show()}
    private fun ttmm(){val group=edit("Event / group name *");val members=edit("Registered member profile IDs, comma separated *");val bill=edit("Total bill ₹ *");val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;add(this,group);add(this,members);add(this,bill)};AlertDialog.Builder(this).setTitle("TTMM group expense").setView(box).setPositiveButton("CALCULATE",null).setNegativeButton("CANCEL",null).create().also{d->d.setOnShowListener{d.getButton(-1).setOnClickListener{val ids=members.text.toString().split(",").map{it.trim()}.filter{it.isNotBlank()};val registered=store.all("profiles").map{it.optString("id")}.toSet();val total=bill.text.toString().toDoubleOrNull();if(ids.isEmpty()||ids.any{it !in registered})members.error="Members: every member must be a registered profile ID" else if(total==null||total<0)bill.error="Total bill: enter zero or a positive amount" else{val share=total/ids.size;store.add("ttmm_groups",JSONObject().apply{put("id","TT-${System.currentTimeMillis()}");put("name",group.text.toString());put("memberIds",ids.joinToString(","));put("totalBill",total);put("equalShare",share);put("status","OPEN")});d.dismiss();AlertDialog.Builder(this).setTitle("TTMM allocation").setMessage(ids.joinToString("\n"){"$it • share ₹${"%.2f".format(share)}\nMembers with unpaid/less-paid share become borrowers; settlement requires consent OTP."}).setPositiveButton("OK",null).show()}}};d.show()}}
    private fun advisor(){val self=selfId();val assets=store.all("assets").count{it.optString("ownerProfileId")==self};val credits=store.all("credits").filter{it.optString("lenderId")==self||it.optString("borrowerId")==self};val insurance=store.all("insurance").count{it.optString("insuredProfileId")==self};AlertDialog.Builder(this).setTitle("AI Advisor").setMessage("Authorized records reviewed: $assets asset/liability records, ${credits.size} credit records, $insurance insurance records.\n\nSuggestions: review liquidity, repayment due dates, protection coverage and nominee completeness. No money is moved automatically.").setPositiveButton("OK",null).show()}
    private fun settings(){val m=prefs.getString("current_mobile","") ?: "";AlertDialog.Builder(this).setTitle("Settings").setMessage("Session persistence: enabled\nProfile: ${prefs.getString("name_$m","User")}\nMobile: $m\nLogo/profile header: enabled\nKeyboard-safe scrolling: enabled").setPositiveButton("OK",null).show()}
}
