package com.udhaardaar.mvp

import android.app.AlertDialog
import android.content.Intent
import android.graphics.Color
import android.os.Bundle
import android.view.View
import android.view.WindowManager
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import org.json.JSONObject

/** V6.1.2 rectification centre: profile-linked transactions, consent gates and mobile-safe UI. */
class V61RectifiedActivity : AppCompatActivity() {
    private val store by lazy { V5LocalStore(this) }
    private val consent by lazy { V5OtpConsentService(this) }
    private val prefs by lazy { getSharedPreferences("udhaardaar_accounts", MODE_PRIVATE) }
    private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt()
    private fun field(h:String)=EditText(this).apply{hint=h;setSingleLine(true);setPadding(dp(12),dp(8),dp(12),dp(8))}
    private fun button(s:String,a:()->Unit)=Button(this).apply{text=s;setOnClickListener{a()}}
    private fun box(vararg v:View)=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;v.forEach{addView(it,LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(6)})}}
    private fun toast(s:String)=Toast.makeText(this,s,Toast.LENGTH_LONG).show()
    private fun selfId():String{val m=prefs.getString("current_mobile","")? :"";return store.all("profiles").firstOrNull{it.optString("mobile")==m}?.optString("id").orEmpty()}

    override fun onCreate(b:Bundle?){super.onCreate(b);window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);if(!prefs.getBoolean("logged_in",false)){startActivity(Intent(this,LoginActivity::class.java));finish();return};ensureProfile();render()}
    private fun ensureProfile(){val m=prefs.getString("current_mobile","")?:"";if(m.isBlank())return;if(store.all("profiles").none{it.optString("mobile")==m})store.add("profiles",JSONObject().apply{put("id","USR-$m");put("name",prefs.getString("name_$m","User"));put("mobile",m)})}
    private fun render(){val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(16),dp(16),dp(16),dp(80))};fun add(v:View){r.addView(v,LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(7)})};add(TextView(this).apply{text="ARTHSAATHI • V6.1.2\nProfile-linked financial centre";textSize=22f;setTextColor(Color.rgb(18,48,76))});add(TextView(this).apply{text="25-point rectification baseline • registered profile IDs • consent OTP • keyboard-safe";textSize=12f});add(button("PROFILE SEARCH / CREATE"){profileSearch()});add(button("REGISTER CREDIT / UDHAAR"){registerCredit()});add(button("REPAYMENT CENTRE — CREDIT GIVEN / RECEIVED"){repayments()});add(button("QR KHATA — DUE DATE / PARTIAL / FULL"){qrKhata()});add(button("ASSET & LIABILITY VAULT + AI ALERTS"){vault()});add(button("INSURANCE + PMSBY / PMJJBY"){insurance()});add(button("DPN / WILL — FULL PREVIEW + CONSENT OTP"){documents()});add(button("INHERITANCE & CLAIM CENTRE"){info("Inheritance & Claim Centre","Track nominees, beneficiaries, assets, policies and claim status. Records remain linked to registered profiles and supporting documents.")});add(button("LEGAL ASSISTANCE DIRECTORY"){info("Legal Assistance","Directory fields: lawyer name, address, phone, domain, expertise and experience.")});add(button("TTMM — GROUP EXPENSES / SETTLEMENT"){ttmm()});add(button("AI ADVISOR — AUTHORIZED DATA ONLY"){aiAdvisor()});add(button("SETTINGS / PROFILE PHOTO / SESSION"){info("Settings","Session persistence is enabled. Profile photo uses the existing profile settings flow. Screens use resize-aware scrolling.")});add(TextView(this).apply{text="No QA sample loader. No free-text parties in transactions. Names are entered only during profile creation.";textSize=11f});add(button("LOG OUT"){prefs.edit().putBoolean("logged_in",false).apply();startActivity(Intent(this,LoginActivity::class.java));finish()});setContentView(ScrollView(this).apply{isFillViewport=true;addView(r)})}

    private fun profileSearch(){val q=field("Search name / mobile / PAN / Aadhaar / GSTIN / profile ID");val list=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};val d=AlertDialog.Builder(this).setTitle("Registered profile search").setView(box(q,list)).setNegativeButton("CANCEL",null).create();fun refresh(){list.removeAllViews();val x=q.text.toString().trim().lowercase();val rows=store.all("profiles").filter{p->x.isEmpty()||listOf("id","name","mobile","pan","aadhaar","gstin").any{p.optString(it).lowercase().contains(x)}};if(rows.isEmpty()){list.addView(TextView(this).apply{text="No such user found";setTextColor(Color.RED)});list.addView(button("CREATE NEW PROFILE"){d.dismiss();createProfile()})}else rows.take(15).forEach{p->list.addView(button("${p.optString("name")} • ${p.optString("id")}\n${p.optString("mobile")}"){d.dismiss();history(p)})}};q.addTextChangedListener(object:android.text.TextWatcher{override fun beforeTextChanged(s:CharSequence?,a:Int,c:Int,e:Int){};override fun onTextChanged(s:CharSequence?,a:Int,b:Int,c:Int){refresh()};override fun afterTextChanged(e:android.text.Editable?){}});d.show();refresh()}
    private fun createProfile(){val n=field("Full name / business name *");val m=field("Mobile number *");val pan=field("PAN");val aad=field("Aadhaar");val gst=field("GSTIN");val d=AlertDialog.Builder(this).setTitle("Create registered profile").setView(box(n,m,pan,aad,gst)).setNegativeButton("CANCEL",null).setPositiveButton("SAVE",null).create();d.setOnShowListener{d.getButton(-1).setOnClickListener{val name=n.text.toString().trim();val mob=m.text.toString().trim();when{name.length<2->n.error="Name: enter at least 2 characters";!V5Validation.mobile(mob)->m.error="Mobile: enter a valid 10-digit Indian mobile number";store.all("profiles").any{it.optString("mobile")==mob}->m.error="Mobile: already registered";else->{store.add("profiles",JSONObject().apply{put("id","USR-${System.currentTimeMillis()}");put("name",name);put("mobile",mob);put("pan",pan.text.toString().trim().uppercase());put("aadhaar",aad.text.toString().trim());put("gstin",gst.text.toString().trim().uppercase())});d.dismiss();toast("Profile created")}}}};d.show()}
    private fun history(p:JSONObject){val id=p.optString("id");val c=store.all("credits").filter{it.optString("lenderId")==id||it.optString("borrowerId")==id};val out=c.sumOf{it.optDouble("outstanding",0.0)};info("Profile: ${p.optString("name")}","Profile ID: $id\nMobile: ${p.optString("mobile")}\nRelated credits: ${c.size}\nOutstanding: ₹${"%.2f".format(out)}\nScore: based only on consented transaction history.")}

    private fun chooseParty(title:String,done:(JSONObject)->Unit){val q=field("Live search registered profile");val list=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};val d=AlertDialog.Builder(this).setTitle(title).setView(box(q,list)).setNegativeButton("CANCEL",null).create();fun refresh(){list.removeAllViews();val x=q.text.toString().trim().lowercase();val rows=store.all("profiles").filter{p->x.isEmpty()||p.toString().lowercase().contains(x)};if(rows.isEmpty()){list.addView(TextView(this).apply{text="No such user found";setTextColor(Color.RED)});list.addView(button("CREATE NEW PROFILE"){d.dismiss();createProfile()})}else rows.forEach{p->list.addView(button("${p.optString("name")} • ${p.optString("id")}"){d.dismiss();done(p)})}};q.addTextChangedListener(object:android.text.TextWatcher{override fun beforeTextChanged(s:CharSequence?,a:Int,c:Int,e:Int){};override fun onTextChanged(s:CharSequence?,a:Int,b:Int,c:Int){refresh()};override fun afterTextChanged(e:android.text.Editable?){}});d.show();refresh()}
    private fun registerCredit(){chooseParty("Select LENDER"){l->chooseParty("Select BORROWER"){b->creditTerms(l,b)}}}
    private fun creditTerms(l:JSONObject,b:JSONObject){if(l.optString("id")==b.optString("id")){toast("Lender and borrower must be different registered profiles");return};val a=field("Principal amount ₹ *");val roi=field("Interest rate %");val due=field("Due date YYYY-MM-DD *");val method=Spinner(this).apply{adapter=ArrayAdapter(this@V61RectifiedActivity,android.R.layout.simple_spinner_dropdown_item,arrayOf("EMI","Principal + Interest","Bullet / single payment"))};val period=Spinner(this).apply{adapter=ArrayAdapter(this@V61RectifiedActivity,android.R.layout.simple_spinner_dropdown_item,arrayOf("Monthly","Quarterly","Half-yearly","Yearly","One-time"))};val d=AlertDialog.Builder(this).setTitle("Credit terms").setMessage("LENDER ${l.optString("id")} → BORROWER ${b.optString("id")}").setView(box(a,roi,due,method,period)).setNegativeButton("CANCEL",null).setPositiveButton("REVIEW + CONSENT",null).create();d.setOnShowListener{d.getButton(-1).setOnClickListener{val x=a.text.toString().toDoubleOrNull();val r=roi.text.toString().toDoubleOrNull()?:0.0;when{x==null||x<=0->a.error="Amount: enter a positive amount";r<0->roi.error="Interest: cannot be negative";!due.text.toString().trim().matches(Regex("\\d{4}-\\d{2}-\\d{2}"))->due.error="Due date: use YYYY-MM-DD";else->{d.dismiss();saveCredit(l,b,x,r,due.text.toString().trim(),method.selectedItem.toString(),period.selectedItem.toString())}}}};d.show()}
    private fun saveCredit(l:JSONObject,b:JSONObject,a:Double,r:Double,due:String,method:String,period:String){val id="CR-${System.currentTimeMillis()}";val cid=consent.issue(id,"CREDIT_CONSENT",b.optString("id"));val otp=store.find("consents",cid)?.optString("otp","")?:"";val input=field("Counterparty consent OTP");AlertDialog.Builder(this).setTitle("Consent required").setMessage("Credit ₹${"%.2f".format(a)}\nDemo OTP: $otp").setView(input).setNegativeButton("CANCEL",null).setPositiveButton("CONFIRM"){_,_->if(consent.verify(cid,input.text.toString())){store.add("credits",JSONObject().apply{put("id",id);put("lenderId",l.optString("id"));put("borrowerId",b.optString("id"));put("principal",a);put("interestRate",r);put("dueDate",due);put("repaymentMethod",method);put("periodicity",period);put("outstanding",a);put("status","ACTIVE");put("consentId",cid)});toast("Credit registered") }else input.error="OTP: incorrect consent code"}.show()}

    private fun repayments(){val self=selfId();val rows=store.all("credits").filter{it.optString("lenderId")==self||it.optString("borrowerId")==self};if(rows.isEmpty()){toast("No related credit accounts");return};AlertDialog.Builder(this).setTitle("Credit Given / Credit Received").setItems(rows.map{"${it.optString("id")} • due ${it.optString("dueDate")} • ₹${it.optDouble("outstanding",0.0)}"}.toTypedArray()){_,i->recordRepayment(rows[i])}.show()}
    private fun recordRepayment(c:JSONObject){val max=c.optDouble("outstanding",0.0);if(max<=0){toast("Already fully repaid");return};val a=field("Repayment amount ₹ (max $max)");val date=field("Repayment date YYYY-MM-DD");val d=AlertDialog.Builder(this).setTitle("Record repayment").setView(box(a,date)).setNegativeButton("CANCEL",null).setPositiveButton("REQUEST CONSENT",null).create();d.setOnShowListener{d.getButton(-1).setOnClickListener{val x=a.text.toString().toDoubleOrNull();if(x==null||x<=0||x>max)a.error="Repayment: enter an amount between 0 and $max"else{val other=if(c.optString("lenderId")==selfId())c.optString("borrowerId")else c.optString("lenderId");val cid=consent.issue(c.optString("id"),"REPAYMENT_CONSENT",other);val otp=store.find("consents",cid)?.optString("otp","")?:"";val code=field("Consent OTP");AlertDialog.Builder(this).setTitle("Repayment consent").setMessage("Demo OTP: $otp").setView(code).setNegativeButton("CANCEL",null).setPositiveButton("VERIFY"){_,_->if(consent.verify(cid,code.text.toString())){c.put("outstanding",(max-x).coerceAtLeast(0.0));c.put("lastRepaymentDate",date.text.toString().trim());store.replace("credits",c);toast("Repayment recorded") }else code.error="OTP: incorrect consent code"}.show();d.dismiss()}}};d.show()}

    private fun qrKhata(){val p=field("Registered counterparty profile ID *");val a=field("Amount ₹ *");val due=field("Due date YYYY-MM-DD *");AlertDialog.Builder(this).setTitle("QR Khata").setMessage("Counterparty must be a registered profile ID. Partial and full repayments use the consent-gated Repayment Centre.").setView(box(p,a,due)).setNegativeButton("CANCEL",null).setPositiveButton("VALIDATE"){_,_->if(store.all("profiles").any{it.optString("id")==p.text.toString().trim()})toast("QR Khata counterparty validated")else p.error="Profile ID: no such registered user"}.show()}
    private fun vault(){val type=Spinner(this).apply{adapter=ArrayAdapter(this@V61RectifiedActivity,android.R.layout.simple_spinner_dropdown_item,arrayOf("Savings account","Fixed deposit","Property","Gold","Mutual fund","Shares","Insurance","Other asset","Loan","Other liability"))};val value=field("Current / estimated value ₹");AlertDialog.Builder(this).setTitle("Asset & Liability Vault").setMessage("AI alerts can flag idle savings balances after a configured period. No transfer or investment occurs without explicit user action.").setView(box(type,value)).setNegativeButton("CANCEL",null).setPositiveButton("SAVE"){_,_->store.add("assets",JSONObject().apply{put("ownerProfileId",selfId());put("type",type.selectedItem.toString());put("estimatedValue",value.text.toString().toDoubleOrNull()?:0.0)});toast("Vault record saved")}.show()}
    private fun insurance(){val insurer=field("Insurer registered profile ID *");val insured=field("Insured registered profile ID *");val policy=field("Policy number *");val due=field("Premium due date YYYY-MM-DD");val premium=field("Premium amount ₹");val sum=field("Sum insured ₹");val debit=field("Debit account / bank reference");val benefit=Spinner(this).apply{adapter=ArrayAdapter(this@V61RectifiedActivity,android.R.layout.simple_spinner_dropdown_item,arrayOf("None","PMSBY","PMJJBY"))};AlertDialog.Builder(this).setTitle("Insurance & government benefits").setView(box(insurer,insured,policy,due,premium,sum,debit,benefit)).setNegativeButton("CANCEL",null).setPositiveButton("SAVE"){_,_->val ids=store.all("profiles").map{it.optString("id")};when{insurer.text.toString() !in ids->insurer.error="Insurer: select a registered profile";insured.text.toString() !in ids->insured.error="Insured: select a registered profile";policy.text.toString().isBlank()->policy.error="Policy number: required";else->{store.add("insurance",JSONObject().apply{put("insurerProfileId",insurer.text.toString());put("insuredProfileId",insured.text.toString());put("policyNumber",policy.text.toString());put("premiumDueDate",due.text.toString());put("premiumAmount",premium.text.toString().toDoubleOrNull()?:0.0);put("sumInsured",sum.text.toString().toDoubleOrNull()?:0.0);put("debitAccount",debit.text.toString());put("benefit",benefit.selectedItem.toString())});toast("Insurance record saved")}}}.show()}

    private fun documents(){val kind=Spinner(this).apply{adapter=ArrayAdapter(this@V61RectifiedActivity,android.R.layout.simple_spinner_dropdown_item,arrayOf("DPN / Promissory Note","Will / Asset nomination"))};val party=field("Registered beneficiary / counterparty profile ID");val asset=field("Asset / obligation description");val d=AlertDialog.Builder(this).setTitle("Professional document").setView(box(kind,party,asset)).setNegativeButton("CANCEL",null).setPositiveButton("PREVIEW",null).create();d.setOnShowListener{d.getButton(-1).setOnClickListener{val preview="${kind.selectedItem}\n\nParty/Profile ID: ${party.text}\nAsset/Obligation: ${asset.text}\n\nFULL DRAFT PREVIEW\nDeclaration, terms, signatures and consent section will be shown before OTP.\n\nPrototype preview is not a substitute for legal review.";d.dismiss();val otp=field("Document consent OTP");val cid=consent.issue("DOC-${System.currentTimeMillis()}","DOCUMENT_CONSENT",party.text.toString());val code=store.find("consents",cid)?.optString("otp","")?:"";AlertDialog.Builder(this).setTitle("FULL DRAFT PREVIEW").setMessage(preview+"\n\nDemo OTP: $code").setView(otp).setNegativeButton("CANCEL",null).setPositiveButton("CONSENT"){_,_->if(consent.verify(cid,otp.text.toString()))toast("Document consent recorded")else otp.error="OTP: incorrect consent code"}.show()}};d.show()}
    private fun ttmm(){val members=field("Registered member profile IDs, comma separated");val total=field("Total bill ₹");AlertDialog.Builder(this).setTitle("TTMM group expense").setMessage("Members must be registered profile IDs. Equal-share allocation is supported; unpaid/underpaid members can become consent-gated borrowers.").setView(box(members,total)).setNegativeButton("CANCEL",null).setPositiveButton("ALLOCATE"){_,_->val ids=members.text.toString().split(",").map{it.trim()}.filter{it.isNotBlank()};val valid=ids.all{id->store.all("profiles").any{it.optString("id")==id}};if(!valid)toast("Every member must be a registered profile ID")else{val amount=total.text.toString().toDoubleOrNull()?:0.0;toast("${ids.size} members • equal share ₹${if(ids.isEmpty())0.0 else amount/ids.size}")}}.show()}
    private fun aiAdvisor(){val c=store.all("credits").count{it.optString("lenderId")==selfId()||it.optString("borrowerId")==selfId()};val a=store.all("assets").count{it.optString("ownerProfileId")==selfId()};info("AI Advisor","Authorized local data summary:\nCredits: $c\nVault records: $a\n\nRecommendations use only authorized module data. Financial actions require explicit confirmation.")}
    private fun info(t:String,m:String){AlertDialog.Builder(this).setTitle(t).setMessage(m).setPositiveButton("OK",null).show()}
}
