package com.udhaardaar.mvp

import android.app.AlertDialog
import android.graphics.Color
import android.graphics.Typeface
import android.graphics.drawable.GradientDrawable
import android.os.Bundle
import android.view.View
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import org.json.JSONObject

/** V6.2 asset/liability vault with nominee, evidence and AI alert preferences. */
class V62AssetVaultActivity:AppCompatActivity(){
 private val store by lazy{V5LocalStore(this)};private val prefs by lazy{getSharedPreferences("udhaardaar_accounts",MODE_PRIVATE)};private val navy=Color.rgb(16,45,82);private val teal=Color.rgb(12,155,145);private val blue=Color.rgb(42,103,221);private val gold=Color.rgb(211,161,37);private val red=Color.rgb(193,67,72);private val bg=Color.rgb(246,249,252);private val border=Color.rgb(220,228,236)
 private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt();private fun box()=GradientDrawable().apply{setColor(Color.WHITE);setStroke(dp(1),border);cornerRadius=dp(14).toFloat()};private fun tv(s:String,z:Float=13f,c:Int=navy,b:Boolean=false)=TextView(this).apply{text=s;textSize=z;setTextColor(c);typeface=Typeface.create("sans-serif",if(b)Typeface.BOLD else Typeface.NORMAL)};private fun e(h:String)=EditText(this).apply{hint=h;textSize=15f;setSingleLine(true);setPadding(dp(12),dp(9),dp(12),dp(9));background=box()};private fun btn(s:String,c:Int=blue,f:()->Unit)=Button(this).apply{text=s;setTextColor(Color.WHITE);setAllCaps(false);setBackgroundColor(c);setOnClickListener{f()}};private fun lp(t:Int)=LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(t)}
 override fun onCreate(b:Bundle?){super.onCreate(b);if(!prefs.getBoolean("logged_in",false)){finish();return};render()}
 private fun render(){val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(16),dp(14),dp(16),dp(28));setBackgroundColor(bg)};root.addView(tv("ArthSaathi  •  Asset & Liability Vault",21f,navy,true));root.addView(tv("Assets • liabilities • evidence • nominee • intelligent alerts",11f,Color.rgb(92,108,124)),lp(3));root.addView(btn("ADD ASSET / LIABILITY",teal){addEntry()},lp(14));val rows=store.all("vault");if(rows.isEmpty())root.addView(tv("Your vault is ready. Add your first asset, liability or supporting evidence.",13f,navy),lp(14)) else rows.reversed().take(30).forEach{j->root.addView(entry(j),lp(7))};root.addView(btn("AI ALERT SETTINGS",gold){alerts()},lp(14));root.addView(btn("BACK TO HOME",Color.rgb(90,105,120)){finish()},lp(8));setContentView(ScrollView(this).apply{isFillViewport=true;addView(root)})}
 private fun addEntry(){val type=Spinner(this).apply{adapter=ArrayAdapter(this@V62AssetVaultActivity,android.R.layout.simple_spinner_dropdown_item,arrayOf("Savings account","Fixed deposit","Property","Gold","Mutual fund","Shares","Insurance","Vehicle","Loan","Other"))};val name=e("Asset / liability name *");val value=e("Current value / outstanding ₹ *");val nominee=e("Nominee / beneficiary");val evidence=e("Evidence reference / document note");AlertDialog.Builder(this).setTitle("Add to Asset Vault").setView(line(type,name,value,nominee,evidence)).setNegativeButton("CANCEL",null).setPositiveButton("SAVE"){_,_->val n=name.text.toString().trim();val v=value.text.toString().toDoubleOrNull();if(n.isBlank()||v==null||v<0){Toast.makeText(this,"Enter a name and valid value",Toast.LENGTH_LONG).show();return@setPositiveButton};store.add("vault",JSONObject().apply{put("id","AST-${System.currentTimeMillis()}");put("type",type.selectedItem.toString());put("name",n);put("value",v);put("nominee",nominee.text.toString().trim());put("evidence",evidence.text.toString().trim());put("alertsEnabled",true);put("createdAt",System.currentTimeMillis())});render()}.show()}
 private fun entry(j:JSONObject)=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(13),dp(11),dp(13),dp(11));background=box();addView(tv("${j.optString("type")}  •  ${j.optString("id")}",10f,teal,true));addView(tv(j.optString("name"),15f,navy,true),lp(3));addView(tv("Value / outstanding: ₹${"%.2f".format(j.optDouble("value",0.0))}",11f,navy),lp(2));addView(tv("Nominee: ${j.optString("nominee").ifBlank{"Not set"}}\nEvidence: ${j.optString("evidence").ifBlank{"Not referenced"}}",10f,Color.rgb(92,108,124)),lp(3))}
 private fun alerts(){val idle=e("Alert after idle savings balance (days)").apply{setText("15")};val threshold=e("Minimum balance to flag (₹)");AlertDialog.Builder(this).setTitle("AI Asset Vault Alerts").setMessage("ArthSaathi can suggest review of idle cash, missing nominees, expiring documents or protection gaps. It never transfers money or invests automatically.").setView(line(idle,threshold)).setNegativeButton("CANCEL",null).setPositiveButton("SAVE") {_,_->getSharedPreferences("arthsaathi_alerts",MODE_PRIVATE).edit().putInt("idleDays",idle.text.toString().toIntOrNull()?:15).putFloat("threshold",threshold.text.toString().toFloatOrNull()?:0f).apply();Toast.makeText(this,"Alert preferences saved",Toast.LENGTH_LONG).show()}.show()}
 private fun line(vararg v:View)=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;v.forEachIndexed{i,x->addView(x,if(i==0)LinearLayout.LayoutParams(-1,-2) else lp(7))}}
}
