package com.udhaardaar.mvp

import android.app.AlertDialog
import android.app.DatePickerDialog
import android.content.Intent
import android.graphics.Color
import android.graphics.Typeface
import android.graphics.drawable.GradientDrawable
import android.net.Uri
import android.os.Bundle
import android.text.*
import android.view.*
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import org.json.JSONObject
import java.text.SimpleDateFormat
import java.util.*
import kotlin.math.pow
import kotlin.math.roundToInt
import kotlin.random.Random

/** V6.2 credit journey: registered profiles -> terms/EMI -> guarantor/document -> consent OTP -> record. */
class V62CreditRegistrationActivity:AppCompatActivity(){
 private val store by lazy{V5LocalStore(this)};private val prefs by lazy{getSharedPreferences("udhaardaar_accounts",MODE_PRIVATE)};private val draft by lazy{getSharedPreferences("v62_credit_draft",MODE_PRIVATE)}
 private val navy=Color.rgb(16,45,82);private val teal=Color.rgb(12,155,145);private val blue=Color.rgb(42,103,221);private val green=Color.rgb(18,137,91);private val gold=Color.rgb(211,161,37);private val red=Color.rgb(193,67,72);private val muted=Color.rgb(92,108,124);private val bg=Color.rgb(246,249,252);private val border=Color.rgb(220,228,236)
 private var lender:JSONObject?=null;private var borrower:JSONObject?=null;private var guarantor:JSONObject?=null;private var invoiceUri="";private var step=1;private lateinit var root:LinearLayout
 private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt();private fun tv(s:String,z:Float,c:Int=navy,b:Boolean=false)=TextView(this).apply{text=s;textSize=z;setTextColor(c);typeface=Typeface.create("sans-serif",if(b)Typeface.BOLD else Typeface.NORMAL);includeFontPadding=false};private fun field(h:String)=EditText(this).apply{hint=h;textSize=15f;setTextColor(navy);setHintTextColor(muted);setPadding(dp(13),dp(10),dp(13),dp(10));minHeight=dp(52);setSingleLine(true);background=box()};private fun box(fill:Int=Color.WHITE)=GradientDrawable().apply{setColor(fill);setStroke(dp(1),border);cornerRadius=dp(14).toFloat()};private fun btn(s:String,c:Int=blue,click:()->Unit)=Button(this).apply{text=s;textSize=13f;setTextColor(Color.WHITE);setAllCaps(false);setBackgroundColor(c);minHeight=dp(50);setOnClickListener{click()}};private fun add(v:View,top:Int=8){root.addView(v,LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(top)})};private fun lp(top:Int=6)=LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(top)}
 override fun onCreate(b:Bundle?){super.onCreate(b);window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);if(!prefs.getBoolean("logged_in",false)){startActivity(Intent(this,LoginActivity::class.java));finish();return};render()}
 private fun render(){root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(16),dp(12),dp(16),dp(28));setBackgroundColor(bg)};val head=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL};head.addView(ImageView(this).apply{setImageResource(R.drawable.udhaardaar_logo);scaleType=ImageView.ScaleType.CENTER_INSIDE},LinearLayout.LayoutParams(dp(44),dp(44)));head.addView(tv("ArthSaathi\nRegister Credit",18f,navy,true),LinearLayout.LayoutParams(0,-2,1f).apply{leftMargin=dp(10)});head.addView(tv("$step / 4",11f,teal,true));root.addView(head);add(tv("Search registered profiles first. If a profile is absent, create it and return to this journey.",11f,muted),6);add(stepBar(),8);when(step){1->profileStep();2->termsStep();3->guarantorStep();4->consentStep()};setContentView(ScrollView(this).apply{isFillViewport=true;addView(root)})}
 private fun stepBar()=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;arrayOf("Profile","Terms","Guarantor","Consent").forEachIndexed{i,s->addView(tv("${i+1}. $s",9f,if(i+1<=step)teal else muted,i+1<=step).apply{gravity=Gravity.CENTER;padding();background=box(if(i+1<=step)Color.rgb(236,249,246) else Color.WHITE)},LinearLayout.LayoutParams(0,dp(38),1f).apply{if(i>0)leftMargin=dp(4)})}};
 private fun TextView.padding(){setPadding(dp(4),dp(5),dp(4),dp(5))}
 private fun profileStep(){add(tv("1  WHO IS INVOLVED?",11f,muted,true),16);party("LENDER",lender,blue){choose("Select lender"){lender=it;render()}};party("BORROWER",borrower,green){choose("Select borrower"){borrower=it;render()}};if(lender!=null&&borrower!=null&&lender!!.optString("id")!=borrower!!.optString("id"))add(btn("Continue to Credit Terms  →",blue){step=2;render()},14);add(tv("History, outstanding and score are shown from consented records only.",10f,muted),10)}
 private fun party(role:String,p:JSONObject?,accent:Int,click:()->Unit){val c=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(13),dp(12),dp(13),dp(12));background=box();setOnClickListener{click()}};c.addView(tv(role,10f,accent,true));if(p==null){c.addView(tv("Tap to search / create registered profile",15f,navy,true),lp(4));c.addView(tv("Name • Mobile • PAN • Aadhaar • GSTIN • Profile ID",10f,muted),lp(2))}else{c.addView(tv("${p.optString("name")}  •  ${p.optString("id")}",15f,navy,true),lp(4));val h=history(p.optString("id"));c.addView(tv("${p.optString("mobile")}  •  ${h.first} records  •  ₹${"%.0f".format(h.second)} outstanding  •  Score ${score(h.first,h.second)}",10f,teal,true),lp(4))};add(c,7)}
 private fun choose(title:String,done:(JSONObject)->Unit){val q=field("Search name / mobile / PAN / Aadhaar / GSTIN / profile ID");val list=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};val wrap=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(4),dp(4),dp(4),dp(4));addView(q);addView(list,lp())};val d=AlertDialog.Builder(this).setTitle(title).setView(wrap).setNegativeButton("CANCEL",null).create();fun refresh(){list.removeAllViews();val x=q.text.toString().trim().lowercase();val rows=store.all("profiles").filter{p->x.isEmpty()||listOf("id","name","mobile","pan","aadhaar","gstin").any{p.optString(it).lowercase().contains(x)}};if(rows.isEmpty()){list.addView(tv("No registered profile found",11f,red,true));list.addView(btn("CREATE NEW PROFILE",teal){d.dismiss();createProfile(done)},lp(8))}else rows.take(15).forEach{p->list.addView(btn("${p.optString("name")}  •  ${p.optString("mobile")}\n${p.optString("id")}",Color.WHITE){showHistory(p){done(p)}},lp(5))}};q.addTextChangedListener(object:TextWatcher{override fun beforeTextChanged(s:CharSequence?,a:Int,c:Int,d:Int){};override fun onTextChanged(s:CharSequence?,a:Int,b:Int,c:Int){refresh()};override fun afterTextChanged(e:Editable?){}});d.show();refresh()}
 private fun showHistory(p:JSONObject,done:()->Unit){val h=history(p.optString("id"));AlertDialog.Builder(this).setTitle("${p.optString("name")} • consented history").setMessage("Profile ID: ${p.optString("id")}\nMobile: ${p.optString("mobile")}\nRelated records: ${h.first}\nOutstanding: ₹${"%.2f".format(h.second)}\nScore: ${score(h.first,h.second)}\n\nOnly consented transaction history is used.").setNegativeButton("CANCEL",null).setPositiveButton("SELECT"){_,_->done()}.show()}
 private fun createProfile(done:(JSONObject)->Unit){val n=field("Full name / business name *");val m=field("Mobile number *");val pan=field("PAN");val aad=field("Aadhaar");val gst=field("GSTIN");val f=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;addView(n);addView(m,lp());addView(pan,lp());addView(aad,lp());addView(gst,lp())};val d=AlertDialog.Builder(this).setTitle("Create registered profile").setView(f).setNegativeButton("CANCEL",null).setPositiveButton("SAVE + RETURN",null).create();d.setOnShowListener{d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener{val name=n.text.toString().trim();val mob=m.text.toString().trim();val pv=pan.text.toString().trim().uppercase();val gv=gst.text.toString().trim().uppercase();when{name.length<2->n.error="Enter name";!V5Validation.mobile(mob)->m.error="Enter valid 10-digit mobile";store.all("profiles").any{it.optString("mobile")==mob}->m.error="Mobile already registered";pv.isNotBlank()&&!Regex("[A-Z]{5}[0-9]{4}[A-Z]").matches(pv)->pan.error="Invalid PAN";gv.isNotBlank()&&!Regex("[0-9]{2}[A-Z0-9]{13}").matches(gv)->gst.error="Invalid GSTIN";else->{val p=JSONObject().apply{put("id","USR-${System.currentTimeMillis()}");put("name",name);put("mobile",mob);put("pan",pv);put("aadhaar",aad.text.toString().trim());put("gstin",gv);put("createdAt",System.currentTimeMillis())};store.add("profiles",p);d.dismiss();done(p)}}}};d.show()}
 private fun termsStep(){add(tv("2  CREDIT TERMS & AUTO CALCULATION",11f,muted,true),16);val type=Spinner(this).apply{adapter=ArrayAdapter(this@V62CreditRegistrationActivity,android.R.layout.simple_spinner_dropdown_item,arrayOf("Personal / Hand Loan","Trade Credit","Rental / Lease","Other Credit"))};val amount=field("Principal amount ₹ *");val roi=field("ROI / interest %");val start=field("Start date — select");val end=field("End / due date — select");val method=Spinner(this).apply{adapter=ArrayAdapter(this@V62CreditRegistrationActivity,android.R.layout.simple_spinner_dropdown_item,arrayOf("EMI","Principal + Interest","Bullet / single payment"))};val period=Spinner(this).apply{adapter=ArrayAdapter(this@V62CreditRegistrationActivity,android.R.layout.simple_spinner_dropdown_item,arrayOf("Monthly","Quarterly","Half-yearly","Yearly","One-time"))};val emi=field("EMI — automatically calculated").apply{isFocusable=false};val summary=tv("Enter principal, ROI and dates.",10f,teal,true);val invoice=btn("Upload trade invoice / supporting document",teal){pickInvoice()};date(start);date(end);add(label("Credit type",type));add(label("Principal",amount));add(label("ROI",roi));add(label("Start",start));add(label("End",end));add(label("Repayment method",method));add(label("Periodicity",period));add(label("Auto EMI",emi));add(summary,4);add(invoice,6);add(tv("${lender!!.optString("name")}  →  ${borrower!!.optString("name")}",11f,navy,true),10)
  fun recalc(){if(method.selectedItemPosition!=0){emi.setText("");summary.text="Selected method does not use EMI.";return};val p=amount.text.toString().replace(",","").toDoubleOrNull();val rate=roi.text.toString().toDoubleOrNull()?:0.0;val s=parse(start.text.toString());val e=parse(end.text.toString());if(p==null||p<=0||s==null||e==null||e.time<=s.time){emi.setText("");summary.text="Enter principal, ROI and valid dates.";return};val f=when(period.selectedItemPosition){0->12;1->4;2->2;3->1;else->0};if(f==0){emi.setText("");summary.text="One-time repayment selected.";return};val months=(e.time-s.time).toDouble()/(1000*60*60*24*30.4375);val n=maxOf(1,(months/(12.0/f)).roundToInt());val r=rate/100.0/f;val pay=if(r==0.0)p/n else p*r*(1+r).pow(n)/((1+r).pow(n)-1);emi.setText("%.2f".format(Locale.US,pay));summary.text="$n installments • estimated total ₹${"%.2f".format(Locale.US,pay*n)}"};val w=object:TextWatcher{override fun beforeTextChanged(s:CharSequence?,a:Int,c:Int,d:Int){};override fun onTextChanged(s:CharSequence?,a:Int,b:Int,c:Int){recalc()};override fun afterTextChanged(e:Editable?){}};amount.addTextChangedListener(w);roi.addTextChangedListener(w);start.addTextChangedListener(w);end.addTextChangedListener(w);method.onItemSelectedListener=spin{recalc()};period.onItemSelectedListener=spin{recalc()};add(two(btn("← Back"){step=1;render()},btn("Continue →"){val p=amount.text.toString().toDoubleOrNull();if(p==null||p<=0){amount.error="Enter amount"}else{draft.edit().putString("amount",amount.text.toString()).putString("roi",roi.text.toString()).putString("start",start.text.toString()).putString("end",end.text.toString()).putString("type",type.selectedItem.toString()).putString("method",method.selectedItem.toString()).putString("period",period.selectedItem.toString()).putString("emi",emi.text.toString()).putString("invoice",invoiceUri).apply();step=3;render()}}),14)}
 private fun label(s:String,v:View)=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;addView(tv(s,10f,muted,true));addView(v,lp())};private fun two(a:Button,b:Button)=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;addView(a,LinearLayout.LayoutParams(0,dp(50),1f).apply{rightMargin=dp(4)});addView(b,LinearLayout.LayoutParams(0,dp(50),1f).apply{leftMargin=dp(4)})};private fun spin(action:()->Unit)=object:AdapterView.OnItemSelectedListener{override fun onNothingSelected(p:AdapterView<*>?){};override fun onItemSelected(p:AdapterView<*>?,v:View?,pos:Int,id:Long){action()}}
 private fun date(e:EditText){e.isFocusable=false;e.setOnClickListener{val c=Calendar.getInstance();DatePickerDialog(this,{_,y,m,d->c.set(y,m,d);e.setText(SimpleDateFormat("dd MMM yyyy",Locale.getDefault()).format(c.time))},c.get(Calendar.YEAR),c.get(Calendar.MONTH),c.get(Calendar.DAY_OF_MONTH)).show()}};private fun parse(s:String)=runCatching{SimpleDateFormat("dd MMM yyyy",Locale.getDefault()).parse(s)}.getOrNull()
 private fun guarantorStep(){add(tv("3  GUARANTOR & DOCUMENT",11f,muted,true),16);val c=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(13),dp(12),dp(13),dp(12));background=box()};if(guarantor==null){c.addView(tv("No guarantor selected",14f,navy,true));c.addView(btn("Add guarantor",teal){choose("Select guarantor"){guarantor=it;render()}},lp(7))}else{c.addView(tv("${guarantor!!.optString("name")} • ${guarantor!!.optString("id")}",14f,navy,true));c.addView(btn("Remove guarantor",red){guarantor=null;render()},lp(7))};add(c);add(tv("Digital consent document",10f,muted,true),12);add(tv("DPN / agreement / invoice: ${if(invoiceUri.isBlank())"Not attached" else "Attached" )}",12f,navy,true),4);add(two(btn("← Back"){step=2;render()},btn("Review & Consent →"){step=4;render()}),14)}
 private fun consentStep(){add(tv("4  REVIEW, CONSENT & OTP",11f,muted,true),16);val a=draft.getString("amount","")?:"";val review=tv("LENDER: ${lender!!.optString("name")}\nBORROWER: ${borrower!!.optString("name")}\nPrincipal: ₹$a\nROI: ${draft.getString("roi","")}%\nMethod: ${draft.getString("method","")}\nPeriodicity: ${draft.getString("period","")}\nEMI: ₹${draft.getString("emi","")}\nDocument: ${if(invoiceUri.isBlank())"Not attached" else "Attached"}",13f,navy,true);review.setPadding(dp(14),dp(14),dp(14),dp(14));review.background=box();add(review);add(tv("Both parties must consent. Demo OTP is displayed until a production SMS/consent gateway is connected.",10f,muted),10);add(btn("REQUEST CONSENT OTP",teal){verifyOtp()},14);add(btn("← Back to guarantor",Color.rgb(90,105,120)){step=3;render()},8)}
 private fun verifyOtp(){val code=(100000+Random.nextInt(900000)).toString();val e=field("Enter 6-digit consent OTP");val d=AlertDialog.Builder(this).setTitle("Two-party digital consent").setMessage("Demo OTP: $code\nConsent target: ${borrower!!.optString("name")}").setView(e).setNegativeButton("CANCEL",null).setPositiveButton("CONFIRM",null).create();d.setOnShowListener{d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener{if(e.text.toString()==code){registerFinal();d.dismiss()}else e.error="Incorrect OTP"}};d.show()}
 private fun registerFinal(){val id="CR-${System.currentTimeMillis()}";store.add("credits",JSONObject().apply{put("id",id);put("lenderId",lender!!.optString("id"));put("borrowerId",borrower!!.optString("id"));put("principal",draft.getString("amount", "0").toDoubleOrNull()?:0.0);put("interestRate",draft.getString("roi","0").toDoubleOrNull()?:0.0);put("startDate",draft.getString("start",""));put("dueDate",draft.getString("end",""));put("repaymentMethod",draft.getString("method",""));put("periodicity",draft.getString("period",""));put("emi",draft.getString("emi","0").toDoubleOrNull()?:0.0);put("documentUri",invoiceUri);put("guarantorId",guarantor?.optString("id")?:"");put("outstanding",draft.getString("amount","0").toDoubleOrNull()?:0.0);put("status","ACTIVE");put("consentStatus","OTP_VERIFIED");put("createdAt",System.currentTimeMillis())});draft.edit().clear().apply();AlertDialog.Builder(this).setTitle("Credit registered").setMessage("Reference: $id\nThe record is linked to both registered profiles and consent is recorded.").setPositiveButton("DONE"){_,_->finish()}.show()}
 private fun pickInvoice(){startActivityForResult(Intent(Intent.ACTION_OPEN_DOCUMENT).apply{type="application/pdf";addCategory(Intent.CATEGORY_OPENABLE);putExtra(Intent.EXTRA_MIME_TYPES,arrayOf("application/pdf","image/*"))},6202)};override fun onActivityResult(r:Int,c:Int,d:Intent?){super.onActivityResult(r,c,d);if(r==6202&&c==RESULT_OK){invoiceUri=d?.data?.toString()?:"";invoiceUri=invoiceUri.trim('"');Toast.makeText(this,"Document attached",Toast.LENGTH_LONG).show()}}
 private fun history(id:String):Pair<Int,Double>{val rows=store.all("credits").filter{it.optString("lenderId")==id||it.optString("borrowerId")==id};return rows.size to rows.filter{it.optString("status")=="ACTIVE"}.sumOf{it.optDouble("outstanding",0.0)}};private fun score(n:Int,out:Double)=if(n==0)"NEW" else when{out<=0->"A+";n<3->"A";out<10000->"B+";else->"B"}
}
