package com.udhaardaar.mvp

import android.app.AlertDialog
import android.app.DatePickerDialog
import android.graphics.Color
import android.graphics.Typeface
import android.os.Bundle
import android.text.Editable
import android.text.TextWatcher
import android.view.Gravity
import android.view.WindowManager
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import org.json.JSONObject
import java.text.SimpleDateFormat
import java.util.Calendar
import java.util.Locale
import kotlin.math.pow

/** ArthSaathi V6.2 guided credit registration with live EMI calculation. */
class V62CreditRegistrationActivity : AppCompatActivity() {
    private val store by lazy { V5LocalStore(this) }
    private val consent by lazy { V5OtpConsentService(this) }
    private val prefs by lazy { getSharedPreferences("udhaardaar_accounts", MODE_PRIVATE) }
    private val draft by lazy { getSharedPreferences("v62_credit_draft", MODE_PRIVATE) }
    private val navy=Color.rgb(16,45,82); private val teal=Color.rgb(12,171,158); private val blue=Color.rgb(42,103,221)
    private val green=Color.rgb(18,137,91); private val red=Color.rgb(193,67,72); private val muted=Color.rgb(92,108,124)
    private val bg=Color.rgb(246,249,252); private val border=Color.rgb(220,228,236)
    private var lender:JSONObject?=null; private var borrower:JSONObject?=null; private var guarantor:JSONObject?=null; private var step=1
    private lateinit var root:LinearLayout
    private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt()
    private fun tv(s:String,size:Float,color:Int=navy,bold:Boolean=false)=TextView(this).apply{text=s;textSize=size;setTextColor(color);typeface=Typeface.create("sans-serif",if(bold)Typeface.BOLD else Typeface.NORMAL)}
    private fun card(fill:Int=Color.WHITE)=android.graphics.drawable.GradientDrawable().apply{setColor(fill);setStroke(dp(1),border);cornerRadius=dp(16).toFloat()}
    private fun field(h:String)=EditText(this).apply{hint=h;setSingleLine(true);textSize=15f;setPadding(dp(12),dp(9),dp(12),dp(9));background=card()}
    private fun btn(s:String,action:()->Unit)=Button(this).apply{text=s;setTextColor(Color.WHITE);setBackgroundColor(blue);setOnClickListener{action()}}
    private fun add(v:android.view.View,top:Int=8){root.addView(v,LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(top)})}
    private fun lp(top:Int=7)=LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(top)}
    override fun onCreate(b:Bundle?){super.onCreate(b);window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);if(!prefs.getBoolean("logged_in",false)){finish();return};render()}
    private fun render(){root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(16),dp(12),dp(16),dp(24));setBackgroundColor(bg)};setContentView(ScrollView(this).apply{isFillViewport=true;addView(root)});add(tv("ARTHSAATHI",24f,navy,true),0);add(tv("Register Credit",18f,teal,true),2);add(tv("A guided, profile-linked journey",11f,muted),2);add(stepBar(),12);when(step){1->profileStep();2->termsStep();3->guarantorStep();else->consentStep()}}
    private fun stepBar():LinearLayout{val b=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};arrayOf("1 Profile","2 Terms","3 Guarantor","4 Consent").forEachIndexed{i,s->val x=tv(s,10f,if(i+1<=step)teal else muted,i+1<=step);x.gravity=Gravity.CENTER;x.setPadding(dp(3),dp(8),dp(3),dp(8));x.background=card(if(i+1<=step)Color.rgb(235,249,247) else Color.WHITE);b.addView(x,LinearLayout.LayoutParams(0,dp(40),1f).apply{if(i>0)leftMargin=dp(4)})};return b}
    private fun profileStep(){add(tv("WHO IS INVOLVED?",11f,muted,true),16);profileCard("LENDER",lender,blue){chooseProfile("Select lender"){lender=it;render()}};profileCard("BORROWER",borrower,green){chooseProfile("Select borrower"){borrower=it;render()}};if(lender!=null&&borrower!=null&&lender!!.optString("id")!=borrower!!.optString("id"))add(btn("CONTINUE TO CREDIT TERMS  →"){step=2;render()},16);add(tv("Search by name, mobile, PAN, Aadhaar, GSTIN or profile ID. Consent-based history, outstanding and score are shown before selection.",11f,muted),12)}
    private fun profileCard(role:String,p:JSONObject?,accent:Int,action:()->Unit){val b=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(14),dp(12),dp(14),dp(12));background=card();setOnClickListener{action()}};b.addView(tv(role,10f,accent,true));if(p==null){b.addView(tv("Tap to search or create a registered profile",15f,navy,true),lp(4));b.addView(tv("Name • Mobile • PAN • Aadhaar • GSTIN",10f,muted),lp(2))}else{b.addView(tv("${p.optString("name")} • ${p.optString("id")}",15f,navy,true),lp(4));val rows=relatedCredits(p.optString("id"));val out=rows.filter{it.optString("status")=="ACTIVE"}.sumOf{it.optDouble("outstanding",0.0)};b.addView(tv("${p.optString("mobile")} • History ${rows.size} • Outstanding ₹${"%.0f".format(out)} • Score ${score(rows)}",10f,teal,true),lp(6))};add(b,7)}
    private fun chooseProfile(title:String,done:(JSONObject)->Unit){val search=field("Search name / mobile / PAN / Aadhaar / GSTIN / profile ID");val list=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(4),dp(4),dp(4),dp(4));addView(search);addView(list,lp())};val d=AlertDialog.Builder(this).setTitle(title).setView(box).setNegativeButton("CANCEL",null).create();fun refresh(){list.removeAllViews();val q=search.text.toString().trim().lowercase();val rows=store.all("profiles").filter{p->q.isEmpty()||listOf("id","name","mobile","pan","aadhaar","gstin").any{p.optString(it).lowercase().contains(q)}};if(rows.isEmpty()){list.addView(tv("No registered profile found",12f,red,true));list.addView(btn("CREATE NEW PROFILE"){d.dismiss();createProfile(done)},lp(8))}else rows.take(12).forEach{p->list.addView(Button(this).apply{text="${p.optString("name")} • ${p.optString("id")}\n${p.optString("mobile")}";gravity=Gravity.START;setOnClickListener{d.dismiss();showHistory(p){done(p)}}},lp(5))}};search.addTextChangedListener(object:TextWatcher{override fun beforeTextChanged(s:CharSequence?,st:Int,c:Int,a:Int){};override fun onTextChanged(s:CharSequence?,st:Int,b:Int,c:Int){refresh()};override fun afterTextChanged(e:Editable?){}});d.show();refresh()}
    private fun showHistory(p:JSONObject,done:()->Unit){val rows=relatedCredits(p.optString("id"));val out=rows.filter{it.optString("status")=="ACTIVE"}.sumOf{it.optDouble("outstanding",0.0)};val msg="Profile ID: ${p.optString("id")}\nMobile: ${p.optString("mobile")}\nRelated credits: ${rows.size}\nOutstanding: ₹${"%.2f".format(out)}\nConsent-based score: ${score(rows)}\n\nOnly consented transaction history is used.";val d=AlertDialog.Builder(this).setTitle("${p.optString("name")} • history").setMessage(msg).setNegativeButton("CANCEL",null).setPositiveButton("SELECT",null).create();d.setOnShowListener{d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener{d.dismiss();done()}};d.show()}
    private fun createProfile(done:(JSONObject)->Unit){val n=field("Full name / business name *");val m=field("Mobile number *");val pan=field("PAN (optional)");val aad=field("Aadhaar (optional)");val gst=field("GSTIN (optional)");val f=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;addView(n);addView(m,lp());addView(pan,lp());addView(aad,lp());addView(gst,lp())};val d=AlertDialog.Builder(this).setTitle("Create registered profile").setView(f).setNegativeButton("CANCEL",null).setPositiveButton("SAVE + CONTINUE",null).create();d.setOnShowListener{d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener{val name=n.text.toString().trim();val mob=m.text.toString().trim();val pv=pan.text.toString().trim().uppercase();val gv=gst.text.toString().trim().uppercase();when{name.length<2->n.error="Enter at least 2 characters";!V5Validation.mobile(mob)->m.error="Enter a valid 10-digit Indian mobile number";store.all("profiles").any{it.optString("mobile")==mob}->m.error="Mobile already registered";pv.isNotBlank()&&!Regex("[A-Z]{5}[0-9]{4}[A-Z]").matches(pv)->pan.error="Invalid PAN format";gv.isNotBlank()&&!Regex("[0-9]{2}[A-Z0-9]{13}").matches(gv)->gst.error="Invalid GSTIN format";else->{val p=JSONObject().apply{put("id","USR-${System.currentTimeMillis()}");put("name",name);put("mobile",mob);put("pan",pv);put("aadhaar",aad.text.toString().trim());put("gstin",gv);put("createdAt",System.currentTimeMillis())};store.add("profiles",p);d.dismiss();done(p)}}}};d.show()}
    private fun termsStep(){add(tv("CREDIT TERMS",11f,muted,true),16);val amount=field("Principal amount ₹ *");val roi=field("Interest / ROI %");val start=field("Start date — tap to select");val end=field("End / due date — tap to select");val emi=field("EMI amount ₹ — auto calculated").apply{isFocusable=false;isClickable=false};val tenure=tv("Enter amount, ROI and dates to calculate EMI",11f,teal,true);val notes=field("Purpose / notes (optional)");val method=Spinner(this).apply{adapter=ArrayAdapter(this@V62CreditRegistrationActivity,android.R.layout.simple_spinner_dropdown_item,arrayOf("EMI","Principal + Interest","Bullet / single payment"))};val period=Spinner(this).apply{adapter=ArrayAdapter(this@V62CreditRegistrationActivity,android.R.layout.simple_spinner_dropdown_item,arrayOf("Monthly","Quarterly","Half-yearly","Yearly","One-time"))};datePicker(start);datePicker(end);add(labelled("Principal",amount));add(labelled("ROI",roi));add(labelled("Start",start));add(labelled("End",end));add(labelled("Repayment method",method));add(labelled("Periodicity",period));add(labelled("Auto EMI",emi));add(tenure,4);add(labelled("Notes",notes));add(tv("LENDER  ${lender!!.optString("name")}  →  BORROWER  ${borrower!!.optString("name")}",11f,teal,true),12)
        fun recalc(){if(method.selectedItemPosition!=0){emi.setText("");tenure.text="EMI auto-calculation applies when repayment method is EMI";return};val p=amount.text.toString().replace(",","").toDoubleOrNull();val rate=roi.text.toString().replace(",","").toDoubleOrNull()?:0.0;val s=parseDate(start.text.toString());val e=parseDate(end.text.toString());if(p==null||p<=0||s==null||e==null||e.time<=s.time){emi.setText("");tenure.text="Enter amount, ROI and valid start/end dates";return};val periodsPerYear=when(period.selectedItemPosition){0->12;1->4;2->2;3->1;else->0};if(periodsPerYear==0){emi.setText("");tenure.text="One-time repayment does not use EMI";return};val months=((e.time-s.time).toDouble()/(1000.0*60*60*24*30.4375));val n=kotlin.math.max(1,kotlin.math.round(months/(12.0/periodsPerYear)).toInt());val periodicRate=rate/100.0/periodsPerYear;val payment=if(periodicRate==0.0)p/n else p*periodicRate*(1+periodicRate).pow(n)/((1+periodicRate).pow(n)-1);emi.setText(String.format(Locale.US,"%.2f",payment));tenure.text="$n ${if(n==1)"installment" else "installments"} • estimated total repayment ₹${String.format(Locale.US,"%.2f",payment*n)}"}
        val watcher=object:TextWatcher{override fun beforeTextChanged(s:CharSequence?,st:Int,c:Int,a:Int){};override fun onTextChanged(s:CharSequence?,st:Int,b:Int,c:Int){recalc()};override fun afterTextChanged(e:Editable?){}};amount.addTextChangedListener(watcher);roi.addTextChangedListener(watcher);start.addTextChangedListener(watcher);end.addTextChangedListener(watcher);method.onItemSelectedListener=object:android.widget.AdapterView.OnItemSelectedListener{override fun onNothingSelected(p:android.widget.AdapterView<*>?){};override fun onItemSelected(p:android.widget.AdapterView<*>?,v:android.view.View?,pos:Int,id:Long){recalc()}};period.onItemSelectedListener=object:android.widget.AdapterView.OnItemSelectedListener{override fun onNothingSelected(p:android.widget.AdapterView<*>?){};override fun onItemSelected(p:android.widget.AdapterView<*>?,v:android.view.View?,pos:Int,id:Long){recalc()}}
        add(two(btn("← BACK"){step=1;render()},btn("CONTINUE →"){val a=amount.text.toString().toDoubleOrNull();val r=roi.text.toString().toDoubleOrNull()?:0.0;val em=emi.text.toString().toDoubleOrNull()?:0.0;when{a==null||a<=0->amount.error="Enter a positive amount";r<0->roi.error="ROI cannot be negative";start.text.isNullOrBlank()->start.error="Select start date";end.text.isNullOrBlank()->end.error="Select end date";method.selectedItemPosition==0&&em<=0->emi.error="EMI could not be calculated — check amount, ROI and dates";else->{draft.edit().putString("amount",a.toString()).putString("roi",r.toString()).putString("start",start.text.toString()).putString("end",end.text.toString()).putString("method",method.selectedItem.toString()).putString("period",period.selectedItem.toString()).putString("emi",em.toString()).putString("notes",notes.text.toString()).apply();step=3;render()}}}),16)
    }
    private fun labelled(title:String,v:android.view.View)=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;addView(tv(title,10f,muted,true));addView(v,lp())}
    private fun two(a:Button,b:Button)=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;addView(a,LinearLayout.LayoutParams(0,dp(52),1f).apply{rightMargin=dp(5)});addView(b,LinearLayout.LayoutParams(0,dp(52),1f).apply{leftMargin=dp(5)})}
    private fun datePicker(target:EditText){target.isFocusable=false;target.setOnClickListener{val c=Calendar.getInstance();DatePickerDialog(this,{_,y,m,d->c.set(y,m,d);target.setText(SimpleDateFormat("dd MMM yyyy",Locale.getDefault()).format(c.time))},c.get(Calendar.YEAR),c.get(Calendar.MONTH),c.get(Calendar.DAY_OF_MONTH)).show()}}
    private fun parseDate(s:String)=runCatching{SimpleDateFormat("dd MMM yyyy",Locale.getDefault()).parse(s)}.getOrNull()
    private fun guarantorStep(){add(tv("GUARANTOR & DOCUMENT",11f,muted,true),16);add(tv("Optional guarantor. Link a digital document such as DPN, invoice or agreement.",11f,muted),4);val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(14),dp(14),dp(14),dp(14));background=card()};if(guarantor==null){box.addView(tv("No guarantor selected",15f,navy,true));box.addView(Button(this).apply{text="ADD GUARANTOR";setOnClickListener{chooseProfile("Select guarantor"){guarantor=it;render()}}},lp())}else{box.addView(tv("${guarantor!!.optString("name")} • ${guarantor!!.optString("id")}",15f,navy,true));box.addView(Button(this).apply{text="REMOVE GUARANTOR";setOnClickListener{guarantor=null;render()}},lp())};add(box,8);val doc=field("Digital document reference — DPN / invoice / agreement");add(labelled("Digital document",doc),12);add(two(btn("← BACK"){step=2;render()},btn("REVIEW + CONSENT →"){draft.edit().putString("document",doc.text.toString()).apply();step=4;render()}),16)}
    private fun consentStep(){val amount=draft.getString("amount","0")?:"0";val roi=draft.getString("roi","0")?:"0";val start=draft.getString("start","")?:"";val end=draft.getString("end","")?:"";val method=draft.getString("method","")?:"";val period=draft.getString("period","")?:"";val emi=draft.getString("emi","0")?:"0";val doc=draft.getString("document","")?:"";add(tv("FINAL REVIEW",11f,muted,true),16);val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(14),dp(14),dp(14),dp(14));background=card(Color.rgb(239,249,246))};r.addView(tv("₹$amount • $method • $period",17f,navy,true));r.addView(tv("ROI $roi% • $start → $end • EMI ₹$emi",11f,muted),lp());r.addView(tv("Lender: ${lender!!.optString("name")}\nBorrower: ${borrower!!.optString("name")}${guarantor?.let{"\nGuarantor: ${it.optString("name")}"}?:""}",11f,navy),lp());r.addView(tv("Document: ${doc.ifBlank{"Not specified"}}",10f,muted),lp());add(r,8);add(tv("Both lender and borrower consent are required.",10f,muted),10);add(btn("REQUEST CONSENT OTP"){requestConsent(amount,roi,start,end,method,period,doc)},16);add(btn("← BACK TO GUARANTOR"){step=3;render()},6)}
    private fun requestConsent(amount:String,roi:String,start:String,end:String,method:String,period:String,doc:String){val id="CR-${System.currentTimeMillis()}";val bc=consent.issue(id,"CREDIT_CONSENT_BORROWER",borrower!!.optString("id"));val lc=consent.issue(id,"CREDIT_CONSENT_LENDER",lender!!.optString("id"));val bo=store.find("consents",bc)?.optString("otp","")?:"";val lo=store.find("consents",lc)?.optString("otp","")?:"";val b=field("Borrower OTP");val l=field("Lender OTP");val f=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;addView(tv("Borrower demo OTP: $bo",11f,teal,true));addView(b,lp());addView(tv("Lender demo OTP: $lo",11f,teal,true),lp());addView(l,lp())};val d=AlertDialog.Builder(this).setTitle("Consent verification").setMessage("Verify both parties before creating the credit record.").setView(f).setNegativeButton("CANCEL",null).setPositiveButton("VERIFY + REGISTER",null).create();d.setOnShowListener{d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener{if(!consent.verify(bc,b.text.toString().trim())||!consent.verify(lc,l.text.toString().trim())){Toast.makeText(this,"Consent not verified — record not created",Toast.LENGTH_LONG).show();return@setOnClickListener};val c=JSONObject().apply{put("id",id);put("lenderId",lender!!.optString("id"));put("borrowerId",borrower!!.optString("id"));put("principal",amount.toDoubleOrNull()?:0.0);put("interestRate",roi.toDoubleOrNull()?:0.0);put("startDate",start);put("dueDate",end);put("repaymentMethod",method);put("periodicity",period);put("emiAmount",emiSafe());put("notes",draft.getString("notes","")?:"");put("documentRef",doc);put("guarantorId",guarantor?.optString("id")?:"");put("outstanding",amount.toDoubleOrNull()?:0.0);put("status","ACTIVE");put("consentIdBorrower",bc);put("consentIdLender",lc);put("createdAt",System.currentTimeMillis())};store.add("credits",c);draft.edit().clear().apply();d.dismiss();AlertDialog.Builder(this).setTitle("Credit registered ✓").setMessage("$id is registered with both-party consent.\n\n₹$amount outstanding\nDue: $end\nMethod: $method").setPositiveButton("DONE"){_,_->finish()}.show()}};d.show()}
    private fun emiSafe()=draft.getString("emi","0")?.toDoubleOrNull()?:0.0
    private fun relatedCredits(id:String)=store.all("credits").filter{it.optString("lenderId")==id||it.optString("borrowerId")==id}
    private fun score(rows:List<JSONObject>):Int{if(rows.isEmpty())return 700;val principal=rows.sumOf{it.optDouble("principal",0.0)};val paid=rows.sumOf{(it.optDouble("principal",0.0)-it.optDouble("outstanding",0.0)).coerceAtLeast(0.0)};return (650+(if(principal>0)paid/principal else 0.0).coerceIn(0.0,1.0)*220).toInt().coerceIn(300,900)}
}
