package com.udhaardaar.mvp

import android.app.AlertDialog
import android.app.DatePickerDialog
import android.content.Intent
import android.graphics.Color
import android.graphics.Typeface
import android.graphics.drawable.GradientDrawable
import android.os.Bundle
import android.text.*
import android.view.*
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import org.json.JSONObject
import java.text.SimpleDateFormat
import java.util.*
import kotlin.math.pow
import kotlin.random.Random

class V62CreditRegistrationActivity : AppCompatActivity() {
    private val store by lazy { V5LocalStore(this) }
    private val prefs by lazy { getSharedPreferences("udhaardaar_accounts", MODE_PRIVATE) }
    private val draft by lazy { getSharedPreferences("v62_credit_draft", MODE_PRIVATE) }
    private val navy=Color.rgb(16,45,82); private val teal=Color.rgb(12,155,145); private val blue=Color.rgb(42,103,221); private val green=Color.rgb(18,137,91); private val gold=Color.rgb(211,161,37); private val red=Color.rgb(193,67,72); private val bg=Color.rgb(246,249,252); private val border=Color.rgb(220,228,236); private val muted=Color.rgb(92,108,124)
    private var lender:JSONObject?=null; private var borrower:JSONObject?=null; private var guarantor:JSONObject?=null; private var invoiceUri=""; private var step=1
    private lateinit var root:LinearLayout
    private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt()
    private fun card()=GradientDrawable().apply{setColor(Color.WHITE);setStroke(dp(1),border);cornerRadius=dp(14).toFloat()}
    private fun tv(s:String,z:Float=13f,c:Int=navy,b:Boolean=false)=TextView(this).apply{text=s;textSize=z;setTextColor(c);typeface=Typeface.create("sans-serif",if(b)Typeface.BOLD else Typeface.NORMAL);includeFontPadding=false}
    private fun field(h:String)=EditText(this).apply{hint=h;textSize=15f;setTextColor(navy);setHintTextColor(muted);setSingleLine(true);setPadding(dp(13),dp(10),dp(13),dp(10));minHeight=dp(52);background=card()}
    private fun btn(s:String,c:Int=blue,f:()->Unit)=Button(this).apply{text=s;textSize=13f;setTextColor(Color.WHITE);setAllCaps(false);minHeight=dp(50);setBackgroundColor(c);setOnClickListener{f()}}
    private fun add(v:View,t:Int=7){root.addView(v,LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(t)})}
    private fun margin(t:Int=6)=LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(t)}
    override fun onCreate(b:Bundle?){super.onCreate(b);window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);if(!prefs.getBoolean("logged_in",false)){startActivity(Intent(this,LoginActivity::class.java));finish();return};render()}
    private fun render(){root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(16),dp(12),dp(16),dp(28));setBackgroundColor(bg)};val h=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL};h.addView(ImageView(this).apply{setImageResource(R.drawable.udhaardaar_logo);scaleType=ImageView.ScaleType.CENTER_INSIDE},LinearLayout.LayoutParams(dp(44),dp(44)));h.addView(tv("ArthSaathi\nRegister Credit",18f,navy,true),LinearLayout.LayoutParams(0,-2,1f).apply{leftMargin=dp(10)});h.addView(tv("$step / 4",11f,teal,true));root.addView(h);add(tv("Search registered profiles → terms → guarantor/document → consent OTP → registration",10f,muted),5);add(stepBar(),8);when(step){1->profileStep();2->termsStep();3->guarantorStep();4->consentStep()};setContentView(ScrollView(this).apply{isFillViewport=true;addView(root)})}
    private fun stepBar()=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;arrayOf("Profile","Terms","Guarantor","Consent").forEachIndexed{i,s->val x=tv("${i+1}. $s",9f,if(i+1<=step)teal else muted,i+1<=step);x.gravity=Gravity.CENTER;x.setPadding(dp(4),dp(5),dp(4),dp(5));x.background=card();addView(x,LinearLayout.LayoutParams(0,dp(38),1f).apply{if(i>0)leftMargin=dp(4)})}}
    private fun profileStep(){add(tv("1  WHO IS INVOLVED?",11f,muted,true),15);party("LENDER",lender,blue){choose("Select lender"){lender=it;render()}};party("BORROWER",borrower,green){choose("Select borrower"){borrower=it;render()}};if(lender!=null&&borrower!=null&&lender!!.optString("id")!=borrower!!.optString("id"))add(btn("Continue to Credit Terms  →"){step=2;render()},14);add(tv("Search by name, mobile, PAN, Aadhaar, GSTIN or profile ID. Consent-based history/outstanding/score is displayed before selection.",10f,muted),10)}
    private fun party(role:String,p:JSONObject?,accent:Int,f:()->Unit){val c=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(13),dp(12),dp(13),dp(12));background=card();setOnClickListener{f()}};c.addView(tv(role,10f,accent,true));if(p==null){c.addView(tv("Tap to search or create registered profile",15f,navy,true),margin(3));c.addView(tv("Name • Mobile • PAN • Aadhaar • GSTIN",10f,muted),margin(2))}else{val h=history(p.optString("id"));c.addView(tv("${p.optString("name")} • ${p.optString("id")}",15f,navy,true),margin(3));c.addView(tv("${p.optString("mobile")} • ${h.first} records • ₹${"%.0f".format(h.second)} outstanding • Score ${score(h.first,h.second)}",10f,teal,true),margin(3))};add(c,7)}
    private fun choose(title:String,done:(JSONObject)->Unit){val q=field("Search name / mobile / PAN / Aadhaar / GSTIN / profile ID");val list=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};val wrap=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;addView(q);addView(list,margin())};val d=AlertDialog.Builder(this).setTitle(title).setView(wrap).setNegativeButton("CANCEL",null).create();fun refresh(){list.removeAllViews();val x=q.text.toString().trim().lowercase();val rows=store.all("profiles").filter{p->x.isEmpty()||listOf("id","name","mobile","pan","aadhaar","gstin").any{p.optString(it).lowercase().contains(x)}};if(rows.isEmpty()){list.addView(tv("No registered profile found",11f,red,true));list.addView(btn("CREATE NEW PROFILE",teal){d.dismiss();createProfile(done)},margin(7))}else rows.take(15).forEach{p->list.addView(btn("${p.optString("name")} • ${p.optString("mobile")}\n${p.optString("id")}",Color.DKGRAY){d.dismiss();showHistory(p){done(p)}},margin(5))}};q.addTextChangedListener(object:TextWatcher{override fun beforeTextChanged(s:CharSequence?,a:Int,c:Int,d:Int){};override fun onTextChanged(s:CharSequence?,a:Int,b:Int,c:Int){refresh()};override fun afterTextChanged(e:Editable?){}});d.show();refresh()}
    private fun showHistory(p:JSONObject,done:()->Unit){val h=history(p.optString("id"));AlertDialog.Builder(this).setTitle("${p.optString("name")} • history").setMessage("Profile ID: ${p.optString("id")}\nMobile: ${p.optString("mobile")}\nRelated credits: ${h.first}\nOutstanding: ₹${"%.2f".format(h.second)}\nScore: ${score(h.first,h.second)}\n\nOnly consented transaction history is used.").setNegativeButton("CANCEL",null).setPositiveButton("SELECT"){_,_->done()}.show()}
    private fun createProfile(done:(JSONObject)->Unit){val n=field("Full name / business name *");val m=field("Mobile number *");val pan=field("PAN");val aad=field("Aadhaar");val gst=field("GSTIN");val wrap=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;addView(n);addView(m,margin());addView(pan,margin());addView(aad,margin());addView(gst,margin())};val d=AlertDialog.Builder(this).setTitle("Create registered profile").setView(wrap).setNegativeButton("CANCEL",null).setPositiveButton("SAVE + RETURN",null).create();d.setOnShowListener{d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener{val name=n.text.toString().trim();val mob=m.text.toString().trim();val pv=pan.text.toString().trim().uppercase();val gv=gst.text.toString().trim().uppercase();when{name.length<2->n.error="Enter name";!V5Validation.mobile(mob)->m.error="Enter valid 10-digit mobile";store.all("profiles").any{it.optString("mobile")==mob}->m.error="Mobile already registered";pv.isNotBlank()&&!Regex("[A-Z]{5}[0-9]{4}[A-Z]").matches(pv)->pan.error="Invalid PAN";gv.isNotBlank()&&!Regex("[0-9]{2}[A-Z0-9]{13}").matches(gv)->gst.error="Invalid GSTIN";else->{val p=JSONObject().apply{put("id","USR-${System.currentTimeMillis()}");put("name",name);put("mobile",mob);put("pan",pv);put("aadhaar",aad.text.toString().trim());put("gstin",gv)};store.add("profiles",p);d.dismiss();done(p)}}}};d.show()}
    private fun termsStep(){add(tv("2  CREDIT TERMS & LIVE EMI",11f,muted,true),15);val type=Spinner(this).apply{adapter=ArrayAdapter(this@V62CreditRegistrationActivity,android.R.layout.simple_spinner_dropdown_item,arrayOf("Personal / Hand Loan","Trade Credit","Rental / Lease","Other Credit"))};val amount=field("Principal amount ₹ *");val roi=field("ROI / interest %");val start=field("Start date — select");val end=field("End / due date — select");val method=Spinner(this).apply{adapter=ArrayAdapter(this@V62CreditRegistrationActivity,android.R.layout.simple_spinner_dropdown_item,arrayOf("EMI","Principal + Interest","Bullet / single payment"))};val period=Spinner(this).apply{adapter=ArrayAdapter(this@V62CreditRegistrationActivity,android.R.layout.simple_spinner_dropdown_item,arrayOf("Monthly","Quarterly","Half-yearly","Yearly","One-time"))};val emi=field("EMI — automatically calculated").apply{isFocusable=false};val summary=tv("Enter principal, ROI and valid dates.",10f,teal,true);date(start);date(end);add(label("Credit type",type));add(label("Principal",amount));add(label("ROI",roi));add(label("Start",start));add(label("End",end));add(label("Repayment method",method));add(label("Periodicity",period));add(label("Auto EMI",emi));add(summary,3);if(type.selectedItemPosition==1){add(tv("Trade credit: attach invoice/supporting document in the next step.",10f,muted),5)}
        fun recalc(){if(method.selectedItemPosition!=0){emi.setText("");summary.text="Selected method does not use EMI.";return};val p=amount.text.toString().replace(",","").toDoubleOrNull();val rate=roi.text.toString().toDoubleOrNull()?:0.0;val s=parse(start.text.toString());val e=parse(end.text.toString());if(p==null||p<=0||s==null||e==null||e.time<=s.time){emi.setText("");summary.text="Enter principal, ROI and valid dates.";return};val freq=when(period.selectedItemPosition){0->12;1->4;2->2;3->1;else->0};if(freq==0){emi.setText("");summary.text="One-time repayment selected.";return};val months=(e.time-s.time).toDouble()/(1000*60*60*24*30.4375);val n=maxOf(1,kotlin.math.round(months/(12.0/freq)).toInt());val r=rate/100.0/freq;val pay=if(r==0.0)p/n else p*r*(1+r).pow(n)/((1+r).pow(n)-1);emi.setText("%.2f".format(Locale.US,pay));summary.text="$n installments • estimated total ₹${"%.2f".format(Locale.US,pay*n)}"}
        val w=object:TextWatcher{override fun beforeTextChanged(s:CharSequence?,a:Int,c:Int,d:Int){};override fun onTextChanged(s:CharSequence?,a:Int,b:Int,c:Int){recalc()};override fun afterTextChanged(e:Editable?){}};amount.addTextChangedListener(w);roi.addTextChangedListener(w);start.addTextChangedListener(w);end.addTextChangedListener(w);method.onItemSelectedListener=spin{recalc()};period.onItemSelectedListener=spin{recalc()};add(two(btn("← Back"){step=1;render()},btn("Continue →"){if(amount.text.toString().toDoubleOrNull().orZero()<=0)amount.error="Enter amount" else {draft.edit().putString("amount",amount.text.toString()).putString("roi",roi.text.toString()).putString("start",start.text.toString()).putString("end",end.text.toString()).putString("type",type.selectedItem.toString()).putString("method",method.selectedItem.toString()).putString("period",period.selectedItem.toString()).putString("emi",emi.text.toString()).apply();step=3;render()}}),14)}
    private fun Double?.orZero()=this?:0.0
    private fun label(s:String,v:View)=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;addView(tv(s,10f,muted,true));addView(v,margin())};private fun two(a:Button,b:Button)=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;addView(a,LinearLayout.LayoutParams(0,dp(50),1f).apply{rightMargin=dp(4)});addView(b,LinearLayout.LayoutParams(0,dp(50),1f).apply{leftMargin=dp(4)})};private fun spin(f:()->Unit)=object:AdapterView.OnItemSelectedListener{override fun onNothingSelected(p:AdapterView<*>?){};override fun onItemSelected(p:AdapterView<*>?,v:View?,pos:Int,id:Long){f()}}
    private fun date(e:EditText){e.isFocusable=false;e.setOnClickListener{val c=Calendar.getInstance();DatePickerDialog(this,{_,y,m,d->c.set(y,m,d);e.setText(SimpleDateFormat("dd MMM yyyy",Locale.getDefault()).format(c.time))},c.get(Calendar.YEAR),c.get(Calendar.MONTH),c.get(Calendar.DAY_OF_MONTH)).show()}}
    private fun parse(s:String)=runCatching{SimpleDateFormat("dd MMM yyyy",Locale.getDefault()).parse(s)}.getOrNull()
    private fun guarantorStep(){add(tv("3  GUARANTOR & DIGITAL DOCUMENT",11f,muted,true),15);val c=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(13),dp(12),dp(13),dp(12));background=card()};if(guarantor==null){c.addView(tv("No guarantor selected",14f,navy,true));c.addView(btn("Add guarantor",teal){choose("Select guarantor"){guarantor=it;render()}},margin(7))}else{c.addView(tv("${guarantor!!.optString("name")} • ${guarantor!!.optString("id")}",14f,navy,true));c.addView(btn("Remove guarantor",red){guarantor=null;render()},margin(7))};add(c);add(btn("ATTACH INVOICE / DPN / AGREEMENT",teal){pickInvoice()},12);add(tv(if(invoiceUri.isBlank())"No supporting document attached" else "Supporting document attached",10f,muted),3);add(two(btn("← Back"){step=2;render()},btn("Review & Consent →"){step=4;render()}),14)}
    private fun consentStep(){add(tv("4  REVIEW, CONSENT & OTP",11f,muted,true),15);val review=tv("LENDER: ${lender!!.optString("name")}\nBORROWER: ${borrower!!.optString("name")}\nPrincipal: ₹${draft.getString("amount","")}\nROI: ${draft.getString("roi","")}%\nMethod: ${draft.getString("method","")}\nPeriodicity: ${draft.getString("period","")}\nEMI: ₹${draft.getString("emi","")}\nGuarantor: ${guarantor?.optString("name")?:("Not added")}\nDocument: ${if(invoiceUri.isBlank())"Not attached" else "Attached"}",13f,navy,true);review.setPadding(dp(14),dp(14),dp(14),dp(14));review.background=card();add(review);add(tv("Both parties must consent. Until production SMS is connected, the demo OTP is displayed for testing.",10f,muted),10);add(btn("REQUEST CONSENT OTP",teal){otp()},14);add(btn("← Back to guarantor",Color.rgb(90,105,120)){step=3;render()},7)}
    private fun otp(){val code=(100000+Random.nextInt(900000)).toString();val e=field("Enter 6-digit OTP");val d=AlertDialog.Builder(this).setTitle("Two-party digital consent").setMessage("Demo OTP: $code\nConsent target: ${borrower!!.optString("name")}").setView(e).setNegativeButton("CANCEL",null).setPositiveButton("CONFIRM",null).create();d.setOnShowListener{d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener{if(e.text.toString()==code){saveFinal();d.dismiss()}else e.error="Incorrect OTP"}};d.show()}
    private fun saveFinal(){val id="CR-${System.currentTimeMillis()}";val principal=draft.getString("amount","0")?.toDoubleOrNull()?:0.0;store.add("credits",JSONObject().apply{put("id",id);put("lenderId",lender!!.optString("id"));put("borrowerId",borrower!!.optString("id"));put("principal",principal);put("interestRate",draft.getString("roi","0")?.toDoubleOrNull()?:0.0);put("startDate",draft.getString("start",""));put("dueDate",draft.getString("end",""));put("repaymentMethod",draft.getString("method",""));put("periodicity",draft.getString("period",""));put("emi",draft.getString("emi","0")?.toDoubleOrNull()?:0.0);put("guarantorId",guarantor?.optString("id")?:(""));put("documentUri",invoiceUri);put("outstanding",principal);put("status","ACTIVE");put("consentStatus","OTP_VERIFIED");put("createdAt",System.currentTimeMillis())});draft.edit().clear().apply();AlertDialog.Builder(this).setTitle("Credit registered").setMessage("Reference: $id\nThe record is linked to the registered parties and consent status.").setPositiveButton("DONE"){_,_->finish()}.show()}
    private fun pickInvoice(){startActivityForResult(Intent(Intent.ACTION_OPEN_DOCUMENT).apply{type="*/*";addCategory(Intent.CATEGORY_OPENABLE);putExtra(Intent.EXTRA_MIME_TYPES,arrayOf("application/pdf","image/*"))},6202)}
    override fun onActivityResult(r:Int,c:Int,d:Intent?){super.onActivityResult(r,c,d);if(r==6202&&c==RESULT_OK){invoiceUri=d?.data?.toString()?:("");Toast.makeText(this,"Document attached",Toast.LENGTH_LONG).show()}}
    private fun history(id:String):Pair<Int,Double>{val rows=store.all("credits").filter{it.optString("lenderId")==id||it.optString("borrowerId")==id};return rows.size to rows.filter{it.optString("status")=="ACTIVE"}.sumOf{it.optDouble("outstanding",0.0)}}
    private fun score(n:Int,out:Double)=if(n==0)"NEW" else when{out<=0->"A+";n<3->"A";out<10000->"B+";else->"B"}
}
