package com.udhaardaar.mvp

import android.content.Intent
import android.graphics.Color
import android.os.Bundle
import android.view.Gravity
import android.widget.*
import org.json.JSONObject

/** V6.2 extended module shell for domains that must not be hidden behind legacy V5 screens. */
class V62ExtendedModulesActivity : androidx.appcompat.app.AppCompatActivity() {
    private val d get() = resources.displayMetrics.density
    private fun dp(v:Int)=(v*d).toInt()
    private lateinit var root: LinearLayout
    private val store by lazy { V5LocalStore(this) }
    override fun onCreate(b:Bundle?){super.onCreate(b);window.setSoftInputMode(android.view.WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);render()}
    private fun input(h:String)=ArthSaathiV62Design.input(this,h)
    private fun btn(s:String,c:Int=ArthSaathiV62Design.BLUE,go:()->Unit)=ArthSaathiV62Design.button(this,s,c,go)
    private fun add(v:android.view.View,t:Int=8){ArthSaathiV62Design.add(root,v,t)}
    private fun shell(title:String,sub:String){root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(16),dp(12),dp(16),dp(90));setBackgroundColor(ArthSaathiV62Design.BG)};add(ArthSaathiV62Design.title(this,title,sub),0);setContentView(ScrollView(this).apply{isFillViewport=true;addView(root)})}
    private fun menu(){shell("ArthSaathi Financial Centre","Formal credit • QR Khata • ChargeCheck • funding • people • address");add(ArthSaathiV62Design.section(this,"CREDIT & FUNDING"),10);add(btn("FORMAL CREDIT & LOAN OFFERS",ArthSaathiV62Design.BLUE){formal()});add(btn("FUNDING / LENDING REQUEST",ArthSaathiV62Design.TEAL){funding()});add(btn("CHARGECHECK",ArthSaathiV62Design.GOLD){charge()});add(btn("QR UDHAR KHATA",ArthSaathiV62Design.GREEN){khata()});add(ArthSaathiV62Design.section(this,"PEOPLE & DATA"),12);add(btn("PROFILE • FAMILY • CONTACTS",ArthSaathiV62Design.BLUE){people()});add(btn("ADDRESS & LOCATION",ArthSaathiV62Design.TEAL){address()});add(btn("LIABILITY VAULT",ArthSaathiV62Design.RED){liability()});add(btn("GOVERNMENT SCHEMES & BENEFITS",ArthSaathiV62Design.GREEN){benefits()});add(btn("REPORTS & STATEMENTS",ArthSaathiV62Design.NAVY){reports()});add(btn("BACK TO HOME",ArthSaathiV62Design.NAVY){finish()})}
    private fun formal(){shell("Formal Credit","Record or compare authorised formal-credit offers");val provider=input("Bank / NBFC / institution");val product=input("Loan product");val principal=input("Principal amount ₹");val rate=input("Annual interest %");val tenure=input("Tenure months");val fee=input("Processing + other charges ₹");listOf(provider,product,principal,rate,tenure,fee).forEach{add(it)};add(btn("SAVE FORMAL CREDIT OFFER"){store.add("formal_credit",JSONObject().apply{put("id","FC-${System.currentTimeMillis()}");put("provider",provider.text.toString());put("product",product.text.toString());put("principal",principal.text.toString());put("rate",rate.text.toString());put("tenure",tenure.text.toString());put("charges",fee.text.toString())});Toast.makeText(this,"Formal credit offer saved",Toast.LENGTH_SHORT).show()});add(btn("CHARGE & COST COMPARISON",ArthSaathiV62Design.GOLD){charge()});add(btn("BACK",ArthSaathiV62Design.NAVY){menu()})}
    private fun funding(){shell("Funding Marketplace","User-controlled funding request; disclosure only after explicit consent");val purpose=input("Purpose of funding *");val amount=input("Amount required ₹ *");val tenure=input("Preferred tenure months");val source=input("Preferred source: bank / NBFC / institution / permitted user");listOf(purpose,amount,tenure,source).forEach{add(it)};add(btn("REQUEST FUNDING — CONSENT REQUIRED",ArthSaathiV62Design.TEAL){if(purpose.text.isBlank()||amount.text.isBlank()){Toast.makeText(this,"Purpose and amount are required",Toast.LENGTH_SHORT).show();return@btn};AlertDialog.Builder(this).setTitle("Funding consent").setMessage("I authorise ArthSaathi to share the selected credit profile only with providers I choose for this funding request. QR scanning alone does not grant access.").setNegativeButton("CANCEL",null).setPositiveButton("AGREE & CREATE REQUEST"){_,_->store.add("funding_requests",JSONObject().apply{put("id","F-${System.currentTimeMillis()}");put("purpose",purpose.text.toString());put("amount",amount.text.toString());put("tenure",tenure.text.toString());put("source",source.text.toString());put("consent","GRANTED");put("status","REQUESTED")});Toast.makeText(this,"Funding request created",Toast.LENGTH_SHORT).show()}}.show()});add(btn("BACK",ArthSaathiV62Design.NAVY){menu()})}
    private fun charge(){shell("ChargeCheck","Sanctioned vs actual cost with evidence and review");val id=input("Loan/account ID *");val sanctioned=input("Sanctioned interest / charges ₹");val actual=input("Actual interest / charges ₹");val penalty=input("Penalties ₹");val tax=input("Taxes ₹");val evidence=input("Statement / sanction evidence reference");listOf(id,sanctioned,actual,penalty,tax,evidence).forEach{add(it)};add(btn("RUN CHARGECHECK",ArthSaathiV62Design.GOLD){val s=sanctioned.text.toString().toDoubleOrNull()?:0.0;val a=actual.text.toString().toDoubleOrNull()?:0.0;val p=penalty.text.toString().toDoubleOrNull()?:0.0;val t=tax.text.toString().toDoubleOrNull()?:0.0;val variance=a+p+t-s;store.add("chargecheck",JSONObject().apply{put("account",id.text.toString());put("sanctioned",s);put("actual",a);put("penalties",p);put("taxes",t);put("variance",variance);put("evidence",evidence.text.toString());put("status","REVIEW_REQUIRED")});AlertDialog.Builder(this).setTitle("ChargeCheck result").setMessage("Recorded variance: ₹$variance\nStatus: REVIEW REQUIRED\nEvidence: ${evidence.text}").setPositiveButton("OK",null).show()});add(btn("BACK",ArthSaathiV62Design.NAVY){menu()})}
    private fun khata(){shell("QR Udhaar Khata","QR is an entry point to a consented relationship, not an open financial-history key");val party=input("Customer / counterparty identifier *");val amount=input("Credit/debit amount ₹ *");val direction=Spinner(this).apply{adapter=ArrayAdapter(this@V62ExtendedModulesActivity,android.R.layout.simple_spinner_dropdown_item,arrayOf("CREDIT","REPAYMENT"))};val note=input("Invoice / items / note");add(party);add(amount);add(direction);add(note);add(btn("SCAN QR / OPEN RELATIONSHIP",ArthSaathiV62Design.TEAL){startActivity(Intent(this,QrCreditScannerActivity::class.java))});add(btn("RECORD KHATA ENTRY",ArthSaathiV62Design.GREEN){if(party.text.isBlank()||amount.text.isBlank()){Toast.makeText(this,"Party and amount are required",Toast.LENGTH_SHORT).show();return@btn};store.add("qr_khata_v62",JSONObject().apply{put("id","QK-${System.currentTimeMillis()}");put("party",party.text.toString());put("amount",amount.text.toString());put("direction",direction.selectedItem.toString());put("note",note.text.toString());put("status","OPEN")});Toast.makeText(this,"QR Khata entry saved",Toast.LENGTH_SHORT).show()});add(btn("BACK",ArthSaathiV62Design.NAVY){menu()})}
    private fun people(){shell("People & Family","One identity layer shared by credit, assets, insurance and legacy");val name=input("Full name *");val mobile=input("Mobile");val pan=input("PAN");val relation=input("Family / contact relationship");val role=input("Role: borrower / lender / supplier / buyer / nominee / other");listOf(name,mobile,pan,relation,role).forEach{add(it)};add(btn("SAVE PERSON / CONTACT",ArthSaathiV62Design.BLUE){if(name.text.isBlank()){Toast.makeText(this,"Name required",Toast.LENGTH_SHORT).show();return@btn};store.add("people_v62",JSONObject().apply{put("id","P-${System.currentTimeMillis()}");put("name",name.text.toString());put("mobile",mobile.text.toString());put("pan",pan.text.toString());put("relation",relation.text.toString());put("role",role.text.toString())});Toast.makeText(this,"Person saved",Toast.LENGTH_SHORT).show()});add(btn("BACK",ArthSaathiV62Design.NAVY){menu()})}
    private fun address(){shell("Address & Location","Location-assisted capture + PIN enrichment; user confirmation is mandatory");val pin=input("PIN code");val line=input("Address line");val city=input("City");val district=input("District");val state=input("State");listOf(pin,line,city,district,state).forEach{add(it)};add(btn("USE CURRENT LOCATION (PERMISSION REQUIRED)",ArthSaathiV62Design.TEAL){Toast.makeText(this,"Location permission can be requested here; address remains subject to user confirmation.",Toast.LENGTH_LONG).show()});add(btn("SAVE CONFIRMED ADDRESS",ArthSaathiV62Design.BLUE){store.add("addresses_v62",JSONObject().apply{put("pin",pin.text.toString());put("line",line.text.toString());put("city",city.text.toString());put("district",district.text.toString());put("state",state.text.toString());put("source","USER_CONFIRMED")});Toast.makeText(this,"Address saved",Toast.LENGTH_SHORT).show()});add(btn("BACK",ArthSaathiV62Design.NAVY){menu()})}
    private fun liability(){shell("Liability Vault","Loans, obligations and other liabilities connected to the financial snapshot");val name=input("Liability / loan name *");val lender=input("Lender");val outstanding=input("Outstanding ₹");val rate=input("Interest %");val due=input("Next due date");listOf(name,lender,outstanding,rate,due).forEach{add(it)};add(btn("SAVE LIABILITY",ArthSaathiV62Design.RED){store.add("liabilities_v62",JSONObject().apply{put("id","L-${System.currentTimeMillis()}");put("name",name.text.toString());put("lender",lender.text.toString());put("outstanding",outstanding.text.toString());put("rate",rate.text.toString());put("due",due.text.toString())});Toast.makeText(this,"Liability saved",Toast.LENGTH_SHORT).show()});add(btn("BACK",ArthSaathiV62Design.NAVY){menu()})}
    private fun benefits(){shell("Government Schemes & Benefits","Eligibility records and reminders; no automatic enrolment");val name=input("Scheme / benefit");val provider=input("Provider");val condition=input("Eligibility / condition",true);add(name);add(provider);add(condition);add(btn("SAVE BENEFIT & CONDITIONS",ArthSaathiV62Design.GREEN){store.add("benefits_v62",JSONObject().apply{put("id","B-${System.currentTimeMillis()}");put("name",name.text.toString());put("provider",provider.text.toString());put("condition",condition.text.toString())});Toast.makeText(this,"Benefit saved",Toast.LENGTH_SHORT).show()});add(btn("BACK",ArthSaathiV62Design.NAVY){menu()})}
    private fun reports(){shell("Reports & Statements","Connected records from V6.2 modules");val counts=listOf("Formal credit" to "formal_credit","Funding requests" to "funding_requests","ChargeCheck" to "chargecheck","QR Khata" to "qr_khata_v62","People" to "people_v62","Liabilities" to "liabilities_v62");add(ArthSaathiV62Design.text(this,counts.joinToString("\n"){(n,k)->"$n: ${store.all(k).size}"},15f,ArthSaathiV62Design.NAVY,true),10);add(btn("BACK",ArthSaathiV62Design.NAVY){menu()})}
    override fun onBackPressed(){finish()}
    init { }
    private fun render(){menu()}
}
