package com.udhaardaar.mvp

import android.app.AlertDialog
import android.content.Intent
import android.os.Bundle
import android.widget.*
import org.json.JSONObject

/** V6.2 extended first-class modules. */
class V62ExtendedModulesActivity:androidx.appcompat.app.AppCompatActivity(){
 private val d get()=resources.displayMetrics.density
 private lateinit var root:LinearLayout
 private val store by lazy{V5LocalStore(this)}
 private fun dp(v:Int)=(v*d).toInt()
 private fun input(h:String)=ArthSaathiV62Design.input(this,h)
 private fun btn(s:String,c:Int=ArthSaathiV62Design.BLUE,go:()->Unit)=ArthSaathiV62Design.button(this,s,c,go)
 private fun add(v:android.view.View,t:Int=8)=ArthSaathiV62Design.add(root,v,t)
 override fun onCreate(b:Bundle?){super.onCreate(b);window.setSoftInputMode(android.view.WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);menu()}
 private fun shell(title:String,sub:String){root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(16),dp(12),dp(16),dp(90));setBackgroundColor(ArthSaathiV62Design.BG)};setContentView(ScrollView(this).apply{isFillViewport=true;addView(root)});add(ArthSaathiV62Design.title(this,title,sub),0)}
 private fun menu(){shell("Financial Centre","Formal credit • QR Khata • ChargeCheck • funding • people • address");add(ArthSaathiV62Design.section(this,"CREDIT & FUNDING"),10);add(btn("FORMAL CREDIT & LOAN OFFERS"){formal()});add(btn("FUNDING / LENDING REQUEST",ArthSaathiV62Design.TEAL){funding()});add(btn("CHARGECHECK",ArthSaathiV62Design.GOLD){startActivity(Intent(this,V62ChargeCheckActivity::class.java))});add(btn("QR UDHAR KHATA",ArthSaathiV62Design.GREEN){khata()});add(ArthSaathiV62Design.section(this,"PEOPLE & DATA"),12);add(btn("PROFILE • FAMILY • CONTACTS"){people()});add(btn("ADDRESS & LOCATION",ArthSaathiV62Design.TEAL){address()});add(btn("LIABILITY VAULT",ArthSaathiV62Design.RED){liability()});add(btn("GOVERNMENT SCHEMES & BENEFITS",ArthSaathiV62Design.GREEN){benefits()});add(btn("REPORTS & STATEMENTS",ArthSaathiV62Design.NAVY){reports()});add(btn("BACK TO HOME",ArthSaathiV62Design.NAVY){finish()})}
 private fun formal(){shell("Formal Credit","Record authorised formal-credit products and open ChargeCheck");val p=input("Bank / NBFC / institution");val n=input("Loan product");val a=input("Principal amount ₹");val r=input("Annual interest %");val t=input("Tenure months");val f=input("Processing + other charges ₹");listOf(p,n,a,r,t,f).forEach{add(it)};add(btn("SAVE FORMAL CREDIT OFFER"){store.add("formal_credit",JSONObject().apply{put("id","FC-${System.currentTimeMillis()}");put("provider",p.text.toString());put("product",n.text.toString());put("principal",a.text.toString());put("rate",r.text.toString());put("tenure",t.text.toString());put("charges",f.text.toString())});Toast.makeText(this,"Formal credit offer saved",Toast.LENGTH_SHORT).show()});add(btn("OPEN CHARGECHECK",ArthSaathiV62Design.GOLD){startActivity(Intent(this,V62ChargeCheckActivity::class.java))});add(btn("BACK",ArthSaathiV62Design.NAVY){menu()})}
 private fun funding(){shell("Funding / Lending","Disclosure only after explicit consent and authorised provider selection");val p=input("Purpose of funding *");val a=input("Amount required ₹ *");val t=input("Preferred tenure months");val s=input("Preferred source");listOf(p,a,t,s).forEach{add(it)};add(btn("REQUEST FUNDING — CONSENT REQUIRED",ArthSaathiV62Design.TEAL){if(p.text.toString().isBlank()||a.text.toString().isBlank()){Toast.makeText(this,"Purpose and amount are required",Toast.LENGTH_SHORT).show()}else{AlertDialog.Builder(this).setTitle("Funding consent").setMessage("I authorise ArthSaathi to share the selected credit profile only with providers I choose for this request. QR scanning alone does not grant access.").setNegativeButton("CANCEL",null).setPositiveButton("AGREE & CREATE REQUEST"){_,_->store.add("funding_requests",JSONObject().apply{put("id","F-${System.currentTimeMillis()}");put("purpose",p.text.toString());put("amount",a.text.toString());put("tenure",t.text.toString());put("source",s.text.toString());put("consent","GRANTED");put("status","REQUESTED")});Toast.makeText(this,"Funding request created",Toast.LENGTH_SHORT).show()}.show()}});add(btn("BACK",ArthSaathiV62Design.NAVY){menu()})}
 private fun khata(){shell("QR Udhaar Khata","QR is an entry point to a consented relationship — never an open history key");val party=input("Customer / counterparty identifier *");val amount=input("Credit/debit amount ₹ *");val direction=Spinner(this).apply{adapter=ArrayAdapter(this@V62ExtendedModulesActivity,android.R.layout.simple_spinner_dropdown_item,arrayOf("CREDIT","REPAYMENT"))};val note=input("Invoice / items / note");listOf(party,amount,direction,note).forEach{add(it)};add(btn("SCAN QR / OPEN RELATIONSHIP",ArthSaathiV62Design.TEAL){startActivity(Intent(this,QrCreditScannerActivity::class.java))});add(btn("RECORD KHATA ENTRY",ArthSaathiV62Design.GREEN){if(party.text.toString().isBlank()||amount.text.toString().isBlank()){Toast.makeText(this,"Party and amount are required",Toast.LENGTH_SHORT).show()}else{store.add("qr_khata_v62",JSONObject().apply{put("id","QK-${System.currentTimeMillis()}");put("party",party.text.toString());put("amount",amount.text.toString());put("direction",direction.selectedItem.toString());put("note",note.text.toString());put("status","OPEN")});Toast.makeText(this,"QR Khata entry saved",Toast.LENGTH_SHORT).show()}});add(btn("BACK",ArthSaathiV62Design.NAVY){menu()})}
 private fun people(){shell("People & Family","One identity layer shared by credit, assets, insurance and legacy");val n=input("Full name *");val m=input("Mobile");val p=input("PAN");val rel=input("Family / contact relationship");val role=input("Role");listOf(n,m,p,rel,role).forEach{add(it)};add(btn("SAVE PERSON / CONTACT"){if(n.text.toString().isBlank()){Toast.makeText(this,"Name required",Toast.LENGTH_SHORT).show()}else{store.add("people_v62",JSONObject().apply{put("id","P-${System.currentTimeMillis()}");put("name",n.text.toString());put("mobile",m.text.toString());put("pan",p.text.toString());put("relation",rel.text.toString());put("role",role.text.toString())});Toast.makeText(this,"Person saved",Toast.LENGTH_SHORT).show()}});add(btn("BACK",ArthSaathiV62Design.NAVY){menu()})}
 private fun address(){shell("Address & Location","Location-assisted capture with user confirmation");val pin=input("PIN code");val line=input("Address line");val city=input("City");val district=input("District");val state=input("State");listOf(pin,line,city,district,state).forEach{add(it)};add(btn("USE CURRENT LOCATION",ArthSaathiV62Design.TEAL){Toast.makeText(this,"Location assistance will request permission and then require confirmation.",Toast.LENGTH_LONG).show()});add(btn("SAVE CONFIRMED ADDRESS"){store.add("addresses_v62",JSONObject().apply{put("pin",pin.text.toString());put("line",line.text.toString());put("city",city.text.toString());put("district",district.text.toString());put("state",state.text.toString());put("source","USER_CONFIRMED")});Toast.makeText(this,"Address saved",Toast.LENGTH_SHORT).show()});add(btn("BACK",ArthSaathiV62Design.NAVY){menu()})}
 private fun liability(){shell("Liability Vault","Loans and obligations connected to the financial snapshot");val n=input("Liability / loan name *");val l=input("Lender");val o=input("Outstanding ₹");val r=input("Interest %");val due=input("Next due date");listOf(n,l,o,r,due).forEach{add(it)};add(btn("SAVE LIABILITY",ArthSaathiV62Design.RED){store.add("liabilities_v62",JSONObject().apply{put("id","L-${System.currentTimeMillis()}");put("name",n.text.toString());put("lender",l.text.toString());put("outstanding",o.text.toString());put("rate",r.text.toString());put("due",due.text.toString())});Toast.makeText(this,"Liability saved",Toast.LENGTH_SHORT).show()});add(btn("BACK",ArthSaathiV62Design.NAVY){menu()})}
 private fun benefits(){shell("Government Schemes & Benefits","Eligibility records and reminders");val n=input("Scheme / benefit");val p=input("Provider");val c=input("Eligibility / condition");listOf(n,p,c).forEach{add(it)};add(btn("SAVE BENEFIT & CONDITIONS",ArthSaathiV62Design.GREEN){store.add("benefits_v62",JSONObject().apply{put("id","B-${System.currentTimeMillis()}");put("name",n.text.toString());put("provider",p.text.toString());put("condition",c.text.toString())});Toast.makeText(this,"Benefit saved",Toast.LENGTH_SHORT).show()});add(btn("BACK",ArthSaathiV62Design.NAVY){menu()})}
 private fun reports(){shell("Reports & Statements","Connected V6.2 records");val counts=listOf("Formal credit" to "formal_credit","Funding requests" to "funding_requests","ChargeCheck" to "chargecheck","QR Khata" to "qr_khata_v62","People" to "people_v62","Liabilities" to "liabilities_v62");add(ArthSaathiV62Design.text(this,counts.joinToString("\n"){(n,k)->"$n: ${store.all(k).size}"},15f,ArthSaathiV62Design.NAVY,true),10);add(btn("BACK",ArthSaathiV62Design.NAVY){menu()})}
 override fun onBackPressed(){finish()}
}
