package com.udhaardaar.mvp

import android.app.AlertDialog
import android.content.Intent
import android.graphics.Color
import android.graphics.Typeface
import android.graphics.drawable.GradientDrawable
import android.os.Bundle
import android.view.Gravity
import android.view.View
import android.widget.*
import androidx.appcompat.app.AppCompatActivity

/** ArthSaathi V6.2 command centre. V6.1 completed workflows remain the functional backbone. */
class V62HomeActivity:AppCompatActivity(){
 private val navy=Color.rgb(16,45,82);private val teal=Color.rgb(12,155,145);private val blue=Color.rgb(42,103,221);private val green=Color.rgb(18,137,91);private val gold=Color.rgb(211,161,37);private val red=Color.rgb(193,67,72);private val bg=Color.rgb(246,249,252);private val muted=Color.rgb(92,108,124);private val border=Color.rgb(220,228,236);private val prefs by lazy{getSharedPreferences("udhaardaar_accounts",MODE_PRIVATE)}
 private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt();private fun card(fill:Int=Color.WHITE,r:Int=16)=GradientDrawable().apply{setColor(fill);setStroke(dp(1),border);cornerRadius=dp(r).toFloat()};private fun t(s:String,z:Float,c:Int=navy,b:Boolean=false)=TextView(this).apply{text=s;textSize=z;setTextColor(c);typeface=Typeface.create("sans-serif",if(b)Typeface.BOLD else Typeface.NORMAL);includeFontPadding=false};private fun lp(top:Int)=LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(top)}
 override fun onCreate(b:Bundle?){super.onCreate(b);window.setSoftInputMode(android.view.WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);render()};override fun onResume(){super.onResume();if(!isFinishing&&prefs.getBoolean("logged_in",false))render()}
 private fun credit(){startActivity(Intent(this,V62CreditRegistrationActivity::class.java))};private fun oldCore(){startActivity(Intent(this,V61RectifiedActivity::class.java))};private fun go(c:Class<*>){startActivity(Intent(this,c))}
 private fun render(){if(!prefs.getBoolean("logged_in",false)){startActivity(Intent(this,LoginActivity::class.java));finish();return};val m=prefs.getString("current_mobile","")?:"";val name=prefs.getString("name_$m","User")?:"User";val first=name.trim().firstOrNull()?.uppercaseChar()?.toString()?:"U";val h=java.util.Calendar.getInstance().get(java.util.Calendar.HOUR_OF_DAY);val greet=when(h){in 5..11->"Good morning";in 12..16->"Good afternoon";in 17..20->"Good evening";else->"Good night"}
  val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(16),dp(12),dp(16),dp(10));setBackgroundColor(bg)}
  val head=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(dp(10),dp(8),dp(8),dp(8));background=card()};head.addView(ImageView(this).apply{setImageResource(R.drawable.udhaardaar_logo);scaleType=ImageView.ScaleType.CENTER_INSIDE;contentDescription="ArthSaathi logo"},LinearLayout.LayoutParams(dp(58),dp(58)));val brand=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};brand.addView(t("ArthSaathi",23f,navy,true));brand.addView(t("Navigate Your Financial Journey",10f,teal,true),lp(2));brand.addView(t("Plan • Protect • Grow • Nominate",9f,gold,true),lp(2));head.addView(brand,LinearLayout.LayoutParams(0,-2,1f).apply{leftMargin=dp(10)});head.addView(t(first,13f,navy,true).apply{gravity=Gravity.CENTER;background=card();setOnClickListener{oldCore()}},LinearLayout.LayoutParams(dp(40),dp(40)));root.addView(head)
  root.addView(t("$greet, $name",18f,navy,true),lp(12));root.addView(t("One place to plan, protect, grow and nominate.",11f,muted),lp(3))
  val hero=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(14),dp(12),dp(14),dp(12));background=card(navy,18)};hero.addView(t("YOUR FINANCIAL SNAPSHOT",9f,Color.rgb(175,205,232),true));val stats=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};stats.addView(stat("TO RECEIVE","₹0",Color.rgb(111,223,183)),LinearLayout.LayoutParams(0,dp(60),1f).apply{rightMargin=dp(4);topMargin=dp(8)});stats.addView(stat("TO PAY","₹0",Color.rgb(255,147,151)),LinearLayout.LayoutParams(0,dp(60),1f).apply{leftMargin=dp(4);rightMargin=dp(4);topMargin=dp(8)});stats.addView(stat("ACTIVE","0",Color.rgb(123,176,255)),LinearLayout.LayoutParams(0,dp(60),1f).apply{leftMargin=dp(4);topMargin=dp(8)});hero.addView(stats);root.addView(hero,lp(10))
  val sec=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL};sec.addView(t("Quick access",13f,navy,true),LinearLayout.LayoutParams(0,-2,1f));sec.addView(t("All services  ›",10f,teal,true).apply{setOnClickListener{services()} });root.addView(sec,lp(12))
  val r1=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};r1.addView(action("Credit","Register • search",blue,"₹"){credit()},aLp(true));r1.addView(action("Repayment","Dues • consent",green,"↻"){go(V5RepaymentActivity::class.java)},aLp(true));r1.addView(action("Asset Vault","Assets • evidence",teal,"◆"){go(V5AssetVaultActivity::class.java)},aLp(false));root.addView(r1,lp(6));val r2=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};r2.addView(action("Protect","Insurance • benefits",green,"+"){go(V5SupportWorkflowsActivity::class.java)},aLp(true));r2.addView(action("Legacy","Will • nomination",gold,"◇"){go(V5DeathClaimLegalActivity::class.java)},aLp(true));r2.addView(action("Legal","Claims • lawyers",red,"⚖"){go(V5DeathClaimLegalActivity::class.java)},aLp(false));root.addView(r2,lp(6))
  val ai=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(dp(12),dp(10),dp(12),dp(10));background=card(Color.rgb(238,248,245),16);setOnClickListener{go(V5SupportWorkflowsActivity::class.java)}};ai.addView(t("✦",22f,gold,true),LinearLayout.LayoutParams(dp(34),-1));val ab=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};ab.addView(t("AI Financial Advisor",13f,navy,true));ab.addView(t("Explainable alerts • opportunities • reminders",9f,muted),lp(2));ai.addView(ab,LinearLayout.LayoutParams(0,-2,1f));ai.addView(t("›",22f,teal,true));root.addView(ai,lp(9))
  root.addView(Space(this),LinearLayout.LayoutParams(1,0,1f));val nav=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER;setPadding(dp(4),dp(4),dp(4),dp(4));background=card()};nav.addView(bottom("⌂","Home",true){render()},LinearLayout.LayoutParams(0,dp(52),1f));nav.addView(bottom("₹","Credit",false){credit()},LinearLayout.LayoutParams(0,dp(52),1f));nav.addView(bottom("↻","Repay",false){go(V5RepaymentActivity::class.java)},LinearLayout.LayoutParams(0,dp(52),1f));nav.addView(bottom("◆","Vault",false){go(V5AssetVaultActivity::class.java)},LinearLayout.LayoutParams(0,dp(52),1f));nav.addView(bottom("☰","More",false){services()},LinearLayout.LayoutParams(0,dp(52),1f));root.addView(nav,lp(8));setContentView(root)}
 private fun stat(a:String,b:String,c:Int)=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(8),dp(5),dp(8),dp(5));background=GradientDrawable().apply{setColor(Color.argb(35,255,255,255));cornerRadius=dp(10).toFloat()};addView(t(a,8f,c,true));addView(t(b,16f,Color.WHITE,true),lp(2))};private fun action(a:String,b:String,c:Int,s:String,click:()->Unit)=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.CENTER_VERTICAL;setPadding(dp(10),dp(8),dp(8),dp(7));background=card();setOnClickListener{click()};addView(t(s,18f,c,true));addView(t(a,11f,navy,true),lp(3));addView(t(b,8f,muted),lp(2))};private fun aLp(r:Boolean)=LinearLayout.LayoutParams(0,dp(76),1f).apply{if(r)rightMargin=dp(4)};private fun bottom(s:String,a:String,sel:Boolean,click:()->Unit)=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.CENTER;setOnClickListener{click()};addView(t(s,18f,if(sel)teal else muted,true));addView(t(a,8f,if(sel)teal else muted,sel),lp(2))}
 private fun services(){AlertDialog.Builder(this).setTitle("ArthSaathi Services").setItems(arrayOf("Profile Search / Create","QR Khata","Insurance & Benefits","Will & Nomination","Inheritance & Claim Centre","Legal Assistance Directory","TTMM Group Expenses","AI Financial Advisor","Settings / Profile Photo")){_,which->when(which){0->oldCore();1->go(QrCreditScannerActivity::class.java);2->go(V5SupportWorkflowsActivity::class.java);3->go(V5DeathClaimLegalActivity::class.java);4->go(V5DeathClaimLegalActivity::class.java);5->go(V5DeathClaimLegalActivity::class.java);6->go(V5TTMMActivity::class.java);7->go(V5SupportWorkflowsActivity::class.java);8->oldCore()}}.setNegativeButton("CLOSE",null).show()}
}
