package com.udhaardaar.mvp
import android.app.AlertDialog
import android.os.Bundle
import android.widget.*
import org.json.JSONObject

class V62LegacyLegalAIActivity:androidx.appcompat.app.AppCompatActivity(){
 private val s by lazy{V5LocalStore(this)};private val d by lazy{resources.displayMetrics.density};private val root by lazy{LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(16.dp,8.dp,16.dp,28.dp);setBackgroundColor(ArthSaathiV62Design.BG)}};private val Int.dp:Int get()=(this*d).toInt()
 override fun onCreate(b:Bundle?){super.onCreate(b);render()}
 private fun render(){root.removeAllViews();ArthSaathiV62Design.add(root,ArthSaathiV62Design.title(this,"Legacy • Legal • AI","Protect today. Prepare tomorrow."),2);card("WILL & NOMINATION","Create a guided will from verified vault records and nominate beneficiaries."){willDialog()};card("CLAIM ASSISTANCE","Assemble assets, policies, liabilities, nominees and documents into a claim checklist."){claimDialog()};card("LEGAL ASSISTANCE","Find legal help by matter/domain. Never treat AI output as legal advice."){legalDialog()};card("AI FINANCIAL ADVISOR","Explainable insights from ArthSaathi records: obligations, protection gaps, idle funds and savings."){aiDialog()};setContentView(ScrollView(this).apply{isFillViewport=true;addView(root)})}
 private fun card(title:String,sub:String,click:()->Unit){val b=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(14.dp,12.dp,14.dp,12.dp);background=ArthSaathiV62Design.card()};b.setOnClickListener{click()};b.addView(ArthSaathiV62Design.text(this,title,13f,ArthSaathiV62Design.NAVY,true));b.addView(ArthSaathiV62Design.text(this,sub,10f,ArthSaathiV62Design.MUTED),LinearLayout.LayoutParams(-1,-2).apply{topMargin=5.dp});ArthSaathiV62Design.add(root,b,8)}
 private fun willDialog(){val n=ArthSaathiV62Design.input(this,"Nominee / beneficiary name");val a=ArthSaathiV62Design.input(this,"Assets / instructions");AlertDialog.Builder(this).setTitle("Guided Will Draft").setMessage("This creates a draft for review. Obtain independent legal advice before execution.").setView(LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(16.dp,0,16.dp,0);addView(n);addView(a)}).setNegativeButton("CANCEL",null).setPositiveButton("SAVE DRAFT"){_,_->s.add(V62Store.WILLS,JSONObject().apply{put("id",V62Store.id("WILL"));put("beneficiary",n.text.toString());put("instructions",a.text.toString());put("status","DRAFT");put("createdAt",System.currentTimeMillis())});Toast.makeText(this,"Will draft saved.",Toast.LENGTH_SHORT).show()}.show()}
 private fun claimDialog(){val p=s.all(V62Store.INSURANCE).size;val a=s.all(V62Store.ASSETS).size;val docs=s.all(V62Store.DOCUMENTS).size;AlertDialog.Builder(this).setTitle("Claim Assistance").setMessage("Potential evidence assembled from your vault:\n\nInsurance policies: $p\nAssets: $a\nDocuments: $docs\n\nAdd the event, claimant and required authority documents before submission.").setPositiveButton("OK",null).show()}
 private fun legalDialog(){AlertDialog.Builder(this).setTitle("Legal Assistance").setMessage("Legal directory endpoint: legal/assistance\n\nSearch should support domain, city and expertise and display verified contact details when a connected directory is available.").setPositiveButton("OK",null).show()}
 private fun aiDialog(){val m=V62MisEngine.metrics(this);AlertDialog.Builder(this).setTitle("AI Financial Advisor").setMessage("Current verified data:\nAssets: ₹${m.optDouble("assetValue",0.0).toInt()}\nInterest received: ₹${m.optDouble("interestReceived",0.0).toInt()}\nIdle funds: ₹${m.optDouble("idleFunds",0.0).toInt()}\nSavings recorded: ₹${m.optDouble("appSavings",0.0).toInt()}\n\nAI recommendations must cite the underlying record and assumptions.").setPositiveButton("OK",null).show()}
}
