package com.udhaardaar.mvp

import android.app.AlertDialog
import android.os.Bundle
import android.widget.*
import org.json.JSONObject
import java.util.Locale

class V62LegacyLegalAIActivity : androidx.appcompat.app.AppCompatActivity() {
    private val s by lazy { V5LocalStore(this) }
    private val d by lazy { resources.displayMetrics.density }
    private val root by lazy { LinearLayout(this).apply { orientation=LinearLayout.VERTICAL;setPadding(16.dp,8.dp,16.dp,28.dp);setBackgroundColor(ArthSaathiV62Design.BG) } }
    private val Int.dp:Int get()=(this*d).toInt()
    override fun onCreate(b:Bundle?){super.onCreate(b);window.setSoftInputMode(16);render()}
    override fun onResume(){super.onResume();if(!isFinishing)render()}
    private fun add(v:android.view.View,gap:Int=8)=ArthSaathiV62Design.add(root,v,gap)
    private fun render(){root.removeAllViews();add(ArthSaathiV62Design.title(this,"Legacy • Legal • AI","Protect today • Prepare tomorrow"),2);add(ArthSaathiV62Design.text(this,"One connected layer: assets, nominees, claims, legal support and portfolio intelligence use the same consented financial records.",10f,ArthSaathiV62Design.MUTED),8);card("WILL & NOMINATION","Versioned will drafts linked to assets and beneficiaries"){willDialog()};card("CLAIM ASSISTANCE","Build a claim case from policies, assets and retained evidence"){claimDialog()};card("LEGAL ASSISTANCE","Find registered advocates by matter, city and language; advocates can register their profile"){legalDialog()};card("AI FINANCIAL ADVISOR","Compare recorded investment performance with an alternative scenario and review rebalancing/switch considerations"){aiDialog()};card("ALERTS","Renewal, due-date and ChargeCheck alerts generated from the shared data core"){alertsDialog()};setContentView(ScrollView(this).apply{isFillViewport=true;addView(root)})}
    private fun card(title:String,sub:String,click:()->Unit){val b=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(14.dp,12.dp,14.dp,12.dp);background=ArthSaathiV62Design.card();setOnClickListener{click()}};b.addView(ArthSaathiV62Design.text(this,title,13f,ArthSaathiV62Design.NAVY,true));b.addView(ArthSaathiV62Design.text(this,sub,10f,ArthSaathiV62Design.MUTED),LinearLayout.LayoutParams(-1,-2).apply{topMargin=5.dp});add(b)}
    private fun willDialog(){val assets=s.all(V62Store.ASSETS).filter{it.optBoolean("currentAsset",true)};val beneficiary=ArthSaathiV62Design.input(this,"Beneficiary / nominee name *");val executor=ArthSaathiV62Design.input(this,"Executor / trusted person");val instructions=ArthSaathiV62Design.input(this,"Distribution / legacy instructions *");val selected=mutableSetOf<String>();val assetBox=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};if(assets.isEmpty())assetBox.addView(ArthSaathiV62Design.text(this@V62LegacyLegalAIActivity,"No current assets recorded yet; an instruction-only draft is still allowed.",10f,ArthSaathiV62Design.MUTED));assets.forEach{a->assetBox.addView(CheckBox(this).apply{text="${a.optString("Asset name / description",a.optString("type"))} • ₹${"%.2f".format(Locale.US,a.optDouble("value"))}";setOnCheckedChangeListener{_,checked->if(checked)selected.add(a.optString("id"))else selected.remove(a.optString("id"))}})};val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(16.dp,0,16.dp,0);addView(beneficiary);addView(executor);addView(ArthSaathiV62Design.text(this@V62LegacyLegalAIActivity,"LINK ASSETS",11f,ArthSaathiV62Design.TEAL,true));addView(assetBox);addView(instructions)};AlertDialog.Builder(this).setTitle("Guided Will Draft").setMessage("Draft only — independent legal review and lawful execution are required.").setView(box).setNegativeButton("CANCEL",null).setPositiveButton("SAVE VERSIONED DRAFT"){_,_->if(beneficiary.text.isBlank()||instructions.text.isBlank())Toast.makeText(this,"Beneficiary and instructions are required.",Toast.LENGTH_LONG).show()else{val id=V62Store.id("WILL");val versions=s.all(V62Store.WILLS).count{it.optString("beneficiary")==beneficiary.text.toString().trim()}+1;s.add(V62Store.WILLS,JSONObject().apply{put("id",id);put("willGroupId",beneficiary.text.toString().trim());put("version",versions);put("ownerUserId",V62Integration.currentUserId(this@V62LegacyLegalAIActivity));put("beneficiary",beneficiary.text.toString().trim());put("executor",executor.text.toString().trim());put("assetIds",selected.joinToString("|"));put("instructions",instructions.text.toString().trim());put("status","DRAFT");put("createdAt",System.currentTimeMillis())});val nom=V62Store.id("NOM");s.add(V62Store.NOMINEES,JSONObject().apply{put("id",nom);put("ownerUserId",V62Integration.currentUserId(this@V62LegacyLegalAIActivity));put("name",beneficiary.text.toString().trim());put("assetIds",selected.joinToString("|"));put("source","WILL_DRAFT");put("createdAt",System.currentTimeMillis())});V62EventBus.publish(V62Event(V62Events.WILL_CHANGED,id));V62EventBus.publish(V62Event(V62Events.NOMINEE_CHANGED,nom));Toast.makeText(this,"Version $versions will draft saved and nominee linked.",Toast.LENGTH_LONG).show()}}.show()}
    private fun claimDialog(){val p=s.all(V62Store.INSURANCE);val a=s.all(V62Store.ASSETS);val docs=s.all(V62Store.DOCUMENTS);val claimant=ArthSaathiV62Design.input(this,"Claimant name / relation *");val event=ArthSaathiV62Design.input(this,"Claim event / date *");AlertDialog.Builder(this).setTitle("Claim Assistance").setMessage("Evidence available from the shared vault: policies ${p.size} • assets ${a.size} • documents ${docs.size}. A claim case links these records without automatically submitting anything.").setView(LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;addView(claimant);addView(event)}).setNegativeButton("CANCEL",null).setPositiveButton("CREATE CLAIM CASE"){_,_->if(claimant.text.isBlank()||event.text.isBlank())Toast.makeText(this,"Claimant and event are required.",Toast.LENGTH_LONG).show()else{val id=V62Store.id("CLAIM");s.add(V62Store.CLAIMS,JSONObject().apply{put("id",id);put("ownerUserId",V62Integration.currentUserId(this@V62LegacyLegalAIActivity));put("claimant",claimant.text.toString().trim());put("event",event.text.toString().trim());put("policyIds",p.joinToString("|"){it.optString("id")});put("assetIds",a.joinToString("|"){it.optString("id")});put("documentIds",docs.joinToString("|"){it.optString("id")});put("status","DRAFT");put("createdAt",System.currentTimeMillis())});V62EventBus.publish(V62Event(V62Events.CLAIM_CHANGED,id));Toast.makeText(this,"Claim case created with linked evidence.",Toast.LENGTH_LONG).show()}}.show()}
    private fun legalDialog(){val advocates=s.all("v62_advocates");val mode=Spinner(this).apply{adapter=ArrayAdapter(this@V62LegacyLegalAIActivity,android.R.layout.simple_spinner_dropdown_item,arrayOf("Find an advocate","Register advocate profile"))};val matter=ArthSaathiV62Design.input(this,"Matter / legal domain");val city=ArthSaathiV62Design.input(this,"City / locality");val language=ArthSaathiV62Design.input(this,"Language");val expertise=ArthSaathiV62Design.input(this,"Expertise / specialisation");val name=ArthSaathiV62Design.input(this,"Advocate / counsel name");val bar=ArthSaathiV62Design.input(this,"Bar registration / verification reference");val phone=ArthSaathiV62Design.input(this,"Contact number");val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;addView(mode);addView(matter);addView(city);addView(language);addView(expertise);addView(name);addView(bar);addView(phone)};AlertDialog.Builder(this).setTitle("ArthSaathi Advocate Network").setMessage("Profiles are stored separately from ordinary user contacts. VERIFIED status is only applied when a connected verification process confirms the advocate; this local build does not fabricate verification.").setView(box).setNegativeButton("CANCEL",null).setPositiveButton("CONTINUE"){_,_->if(mode.selectedItemPosition==0)showAdvocateResults(advocates,matter.text.toString(),city.text.toString(),language.text.toString(),expertise.text.toString())else if(name.text.isBlank()||bar.text.isBlank()||phone.text.isBlank())Toast.makeText(this,"Advocate name, registration reference and contact are required.",Toast.LENGTH_LONG).show()else{s.add("v62_advocates",JSONObject().apply{put("id",V62Store.id("ADV"));put("name",name.text.toString().trim());put("barReference",bar.text.toString().trim());put("phone",phone.text.toString().trim());put("matter",matter.text.toString().trim());put("city",city.text.toString().trim());put("language",language.text.toString().trim());put("expertise",expertise.text.toString().trim());put("verificationStatus","PENDING");put("createdAt",System.currentTimeMillis())});Toast.makeText(this,"Advocate profile submitted as PENDING verification.",Toast.LENGTH_LONG).show()}}.show()}
    private fun showAdvocateResults(all:List<JSONObject>,matter:String,city:String,language:String,expertise:String){val q=listOf(matter,city,language,expertise).filter{it.isNotBlank()}.map{it.lowercase()};val hits=all.filter{a->q.all{needle->listOf(a.optString("matter"),a.optString("city"),a.optString("language"),a.optString("expertise"),a.optString("name")).joinToString(" ").lowercase().contains(needle)}};val msg=if(hits.isEmpty())"No locally registered advocate profile matches these filters yet. Use Register advocate profile to add one." else hits.joinToString("\n\n"){a->"${a.optString("name")}\n${a.optString("matter")} • ${a.optString("expertise")}\n${a.optString("city")} • ${a.optString("language")}\nStatus: ${a.optString("verificationStatus")}"};AlertDialog.Builder(this).setTitle("Advocate Results (${hits.size})").setMessage(msg).setPositiveButton("OK",null).show()}
    private fun aiDialog(){val m=V62MisEngine.metrics(this);val assets=s.all(V62Store.ASSETS).filter{it.optString("ownerUserId")==V62Integration.currentUserId(this)&&it.optBoolean("currentAsset",true)};val invest=assets.filter{val t=it.optString("type").uppercase();t.contains("MUTUAL")||t.contains("FUND")||t.contains("STOCK")||t.contains("DEMAT")||t.contains("INVEST")};val names=invest.map{it.optString("Asset name / description",it.optString("type"))}.ifEmpty{listOf("No recorded investment asset")};val picker=Spinner(this).apply{adapter=ArrayAdapter(this@V62LegacyLegalAIActivity,android.R.layout.simple_spinner_dropdown_item,names)};val alt=ArthSaathiV62Design.input(this,"Alternative expected return % (scenario)");val risk=ArthSaathiV62Design.input(this,"Alternative risk / suitability notes");val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;addView(picker);addView(alt);addView(risk)};AlertDialog.Builder(this).setTitle("AI Portfolio Review").setMessage("AI compares the recorded yield/performance with your alternative scenario. It does not execute a switch. Suitability, tax, exit load, liquidity and regulatory requirements must be reviewed before action.").setView(box).setNegativeButton("CANCEL",null).setPositiveButton("COMPARE & SUGGEST"){_,_->val asset=if(invest.isEmpty())null else invest[picker.selectedItemPosition];val current=asset?.optDouble("yieldPercent",0.0)?:0.0;val alternative=alt.text.toString().toDoubleOrNull();val comparison=if(alternative==null)"Enter an alternative expected return to compare." else if(alternative>current)"Scenario return is ${"%.2f".format(Locale.US,alternative-current)} percentage points above the recorded ${"%.2f".format(Locale.US,current)}%. Review risk, tax, liquidity and costs before considering a switch." else "Recorded performance is not below the scenario by the input return. Review diversification, risk, tax and costs before changing anything.";val base="Liquidity ₹${"%.0f".format(Locale.US,m.optDouble("assetValue"))} • liabilities ₹${"%.0f".format(Locale.US,m.optDouble("liabilities"))} • informal exposure ₹${"%.0f".format(Locale.US,m.optDouble("informalCreditExposure"))}.";val displayName=asset?.optString("Asset name / description",asset.optString("type")) ?: "Portfolio";AlertDialog.Builder(this).setTitle("Explainable AI Suggestion").setMessage("$displayName\nRecorded yield: ${"%.2f".format(Locale.US,current)}%\n\n$comparison\n\nSuitability notes: ${risk.text.ifBlank{"Not provided"}}\n\n$base\n\nNo automatic investment switch is performed.").setPositiveButton("OK",null).show()}}.show()}
    private fun alertsDialog(){val a=s.all(V62Store.ALERTS).takeLast(20).reversed();AlertDialog.Builder(this).setTitle("ArthSaathi Alerts").setMessage(if(a.isEmpty())"No generated alerts yet." else a.joinToString("\n\n"){"${it.optString("severity")}: ${it.optString("message")}"}).setPositiveButton("OK",null).show()}
}
