package com.udhaardaar.mvp

import android.graphics.Color
import android.os.Bundle
import android.view.Gravity
import android.widget.*
import kotlin.math.max

class V62MISActivity:androidx.appcompat.app.AppCompatActivity(){
 private val store by lazy{V5LocalStore(this)};private val d by lazy{resources.displayMetrics.density};private val root by lazy{LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(ArthSaathiV62Design.dp(16,d),ArthSaathiV62Design.dp(8,d),ArthSaathiV62Design.dp(16,d),ArthSaathiV62Design.dp(28,d));setBackgroundColor(ArthSaathiV62Design.BG)}}
 private fun money(x:Double)="₹${String.format(java.util.Locale.US,"%,.0f",x)}"
 override fun onCreate(b:Bundle?){super.onCreate(b);window.setSoftInputMode(android.view.WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);render()};override fun onResume(){super.onResume();if(!isFinishing)render()}
 private fun cardTitle(s:String)=ArthSaathiV62Design.text(this,s,11f,ArthSaathiV62Design.MUTED,true)
 private fun render(){root.removeAllViews();ArthSaathiV62Design.add(root,ArthSaathiV62Design.title(this,"MIS & Financial Intelligence","See the complete financial picture"),2)
  val assets=store.all(ArthSaathiV62Core.ASSETS);val reps=store.all(ArthSaathiV62Core.REPAYMENTS);val savings=store.all(ArthSaathiV62Core.SAVINGS);val policies=store.all(ArthSaathiV62Core.INSURANCE);val rel=store.all(ArthSaathiV62Core.RELATIONSHIPS)
  val total=assets.sumOf{it.optDouble("value",0.0)};val returns=reps.sumOf{it.optDouble("interest",0.0)};val charges=assets.sumOf{it.optDouble("charges",0.0)}+reps.sumOf{it.optDouble("charges",0.0)};val saved=savings.sumOf{it.optDouble("amount",0.0)};val idle=assets.filter{it.optBoolean("idle",false)}.sumOf{it.optDouble("value",0.0)}
  metric("TOTAL ASSETS",money(total));metric("RETURNS / INTEREST RECEIVED",money(returns));metric("CHARGES INCURRED",money(charges));metric("SAVINGS CREATED",money(saved));metric("IDLE / INACTIVE FUNDS",money(idle));metric("ACTIVE RELATIONSHIPS",rel.count{it.optString("status")!="CLOSED"}.toString())
  ArthSaathiV62Design.add(root,cardTitle("ASSET ALLOCATION"),14);val allocation=assets.groupBy{it.optString("type","Other")};if(allocation.isEmpty())ArthSaathiV62Design.add(root,ArthSaathiV62Design.text(this,"No assets recorded yet. Add assets to activate portfolio intelligence.",11f,ArthSaathiV62Design.MUTED),6) else {val vals=allocation.values.map{it.sumOf{a->a.optDouble("value",0.0)}.map{it.toFloat()}.getOrElse{0f}};val chart=V62DonutChart(this,vals.map{max(0f,it)});ArthSaathiV62Design.add(root,chart,6);allocation.entries.forEachIndexed{i,e->tableRow(e.key,money(e.value.sumOf{it.optDouble("value",0.0)}),"${e.value.size} item(s)",i%2==0)}}
  ArthSaathiV62Design.add(root,cardTitle("PERFORMANCE & RISK"),16);tableHeader("Metric","Recorded","Interpretation");tableRow("Average investment",if(assets.isEmpty())"₹0" else money(total/assets.size),"Across recorded assets",true);tableRow("Investment period",periodText(assets),"Based on available dates",false);tableRow("Risk",riskText(assets),"Based on recorded risk tags",true);tableRow("Insurance cover",policies.size.toString(),"Policies in protection vault",false);tableRow("Opportunity cost",money(opportunityCost(idle,assets)),"Estimate only; assumptions required",true)
  ArthSaathiV62Design.add(root,cardTitle("RETURNS • CHARGES • SAVINGS"),16);tableHeader("Measure","Amount","Source");tableRow("Interest / returns",money(returns),"Repayments",true);tableRow("Charges",money(charges),"Assets + repayments",false);tableRow("App savings",money(saved),"Recorded savings",true);tableRow("Idle funds",money(idle),"Asset Vault",false)
  ArthSaathiV62Design.add(root,ArthSaathiV62Design.text(this,"AI INSIGHT RULE",11f,ArthSaathiV62Design.MUTED,true),16);ArthSaathiV62Design.add(root,ArthSaathiV62Design.text(this,"ArthSaathi must show opportunity cost only when a comparison portfolio, period and assumptions are available. It should never present an invented return as fact.",11f,ArthSaathiV62Design.NAVY),5);ArthSaathiV62Design.add(root,ArthSaathiV62Design.button(this,"REFRESH INTELLIGENCE",ArthSaathiV62Design.TEAL){render()},12);setContentView(ScrollView(this).apply{isFillViewport=true;addView(root)})}
 private fun metric(k:String,v:String){val b=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(ArthSaathiV62Design.dp(12,d),ArthSaathiV62Design.dp(9,d),ArthSaathiV62Design.dp(12,d),ArthSaathiV62Design.dp(9,d));background=ArthSaathiV62Design.card(Color.WHITE,14,d)};b.addView(ArthSaathiV62Design.text(this,k,9f,ArthSaathiV62Design.MUTED,true));b.addView(ArthSaathiV62Design.text(this,v,18f,ArthSaathiV62Design.NAVY,true));ArthSaathiV62Design.add(root,b,6)}
 private fun tableHeader(a:String,b:String,c:String){val r=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;setPadding(8,8,8,8);background=ArthSaathiV62Design.card(0xffeef3f8.toInt(),10,d)};listOf(a,b,c).forEachIndexed{i,s->r.addView(ArthSaathiV62Design.text(this,s,9f,ArthSaathiV62Design.MUTED,true),LinearLayout.LayoutParams(0,-2,if(i==0)1.3f else 1f))};ArthSaathiV62Design.add(root,r,5)}
 private fun tableRow(a:String,b:String,c:String,even:Boolean){val r=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(8,9,8,9);background=ArthSaathiV62Design.card(if(even)Color.WHITE else 0xfff8fafc.toInt(),10,d)};listOf(a,b,c).forEachIndexed{i,s->r.addView(ArthSaathiV62Design.text(this,s,10f,ArthSaathiV62Design.NAVY,i==0),LinearLayout.LayoutParams(0,-2,if(i==0)1.3f else 1f))};ArthSaathiV62Design.add(root,r,2)}
 private fun periodText(a:List<org.json.JSONObject>):String="${a.size} recorded asset(s)";private fun riskText(a:List<org.json.JSONObject>):String{val n=a.count{it.optString("risk").isNotBlank()};return if(n==0)"Not enough tagged data" else "${n}/${a.size} assets risk-tagged"};private fun opportunityCost(idle:Double,a:List<org.json.JSONObject>):Double{val rate=a.mapNotNull{it.optDouble("yieldPercent",Double.NaN).takeUnless{it.isNaN()}}.maxOrNull()?:0.0;return idle*rate/100.0}
}
