package com.udhaardaar.mvp

import android.os.Bundle
import android.widget.*
import org.json.JSONObject

class V62MISActivity:androidx.appcompat.app.AppCompatActivity(){
 private val store by lazy{V5LocalStore(this)};private val d by lazy{resources.displayMetrics.density};private val root by lazy{LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(ArthSaathiV62Design.dp(16,d),ArthSaathiV62Design.dp(10,d),ArthSaathiV62Design.dp(16,d),ArthSaathiV62Design.dp(28,d));setBackgroundColor(ArthSaathiV62Design.BG)}}
 private fun money(x:Double)="₹${String.format(java.util.Locale.US,"%,.0f",x)}"
 override fun onCreate(b:Bundle?){super.onCreate(b);render()}
 override fun onResume(){super.onResume();if(::root.isInitialized)render()}
 private fun render(){root.removeAllViews();ArthSaathiV62Design.add(root,ArthSaathiV62Design.title(this,"MIS & Financial Intelligence","Know where your money works"),2);ArthSaathiV62Design.add(root,ArthSaathiV62Design.text(this,"This page consolidates data captured inside ArthSaathi. AI insights must remain explainable and based on recorded data, not assumptions.",10f,ArthSaathiV62Design.MUTED),8)
  val assets=store.all(ArthSaathiV62Core.ASSETS);val reps=store.all(ArthSaathiV62Core.REPAYMENTS);val savings=store.all(ArthSaathiV62Core.SAVINGS);val policies=store.all(ArthSaathiV62Core.INSURANCE);val credits=store.all(ArthSaathiV62Core.RELATIONSHIPS);val assetValue=assets.sumOf{it.optDouble("value",0.0)};val interest=reps.sumOf{it.optDouble("interest",0.0)};val charges=assets.sumOf{it.optDouble("charges",0.0)}+reps.sumOf{it.optDouble("charges",0.0)};val saved=savings.sumOf{it.optDouble("amount",0.0)}
  metric("TOTAL ASSETS",money(assetValue));metric("INTEREST / RETURNS RECORDED",money(interest));metric("CHARGES INCURRED",money(charges));metric("SAVINGS / OPPORTUNITY COST SAVED",money(saved));metric("INSURANCE POLICIES",policies.size.toString());metric("ACTIVE FINANCIAL RELATIONSHIPS",credits.size.toString())
  ArthSaathiV62Design.add(root,ArthSaathiV62Design.text(this,"PORTFOLIO & RISK VIEW",11f,ArthSaathiV62Design.MUTED,true),14);val allocation=assets.groupBy{it.optString("type","Other")};if(allocation.isEmpty())ArthSaathiV62Design.add(root,ArthSaathiV62Design.text(this,"No structured assets yet. Add assets in Asset Vault to activate allocation analytics.",11f,ArthSaathiV62Design.MUTED),5) else allocation.forEach{(type,list)->val v=list.sumOf{it.optDouble("value",0.0)};ArthSaathiV62Design.add(root,ArthSaathiV62Design.text(this,"$type   ${money(v)}   • ${list.size} item(s)",13f,ArthSaathiV62Design.NAVY,true),5)}
  ArthSaathiV62Design.add(root,ArthSaathiV62Design.text(this,"ATTENTION & OPPORTUNITY",11f,ArthSaathiV62Design.MUTED,true),14);val idle=assets.filter{it.optBoolean("idle",false)}.sumOf{it.optDouble("value",0.0)};ArthSaathiV62Design.add(root,ArthSaathiV62Design.text(this,"Idle / inactive funds: ${money(idle)}\nCompare idle funds with recorded highest-yielding assets before making any switch.\nOpportunity cost: the estimated return difference should be shown with source, period and assumptions.",11f,ArthSaathiV62Design.NAVY),5);ArthSaathiV62Design.add(root,ArthSaathiV62Design.button(this,"ADD MIS DATA / REFRESH",ArthSaathiV62Design.TEAL){render()},12);setContentView(ScrollView(this).apply{isFillViewport=true;addView(root)})}
 private fun metric(k:String,v:String){val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(ArthSaathiV62Design.dp(12,d),ArthSaathiV62Design.dp(10,d),ArthSaathiV62Design.dp(12,d),ArthSaathiV62Design.dp(10,d));background=ArthSaathiV62Design.card(Color.WHITE,14,d)};box.addView(ArthSaathiV62Design.text(this,k,9f,ArthSaathiV62Design.MUTED,true));box.addView(ArthSaathiV62Design.text(this,v,18f,ArthSaathiV62Design.NAVY,true),LinearLayout.LayoutParams(-1,-2).apply{topMargin=ArthSaathiV62Design.dp(3,d)});ArthSaathiV62Design.add(root,box,6)}
}
