package com.udhaardaar.mvp
import android.graphics.Color
import android.os.Bundle
import android.view.Gravity
import android.widget.*
class V62MISActivity:androidx.appcompat.app.AppCompatActivity(){
 private val s by lazy{V5LocalStore(this)};private val d by lazy{resources.displayMetrics.density};private val root by lazy{LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(16.dp,8.dp,16.dp,28.dp);setBackgroundColor(ArthSaathiV62Design.BG)}}
 private val Int.dp:Int get()=(this*d).toInt();private fun money(x:Double)="₹${String.format(java.util.Locale.US,"%,.0f",x)}"
 override fun onCreate(b:Bundle?){super.onCreate(b);window.setSoftInputMode(16);render()};override fun onResume(){super.onResume();if(!isFinishing)render()}
 private fun render(){root.removeAllViews();ArthSaathiV62Design.add(root,ArthSaathiV62Design.title(this,"MIS & Financial Intelligence","See the complete financial picture"),2);val a=s.all(ArthSaathiV62Core.ASSETS);val r=s.all(ArthSaathiV62Core.REPAYMENTS);val sv=s.all(ArthSaathiV62Core.SAVINGS);val p=s.all(ArthSaathiV62Core.INSURANCE);val rel=s.all(ArthSaathiV62Core.RELATIONSHIPS);val total=a.sumOf{it.optDouble("value",0.0)};val ret=r.sumOf{it.optDouble("interest",0.0)};val charges=a.sumOf{it.optDouble("charges",0.0)}+r.sumOf{it.optDouble("charges",0.0)};val saved=sv.sumOf{it.optDouble("amount",0.0)};val idle=a.filter{it.optBoolean("idle",false)}.sumOf{it.optDouble("value",0.0)}
 listOf("TOTAL ASSETS" to money(total),"RETURNS / INTEREST RECEIVED" to money(ret),"CHARGES INCURRED" to money(charges),"SAVINGS CREATED" to money(saved),"IDLE / INACTIVE FUNDS" to money(idle),"ACTIVE RELATIONSHIPS" to rel.count{it.optString("status")!="CLOSED"}.toString()).forEach{metric(it.first,it.second)}
 ArthSaathiV62Design.add(root,ArthSaathiV62Design.section(this,"ASSET ALLOCATION"),10);val g=a.groupBy{it.optString("type","Other")};if(g.isNotEmpty()){ArthSaathiV62Design.add(root,V62DonutChart(this,g.values.map{it.sumOf{q->q.optDouble("value",0.0)}.toFloat()}),4);g.entries.forEachIndexed{i,e->row(e.key,money(e.value.sumOf{q->q.optDouble("value",0.0)}),"${e.value.size} item(s)",i%2==0)}}else ArthSaathiV62Design.add(root,ArthSaathiV62Design.text(this,"No assets recorded yet.",11f,ArthSaathiV62Design.MUTED),4)
 ArthSaathiV62Design.add(root,ArthSaathiV62Design.section(this,"PERFORMANCE • RISK • OPPORTUNITY"),14);head("Metric","Recorded","Basis");row("Average investment",if(a.isEmpty())"₹0" else money(total/a.size),"Recorded assets",true);row("Risk tags",risk(a),"Asset records",false);row("Insurance policies",p.size.toString(),"Protection vault",true);row("Opportunity cost",money(idleCost(idle,a)),"Idle × highest recorded yield",false)
 ArthSaathiV62Design.add(root,ArthSaathiV62Design.section(this,"RETURNS • CHARGES • SAVINGS"),14);head("Measure","Amount","Source");row("Interest / returns",money(ret),"Repayments",true);row("Charges",money(charges),"Assets + repayments",false);row("App savings",money(saved),"Recorded savings",true);row("Idle funds",money(idle),"Asset Vault",false);ArthSaathiV62Design.add(root,ArthSaathiV62Design.text(this,"Opportunity-cost figures are estimates only and are shown with the recorded yield assumption; ArthSaathi must not invent a benchmark.",10f,ArthSaathiV62Design.MUTED),14);ArthSaathiV62Design.add(root,ArthSaathiV62Design.button(this,"REFRESH INTELLIGENCE",ArthSaathiV62Design.TEAL){render()},10);setContentView(ScrollView(this).apply{isFillViewport=true;addView(root)})}
 private fun metric(k:String,v:String){val b=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(12.dp,9.dp,12.dp,9.dp);background=ArthSaathiV62Design.card(Color.WHITE,14,d)};b.addView(ArthSaathiV62Design.text(this,k,9f,ArthSaathiV62Design.MUTED,true));b.addView(ArthSaathiV62Design.text(this,v,18f,ArthSaathiV62Design.NAVY,true));ArthSaathiV62Design.add(root,b,6)}
 private fun head(a:String,b:String,c:String){val r=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;setPadding(8.dp,7.dp,8.dp,7.dp);background=ArthSaathiV62Design.card(0xffeef3f8.toInt(),10,d)};listOf(a,b,c).forEachIndexed{i,x->r.addView(ArthSaathiV62Design.text(this,x,9f,ArthSaathiV62Design.MUTED,true),LinearLayout.LayoutParams(0,-2,if(i==0)1.3f else 1f))};ArthSaathiV62Design.add(root,r,4)}
 private fun row(a:String,b:String,c:String,even:Boolean){val r=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(8.dp,8.dp,8.dp,8.dp);background=ArthSaathiV62Design.card(if(even)Color.WHITE else 0xfff8fafc.toInt(),10,d)};listOf(a,b,c).forEachIndexed{i,x->r.addView(ArthSaathiV62Design.text(this,x,10f,ArthSaathiV62Design.NAVY,i==0),LinearLayout.LayoutParams(0,-2,if(i==0)1.3f else 1f))};ArthSaathiV62Design.add(root,r,2)}
 private fun risk(a:List<org.json.JSONObject>)="${a.count{it.optString("risk").isNotBlank()}} / ${a.size} tagged";private fun idleCost(idle:Double,a:List<org.json.JSONObject>):Double{val y=a.mapNotNull{it.optDouble("yieldPercent",Double.NaN).takeUnless{n->n.isNaN()}}.maxOrNull()?:0.0;return idle*y/100}
}
