package com.udhaardaar.mvp
import android.app.AlertDialog
import android.os.Bundle
import android.widget.*
import org.json.JSONObject
import kotlin.random.Random
class V62RepaymentActivity:androidx.appcompat.app.AppCompatActivity(){
 private val s by lazy{V5LocalStore(this)};private val d by lazy{resources.displayMetrics.density};private val root by lazy{LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(16.dp,8.dp,16.dp,28.dp);setBackgroundColor(ArthSaathiV62Design.BG)}};private val Int.dp:Int get()=(this*d).toInt()
 override fun onCreate(b:Bundle?){super.onCreate(b);window.setSoftInputMode(16);render()};override fun onResume(){super.onResume();if(!isFinishing)render()}
 private fun render(){root.removeAllViews();ArthSaathiV62Design.add(root,ArthSaathiV62Design.title(this,"Repayment Centre","Record • Reconcile • Update"),2);ArthSaathiV62Design.add(root,ArthSaathiV62Design.text(this,"Every payment updates the same relationship record, outstanding balance, repayment history and downstream MIS/alerts. Consent is required before changing a repayment record.",10f,ArthSaathiV62Design.MUTED),8);val rows=s.all(ArthSaathiV62Core.RELATIONSHIPS).filter{it.optString("status")!="CLOSED"};if(rows.isEmpty())ArthSaathiV62Design.add(root,ArthSaathiV62Design.text(this,"No active relationships yet.",13f,ArthSaathiV62Design.NAVY,true),12) else rows.forEach{j->val out=j.optDouble("outstanding",j.optDouble("amount",0.0));val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(13.dp,11.dp,13.dp,11.dp);background=ArthSaathiV62Design.card()};box.addView(ArthSaathiV62Design.text(this,"${j.optString("type","CREDIT")} • ${j.optString("userRole")}",10f,ArthSaathiV62Design.TEAL,true));box.addView(ArthSaathiV62Design.text(this,"₹${"%.2f".format(j.optDouble("amount",0.0))} • Outstanding ₹${"%.2f".format(out)}",15f,ArthSaathiV62Design.NAVY,true));box.addView(ArthSaathiV62Design.text(this,"${j.optString("method")} • ${j.optString("period")} • EMI ₹${"%.2f".format(j.optDouble("emi",0.0))}",10f,ArthSaathiV62Design.MUTED));if(out>0)box.addView(ArthSaathiV62Design.button(this,"RECORD REPAYMENT — CONSENT + OTP",ArthSaathiV62Design.GREEN){record(j,out)},LinearLayout.LayoutParams(-1,-2).apply{topMargin=7.dp});ArthSaathiV62Design.add(root,box,7)};setContentView(ScrollView(this).apply{isFillViewport=true;addView(root)})}
 private fun record(j:JSONObject,max:Double){val amount=ArthSaathiV62Design.input(this,"Amount paid ₹ (max ${"%.2f".format(max)})");val date=ArthSaathiV62Design.input(this,"Payment date YYYY-MM-DD");val w=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;addView(amount);addView(date,LinearLayout.LayoutParams(-1,-2).apply{topMargin=7.dp})};AlertDialog.Builder(this).setTitle("Counterparty repayment consent").setMessage("The counterparty must approve this repayment change with OTP before the ledger is updated.").setView(w).setNegativeButton("CANCEL",null).setPositiveButton("REQUEST OTP"){_,_->val p=amount.text.toString().toDoubleOrNull();if(p==null||p<=0||p>max){Toast.makeText(this,"Enter a valid amount.",Toast.LENGTH_SHORT).show();return@setPositiveButton};otp(j,p,date.text.toString())}.show()}
 private fun otp(j:JSONObject,p:Double,date:String){val code=(100000+Random.nextInt(900000)).toString();val e=ArthSaathiV62Design.input(this,"Enter 6-digit OTP");AlertDialog.Builder(this).setTitle("Two-party consent OTP").setMessage("Demo OTP: $code").setView(e).setNegativeButton("CANCEL",null).setPositiveButton("VERIFY"){_,_->if(e.text.toString()==code){val before=j.optDouble("outstanding",j.optDouble("amount",0.0));j.put("outstanding",(before-p).coerceAtLeast(0.0));j.put("lastRepaymentAmount",p);j.put("lastRepaymentDate",date);j.put("consentStatus","OTP_VERIFIED");s.replace(ArthSaathiV62Core.RELATIONSHIPS,j);val paymentId=V62Store.id("PAY");s.add(ArthSaathiV62Core.REPAYMENTS,JSONObject().apply{put("id",paymentId);put("relationshipId",j.optString("id"));put("counterpartyId",j.optString("counterpartyId"));put("amount",p);put("date",date);put("interest",0.0);put("consentVerified",true);put("createdAt",System.currentTimeMillis())});V62EventBus.publish(ArthSaathiV62Domain.Event(V62Events.REPAYMENT_CHANGED,paymentId));Toast.makeText(this,"Repayment recorded with consent.",Toast.LENGTH_LONG).show();render()}else Toast.makeText(this,"Incorrect OTP",Toast.LENGTH_SHORT).show()}.show()}
}