package com.udhaardaar.mvp

import android.app.AlertDialog
import android.graphics.Color
import android.graphics.Typeface
import android.graphics.drawable.GradientDrawable
import android.os.Bundle
import android.view.Gravity
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import org.json.JSONObject
import kotlin.random.Random

/** V6.2 consent-based repayment centre for credit given/received. */
class V62RepaymentActivity:AppCompatActivity(){
 private val store by lazy{V5LocalStore(this)};private val prefs by lazy{getSharedPreferences("udhaardaar_accounts",MODE_PRIVATE)};private val navy=Color.rgb(16,45,82);private val teal=Color.rgb(12,155,145);private val blue=Color.rgb(42,103,221);private val green=Color.rgb(18,137,91);private val red=Color.rgb(193,67,72);private val bg=Color.rgb(246,249,252);private val border=Color.rgb(220,228,236)
 private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt();private fun box()=GradientDrawable().apply{setColor(Color.WHITE);setStroke(dp(1),border);cornerRadius=dp(14).toFloat()};private fun tv(s:String,z:Float=13f,c:Int=navy,b:Boolean=false)=TextView(this).apply{text=s;textSize=z;setTextColor(c);typeface=Typeface.create("sans-serif",if(b)Typeface.BOLD else Typeface.NORMAL);setPadding(dp(3),dp(3),dp(3),dp(3))};private fun e(h:String)=EditText(this).apply{hint=h;textSize=15f;setSingleLine(true);setPadding(dp(12),dp(9),dp(12),dp(9));background=box()};private fun btn(s:String,c:Int=blue,f:()->Unit)=Button(this).apply{text=s;setTextColor(Color.WHITE);setAllCaps(false);setBackgroundColor(c);setOnClickListener{f()}}
 override fun onCreate(b:Bundle?){super.onCreate(b);if(!prefs.getBoolean("logged_in",false)){finish();return};render()}
 private fun render(){val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(16),dp(14),dp(16),dp(28));setBackgroundColor(bg)};root.addView(tv("ArthSaathi  •  Repayment Centre",21f,navy,true));root.addView(tv("Credit given + received • consent required for every repayment",11f,Color.rgb(92,108,124)),margin(3));val self=prefs.getString("current_mobile","")?:"";val mine=store.all("profiles").firstOrNull{it.optString("mobile")==self}?.optString("id")?:"";val rows=store.all("credits").filter{it.optString("lenderId")==mine||it.optString("borrowerId")==mine};if(rows.isEmpty()){root.addView(tv("No active credit records linked to this profile.",14f,navy,true),margin(18))}else rows.forEach{j->root.addView(row(j,mine),margin(8))};root.addView(btn("VIEW ALL CREDIT WORKFLOWS",teal){startActivity(android.content.Intent(this,V61RectifiedActivity::class.java))},margin(14));root.addView(btn("BACK TO HOME",Color.rgb(90,105,120)){finish()},margin(8));setContentView(ScrollView(this).apply{isFillViewport=true;addView(root)})}
 private fun row(j:JSONObject,mine:String)=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(13),dp(11),dp(13),dp(11));background=box();val given=j.optString("lenderId")==mine;addView(tv(if(given)"CREDIT GIVEN" else "CREDIT RECEIVED",10f,if(given)green else blue,true));addView(tv("${j.optString("id")}  •  ₹${"%.2f".format(j.optDouble("principal",0.0))}",14f,navy,true),margin(3));addView(tv("Outstanding ₹${"%.2f".format(j.optDouble("outstanding",0.0))}  •  Due ${j.optString("dueDate")}",11f,Color.rgb(92,108,124)),margin(2));addView(tv("${j.optString("repaymentMethod")} • ${j.optString("periodicity")} • EMI ₹${"%.2f".format(j.optDouble("emi",0.0))}",10f,teal,true),margin(2));if(j.optDouble("outstanding",0.0)>0)addView(btn("RECORD REPAYMENT",green){record(j)},margin(7))}
 private fun record(j:JSONObject){val max=j.optDouble("outstanding",0.0);val amount=e("Amount paid ₹ (max ${"%.2f".format(max)})");val date=e("Payment date YYYY-MM-DD");val d=AlertDialog.Builder(this).setTitle("Repayment consent").setMessage("The counterparty must consent before this repayment changes the record.").setView(line(amount,date)).setNegativeButton("CANCEL",null).setPositiveButton("REQUEST OTP",null).create();d.setOnShowListener{d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener{val p=amount.text.toString().toDoubleOrNull();if(p==null||p<=0||p>max){amount.error="Enter a valid amount";return@setOnClickListener};val code=(100000+Random.nextInt(900000)).toString();d.dismiss();val otp=e("6-digit OTP");AlertDialog.Builder(this).setTitle("Two-party consent OTP").setMessage("Demo OTP: $code").setView(otp).setNegativeButton("CANCEL",null).setPositiveButton("VERIFY"){_,_->if(otp.text.toString()==code){j.put("outstanding",max-p);j.put("lastRepaymentAmount",p);j.put("lastRepaymentDate",date.text.toString());j.put("consentStatus","OTP_VERIFIED");store.replace("credits",j);Toast.makeText(this,"Repayment recorded with consent",Toast.LENGTH_LONG).show();render()}else Toast.makeText(this,"Incorrect OTP",Toast.LENGTH_LONG).show()}.show()}};d.show()}
 private fun line(a:EditText,b:EditText)=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;addView(a);addView(b,margin(7))};private fun margin(t:Int)=LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(t)}
}
