package com.udhaardaar.mvp

import android.os.Bundle
import android.widget.*
import org.json.JSONObject

class V62TTMMActivity:androidx.appcompat.app.AppCompatActivity(){
 private val store by lazy{V5LocalStore(this)};private val d by lazy{resources.displayMetrics.density};private val root by lazy{LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(ArthSaathiV62Design.dp(16,d),ArthSaathiV62Design.dp(10,d),ArthSaathiV62Design.dp(16,d),ArthSaathiV62Design.dp(28,d));setBackgroundColor(ArthSaathiV62Design.BG)}}
 private val members=mutableListOf<String>();private fun input(h:String)=ArthSaathiV62Design.input(this,h)
 override fun onCreate(b:Bundle?){super.onCreate(b);render()}
 private fun render(){root.removeAllViews();ArthSaathiV62Design.add(root,ArthSaathiV62Design.title(this,"TTMM","Together Today • Money Managed"),2);ArthSaathiV62Design.add(root,ArthSaathiV62Design.text(this,"A shared-money workspace for trips, families, friends and groups: record who paid, who benefited, split fairly, settle dues and keep a transparent history.",10f,ArthSaathiV62Design.MUTED),8);ArthSaathiV62Design.add(root,ArthSaathiV62Design.text(this,"GROUP MEMBERS",11f,ArthSaathiV62Design.MUTED,true),12);val name=input("Member name / mobile");ArthSaathiV62Design.add(root,name,5);ArthSaathiV62Design.add(root,ArthSaathiV62Design.button(this,"ADD MEMBER",ArthSaathiV62Design.TEAL){if(name.text.toString().trim().isNotEmpty()){members.add(name.text.toString().trim());name.setText("");render()}},5);members.forEachIndexed{i,m->ArthSaathiV62Design.add(root,ArthSaathiV62Design.text(this,"${i+1}. $m",13f,ArthSaathiV62Design.NAVY,true),4)};ArthSaathiV62Design.add(root,ArthSaathiV62Design.text(this,"ADD SHARED EXPENSE",11f,ArthSaathiV62Design.MUTED,true),14);val desc=input("Expense description");val amount=input("Amount ₹");val payer=input("Paid by — member");val split=Spinner(this).apply{adapter=ArrayAdapter(this@V62TTMMActivity,android.R.layout.simple_spinner_dropdown_item,arrayOf("Equal split","Custom amounts","Percentage split","Shares / units"))};ArthSaathiV62Design.add(root,desc,5);ArthSaathiV62Design.add(root,amount,5);ArthSaathiV62Design.add(root,payer,5);ArthSaathiV62Design.add(root,split,5);ArthSaathiV62Design.add(root,ArthSaathiV62Design.button(this,"RECORD EXPENSE & CALCULATE DUES",ArthSaathiV62Design.BLUE){record(desc.text.toString(),amount.text.toString(),payer.text.toString(),split.selectedItem.toString())},10);ArthSaathiV62Design.add(root,ArthSaathiV62Design.text(this,"Every expense updates group balances. Settlement entries reduce dues; the group history remains auditable.",10f,ArthSaathiV62Design.MUTED),10);setContentView(ScrollView(this).apply{isFillViewport=true;addView(root)})}
 private fun record(desc:String,amount:String,payer:String,method:String){val a=amount.replace(",","").toDoubleOrNull()?:0.0;if(a<=0||members.isEmpty()){Toast.makeText(this,"Add members and a valid amount.",Toast.LENGTH_SHORT).show();return};store.add(ArthSaathiV62Core.TTMM,JSONObject().apply{put("id",ArthSaathiV62Core.id("TTMM"));put("description",desc);put("amount",a);put("payer",payer);put("splitMethod",method);put("members",members.joinToString("|"));put("createdAt",System.currentTimeMillis())});Toast.makeText(this,"Expense recorded. Group dues updated.",Toast.LENGTH_SHORT).show();render()}
}
