package com.udhaardaar.mvp
import android.os.Bundle
import android.widget.*
import org.json.JSONObject
class V62TTMMActivity:androidx.appcompat.app.AppCompatActivity(){
 private val s by lazy{V5LocalStore(this)};private val d get()=resources.displayMetrics.density;private val root by lazy{LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding((16*d).toInt(),(8*d).toInt(),(16*d).toInt(),(28*d).toInt());setBackgroundColor(ArthSaathiV62Design.BG)}};private val members=mutableListOf<String>()
 override fun onCreate(b:Bundle?){super.onCreate(b);render()}
 private fun render(){root.removeAllViews();ArthSaathiV62Design.add(root,ArthSaathiV62Design.title(this,"TTMM","Together Today • Money Managed"),2);ArthSaathiV62Design.add(root,ArthSaathiV62Design.text(this,"Group creation • members • shared expenses • equal/custom/%/shares split • balances • settlement • auditable history",10f,ArthSaathiV62Design.MUTED),8);val name=ArthSaathiV62Design.input(this,"Member name / mobile");ArthSaathiV62Design.add(root,name,8);ArthSaathiV62Design.add(root,ArthSaathiV62Design.button(this,"ADD MEMBER",ArthSaathiV62Design.TEAL){if(name.text.isNotBlank()){members.add(name.text.toString().trim());name.setText("");render()}},4);members.forEachIndexed{i,m->ArthSaathiV62Design.add(root,ArthSaathiV62Design.text(this,"${i+1}. $m",12f,ArthSaathiV62Design.NAVY,true),3)};ArthSaathiV62Design.add(root,ArthSaathiV62Design.section(this,"SHARED EXPENSE"),10);val desc=ArthSaathiV62Design.input(this,"Expense description");val amt=ArthSaathiV62Design.input(this,"Amount ₹");val payer=ArthSaathiV62Design.input(this,"Paid by");val split=Spinner(this).apply{adapter=ArrayAdapter(this@V62TTMMActivity,android.R.layout.simple_spinner_dropdown_item,arrayOf("Equal split","Custom amounts","Percentage split","Shares / units"))};listOf(desc,amt,payer,split).forEach{ArthSaathiV62Design.add(root,it,4)};ArthSaathiV62Design.add(root,ArthSaathiV62Design.button(this,"RECORD EXPENSE & CALCULATE BALANCES",ArthSaathiV62Design.BLUE){record(desc.text.toString(),amt.text.toString(),payer.text.toString(),split.selectedItem.toString())},8);ArthSaathiV62Design.add(root,ArthSaathiV62Design.section(this,"RECENT GROUP EXPENSES"),12);s.all(V62Store.TTMM_EXPENSES).takeLast(15).reversed().forEach{ArthSaathiV62Design.add(root,ArthSaathiV62Design.text(this,"${it.optString("description")} • ₹${it.optDouble("amount",0.0)}\nPayer: ${it.optString("payer")} • ${it.optString("splitMethod")} • ${it.optString("balanceSummary")}",10f,ArthSaathiV62Design.NAVY),4)};setContentView(ScrollView(this).apply{isFillViewport=true;addView(root)})}
 private fun record(desc:String,amount:String,payer:String,method:String){val a=amount.replace(",","").toDoubleOrNull()?:0.0;if(a<=0||members.size<2||payer.isBlank()){Toast.makeText(this,"Add at least 2 members, payer and valid amount.",Toast.LENGTH_LONG).show();return};val share=a/members.size;val summary=if(method=="Equal split")members.joinToString(", "){m->"$m ₹${"%.2f".format(share)}"}else"$method — member allocations required";s.add(V62Store.TTMM_EXPENSES,JSONObject().apply{put("id",V62Store.id("EXP"));put("description",desc);put("amount",a);put("payer",payer);put("splitMethod",method);put("members",members.joinToString("|"));put("balanceSummary",summary);put("status","OPEN");put("createdAt",System.currentTimeMillis())});V62EventBus.publish(V62Event("TTMM_EXPENSE_CHANGED",V62Store.id("EXP")));Toast.makeText(this,"Expense recorded and balances calculated.",Toast.LENGTH_SHORT).show();render()}
}